ReactionMechanismGenerator/RMG-Py

- rmgpy/rmg/model.py
These commits address the issue https://github.com/GreenGroup/RMG-Py/issues/276 where some libraries have duplicate reactions containing both a pdep reaction and a non-pdep reaction, the final mechanism from RMG will end up excluding one of them.  It also works when there are two duplicates of pdep reactions (for instance 2 chebyshevs, or literally any combination of reactions, as long as they are marked duplicate.)
This allows reactions to enter the core by changing the way checkForExistingReaction function works in rmgpy/rmg/model.py
It ignores marked duplicate reactions from reaction libraries and seed mechanisms.  
I've tested this with duplicate reactions in a library as a seed mechanism, a library, and in both library + seed mech.   I hope the pdep handling in the reaction library …
> Fix duplicate reaction handling in reaction libraries and seed mechanisms

- rmgpy/chemkin.py
With the latest commits to RMG, the behavior of treating reaction libraries is a bit different now.  We have made it possible to be more flexible with regards to duplicate reactions.  All duplicate reactions, be it mixed Pdep and nonPdep, reverse or forward directions, MUST be marked duplicate within the kinetic library.  RMG performs a check on loading the library to check this and will throw an error if they are unmarked.  We do not enforce the MultiArrhenius or MultiPDepArrhenius rule for this.  Sometimes people want to have a Pdep and Non-Pdep reaction together.  Maybe they want 2 TROE reactions together, or whatever combination.  I think it should be allowed.
When using multiple libraries, the duplicate checking is in done between libraries and also for template reactions against …
> Also mark duplicate reactions in the reverse direction for chemkin files

- rmgpy/chemkin.py
- rmgpy/kinetics/arrhenius.pyx
These commits hope to address issue https://github.com/GreenGroup/RMG-Py/issues/147, where PLOGs in this format are interpreted incorrectly:
C3H6(48)+HO2(9)=OH(5)+C3H6O(70)                     1.000e+00 0.000     0.000    
PLOG/ 0.010     4.720e+04 2.290     12.336   /
PLOG/ 0.010     1.090e+05 2.180     12.535   /
PLOG/ 1.000     4.660e+07 1.420     14.066   /
PLOG/ 10.000    1.930e+12 0.107     17.385   /
PLOG/ 100.000   1.300e+11 0.544     19.059   / 
I've made the PDepArrhenius and MultiPDepArrhenius classes allow MultiArrhenius objects in their arrhenius list of objects.  That way khigh and klow can be determined from a duplicate reaction MultiArrhenius object at a single pressure.
I've altered the chemkin reading and writing by storing the PLOG kinetics with MultiArrhenius objects …
> Working with duplicate kinetics within a single PLOG

- documentation/source/theory/rmg/prune.rst
- documentation/source/users/rmg/input.rst
- rmgpy/pdep/network.py
Changed `drawMolecules=False` to `True` in the doc and added an explanation
for why a user would want this. Also, small fixup in cantherm's code that now lets users know which reaction RRKM rates are being calculated for.
> Added documentation for making RMG inp files, small cantherm fixup

- rmgpy/data/kinetics/library.py
Previously we listed the adjlist for all reactants and products in the
entry for the reaction. A recent change now has a separate dictionary file
and reaction files, so that reactants can be editted once instead of once
for every reaction they are in.
However, now we need to add a label property to each reaction entry to
substitute for the the adjList. This fix adds one line which adds the
correct label (hopefully in all cases)
> Fix to add labels to libraries in loadOld

- documentation/source/users/rmg/liquids.rst
- rmgpy/data/solvation.py
- rmgpy/data/solvationTest.py
- rmgpy/data/thermo.py
This addresses issue #342 .
When a lone pair is encountered, we turn it into two unpaired electrons for the purpose of adding hydrogens and looking up the solvation thermo of the saturated structure. But we only replace the lone pairs based on the usual valency of the atom. For example for CH2(S) we would replace that lone pair to make sum(unpaired electrons + bonds + charge) be equal to 4. But for H2O we wouldn't replace the lone pairs on Oxygen.
When we "unsaturate" the radicals, we should also correct the "A" H-bonding parameter that we previously calculated for the saturated structure. In the future we can have a radical solute library in the database, which "cancels" out the A value that we got from the molecule, as in RMG-Java. As a quick fix for right now, I am only correcting …
> Fix to solvation thermo for lone pairs

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/rules.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
This pull request addresses https://github.com/GreenGroup/RMG-Py/issues/361.  The summary of changes:
* Make templates use semicolons so that it matches RMG-database format and is easier to search
* Remove duplicate kinetics estimation from rate rules function that was giving incorrect kinetics comments (saying that match is exact even when it is an average- basically it was showing that the node had data, but that data had been set by fillTreesbyAveragingUp)
* Make processNewReactions in rmgpy/rmg/model.py more deterministic.  Make it choose the exergonic direction in more cases so that we don't get different models when we put a reactant in vs. product, etc.
* Enlarge model with new core species individually to fix a logging bug as well as make it easier to see what RMG is doing through …
> Fixing kinetics commenting and other minor bugs

- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- convert the lone pair electrons into 2 unpaired electrons for singlet carbene atoms when converting to rdKit Molecules
- append a multiplicity layer in the augmented identifiers regardless of the multiplicity of the molecule
- use the multiplicity attribute of the Molecule rather than the radical atom count for the multiplicity layer
- use 1 method to create this layer and call it in the callers.
- adds a test in moleculeTest
> fix rdKit conversion and subsequent Identifier generation for singlet carbene species

- diffModels.py
- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/species.py
- remove the symmetry contribution for saturated species if the thermo originates from thermo libraries, or QMTP
- check if pre-computed symmetry number exists before calculating it again
> Symmetry contribution for radicals

- rmgpy/data/base.py
- rmgpy/data/kinetics/groups.py
This pull request addresses https://github.com/GreenGroup/RMG-Py/issues/381
Change the way descendTree works, allowing an optional argument for 'strict' matching, in other words, requiring that groups and the molecules that match them completely match all atom labels.  Our previous check in generate reactions is not very robust.  I decided to alter the base function rather than implement lines in the generate reactions section.
We use strict atom label matching in finding the correct kinetic groups to associate
with a reaction and its reaction template.  However, the previous method used for LogicOr groups
was flawed.  It found the very first child node of an LogicOR group and used its atomLabels
to match the reactant.  However, sometimes the LogicOR group contained children that had …
> Fix the way LogicOR groups are handled in descending kinetics tree

- documentation/source/users/rmg/input.rst
Two examples of pruning parameter set are provided. One is for pruning,
another is non-pruning. By comparing between two examples, users could get
ready to choose pruning parameter properly.
> Add two examples of pruning parameter set

- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
Adds the kekulized form as a resonance isomer.
In response to https://github.com/ReactionMechanismGenerator/RMG-Py/issues/405.
> Make sure that inputted benzene-bond forms of adjlists get kekulized.

- rmgpy/kinetics/arrhenius.pyx
- rmgpy/kinetics/model.pyx
fixed the units in comments of getRateCoefficient and getEffectivePressure
The units described in comments of getRateCoefficient and
getEffectivePressure were not in 'si' and didn't seem to match what the
method actually produced.
> fixed the units in comments

- Makefile
This pull request tries to address https://github.com/ReactionMechanismGenerator/RMG-Py/issues/416
Not sure when the feature was actually updated in RDKit, but let's assume 2015 to be safe.
One thing to be cautious of is when building from Github source for RDKit.  Not sure if version is given from that. But for now assume that most people have a stable release.
> Check RDKit version during 'make' so that people update to 2015+

- rmgpy/data/kinetics/library.py
- rmgpy/rmg/model.py
Addresses https://github.com/ReactionMechanismGenerator/RMG-Py/issues/345
Previously, irreversible reactions were not saved with the appropriate flag into RMG's model.  All reactions were converted to reversible.  This fixes the problem by carrying over the `reversible` as well as `degeneracy` attribute.  Note that the `degeneracy` attribute does not affect rates (kinetics already incorporates degeneracy).  
Checks performed:
- Chemkin files saves irreversible reaction
- Solver incorporates irreversibility and produces different output
> Carry over reversibility of library reactions in reaction libraries and seed mechanisms

- documentation/source/users/rmg/input.rst
Must be a tuple, not a string.
> Correct PDepArrhenius instructions

- documentation/source/_templates/customsidebar.html
Reduced size to improve appearance in Firefox and IE.
I couldn't figure out the reason, but Chrome reduces the size of the icons to 25 px, while Firefox and IE were using the set width of 75 px. I changed the setting to 25 px, which fixes the display in Firefox and IE, but doesn't affect Chrome.
> Change sidebar icon width in documentation website

- rmgpy/molecule/molecule.py
bond.order is a string, not an integer
> default value of bond order should be 'S'

- rmgpy/data/kinetics/common.py
This PR is to allow Retroen family to be in the scope of RMG-Py.
> Newly added Retroen family into RMG

- documentation/source/users/rmg/modules/diffModels.rst
- scripts/diffModels.py
This is for allowing the script to be called easily through the RMG-website by adding a --web flag.
This also makes it less clunky for additional thermo dat files to be used, instead of putting in dummy filenames for thermo.
> Alter the way diffModels.py is called for easier calling by RMG-website

- rmgpy/qm/gaussian.py
- rmgpy/qm/mopac.py
The output file verification was broken if gaussian was used.
The output file verification has also been made consistent for mopac and gaussian output files.
> Fix to gaussian implementation in QMTP

- rmgpy/molecule/adjlistTest.py
- rmgpy/molecule/atomtypeTest.py
- rmgpy/molecule/inchiparsingTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/parser.py
- rmgpy/molecule/parserTest.py
- rmgpy/molecule/resonanceTest.py
This PR addresses https://github.com/ReactionMechanismGenerator/RMG-website/issues/91 and ensures that heavy atoms appear first in the adjacency list.
bf72770 is a unit test contains a number of aromatic species that include the molecule mentioned in the issue.
794eb1a ensure that the risky combo of `.toRDKitMol(molecule, removeHs=True, returnMapping=True)` is not used anymore.
ab4d579 is an improvement of `toRDKitMol` to only add atoms to the index list that will actually exist in the generated rdkit molecule.
a625972 ensures that heavy atoms always preceed H-atoms, when `molecule.sortAtoms()` is called.
> Fix bug91 website & ensure heavy atoms appear first in adj lists

- cantherm.py
Newer version of psutil changed the function name.
> Change Process.get_memory_info() to Process.memory_info() in Cantherm.

- rmgpy/rmg/model.py
Based on @KEHANG CPU profiling, this was eating away a lot of our CPU time, for no good reason.
this is always true since we already know that
- the reaction is new
- at least one species is not in the core yet
> remove " is rxn present in self.edge.reactions"

- rmgpy/molecule/graph.pxd
- rmgpy/molecule/graph.pyx
- rmgpy/molecule/moleculeTest.py
The connectivity values may grow to numbers that do not fit in an C integer anymore, which was statically typed in `graph.pyx`. this resulted in an `OverflowError`.
> Avoid OverflowErrors for the connectivity value algorithm for large molecules

- rmgpy/data/kinetics/family.py
- rmgpy/molecule/molecule.py
- rmgpy/molecule/parser.py
https://github.com/ReactionMechanismGenerator/RMG-Py/issues/471#issuecomment-156007505 showed that this method is expensive, and called too many times.
This hopefully speeds up RMG simulations somewhat.
> Review the Molecule.update() method calls 

- rmgpy/chemkin.py
- rmgpy/qm/main.py
- rmgpy/restart.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/output.py
- rmgpy/stats.py
The idea is that we will eventually have an RMG simulation class (`rmgpy.rmg.RMG`) that is unaware (and doesn't care) of what is done with its state (reaction model, reaction system, ...).
For example: 
the chemkin file, and HTML output writers are moved to the corresponding modules that contain the code that writes the stuff. 
The idea is to decouple everything related to writing information to the user from the actual simulation. It's an easier design to extend in the future, and it could potentially be used as well to (asynchronously) offload these time consuming parts in the future.
> RMG Output via observer pattern

- rmgpy/rmg/main.py
- rmgpy/stats.py
- rmgpy/statsTest.py
This PR fixes importing the optional dependency xlwt to write a statistics file.
It also adds a unit test that verifies this.
> Fix xlwt import in stats module

- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/reactionTest.py
I think that the Troe broadening parameters etc. are 
the same in both directions, so as long as we correctly
reverse the high and low pressure limits, we should be 
able to reverse these reaction types too.
I think ThirdBody with +M and the low-pressure limits of
the PDep reaction types with (+M) should have one more
m3/mol in the units than they would otherwise.
I tried to reduce code duplication by making a special
method to reverse a given Arrhenius rate expression.
One thing this section of code would benefit from is some unit tests. Any volunteers??
(One way to test would be to reverse a reaction rate twice, and see if you end up close to where you started).
> Extend generateReverseRateCoefficient for some PDep types.

- rmgpy/chemkin.py
- rmgpy/data/kinetics/depository.py
- rmgpy/data/kinetics/family.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/output.py
Instead of storing (referencing) the entire reaction family in each reaction instance, this PR changes this.
Instead, we only store the name of the family/library as an attribute, and redirect to the family/library object through a function called `getFamily`. The latter is located in `rmgpy.rmg.model` as this is the only module that needs access to the objects, rather than just the names. The other modules like `chemkin` only require the name of the family/library.
The advantage of this design is:
- we need less space when we serialize a reaction object (this reduces transfer costs across memories)
- we don't get in trouble when a reaction object is created on a remote computer where the references to the reaction family object is different.
> Store the family/library name as a reaction attribute

- rmgpy/cantherm/pdep.py
- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/rules.py
Addresses https://github.com/ReactionMechanismGenerator/RMG-Py/issues/237
Contrary to prior belief, we don't actually need to add the reaction family to the list of unimolecular and bimolecular families.  KineticsGroups.numReactants is capable of providing the reaction order.  However, I have migrated the hardcoded lists into the import old kinetics groups from RMG-Java function, since hardcoding in that function seems very reasonable.
> Reaction order

- rmgpy/rmg/model.py
Previously, the keys in the reaction dictionary of the `CoreEdgeReactionModel` were the 
Family, and Species objects of a reaction.
In a parallellized world where references to these objects may be lost, this causes a lot of trouble.
This PR uses strings as dictionary keys, rather than objects.
Both for species, and families the corresponding _key_ is the label.
In addition, I refactored the interaction with the reaction dictionary into separate functions, but kept the original functionality.
> refactoring of the reaction dictionary interaction

- rmgpy/chemkin.py
- rmgpy/chemkinTest.py
- rmgpy/tools/data/chemkin/chemkin_py/minimal/chem.inp
- rmgpy/tools/data/chemkin/chemkin_py/minimal/species_dictionary.txt
- rmgpy/tools/data/chemkin/chemkin_py/pdd/chem.inp
- rmgpy/tools/data/chemkin/chemkin_py/pdd/species_dictionary.txt
This PR mainly fixed two bugs
- parse comment like "! Template reaction: Disproportionation", where family info is in last token
- parse comment like "Disproportionation estimate: (Average:)". where family info is relied on checking whether the line has "estimate:" or "exact:"
> Fix bugs in readReactionComments

- rmgpy/rmg/model.py
- rmgpy/tools/data/generate/duplicates/input.py
- rmgpy/tools/testGenerateReactions.py
This PR fixes the duplicated reactions that were erroneously not discovered as already existing reactions in the reaction database.
This issue was mentioned [here] (https://github.com/ReactionMechanismGenerator/RMG-database/issues/81) and in #513.
An attempt at creating a unit test that reproduces this is found in the testGenerateReactions module for lack of a better place.
The added unit test generates reactions for 3 input reactants (`HCJ=O, CH2O, and [CH2]OC=O`) through a single reaction family (radical addition to double bond). The one reaction 
`HCJ=O + CH2O <=> [CH2]OC=O`
that results from applying this reaction family, is also present in the seed mechanism (`methylformate`) that is imported. It is checked whether the total number of reactions in the final model is equal to the …
> Fix bug RMG-database #81

- rmgpy/data/kinetics/family.py
The template attribute of a TemplateReaction is obtained [during the generation of the reaction] (https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/data/kinetics/family.py#L1457).
It is used to compute a rate coefficient object, [much more downstream] (https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/rmg/model.py#L882) in the `CERM.generateKinetics(...)` method.
This PR goes from a design in which `templaterxn.template` stores a list of group objects to a design in that stores a list of strings, corresponding to the labels of the groups.
Only, when the group objects are needed again are the group objects retrieved again. The result is that the template attribute contains a much smaller objects (strings), which don't need to go through the …
> TemplateReaction's template are stored as a list of strings

- rmgpy/chemkin.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/output.py
This pull request fixes the `generateReactions.py` script so that it creates the right output html page.
This closes  https://github.com/ReactionMechanismGenerator/RMG-Py/issues/523
It also makes the normal visualization and diff visualizations look nicer, fixes the checkbox javascripts, and also adds 2 new features:
- thermo comment toggling
- search and filter reactions by species when visualizing a single chemkin file
- flux pairs saved in commentary
> New features and fixes to output HTML

- documentation/source/theory/rmg/prune.rst
`larger values will lead to larger edge mechanisms` should be 
`larger values will lead to smaller edge mechanisms`
> Fix typo in pruning documentation

- rmgpy/constraints.py
- rmgpy/data/kinetics/database.py
- rmgpy/data/kinetics/family.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
This PR addresses some of the concerns vented in #521 regarding the manipulation of static user input information like species constraints.
In the current design:
- the `failsSpeciesConstraints` method is moved to the constraints module since it was called in various places; 
- passing the function name to various methods is deprecated: when a method needs the species constraints, it simply calls the global rmg variable that already stored that info
- the species constraints are broadcasted when the info is needed on a remote worker instead of the root worker, and a convenience function `getInput` is created that searches for that info in the global rmg variable or the broadcasted variable.
> code redesign of species constraints

- rmgpy/constraints.py
- rmgpy/constraintsTest.py
- rmgpy/rmg/input.py
fix RMG-website bug #104
cf. https://github.com/ReactionMechanismGenerator/RMG-website/issues/104
> anticipate situation in which species constraints are not loaded.

- rmgpy/rmg/model.py
this ensures that :
if (rxn0.reactants == rxn.reactants and rxn0.products == rxn.products) or \
(rxn0.reactants == rxn.products and rxn0.products == rxn.reactants):
does not produce false negatives because of order differences of the
list elements
> sort reactant and product lists in checkForExistingReaction

- Makefile
- rmgpy/data/kinetics/family.py
- rmgpy/data/rmg.py
- rmgpy/rmg/model.py
- rmgpy/scoop_framework/util.py
This PR introduces a new design for the generation of reactions in parallel.
In the `rmgpy.rmg.model.CoreEdgeReactionModel.enlarge` method, reactions between a new core species and the existing list of core species, for the given list of available reaction families. This process is parallelized across the reaction families, across the list of core species and across the list of resonance isomers of a specific species both for uni- and bimolecular reaction families to minimize worker load imbalances due to the _heterogeneity_ of reaction families, species, and molecules. 
A lazy evaluation scheme of the tasks is chosen to maximize the number of tasks being run at the same time.
- A uniform `rmgpy.scoop_framework.util.map_` interface is introduced that either uses the parallel `map` …
> Parallel generation of reactions in `enlarge`

- rmgpy/data/kinetics/family.py
In the case of forbidden reaction pathway in the reverse direction, delete the forward direction reaction. Usually this means the forbidden groups aren't comprehensive enough.  But since the Transition State is banned in one direction, it is likely should be banned in the other direction as well.  See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/412
We should think about how to fix the databases to avoid this issue through unit tests or changes to the algorithm later.
> Debug kinetics error where reverse direction kinetics cannot be found 

- rmgpy/rmg/outputTest.py
- rmgpy/rmg/pdep.py
- rmgpy/rmg/test_data/saveOutputHTML/eg6/chem_annotated.inp
- rmgpy/rmg/test_data/saveOutputHTML/eg6/species_dictionary.txt
ensures the `getSource()` method of `rmgpy.rmg.pdep.PdepReaction` returns a string, and not an object.
adds a test that tries to save output HTML with output module
should fix #539
> Jinja2 error fix

- rmgpy/tools/diff_models.py
allows to re-use results from diff_models. 
Right now, diff_models does not return anything, as it was always used as a stand-alone script, rather
than a module that could be reused.
> improve diff models functionality

- rmgpy/kinetics/tunneling.pyx
This closes https://github.com/ReactionMechanismGenerator/RMG-Py/issues/533
By using numpy.cosh rather than libc's cosh, we can eliminate the 32-bit precision test which fails for eckhart tunneling.
It appears that we do not use the libc version of the cosh function anywhere else in the code, so hopefully this resolve these sorts of issues for good.
> Fix 32-bit precision problem in eckhart tunneling value

- rmgpy/rmg/input.py
- rmgpy/tools/data/generate/libraryReaction/input.py
- rmgpy/tools/testGenerateReactions.py
This closes https://github.com/ReactionMechanismGenerator/RMG-Py/issues/515
By adding the input species to the edge in the step before reaction libraries are added to edge,
we make sure that when the input species is added, a reaction on the edge containing all input species
can get added to the core.  
The source of the bug is due to the function:
`spec, isNew = rmg.reactionModel.makeNewSpecies()`
giving `False` even though the species is in NEITHER the core nor edge.  (The input species are created but not yet added anywhere).
This was the simplest way I could think of for fixing the bug.  There should be no other instances in which a species is not in either the core or edge when it is created when this function returns `False`.
> Fix issue: reaction library rxns containing all input species not added to core

- rmgpy/rmg/model.py
This is a band-aid to fix https://github.com/ReactionMechanismGenerator/RMG-Py/issues/508
The best way to truly, thoroughly fix this problem is to do the proper isomorphism checks in both __createReaction and  in __generateReactions to get the right degeneracies and not create any symmetric reactions in rmgpy.data.kinetics.family
> Add a safety check in CERM to ensure symmetrical rxns don't enter

- rmgpy/solver/base.pyx
This addresses a small typo in base.pyx
it reused the `index` variable with the value it was last set to.
On the bright side, this serious bug did not lead to model differences for other simulations, which begs the question: "how is that even possible?".
> Fix liquid reactor bug

- rmgpy/rmg/main.py
This is very useful for tracking what version of RMG-database we are on.
Unfortunately we cannot track this is people are using a binary version of RMG-database.  Since RMG-database is not a package, we cannot check rmgdatabase.__version__  However, we can probably assume they are using the package corresponding to the version of rmgpy binary they are using.
> Add git HEAD of RMG-database to output log.

- deploy.sh
- rmgpy/tools/diff_models.py
before, when a RMG-Py travis build was triggered, it created a branch on the RMG-tests repo with the same name as the one that was being pushed by RMG-Py. That lead to name collisions, e.g. for master.
Now we prepend the branch name with `rmgpy-`.
The 2nd commit avoids loading matplotlib when we don't need it, which should speed up travis builds.
> avoid RMG-tests branch name collisions when deploying through travis

- rmgpy/rmg/main.py
Followup to https://github.com/ReactionMechanismGenerator/RMG-Py/pull/560 to account for version printing when somebody is using a anaconda binary.
Already tested in a `rmg_binary` environment through copy pasting `main.py` into the appropriate site-packages folder..
> Print the anaconda package in log file if we cannot extract the git HEAD

- examples/rmg/heptane-eg5/input.py
- rmgpy/rmg/main.py
Fixes https://github.com/ReactionMechanismGenerator/RMG-Py/issues/558
It turns out that pdep jobs do not produce the wrong models, but the convergence takes too long because `RMG.main` was calling `enlarge(reactEdge=True)` too often without updates to `unimolecularReact` and `bimolecularReact` arrays when filterReactions was off.
This fixes the issue and also restructures the `updateReactionThresholdAndReactFlags` function to have better readability.
Also the heptane-eg5 example was updated to reflect a pdep example that takes a little longer to converge without this fix.
> Fix pdep job convergence issue

- examples/rmg/heptane-filterReactions/input.py
- rmgpy/rmg/main.py
Discovered that similar pdep convergence problems occur when both pdep and filterReactions is on.
The `enlarge(reactEdge=True)` step must be skipped in **all** cases where there are no new core species added, except for the very initial enlarge edge step after adding initial species.
> Fix pressure dependence convergence issue with filterReactions on

- rmgpy/molecule/graph.pxd
- rmgpy/molecule/graph.pyx
- rmgpy/molecule/graphTest.py
- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/resonance.py
- rmgpy/molecule/vf2.pyx
revert it back to the triple connectivity values per Vertex,
which has less discriminatory power, but is more robust for larger
molecules.
should address #564
> revert the vertex connectivity value algorithm

- rmgpy/molecule/graph.pxd
- rmgpy/molecule/graph.pyx
- rmgpy/molecule/graphTest.py
- rmgpy/molecule/moleculeTest.py
Was originally intending to return all distinct cycles, but this function now correctly returns a list of only the polycyclic cycles, which will be useful for fitting polycyclic thermo groups.
> Add a function for getting polycyclic cycles only

- rmgpy/data/thermo.py
Kinetics entries already have rank.  Allow rank to be entered as an attribute for thermo as well, for the purpose of prioritizing thermo.
In the initial phase, we can use human-assigned rank to sort thermo, thereafter we can use a metric associated with uncertainties to assign a rank automatically.  
Assign a rank of 3 by default to all thermo groups.
> Allow rank to be an additional attribute in thermo database entries

- rmgpy/data/base.py
- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/molecule/graph.pxd
- rmgpy/molecule/graph.pyx
- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
Previously the ring correction is always same for all the rings in molecule. This PR fixed this issue by feeding information of each ring when adding ring correction thermo data. A demonstration of this PR can be found [here](https://github.com/KEHANG/rmg_issue/blob/master/thermo_issues/thermo_correction_for_multiple-ring_molecules.ipynb).
> Improve thermo estimation for cyclics

- rmgpy/data/kinetics/family.py
- rmgpy/data/thermo.py
This pull request complements the one in RMG-database carrying scripts for saving kinetics library to training reactions and extracting polycyclic groups from thermo libraries.
Main additions:
- A function to save training reactions to disk and overwrite old ones.  Automatically creates the correct atom labels according to RMG reaction family templates.  Also recognizes existing species in the training dictionary.txt and saves new species accordingly.
- A function to retrieve labeled atoms
- An averageThermoData function for use when averaging several groups together and calculates uncertainty automatically with error = 2s, where s is the sample standard deviation
- Don't crash when more than one most specific ring group is found for thermo
> Add functionality to assist in saving training reactions and thermo groups to RMG

- rmgpy/rmg/listener.py
- rmgpy/solver/base.pyx
Closes https://github.com/ReactionMechanismGenerator/RMG-Py/issues/594
Changes opening of csv files for writing from 'w' status to 'wb' status, preventing blank lines from being written in their .csv files when user runs RMG-Py in windows machines.
> Fix csv writing in Windows

- .gitignore
- environment.yml
- environment_windows.yml
- ipython/README
- ipython/canteraSimulation.ipynb
- ipython/data/minimal_model/chem_annotated.inp
- ipython/data/minimal_model/species_dictionary.txt
- meta.yaml
- rmgpy/tools/canteraModel.py
- rmgpy/tools/canteraTest.py
- rmgpy/tools/data.py
- rmgpy/tools/observablesRegression.py
- rmgpy/tools/plot.py
New submodules under `rmgpy.tools`: `canteraModel` and `observablesRegression`
`canteraModel`
Contains classes for creating cantera conditions and cantera jobs.  Is able to mostly automatically simulate reactor conditions and plot them
Cantera dependency as also been added to anaconda build and environment.  
`observablesRegression`
Contains a class for testing observables between two models.  Experimental data handling not yet implemented but will probably be implemented by @nyee 
Also added an `ipython` folder to the RMG-Py main folder, containing useful scripts or other educational ipython notebooks.  Currently only the cantera simulation ipynb is in there.
> Add cantera and observable regression submodules

- rmgpy/chemkin.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
Fix bug that occurs when we try to append a ReactionLibrary to the end of the chemkin file.
There was a bug that occurred because of bad identification of the reaction library
label.  Change the way `addReactionLibraryToOutput` works to be more efficient by no longer
creating new LibraryReaction objects, since they are already in memory.
Fix the saveChemkin function so that when saving edge, it does not save the
`outputSpeciesList` or `outputReactionList`, because that would print a bunch of duplicates on the edge.
Also no longer check duplicates, because it is performed in `enlarge()` for
all core and edge reactions and also when first adding the reaction library to the edge, so this should make it more efficient.
> Fix appending of reactions in CoreEdgeReactionModel.addReactionLibraryToOutput()

- rmgpy/chemkin.py
- rmgpy/tools/testSensitivity.py
There is a design change to the loading of chemkin files.  I think we should no longer
follow RMG-Java's way, and instead read in chemkin files more literally, especially
since all RMG-Py jobs do write almost all the bath gases.  This is also
so that the indices and readouts match cantera and chemkin more closely without unexpected
loading of species.
> Read chemkin files literally: Don't load new bath gases when loading a chemkin file

- rmgpy/molecule/generator.py
- rmgpy/molecule/generatorTest.py
- rmgpy/molecule/parser.py
- rmgpy/molecule/resonance.py
I think the net result of this is mostly that when it fails to generate kekule resonance form due to an RDKit error, it carries on silently without (just like was already done for failing to generate aromatic resonance forms). This fixes the probelm @ejtierne was having in #590.
I also created a "debugRDKitMol" function which is useful at times. We should put it in some error handlers in other places where we hit RDKit errors.
The next step would be to silence the very many `[15:01:43] Explicit valence for atom # 13 N, 4, is greater than permitted` messages that get printed to the standard error stream. This would require some fancy IO juggling like in my debugRDKitMol function. I was tempted to try this, but then came across [this blog …
> Some changes to resonance isomer generation

- rmgpy/rmg/input.py
In simpleReactor initialMoleFractions are read as float.
If totalInitialMoles != 1, RMG will log the previous and corrected mole fractions.
Fixes issue #580
Was previously labeled as https://github.com/ReactionMechanismGenerator/RMG-Py/pull/581
> initialMoleFractions are read as FLOAT if totalInitialMoles is > 1

- rmgpy/chemkin.py
- rmgpy/chemkinTest.py
- rmgpy/data/transport.py
- rmgpy/rmg/model.py
- rmgpy/species.pxd
- rmgpy/species.py
- rmgpy/transport.py
What started as a small fix led to the discovery of multiple bugs.
Summary of fixes:
- Fixes loading of all the transport data from a chemkin `tran.dat` file into the `TransportData` object
- Estimate shape index for monatomic molecules correctly within their estimation methods, not when it reaches the `saveTransportFile` function in `rmgpy.chemkin`
- Deletes duplicate `dipoleMoment`, `polarzibility`, and `Zrot` attributes from the `Species` class and closes https://github.com/ReactionMechanismGenerator/RMG-Py/issues/615
- Correctly saves the rotational relaxation number from the `TransportData` object rather than from `Species.zRot`, which never had anything saved inside.
> Fixes to TransportData

- .travis.yml
- deploy.sh
Previously, pull requests from forks lead to a failure of the deploy key decryption, and a subsequent failure of the Travis CI build of RMG-Py. 
As far as I understand, for security reasons PR's from forks are [not able](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables) to use encrypted environment variables, which is required step to push to the RMG-tests repository.
The solution offered by this PR is to move the decryption command from the `before_install` section into the deploy script. Since the deploy script will exit whenever something fails (`set -e`), it will catch such a situation. The deploy script is moved from the `script` section to the `after_success` section to avoid deploying if one of the unit tests fails.
The bad part is that PR's from forks …
> PRs from forked repo's will no longer fail Travis CI builds due to encrypted env. vars issues

- rmgpy/rmg/main.py
Work around for #602 
A cleaner way to do it is to load database before we load the species constraints. The problem is that setting species constraints is embedded in the loadInput function. loadinput is needed before loadDatabase because RMG needs to know what libraries, families, etc to load. Additionally, this would change the way we implement the "allowed" option in species constraints. Overall I think its better to just use this work around.
@nickvandewiele Can you test to see if this messes up a parallel job specifically in regards to broadcasting either the species constraints or database.
> Add work around to turn off speciesConstraints for training reactions

- rmgpy/data/kinetics/library.py
The RMG solver cannot handle more than 3 reactants or products,
and this is hardcoded within the residual and jacobian so it's not
going to change for a long time.
Closes #601
> Reaction Library and Seed Mechanism loading: Don't allow more than 3 reactants or products

- environment.yml
- environment_windows.yml
- meta.yaml
This PR ensures that people use up-to-date versions of cantera, matplotlib.
> Constrain versions of matplotlib and cantera

- rmgpy/tools/canteraModel.py
- rmgpy/tools/data/regression/benchmark/chem_annotated.inp
- rmgpy/tools/data/regression/benchmark/species_dictionary.txt
- rmgpy/tools/data/regression/input.py
- rmgpy/tools/data/regression/tested/chem_annotated.inp
- rmgpy/tools/data/regression/tested/species_dictionary.txt
- rmgpy/tools/observablesRegression.py
- rmgpy/tools/plot.py
- rmgpy/tools/regression.py
- rmgpy/tools/regressionTest.py
- scripts/checkModels.py
This PR introduces a regression module in `rmgpy.tools` that allows to run regression tests, rather than unit tests. In a later stage, regression testing will be incorporated in the RMG-tests framework, and expanded.
The regression module accepts a input file inspired by the RMG-Py input, e.g.:
```python
options(
title = 'Ethane Pyrolysis',
tolerance = 0.05
)
observable(
label = 'ethane',
structure=adjacencyList(
"""
1 C u0 p0 c0 {2,S} {3,S} {4,S} {5,S}
2 C u0 p0 c0 {1,S} {6,S} {7,S} {8,S}
3 H u0 p0 c0 {1,S}
4 H u0 p0 c0 {1,S}
5 H u0 p0 c0 {1,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {2,S}
"""),
)
observable(
label = 'methyl',
structure=SMILES("[CH3]"),
)
species(
label = 'argon',
structure=SMILES("[Ar]"),
)
reactorSetups(
reactorTypes=['IdealGasReactor'], …
```
> Regression testing

- rmgpy/quantity.pxd
- rmgpy/quantity.py
- rmgpy/quantityTest.py
Make the `ArrayQuantity` class more like the `ScalarQuantity` class in the way they store and use uncertainties as a property, with an `uncertainty_si` attribute. This eliminates confusion due to the differences in the two classes and makes `ArrayQuantity` more robust.
Also added a suite of unit tests.
> ArrayQuantity: better uncertainty handling

- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/reactionTest.py
- rmgpy/solver/liquidTest.py
- rmgpy/tools/testGenerateReactions.py
A few small changes to the way Reaction.__k_effective_cache is stored.
https://github.com/ReactionMechanismGenerator/RMG-Py/issues/271
- renaming it to k_effective_cache
- a unit test that shows the un/pickling is correctly done
The whole design of this attribute can really be improved a lot. This is only some patchwork.
> un/pickle reaction when diffusionLimiter.enabled is set to True

- rmgpy/molecule/graph.pyx
- rmgpy/molecule/moleculeTest.py
This PR contains
- fix of the non-deterministic behavior of method getSmallestSetOfSmallestRings from this [issue#638](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/638)
- unit tests for the getSmallestSetOfSmallestRings
> Fix Non-deterministic behavior of getSSSR according to issue#638

- rmgpy/rmg/model.py
of the CERM.enlarge(...) method.
Nothing is done with the generated reactions, so there is no use of
generating them in the first place.
The original algorithm did not have the reaction generation code neither,
it must have been wrongfully copied.
> Remove the reaction generation in the reactEdge is False clause

- .travis.yml
- rmgpy/qm/gaussian.py
- rmgpy/qm/gaussianTest.py
- rmgpy/qm/mopac.py
- rmgpy/qm/mopacTest.py
If distutils.spawn.find_executable returned None without raising an exception, then the previous algorithm failed.
This should fix #646 (and some of #593).
Before merging, somebody (not me? :wink:) still needs to : 
and of course, make sure the tests pass. I have not been able to test it yet.
> Fix the search for MOPAC executables.

- rmgpy/rmg/model.py
This PR is to mainly address the following two issues
- issue #490 : `source` should be hashable 
- issue #600 : `spec` should be checked if it's still in edge species list
> fix pruning issues when pdep is on

- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
This PR adds a method that converts a Molecule to Group object.
a unittest checks instance type, atom type, atom count, bond count.
> Add a method "toGroup" for the conversion of Molecule to Group objects

- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/modelTest.py
- scripts/thermoEstimator.py
When an existing RMG job is loaded and its species are used in the RMG enlargement algorithm, then one can re-use the thermochemistry of the loaded species. 
Currently, the thermo is not retained, and recomputed again, with the risk of generating thermo that is disparate from what the loaded RMG model has.
This PR checks if a species that is used as a parameter in `CERM.makeNewSpecies` has a `thermo` attribute. If it is present, it is re-used, and not generated again.
> do not recompute thermo when it is already available

- rmgpy/chemkin.py
- rmgpy/chemkinTest.py
- rmgpy/tools/loader.py
When an RMG job was loaded from an existing chem.inp and species dictionary, the current algorithm would look if next to the species names a comment was added, e.g.:
```
SPECIES
Ar                  ! Ar
He                  ! He
Ne                  ! Ne
N2                  ! N2
ethane(1)           ! ethane(1)
CH3(2)              ! [CH3](2)
S(3)             ! C[CH2](3)
C(6)                ! C(6)
END
```
If a species description in the comment section was found, it would use that as the species label, as it is often more descriptive than the chemkin name.
There are some situations where it is preferable to keep the original chemkin name as they are unique, and chemkin compatible.
This PR allows the user to specify if the labels of the loaded species should be the original chemkin name, or …
> Use chemkin names when loading an RMG Job

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
This PR addresses the issue with the (poly)cyclic node name parser, cf. https://github.com/ReactionMechanismGenerator/RMG-Py/issues/648 of `rmgpy.data.ThermoDatabase.getRingGroupsFromComments`
The PR constraints the regex by only matching outermost parentheses of a string, instead of every pair of parentheses. The latter would also hit parentheses contained in the names of polycyclic nodes.
> Improve the (poly)cyclic node name parser of rmgpy.data.ThermoDatabase

- rmgpy/rmg/model.py
The current state only of `CERM.checkForExistingReaction` compares reaction labels, which are a
concatenation of species labels. Species labels are often non-canonical strings, like SMILES or anything that is compatible with the chemkin format. As a result, there's a risk that two distinct
species may lead to the same label, leading to a false
positive match in `CERM.checkForExistingReaction`. 
This PR creates a new function, `areIdenticalSpeciesReferences` that check references
of reactants/products in both directions. It is called within `CERM.checkForExistingReaction`. It uses the lazy `any` operator that returns if one element of the parameter array is True.
> compare reactant/product references in checkForExistingReaction

- rmg.py
- rmgpy/rmg/main.py
- rmgpy/solver/liquidTest.py
- rmgpy/tools/generate_reactions.py
- rmgpy/tools/loader.py
- rmgpy/tools/testGenerateReactions.py
This PR removes 2 redundant parameters from the execute method of the RMG class. The data, i.e. input file and output directory) can already be provided to the RMG object when a new RMG instance is initialized.
> Remove redundant method parameters of RMG.execute(...)

- deploy.sh
wrong syntax for checking if the value of
the TRAVIS_PULL_REQUEST environment variable is
set to "false" in an if..then..else conditional
in bash.
> correct if..then..else conditional in deploy bash script

- examples/generateReactions/input.py
- examples/rmg/ch3no2/input.py
- examples/rmg/commented/input.py
- rmgpy/constraints.py
- rmgpy/rmg/input.py
This PR optimizes the frequently called function `rmgpy.constraints.failsSpeciesConstraints`. 
Previously, the atom count for C, H, N, ... was calculated for every molecule, regardless of whether there was a constraint in place. Now, the default value for a constraint is set to -1, so that it can be used to determine whether an atom count should be calculated or not.
> optimize the failsSpeciesConstraints function

- rmgpy/chemkin.py
When creating `Species` objects by loading a species dictionary, the `reactive` attribute of the created Species object is not explicitly stored, and results in setting the `reactive` attribute of the created Species object is set to `True` by default.
For inerts like Helium, this is incorrect.
This PR checks a hard-coded tuple with 4 elements (the usual inerts) and compares the species label to the elements in that tuple. If a match is found, the reactive attribute is set to `False` for the created species.
> Set reactive species attribute to False for inerts in loadSpeciesDictionary

- rmgpy/rmg/modelTest.py
- rmgpy/rmg/react.py
- rmgpy/rmg/reactTest.py
This PR fixes a bug mentioned [here](https://github.com/ReactionMechanismGenerator/RMG-Py/commit/c147f77a056531d7c135b66b267ae1e29d0b0919#commitcomment-17551953), which might be possibly related to [this issue](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/661) as well.
The bug stored the wrong species index as a reactant in the reaction. When the reaction is _inflated_ again, it should result in replacing the index with the wrong species. This may result in unbalanced reactions.
A number of unit tests were added, and a more comprehensive inline documentation was added to explain the functionality of the functions.
How this bug did not end up generating _more_ recent RMG crashes is really still a mystery to me, and  is being investigated.
> Fix species index bug in react module

- rmgpy/rmg/model.py
- rmgpy/rmg/rmgTest.py
This PR includes
- fix of checkForExistingSpecies for biaromatics according to [issue#643](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/643) where if the molecule has more than one aromatic rings and only some of them are kekulized, the checkForExistingSpecies will fail.By running generateResonanceIsomers in checkForExistingSpecies, it will create isomers with fully
kekulized version, which makes checkForExistingSpecies work again.
- a unittest of checkForExistingSpecies for biaromatics.
> Fix of checkForExistingSpecies for biaromatics according to issue#643

- examples/rmg/commented/input.py
- rmgpy/constraints.py
- rmgpy/molecule/adjlist.py
- rmgpy/molecule/element.pxd
- rmgpy/molecule/element.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/rmg/input.py
[edit]: I changed the adjacency list representation to `i13`, with mass in g/mol rather than kg/mol
This PR is a first step in supporting molecules with non-normal isotopes, like C-13.
Isotopic information for atoms with non-normal isotopes is represented by a `i` layer, e.g.: ethane with one carbon-13 is represented as follows:
```python
1 C u0 p0 c0 i13 {2,S} {3,S} {4,S} {5,S}
2 C u0 p0 c0 {1,S} {6,S} {7,S} {8,S}
3 H u0 p0 c0 {1,S}
4 H u0 p0 c0 {1,S}
5 H u0 p0 c0 {1,S}
6 H u0 p0 c0 {2,S}
7 H u0 p0 c0 {2,S}
8 H u0 p0 c0 {2,S}
```
This PR implements the following: 
- It writes out adjacency lists with `i`-layers, if present.
- It reads adjacency lists with `i`-layers and converts it into the correct Molecule object.
- It updates the `Atom.equivalent()` method to allow for distinguishing …
> Isotope support: reading/writing isotope-aware adjacency lists

- rmgpy/data/solvation.py
- rmgpy/data/solvationTest.py
- rmgpy/kinetics/diffusionLimited.py
- rmgpy/reaction.py
- rmgpy/reactionTest.py
The unit error regarding the diffusivity is corrected. 
Also, all the constants, such as pi, Na and kB are all replaced by the values from rmgpy.constants module. 
fixDiffusionLimitedA(T) function is added for liquid phase reactions. When it is enabled, the Pre-exponential factor A is decreased by the diffusion factor evaluated at a reaction temperature. This corrected pre-exponential factor can be used only for isothermal liquid reactions.
> Fixed unit error in liquid phase reactions and added diffusionLimiter function

- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
This is an update to pull request #582 which I will now close. 
@nickvandewiele to answer your questions, yes this will also be an issue for Carbon and possibly we never caught it earlier because CH2 singlet is less common. I updated the pull request to reflect this.
Also, I did not consider the integer arithmetic, but I think it's ok. We should not have fractional numbers of lone pairs, and I also cannot think of any situation (for carbon or silicon) where the number on the left side would be odd.
> Update lone pairs

- rmgpy/data/kinetics/family.py
See comments at
https://github.com/ReactionMechanismGenerator/RMG-Py/commit/2e2c2bedbd7135a47456be6b218659af20a7b018
> Restore a family's forbidden structures after debugging test.

- rmgpy/molecule/atomtypedatabase.py
This PR fixes a small typo in the `rmgpy.molecule.atomtypedatabase` module.
> fix typo Xd->Xdd in atomtypedatabase module

- documentation/source/users/rmg/liquids.rst
- rmgpy/data/solvation.py
- rmgpy/data/solvationTest.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
I added a new solvent attribute called molecule that stores the solvent's molecular structure and a new Species attribute called isSolvent which gives Boolean True if the species is the solvent and False if not. 
In main.py, I added new codes that check,  for every liquid phase reactions, whether any of the initial species is the solvent. If none of the initial species is the solvent, then it raises Exception with the error message. 
If the RMGPy-database is not updated (with the one containing my latest pull request), RMG will determine whether the species is the solvent or not based on the solvent's string name
If the RMGPy-database is updated with the version containing my latest pull request, RMG will determine whether the species is the solvent or not based on the solvent's molecular …
> Solvent representation

- environment.yml
- environment_windows.yml
- meta.yaml
Coolprop is a fluids property estimator (http://coolprop.org) and its binary now found on https://anaconda.org/RMG/coolprop
Adding it as a dependency in anticipation for future solvation module reliance on this program.
> Add CoolProp dependency to anaconda build and environment

- rmgpy/data/thermo.py
- rmgpy/kinetics/arrhenius.pyx
- rmgpy/kinetics/chebyshev.pyx
- rmgpy/kinetics/falloff.pyx
- rmgpy/kinetics/model.pyx
- rmgpy/molecule/group.py
- rmgpy/molecule/inchiparsingTest.py
- rmgpy/molecule/pathfinder.py
- rmgpy/reaction.py
- rmgpy/rmg/react.py
- rmgpy/species.py
- rmgpy/tools/canteraModel.py
- rmgpy/tools/observablesRegression.py
- rmgpy/tools/plot.py
Fixes https://github.com/ReactionMechanismGenerator/RMG-Py/issues/640
Initializing a class or using a mutable default object in a function leads to problems when recreating a new instance of that class.  This is one of the Python gotchas discussed here: https://pythonconquerstheuniverse.wordpress.com/2012/02/15/mutable-default-arguments/:
“Expressions in default arguments are calculated when the function is defined, not when it’s called.”
I did a regex search for functions and classes initialized with [] or {} default values and fixed their behavior.
> Fix mutable default arguments in Python functions

- rmgpy/molecule/adjlist.py
Previously error messages assumed the first line of the adjlist was a label, and gave the first line. For adjlists without a label, this was not very helpful as an error message. I have changed it so that now it prints the whole adjlist so that it is useful in both cases and likely shows the error so that user can debug faster.
> Change adjlist error message to show entire adjlist

- rmgpy/data/kinetics/family.py
- rmgpy/reduction/reduction.py
- rmgpy/rmg/model.py
- rmgpy/rmg/modelTest.py
- rmgpy/rmg/parreactTest.py
- rmgpy/rmg/pdep.py
- rmgpy/rmg/react.py
- rmgpy/rmg/reactTest.py
- rmgpy/rmg/rmgTest.py
- rmgpy/scoop_framework/util.py
- rmgpy/util.py
Before the reaction filtering modifications, the `enlarge` method would react one new core species against N existing species. After that change, the `enlarge` method would react all N core species against all N species, but filter out those combinations that would lead to negligible reactions.
The original design of the parallel generation of reactions would be used in the new O(N²) design of `enlarge`, resulting in zero speedup.
This PR fixes that by modifying the parallel design to the new structure of `enlarge`. A new function `rmgpy.rmg.react.reactAll` encapsulates the reaction generation.
A critical section in CERM.enlarge is shown here:
```python
rxns = reactAll(self.core.species, numOldCoreSpecies, unimolecularReact, bimolecularReact)
spcs = [self.retrieveNewSpecies(rxn) for rxn …
```
> Fix parallel generation of reactions

- .travis.yml
`$CONDA_ENV_PATH` variable is now deprecated as discussed in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/689
Use a different variable now so that our travis builds don't break anymore.
> Deprecate $CONDA_ENV_PATH in .travis.yml

- scripts/checkModels.py
This PR avoids AttributeError exceptions in the `scripts/checkModel.py` where rxn.family is fetched for PDepReaction instances.
> replace rxn.family by rxn.getSource() call in checkModels script

- rmgpy/data/base.py
- testing/databaseTest.py
This PR fixes a bug where matchNodeToChild (a function entirely used to check the database) was not checking atomLabels. Right now this will fail the database test on travis until the PR with the same name on RMG-database is merged.
> Strict parents

- examples/reduction/minimal/chemkin/chem_annotated.inp
- rmgpy/reduction/optimization.py
This PR adds a number of fixes:
- write the state of reduced model during the optimization. If the reduction does not converge, the intermediate states of the reduced model can be used instead.
- break if the reduced model reaches 0 zero reactions. It implies that the reduction could not be adequately carried out.
- add missing `chem_annotated.inp` in the reduction example folder.
> Write reduced model during optimization

- testing/databaseTest.py
Nothing in the official master database currently fails this test, but it can catch some errors when adding new reaction families or editing the database.
> Avoid error in database test for nodes with no parents.

- rmgpy/data/thermo.py
- rmgpy/qm/main.py
- rmgpy/qm/mainTest.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- scripts/thermoEstimator.py
This PR changes the way the quantumMechanics object is passed around throughout RMG.
In the past, the object was created upon reading the RMG input file, and passed down as a parameter throughout multiple functions.
This PR removes the QM parameter from these functions, and instead fetches it from the global RMG object. In addition, the QM object is broadcast to all available workers: when thermochemistry is calculated on a remote worker (not yet implemented, WIP), this PR allows the retrieval of the QM broadcasted object when it is needed.
_Implementation details:_
**Broadcast:**
the quantumMechanics attribute of the global RMG object is a `QMCalculator` instance. Upon reading the RMG input file, the `rmg.quantumMechanics` attribute is broadcast under the key "quantumMechanics" when it …
> Broadcast quantumMechanics 

- rmgpy/qm/gaussian.py
- rmgpy/qm/molecule.py
- rmgpy/qm/mopac.py
- rmgpy/qm/qmdata.py
This PR fixes issues with some of the qm classes:
- limit the no. of threads used by MOPAC calculations to 1 (to avoid CPU contention when concurrent thermo will be implemented)
- remove mutable argumets in QMData constructor
- remove CCLibData class and replace it by a module function. It's easier, and more pythonic. The class was not adding anything anyway.
> Fix some issues with rmgpy.qm.qmdata

- documentation/source/users/rmg/input.rst
- rmgpy/species.py
Updated the doc-strings and documentation so that users will have a better idea of what is included and excluded when using inert species.
> Add additional details on how the 'reactive' flag for species works

- rmgpy/chemkin.py
- rmgpy/pdep/configuration.pyx
- rmgpy/rmg/model.py
- rmgpy/rmg/pdep.py
- rmgpy/species.py
- rmgpy/speciesTest.py
This PR fixes a bug (cf. #718 ) that results in empty transport data files (`tran.dat`) after the recent merge of the `thermo_engine` branch. Transport data is also needed for p-dep simulations, so they would have crashed as well.
This PR replaces access of `spc.transportData` by method calls `spc.getTransportData()`. The latter checks if the transport data is available, and if not calculates the transport data on the spot.
In terms of code, I moved `generateTransportData` from `rmgpy.rmg.model.Species` to `rmgpy.species.Species`, where it really belongs. This way, `rmgpy.rmg.model.Species` becomes even more empty; only methods for stat. mech and solvent are still part of that class.
I added a unit test for the `getTransportData()` method.
> Fix bug that forgets generating transport data when needed.

- rmgpy/species.py
this PR fixes a bug introduced in d227a597e9424fd96797d337cef3b2077784f156 after merging two methods into one.
The bug only occurs in parallel runs, and was caught in the RMG-tests Travis CI builds, but not in the unit tests of this repo. It only emphasizes the importance of having unit tests with scoop enabled also working for this repo, cf. #663 (WIP). If not, the parallel functionality will be broken in no time...
> fix getThermoData method of species.Species

- examples/rmg/commented/input.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
Allows a value wallTime to be read in on the input file. After wallTime lapses the RMG job terminates and profiling data is created.
> Allow the profiling of RMG Jobs that do not converge

- cantherm.py
- rmgpy/stats.py
It's been a long time RMG cannot print out right memory info; it's always showing 
`Memory used: memory usage was unable to be logged`
Since `process.memory_info()` is returning an object instead of a tuple any more, this PR makes sure memory info is parsed properly.
> fix memory logging

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
Like for saturated species, use thermo rank to pick out the thermo and then sort by enthalpy.  Looks like the old code only fixed the saturated thermo, but still relied on the most stable enthalpy for sorting the
radical thermo which uses HBI corrections.   This would likely use the wrong thing when we calculate a polycyclic radical's thermo..
> Fix getThermoData bug for radical species: Use correct thermo prioritization for the saturated species

- rmgpy/reaction.py
The temperature range given in kinetics entries are often arbitrary
and dictated by the user.  Sometimes these temperature ranges are
very narrow.  Sometimes they fail because NASA polynomials cannot
even be evaluated at Tmin.  Fitting in a narrow range doesn't work well
because RMG will always use the kinetics if its available, even
if we are outside the temperature range.  It makes more sense
to fit to a standard temperature range.
> Always use the same temp range 294-2000K to fit reverse kinetics

- rmgpy/data/base.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/rules.py
This PR tries to fix the issue #712 by
- generating all combinations of cross-level rules
- when calculating the estimated rules, the averaging scheme is only choose distance-1 rules
> Fix tree averaging issue #712

- scripts/thermoEstimator.py
Make `thermoEstimator.py` script output files slightly easier to use.
Previously we were just writing out the chemkin-style thermo entries, and no dictionary.
Generating the full chemkin file is more useful than just the chemkin-style thermo entries. This makes
it easy to fully load the dictionary and chemkin file together to get the species thermo.
> thermoEstimator.py: generate full chem_annotated.inp and species_dictionary.txt

- rmgpy/chemkin.py
Use os.path.join instead of string concatenation for more dependable behavior.
Goes along with fixes in ReactionMechanismGenerator/RMG-website#119.
> Changes to path creation for website tools

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/rules.py
- rmgpy/rmg/main.py
After https://github.com/ReactionMechanismGenerator/RMG-Py/pull/713, we removed true verbose comments due to high memory usage.  Turns out the memory consumption was partially due to incorrect kinetic comments.  These commits try to fix the verbose comments for kinetics (turned on when the `input.py` file contains `options(verboseComments=True)`.)  This should print out all the original rule rules which actually contain data.  
Turning on `verboseComments` starts out with memory usage around 1 GB, and with it off the memory usage starts at around 300 MB.
> Fix and re-add verbose comments back to RMG

- rmgpy/data/thermo.py
- rmgpy/thermo/convertTest.py
- rmgpy/thermo/model.pxd
- rmgpy/thermo/model.pyx
- rmgpy/thermo/nasa.pxd
- rmgpy/thermo/nasa.pyx
- rmgpy/thermo/nasaTest.py
- rmgpy/thermo/thermodata.pxd
- rmgpy/thermo/thermodata.pyx
- rmgpy/thermo/thermoengine.py
- rmgpy/thermo/wilhoit.pxd
- rmgpy/thermo/wilhoit.pyx
- rmgpy/thermo/wilhoitTest.py
This PR attempts to improve the way thermodynamic quantities are exchanged during the conversion between the different HeatCapacityModel implementations: Wilhoit, NASA, and ThermoData.
In doing so, Cp0, and CpInf, the heat capacity at 0K, and infinity have been added as attributes of the superclass, HeatCapacityModel.
Fundamentally, nothing changes in the way these classes compute variables.
The client function, thermoengine.processThermoData that converts different thermo formats becomes less complicated.
> Changes to Wilhoit, NASA, ThermoData

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- testing/databaseTest.py
It's always been a limitation for RMG to estimate polycyclic thermo both quickly and accurately. Previously we have developed QMTP, which partially mitigated the issue, but still too time-consuming for cases where you have thousands of edge polycyclic species. This PR (together RMG-database `smart_polycyclic_thermo` branch) is to continue pursuing the most affordable way: group additivity method, and make specific improvements for polycyclics both data-wise (`RMG-databse`) and algorithmically (`RMG-Py`). 
Two outstanding issues of polycyclic estimation in current version of RMG:
1. not enough data: lots of species cannot find exact matches in database
2. not using available data smartly: 
- e.g., RMG gives appropriate ring correction for …
> Smart polycyclic thermo

- rmgpy/rmg/model.py
Bug was found where reaction 2 in  R_Addition_MultipleBond/training
C2H3O3 <=> C2H2O + HO2
was getting duplicated in the final model.  It appears
that we fail the checkForExistingReaction check because we typically
only check in reverse direction when the family is its ownReverse.
However, this forgets that there are some training reactions that
are in fact in the reverse direction!
Therefore we should more expand the searchRetrieveReactions()
function to generate reverse direction reactions for all families.
This may slow things down, leave optimization till later.
> Possible fix for the duplicate training reactions problem

- rmgpy/data/kinetics/rules.py
- testing/databaseTest.py
Because kinetics groups often contain parentheses, use square brackets instead inside kinetics comments for better differentiation from the actual names of the groups.  This is so that we can also parse the comments more easily later.
> Kinetics comments: use square brackets instead of parentheses

- testing/databaseTest.py
Fixing the sibling/parent check to make it a little more lenient. Should not cause accessibility errors, but will allow certain tree structures that previously threw errors.
> Sibling test

- ipython/globalUncertainty.ipynb
- rmgpy/tools/muq.py
This is a standalone global uncertainty analysis feature using the MIT Uncertainty Quantification Library (MUQ).  This module is eventually to be linked to the general Uncertainty class.  MUQ can be installed via anaconda for Linux users (although currently `~/anaconda/envs/rmg_env/lib` must be appended to the `PYTHONPATH`).  Otherwise more details relating to installation can be found on http://muq.mit.edu
The module is written inside `rmgpy.tools.muq`.  It contains two classes: `ReactorModPiece` and `ReactorPCEFactory` and the general scheme for the algorithm works as shown in the following diagram:
Any number of kinetics (k) and thermo (G) parameter uncertainties can be propagated.  Each parameter's uncertainty is considered to be a uniform uncertainty interval described by:
ln(k) ∼ …
> Uncertainty Class Part II: Global Uncertainty Analysis Module Using MUQ

- rmgpy/rmg/model.py
- rmgpy/rmg/pdep.py
Instead of looping over net reactions of all pdep networks and checking if they're in the core, loop over all core reactions and check if they're pdep.
Alternative solution for #736.
> Mark core pdep reactions as reversible

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
This PR is mainly to address the issue #611 
- checks thermo library existence when loading database instead of crashing after job starts
- adds an unit test for the change method `loadLibraries` in `thermo.py`
> Thermo library existence checking when loading database

- rmgpy/molecule/adjlist.py
- rmgpy/molecule/adjlistTest.py
- rmgpy/molecule/element.py
- rmgpy/molecule/generator.py
- rmgpy/molecule/isomorphismTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/parser.py
This PR starts with commits made by @rwest aiming to address the bond order issue for `Cbf`. The detailed issue and solution were recorded [in issue 767] (https://github.com/ReactionMechanismGenerator/RMG-Py/issues/767). 
In summary, we try to modify a little to the current benzene bond order assignment: dynamic bond order depending on how many benzene bonds an atom has; if atom has three benzene bonds, the bond order for each benzene bond is 4/3, while other cases, the benzene bond order stays unchanged. This fix will have fused aromatics parsed correctly from adjacencylist.
In addition, 3 fused aromatics unittests and 1 adjacencylist unittest are added to make sure new changes are valid. so this PR includes
- new way of assigning benzene bond order
- additional unittests for fused …
> Dynamic benzene bond order to fix issue #767

- documentation/source/users/rmg/input.rst
- examples/rmg/commented/input.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
By default (if 'False') will force all library reactions to be reversible. If set to 'True' in the options section in the input file, will keep library reversibility as is.
> Added the keepIrreversible option

- testing/databaseTest.py
This fixes a unit test in databaseTest. It won't pass travis until the RMG-database commit called entryAcessibility is merged.
> Fix bug with checking parent/child relationshps in databseTest

- rmgpy/chemkin.py
- rmgpy/molecule/element.pxd
- rmgpy/molecule/element.py
- rmgpy/molecule/elementTest.py
- rmgpy/molecule/util.py
This PR adds support for isotope information in chemkin files.
Specifically:
- a new attribute `chemkinName` in the Element class ensures that chemkin-compatible element symbols are written. Chemkin only allows up names of to two characters long, so alternative had to be provided for longer, more straightforward names like "C-13".
- Writing the elements section of the chemkin file is refactored in its own function. However, rather than searching for all unique elements (and isotopes) among the species of the model, the elements are still hard-coded, for efficiency reasons. 
- the utility function `retrieveElementCount` of the `rmgpy.molecule.util` module now supports isotopes as well. That is, non-normal isotopes like C-13 will not be counted as a normal carbon atom, but as a separate key …
> Support for isotope information in chemkin files

- rmgpy/qm/gaussianTest.py
This PR is trying to address issue #775. 
The reason why the first two tests fail is they lack shutil import. The third one needs `g09` installed so that `pm6` can be run. 
Code reviewer can test them on pharos slave node (head node doesn't allow normal users to `mkdir` under /scratch), but since pharos has no `g09`, error like `Segmentation fault` will be observed when you run the third test.
> fix gaussian tests being out of date

- rmgpy/solver/files/liquid_phase_constSPC/input.py
- rmgpy/solver/liquidTest.py
Remove some redundant code in from the test method so that we actually test `initialize()`. Previously, the test would have continued to pass even if `initialize()` were to be modified.
Also switch to use a reduced input file that does not load kinetics families, which greatly reduces test time. Testing on my computer (in a VM) showed a reduction in time from ~170 to ~120 s for the entire test suite. However, I'm not really sure how that happened, since running the original test by itself only took ~20 s. (Possibly due to overhead from using nose and coverage?)
Addresses #786
> Fix and speed up test_liquidInputReading

- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
- meta.yaml
- requirements.txt
- rmg.py
I removed the dependencies of `guppy` and `symmetry` from requirements file after noticing that they are not being used, nor can they currently function, in RMG. 
I tested if RMG still functioned by running `conda remove guppy symmetry` and then `make test`. All the tests passed.
> Remove guppy and symmetry packages

- .travis.yml
Previously we always use the latest miniconda, but occasionally it breaks travis, we'd like to use stable version instead to give stable travis performance.
> change to stable miniconda

- environment_linux.yml
This PR relaxes the requirement for version of libgfrotran to be higher or equal to 1.0, so that numpy and rdkit and cantera can be upgraded, finally will fix issues like #796
> update environment yaml to allow pkgs (numpy, rdkit, cantera) upgrade

- deploy.sh
last commit msg will be used for triggering RMG-tests, RMG-database has the format of last commit msg as `rmgdb-SHA`, to be more consistent, make same style for deployment from RMG-Py.
> make standard last commit msg for RMG-tests

- rmgpy/rmg/main.py
This PR is to fix two typos (`unimolecularReact`, `bimolecularReact`) involved in `reaction filtering`.
> fixed two typos in clear()

- rmgpy/rmg/input.py
This PR tries to address issue #783 that currently users are not allowed to use their own transport libraries. With this patch, everything stays same if user doesn't specify the argument `transportLibraries` in input file. But if one specifies, RMG will use the specified ones.
> enable users to select customized transport liraries

- documentation/source/users/rmg/installation/faq.rst
That's the FAQ at 
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/faq.html
not the one at 
http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/faq.html
I'm not quite sure that we need to have two, but I'll leave merging them to someone else for now.
Closes #817
> Added another entry to the FAQ for issue #817

- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
- meta.yaml
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/resonance.pxd
- rmgpy/molecule/resonance.py
- rmgpy/molecule/resonanceTest.py
This PR is not ready for merging yet, but I'm opening the request so it can start being reviewed.
This is the first part of an overhaul of resonance structure generation in RMG. This PR does not actually affect any functionality. It only adds methods for Clar structure generation that will be actually integrated into the resonance algorithm in the second part.
The motivation behind using Clar structures is the lack of a consistent and deterministic resonance structures for polycyclic aromatic compounds. We currently have a fully delocalized structure, where all bonds in rings are benzene bonds. This works well for thermo estimation because it's consistent with Benson group additivity, but it is not great for kinetics since bonds in PAHs can have different reactivity depending on location …
> Resonance Part 1: Clar Structure Generation

- rmgpy/molecule/resonanceTest.py
For this test, two Clar structures are expected, and were being checked for isomorphism against two test structures. Because the ordering of structures is non-deterministic, the test checks both output molecules against both test molecules, but there was a typo in indexing that caused the test to fail sometimes.
> Fix typo in ClarTest.testPhenalene

- rmgpy/cantherm/pdep.py
- rmgpy/cantherm/statmech.py
- rmgpy/cantherm/thermo.py
- rmgpy/chemkin.py
Addresses #789 
Eliminate standalone Chemkin output writing scripts in Cantherm and use the more robust scripts in `rmgpy.chemkin`. In order to write element counts, atom information from StatmechJob is saved to `species.prop`, then used when writing the thermo output.
Also includes some minor alignment changes when writing Chemkin thermo blocks. The alignment was changed in this commit (e1374f3378473dfbca126299abcf63e44717ccb4), but the original alignment matches Chemkin documentation better. The output has been tested in Chemkin to be extra sure that it still works fine.
Before:
```
C2H4                    H 4  C 2            G10.000    3000.000  764.98        1
```
After:
```
C2H4                    H   4C   2          G    10.000  3000.000  764.98      1
```
> Improve Chemkin output from Cantherm jobs

- rmgpy/cantherm/main.py
This PR updates the cantherm header to address issue #828 
- always have version number aligned with RMG-Py
- correct PI list
- correct website
> update cantherm header

- scripts/checkModels.py
This PR fixes the order of returned values from `diff_models.execute()` used in `checkModels.py`, which RMG-tests relies on.
> fix the order of returned values from diff_models.execute

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/molecule/molecule.py
When estimating radical thermo via HBI, RMG will look for the saturated species in libraries. If only some of the saturated molecules are found in a library, then the ones that were not found get dropped from the list when reordering the molecules based on thermo. This leads to failed isomorphism checks and duplicated species, as seen in #577 and #831.
This fixes the issue by adding any non-matched molecules back into the list.
> Fix bug when reordering molecules after HBI thermo calculation

- rmgpy/molecule/group.py
This PR adds a method `_repr_png_` for `Group` class. We've already had this method developed for `Molecule` (and also `Species`) and `Reaction`, from which we benefit rendering molecules and  reactions in ipython notebook.
Recently there's been requests for easy rendering `Group` in ipython notebook as well. This PR attempts to address that.
> make group easy to display in ipython notebook

- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
We've been adding lots of jupyter notebooks in RMG for functionality demos, but haven't added `jupyter` as RMG's dependency, which requires users to install `jupyter` within the `rmg_env` manually. Sometimes it creates unnecessary confusions. 
This PR is to officially add jupyter as RMG's dependency and eliminate jupyter installation confusion.
> adds jupyter as RMG's denpendency

- rmgpy/data/thermo.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
Previous bicyclic decomposition works well on most large polycyclics. But the algorithm gets confused by some interesting examples listed below.
In the first example, will the 5-member ring go with the 6-member ring containing O or go with 6-member ring containing S? 
In the second example, will the 4-member ring sharing 2 atoms with the 7-member ring get picked or the one sharing 3 atoms with the 7-member ring?
The previous algorithm cannot deal with these two well and give bicyclic decomposition results non-deterministically.
This root problem with this is that the method of `getSSSR` has non-deterministic behaviors, which is also mentioned by the authors of [this method](http://pubs.acs.org/doi/abs/10.1021/ci00015a002). Simply put, if the algorithm finds two candidate rings, both of …
> A more deterministic way of bicyclic decompostion

- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
The calculation of lone pairs was wrong for the N1s atom type,
and could potentially be worng for some of the new sulfur atom types
which will soon be introduced in RMG.
This PR fixes the calculation of the number of lone pairs by using
the valence electrons of an element. An error will be printed
in case the number of lone pairs isn't an integer.
The previous calculation resulted in 3 lone pairs for N1s (where it should only have 2):
atom1.lonePairs = 4 - atom1.radicalElectrons - int(order) = 4 - 1 = 3
The new calculation will give (5-1)/2 = 2 for N1s.
The new calculation will to be identical for carbon \ oxygen \ silicon.
> Correcting updateLonePairs

- scripts/checkModels.py
This bug has existed for a long time that error messages for test model and original (benchmark) model are swapped. This PR fixes that. Currently, this module is only used by RMG-tests.
> fix the bug where original model msg swaps with tested one

- documentation/source/users/rmg/running.rst
- rmgpy/restart.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/rmgTest.py
This PR fixes the issue of restart file generation failure caused by `reaction.reverse` being deleted #822 . The patch 
- replaces `delattr(reaction, 'reverse')` with `reaction.reverse = None`
- adds a unit test for restart file generation
- adds restart documentation to address issue #877
> fix restart file generation

- rmgpy/rmg/main.py
- rmgpy/rmg/rmgTest.py
This PR address the follow-up request from #878 that parsing the generated restart file needs to be tested. So it 
- extends the previous restart unit test with additional parsing step
- refactors restart code to be more modulized (divides original loadRestartFile into two parts: reading and integrating into runtime RMG object)
> Restart code refactor and parsing test

- rmgpy/cantherm/statmech.py
In order to run CanTherm with BAC for nitrogen species in CBS-QB3, some corrections are added in this PR:
Added `N-H`, `C-N` from Table IX in http://jcp.aip.org/resource/1/jcpsa6/v109/i24/p10570_s1 for CBS-Q method
and `N=O`, `N-N`, `N=N`, `N-O` from Table 2 in R. Ashcraft, S. Raman, W.H. Green J. Phys. Chem. B, Vol. 111, No. 41, 2007
> Added BAC for nitrogen and sulfur in statmech.py

- rmgpy/data/kinetics/family.py
- rmgpy/data/solvation.py
- rmgpy/data/thermo.py
- rmgpy/molecule/adjlist.py
- rmgpy/molecule/adjlistTest.py
- rmgpy/molecule/generator.py
- rmgpy/molecule/group.pxd
- rmgpy/molecule/group.py
- rmgpy/molecule/groupTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/parser.py
- rmgpy/molecule/parserTest.py
- rmgpy/molecule/resonance.py
- rmgpy/molecule/resonanceTest.py
This pull request refactors RMG's Bond and GroupBond classes to represent bond order with a float instead of a string. This allows more flexibility with regards to representing bonds and reduces hard-coding of 'S', 'D', 'T', 'B' cases. In addition, I added methods to allow for back conversion if necessary.
This also modified methods that utilizes the order of molecule objects. The reading and writing of adjacency lists still involves string characters, so most of the database is intact and usable. The recipe actions of FORM_BOND, BREAK_BOND, and CHANGE_BOND now involve numbers instead of strings, so an [RMG-database pull request](https://github.com/ReactionMechanismGenerator/RMG-database/pull/156) involves the change of reaction recipes for each reaction family to address this problem. …
> Bond and GroupBond store bond order as float

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/rmg/model.py
Transition state theory asserts that identical reactants should double the symmetry number of a reaction (if not changing transition state geometry), essentially making them twice as fast. See [Fernandez-Ramos et al.](http://link.springer.com/10.1007/s00214-007-0328-0) for a review of reaction symmetry numbers. 
RMG currently doesn't account for this difference. Here is a [symmetrical reaction](http://rmg.mit.edu/database/kinetics/families/R_Addition_MultipleBond/rate_rules/reactant1=multiplicity%202%0A1%20%20C%20u0%20p0%20c0%20%7B2,S%7D%20%7B3,S%7D%20%7B8,S%7D%20%7B9,S%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B4,S%7D%20%7B6,S%7D%20%7B7,S%7D%0A3%20%20C%20u0%20p0%20c0%20%7B1,S%7D%20%7B5,D%7D%20%7B10,S%7D%0A4%20%20C%20u1%20p0%20c0%20%7B2,S%7D%20%7B11,S%7D%20%7B12,S%7D%0A5%20%20C%20u0%20p …
> Degeneracy fix for identical reactants

- rmgpy/molecule/group.py
- rmgpy/molecule/groupTest.py
This method needed to be updated following the switch to floats for bond orders.
> Fix Group._repr_png_()

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
`polycyclic.py` mainly contains bicyclic entries so that most large cyclics can decompose into bicyclics and use some tested formula to estimate their ring corrections. But we also include some important tricyclics so that if target molecules match one of the included tricyclics, it doesn't have to go through bicyclic decomposition.
@zjburas recently reported the issue where tricyclics in `polycyclic.py` cannot be matched directly. The reason is we put our limited number of tricyclics in the second level of tree, the algorithm will pick the entry with deepest level if multiple entries are matched. So what's really happening for tricyclics is although exact match can be found but it's second level, RMG will consider some partial match with deeper levels.
This is fixed by this PR by …
> Enable matching tricyclics stored in polycyclic.py

- rmgpy/chemkin.py
This PR is just a small change to add more helpful warning message when duplicated reactions are found; it lists out the duplicate counterparty (original ones) together with the duplicates.
> add duplicate counterparty in the warning message to help debug

- rmgpy/rmg/rmgTest.py
Remove the restart file generated by unit test before exiting the test
> remove temporary restart file generated by unittest

- rmgpy/molecule/adjlist.py
- testing/databaseTest.py
I checked for all instances of `bond.order` in rmgpy, as requested by @mjliu and found two discrepancies, one of which was alluded to in #898 and #899. The other one improves the robustness of databaseTest.
> Bond order fix

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/data/kinetics/family_test_data/intra_H_migration/groups.py
- rmgpy/data/kinetics/family_test_data/intra_H_migration/rules.py
- rmgpy/data/kinetics/family_test_data/intra_H_migration/training/reactions.py
- rmgpy/molecule/pathfinder.pxd
- rmgpy/molecule/pathfinder.py
This pull request introduces some new functions which will be used in database tests for unimolecular families requiring them to adhere to stricter rules about their formatting. 
Specifically, families that use a backbone/end groups like structure will have the following features:
1. End groups must have all the labels of their root entries
2. Backbones must have all the labels of connected end groups
3. Backbones must use the generic root entries as end groups, such that they are not both defining the backbone and ends
4. Backbones must label all atoms along the shortest path between end groups
> Unimol format tests

- rmgpy/molecule/draw.py
- rmgpy/molecule/drawTest.py
- rmgpy/molecule/group.py
- rmgpy/molecule/groupTest.py
- rmgpy/molecule/molecule.py
- rmgpy/pdep/draw.py
This PR contains minor refactoring of `MoleculeDrawer` and `Group._repr_png_()` to give more flexibility in creating drawings. The motivation for these changes is to allow the website to display svg images instead of png images.
MoleculeDrawer has been refactored to allow saving to file-like objects, which enables writing the drawing to an HTML response object or a string buffer.
The main drawing algorithm in `Group._repr_png()` has been separated into a new function `Group.draw()` which accepts an additional format argument. `Group._repr_png()` now calls `Group.draw()` with 'png' as the format specifier.
> Improve flexibility of Molecule and Group drawing algorithms

- rmgpy/data/kinetics/database.py
Including a notice that the KlippensteinH2O2 kinetic library was deleted
and replaced by BurkeH2inN2 and BurkeH2inArHe, for people whose old input
files were using it, so that they get a more helpful error message if
they try to request it once it's gone.
Related to https://github.com/ReactionMechanismGenerator/RMG-database/pull/168
> Including a notice that KlippensteinH2O2 was deleted

- rmgpy/cantherm/statmech.py
At the suggestion of @rwest updates the references in CanTherm for the spin orbit correction to the more permanent doi URL. Address #924
> Update the URLs for CanTherm reference for SOC to more stable doi URL

- rmgpy/molecule/resonance.py
The lpsolve module redirects interrupt signals to a custom handler, and this change is persistent in python until another change is made. This fix resets the handler to the one that was in use prior to calling lpsolve.
This restores the ability to send KeyboardInterrupt signals to stop an RMG job.
> Fix signal handling after calling lpsolve

- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
- meta.yaml
- requirements.txt
- rmgpy/chemkin.py
- rmgpy/chemkinTest.py
I started out trying to write tests for each untested line, but I realized that it wasn't really helping. A major untested part was writing chemkin files, so I added some additional checks to existing tests. The end result was only +6% coverage within chemkin.py. To increase coverage more, we need to test reading and writing the other kinetics formats besides Arrhenius and Chebyshev.
> Add unit tests to chemkinTest

- rmgpy/data/thermo.py
Including a notice that the KlippensteinH2O2 thermo library was deleted
and replaced by BurkeH2O2, for people whose old input
files were using it, so that they get a more helpful error message if
they try to request it once it's gone.
This is complementary to a similar note we already added for the kinetic KlippensteinH2O2 library.
> Including a notice that KlippensteinH2O2 thermo library was deleted

- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/parser.py
- rmgpy/molecule/parserTest.py
This PR is just one side of fix for `CH` issue. As mentioned in #949 and RMG-database issue [#172](https://github.com/ReactionMechanismGenerator/RMG-database/issues/172), the major part of the change would be to eliminate the inconsistencies of `CH` in database.
The PR [#175](https://github.com/ReactionMechanismGenerator/RMG-database/pull/175) for RMG-database to be merged with this PR together.
> Fix CH ground-state representation

- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/qm/mopacTest.py
Some basic unit-tests for data/kinetics and mopac
the changes to mopac.py cause mopac to verify its output files after its test runs
in data/kinetics/kineticsTest.py
* testFilterReactions - tests that filterReactions output includes all of the reactions it should
* testSaveEntry - tests that running saveEntry on reactions does not produce an error
* testDuplicates - tests that kinetic libraries load properly and that the duplicate management functions do not give false positives
> Kinetics and mopac unittests

- environment_windows.yml
Now these two binaries are available in RMG channel, this PR allows users to install these two directly when creating `rmg_env` environment, solving the issue #960
> windows environment file to include cairo and cairocffi 

- examples/generateReactions/input.py
- examples/rmg/ch3no2/input.py
- examples/rmg/commented/input.py
- ipython/generateReactions.ipynb
KlippensteinH2O2 was the name of a thermo and kinetics library that was recently updated and renamed to BurkeH2O2.py (thermo) and BurkeH2O2inArH2/BurkeH2O2inN2 in [this PR](https://github.com/ReactionMechanismGenerator/RMG-database/pull/168).
This PR reflects these changes to the example files in RMG-Py
> Update name of KlippensteinH2O2 in example files

- rmgpy/data/kinetics/library.py
We're checking that the index number of each library reaction is unique,
but we output a misleading message suggesting that the reaction itself isn't unique.
This minor PR fixes the assertion error message.
Might speed-up debugging when creating new libraries.
> Changed assertion message when library rxn isn't unique (minor fix)

- ipython/localUncertainty.ipynb
Instructs user that they must use the annotated chemkin file.
> Add Comment Stating that Annotated Chemkin File is Necessary

- documentation/source/users/rmg/input.rst
- examples/rmg/commented/input.py
- rmgpy/rmg/input.py
- rmgpy/rmg/inputTest.py
This PR converts a lists of reaction libraries strings to the
`('text',False)` tuples in the `rmgpy/rmg/input.py/database` method.
This allows more intuitive input files to be written and used.
> Allow users to input lists of strings for reactionLibraries

- rmgpy/molecule/generator.pxd
- rmgpy/molecule/generator.py
- rmgpy/molecule/graph.pxd
- rmgpy/molecule/graph.pyx
- rmgpy/molecule/graphTest.py
- rmgpy/molecule/kekulize.pyx
- rmgpy/molecule/kekulizeTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/resonance.pxd
- rmgpy/molecule/resonance.py
- rmgpy/molecule/resonanceTest.py
- setup.py
I'm reopening this pull request, since I still think these resonance fixes have higher priority than the react benzene changes, so they should be reviewed separately and merged first. I've included the new kekulizr module in this pull request because some of the fixes rely on it.
Changelog:
- Add kekulize module for generating Kekule structures.
- Add `getAllSimpleCyclesOfSize()` method to only retrieve monocyclic rings.
- Use `getAllSimplesCyclesOfSize()` instead of `getSSSR()` for ring retrieval to improve robustness of aromaticity detection.
- For bridged polycyclics, the SSSR is not deterministic and can return different sets of rings. Using `getAllSimpleCyclesOfSize()` gives more consistent output.
- Improve generation of aromatic resonance structures when one ring in a polycyclic …
> Resonance Fixes

- rmgpy/thermo/nasa.pyx
The NASA class calls the NASAPolynomial methods, which return the thermo in
J/mol or J/mol-K. However, the NASA Class claims erroneously that it returns
the dimensionless versions.
> Update NASA Class Docstrings for Returning Thermo in J/mol

- rmgpy/data/kinetics/family.py
Added the CO_Disproportionation family to getReactionPairs().
More details about this family in the [corresponding database PR](https://github.com/ReactionMechanismGenerator/RMG-database/pull/184).
The temp change to the .travis.yml file should be removed before merging.
> CO Disproportionation family (Py)

- .travis.yml
- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/rmg/input.py
- rmgpy/rmg/inputTest.py
- rmgpy/rmg/main.py
- rmgpy/thermo/thermoengine.py
This PR introduces an interface to thermo central database, which is designed as a first step to solve inaccurate themo estimation problems for crazy-structured species (potentially can also be expanded to other species spaces where RMG is not familiar with, e.g., sulfur nitrogen compounds).
The whole workflow would include:
- identify target species (e.g., crazy-structured, no exactly matched groups)
- connect to thermo central database
- check if it exists (can fetch thermo if there's results) or not (insert this species to database registration table)
- automatically launch quantum mechanics calculations for registered species (this step is not included in this PR)
The **only requirement** from user who is willing to use the functionality is add an authentication block in RMG …
> Thermo Central Database Interface

- rmgpy/data/transport.py
- rmgpy/data/transportTest.py
- rmgpy/transportDataTest.py
Use `getTransportPropertiesViaLennardJonesParameters`, like would be done in a normal RMG job.
This fixes issues with generating transport properties on RMG-website.
> Add fallback for transport search if group additivity fails

- testing/databaseTest.py
One very specific case would throw an error, but had not elucidating text:
-L2 level class:`Group` with top level class:`LogicOr` as apparent parent
-`LogicOr` did not include the L2 level `Group` inside its definition
-L2 level `Group` was still in tree regardless
> Add one fringe case test to databaseTest

- rmgpy/molecule/draw.py
There has clearly been some thought put into how to align the reactions as seen [here](https://github.com/ReactionMechanismGenerator/RMG-Py/commit/bb3904eb4e7961c2a0935234441df2038a37bd66) and [here](https://github.com/ReactionMechanismGenerator/RMG-Py/commit/d29d620a0bf20253b59bca9a80cffae16e42aaff), although I can't follow the implementation's logic. The end result does look better than just centering every object. 
However, sometimes the algorithm for aligning species would draw a molecule above the `rxn_y =0.0` line, making part of the species above the limits of the image. This PR adds an `if` statement that will catch these cases and set `rxn_y = 0`.
> Add bugfix for alignment of species when displaying reactions

- rmgpy/molecule/resonance.py
When RMG is not run on the main thread (eg. for RMG-website), signal cannot be set and will raise an exception.
> Add try/except for resetting signal after calling lpsolve

- .travis.yml
- Makefile
- rmgpy/data/thermoTest.py
This PR provides a solution for #1035, which categories tests into tests requiring authentication and internet and tests that don't require. It's done using `nose attribute` decorator.
It also reorganizes the test modes in makefile:
- `make test` only runs tests that don't require authentication, designed for general users and develoers with no internet.
- `make test-all` runs all the tests, designed for developers and travis
> categorize tests with authentication requirements

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
We currently reorder the molecules in a `Species()` object when we generate thermo from GAV or HBI to match the order of the thermo estimates based on H298. However, we don't do any reordering when getting thermo from a library. This PR changes `getThermoDataFromLibrary()` to move the matched molecule to the first position in the molecule list.
Reordering molecules affects kinetics estimation in the current algorithm, as explained in #494. While that issue is still yet to be solved, this change should at least make behavior more consistent regardless of the thermo source.
> Reorder molecules when getting thermo data from library

- rmgpy/statmech/torsion.pyx
Modified funtion in torsion.pyx, Function name
FitFourierPotentialToData; new function now begins with twelve fourier
parameters, and adds two fitting parameters every single time a negative barrier
height is found to avoid errors.
> Changed Fourier Fitting in Cantherm

- documentation/source/users/rmg/thermo.rst
- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
- rmgpy/data/kinetics/common.py
- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/molecule/adjlist.py
- rmgpy/molecule/adjlistTest.py
- rmgpy/molecule/draw.py
- rmgpy/molecule/drawTest.py
- rmgpy/molecule/generator.py
- rmgpy/molecule/graph.pxd
- rmgpy/molecule/graph.pyx
- rmgpy/molecule/graphTest.py
- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/resonance.py
- rmgpy/molecule/symmetry.py
- rmgpy/molecule/symmetryTest.py
- rmgpy/molecule/vf2.pxd
- rmgpy/molecule/vf2.pyx
- rmgpy/molecule/vf2Test.py
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/reactionTest.py
- rmgpy/species.pxd
- rmgpy/species.py
- rmgpy/speciesTest.py
This PR expands RMG's ability to estimate symmetry numbers for resonance structures and cyclic compounds.
1. Symmetry numbers used in thermo come from Species objects, not molecule objects
1. When estimating the symmetry number of a Species, a hybrid resonance structure is created that is the average of all the bond orders of various resonance structures.
1. Redid how RMG calculates cyclic symmetry numbers, fixing #858, #119 (and reducing computational time by 50%).
1. Allow for float inputs to Adjacency Lists for the bond order (in addition to the strings). 
1. Updated to a newer cython version for increased functionality
1. Allowed for partial bonds to be represented with dots in ipython notebooks
1. Some doc-string fixes and other functionality improvements.
> Symmetry corrections

- examples/diffModels/Models/DFT_chem.inp
- examples/diffModels/Models/DFT_species_dictionary.txt
- examples/diffModels/Models/Primary_chem.inp
- examples/diffModels/Models/Primary_species_dictionary.txt
- examples/diffModels/example.sh
- rmgpy/rmg/output.py
- rmgpy/tools/diff_models.py
- scripts/diffModels.py
I was using this tool on a large mechanism, and it took forever to weed through all of the identical species and reactions. I added two new methods for controlling the level of output to the HTML file.
By using the `--diffOnly` flag the script will not show any identical species or reactions. By using the
`--commonDiffOnly` flag the script goes one step further and does not show species and reactions that are unique to one of the models.
I also fixed the doc strings, which had some issues.
> Diff models customize output

- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/data/solvationTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/rmg/mainTest.py
- rmgpy/rmg/model.py
- rmgpy/rmg/modelTest.py
- rmgpy/rmg/react.py
- rmgpy/rmg/reactTest.py
- rmgpy/rmg/rmgTest.py
- rmgpy/solver/liquidTest.py
- rmgpy/species.pxd
- rmgpy/species.py
- rmgpy/test_data/testing_database/kinetics/families/H_Abstraction/groups.py
- rmgpy/test_data/testing_database/kinetics/families/R_Addition_MultipleBond/groups.py
- rmgpy/thermo/nasaTest.py
- rmgpy/thermo/thermoengineTest.py
- rmgpy/thermo/wilhoitTest.py
- rmgpy/tools/fluxtest.py
- rmgpy/tools/regressionTest.py
- rmgpy/tools/testSensitivity.py
This PR solves two related problems in RMG: reaction degeneracy values that take into account resonance structures and allows multiple transition states to be stored in RMG's output file. This PR will solve underterminable kinetics problems (#494) , muptiple TS (#323, #142), and proper degeneracy values (#876, #833, #619, #552) . These two problems both involve updates to the degeneracy-finding algorithm, which is why they are in one PR. The major modification for this pull request is the order in which the generate reactions steps take place. The reactions of all resonance structures are now generated before algorithms like degeneracy or finding reverse kinetics are run. In addition, the degeneracy algorithm was redone to take into account which atoms have actually been switched (this …
> Degeneracy & Multiple TS

- examples/rmg/minimal_dynamics/input.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/solver/base.pxd
- rmgpy/solver/base.pyx
- rmgpy/solver/liquid.pyx
- rmgpy/solver/simple.pyx
This pull request implements the dynamics criterion.  The dynamic criterion is designed to work alongside the flux criterion, but instead considers how edge reactions affect core concentrations rather than the formation rates of edge species.  The dynamics criterion moves edge reactions (all species in a given edge reaction) rather than a single edge species to the core.
> Dynamics criterion (AcceleratorTools part 1)

- documentation/source/users/rmg/installation/anacondaDeveloper.rst
This prevents users from getting 'unable to find module rmgpy' issues when installing.
I made this mistake 2 years ago. Time it got fixed for posterity.
> added warning to change folder name during installation

- ipython/canteraSimulation.ipynb
- rmgpy/reaction.py
- rmgpy/reactionTest.py
- rmgpy/species.py
- rmgpy/speciesTest.py
- rmgpy/tools/canteraModel.py
- rmgpy/tools/canteraTest.py
- rmgpy/tools/muq.py
Added an option to 'toCantera' methods in Species and Reaction
to allow for the name of the species/reaction to be the RMG name
instead of the chemkin name. The default behavior is still the same.
We can still not create cantera input files with RMG names. This PR is just one step in addressing issue #1065.
> allow cantera objects to use RMG names

- rmgpy/data/base.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/groups.py
- rmgpy/data/kinetics/rules.py
this enables the assignment of nodalDistance values to the distance between a given node and its parent with the rate rule trees.  Default these values are 1, but in a group file default values for each tree can be set by setting the treeDistances variable 
ex: treeDistances = [1,2,5]
and the values can be directly assigned as inputs to any individual entry
ex:
Entry( .......
nodalDistance=5,
)
Kinetics averaging and estimation have been extended to work with trees where the nodes are different distances apart. 
Nodal averaging is only done between the nodes that are closest to the parent.  But this may be changed later.  
This pull also fixes some issues with the original implementation of the 2-norm (it only compared distances one step out at a time so it would pick [2,0,0] over …
> Nodal distances

- rmgpy/rmg/model.py
- rmgpy/rmg/react.py
deflate now checks all resonance structures before deflating
reaction objects. This is meant to solve issue #1077, if it is
caused by resonance structures when deflating.
Deflate could use species objects in the future, but we currently
don't have an equals or hash function for species.
> allow all resonance structures to be used in deflating

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/groups.py
This pull request enables reaction group additivity to be trained on the current training reactions and trees and estimateKineticsUsingGroupAdditivity to be called on a given template.  
Note this does not in anyway activate group additivity kinetics, it just makes it so that the functions needed to do so run.
> Revive Reaction Group Additivity

- rmgpy/reaction.py
Should fix #1086
Now ought to address the problem of exothermic reactions 
giving negative activation energies as a result of Evans-Polanyi
expressions for any value of E0  (previously it only worked if E0>0).
The aim of this code is as follows:
Calculated Ea values are allowed to be as negative as E0 if E0 
is negative, but if E0 is positive then Ea cannot be below 0.
> Changes to fixBarrierHeight

- deploy.sh
This PR tries to fix the issue #1091 , where Travis fails to detect that unittests are already finished.
The reason is that in `deploy.sh` we run `ssh-agent -s` which creates a child process that is listened/waited by Travis; even with all the tests finished, travis still thinks there's something going on. 
The solution is to kill `ssh-agent` after all the steps done.
> kill ssh-agent process after travis deploys RMG-tests 

- documentation/source/users/cantherm/input.rst
- rmgpy/cantherm/statmech.py
Since we've been increasingly using M06-2x for thermo calculations, this PR tries to expands model chemistry set that cantherm allows by adding M06's atom energies.
One might be interested in how we get these numbers; they are from single atom calculation using the level of theory you want. The assumption for the multiplicity of each atom is: H singlet, C triplet, O triplet, N quartet, S triplet, P quartet.
> added atom energies for m06-2x model chemistry

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/rules.py
this PR fixes nodal distance comments so they appear on a new line
in the chemkin comments. This allows accurate parsing of comments
where one line corresponds to one piece of information, and is
necessary for PR #1076 to be successfully merged in.
> add new line to nodal distance comments

- rmgpy/cantherm/qchem.py
Seems that this line was left unintentionally from an older version of
this file. Causes an error when using the QchemLog() function in
CanTherm for nitrogen containing species:
```
number[i] = 7
IndexError: list assignment index out of range
```
This line was removed in this commit.
> minor: correction to atomic number format for N in qchem.py

- rmgpy/cantherm/pdep.py
- rmgpy/reaction.pxd
- rmgpy/reaction.py
Previously no info of the reaction type (library/family) was given in network.py files generated by Cantherm during an RMG run. This small PR adds such a comment to each reaction() function in PDep network files.
> Added info of reaction type to PDep network files

- rmgpy/solver/simple.pyx
This variable is unused and apparently appears to be the source of a compiling issue for @amarkpayne.
> remove unused “specificColliderEfficiencies” variable from simple.pyx

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/rules.py
- rmgpy/kinetics/arrhenius.pxd
- rmgpy/kinetics/arrhenius.pyx
- rmgpy/kinetics/arrheniusTest.py
There are already locations in the code where Arrhenius is converted into ArrheniusEP. This commit allows for one central location to do the conversion. 
I replaced the instances where the conversion currently happens.
I added a new instance when loading rate rules that have Arrhenius objects.
Sidenote: for some reason loading some parts of the database were not working for me (example testGenerateReactions), and this PR fixed it.
> Added method from arrhenius to Arrhenius ep

- documentation/source/users/cantherm/output.rst
- examples/cantherm/networks/n-butanol/input.py
- examples/cantherm/reactions/H+C2H4=C2H5/input.py
- rmgpy/cantherm/main.py
- rmgpy/cantherm/pdep.py
- rmgpy/chemkin.py
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/reactionTest.py
This PR allows the chemkin input file created during a cantherm run to be ready to use in chemkin/cantera. The major changes are:
1. changed order of running cantherm jobs to run species and thermo before pdep and kinetics.
2. adding headings and labels for chemkin input files.
3. modified the pdep output to not contain both forward and reverse reactions, so it is valid when output. The unused reactions are commented out.
4. updated documentation explaining the chemkin file and changes to pdep output.
When reviewing this PR, it would be helpful if you could run one of your own cantherm jobs to see if you get the intended outcome. Alternatively, you could run n-butanol and H+C2H4 examples to get complete chemkin files or acetyl+O2 to view the pdep changes. You can test the validity of …
> allow cantherm to create valid chemkin files

- examples/cantherm/species/Toulene/input_toluene_FreeRotor.py
- examples/cantherm/species/Toulene/toluene_FreeRotor.py
- examples/cantherm/species/Toulene/toluene_HinderedRotor.py
- rmgpy/cantherm/statmech.py
Two example files for cantherm had C=H. Those were correctly changed to C=C.
In statmech.py, there is an elif statement that was written as an if statement, causing CBS-QB3 atom corrections to be ignored. This was corrected.
> Fixed two example files and a bug in statmech.py

- examples/rmg/commented/input.py
- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/library.py
- rmgpy/reaction.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/mainTest.py
This pull request causes RMG each iteration to automatically:
1) Generate a seed mechanism based on the current chemkin and species dictionary files
2) save that seed mechanism in a seed folder in the run directory
3) save copies of the associated thermo and kinetic libraries into database under
an input name (new parameter in the options block) (or replace the current thermo and kinetic libraries of that name) 
Makes feature for #881.
> automatic seed mechanism generation

- rmgpy/rmg/main.py
This should fix #1116 and #1115.  The seed is now produced in the output directory rather than the working directory and the seed option variables are now properly initialized by RMG.clear().  
An alternative fix to #1115 would be to run options() right before input generation, which would make it so that options variables' default values would only be set at one location (the values in RMG.clear() would be irrelevant).  I don't think we currently use RMG.clear() for anything other than initialization, however if we were to do so, being dependent on the options() call to fill in the options variables would be undesirable.
> Fix seed generation

- rmgpy/quantity.py
Went through quantity.py to improve the error messages by telling
users what options are available when unable to parse the given
units or uncertainty strings
> improve error message for quantity.py

- rmgpy/rmg/main.py
Switch out unix commands for python os/shutil commands.  Ideally would like someone with a windows install to test this.
> fix windows seed generation

- rmgpy/data/thermo.py
- rmgpy/rmg/model.py
- rmgpy/thermo/model.pxd
- rmgpy/thermo/model.pyx
- rmgpy/thermo/nasa.pyx
- rmgpy/thermo/thermodata.pyx
- rmgpy/thermo/thermodataTest.py
- rmgpy/thermo/wilhoit.pyx
This causes RMG to use the names associated with thermo library entries rather than smiles when a thermo library entry is available (and if not already assigned by a seed mechanism or reaction library).
> Use thermo library names

- rmgpy/pdep/network.py
- rmgpy/pdep/networkTest.py
If a memory error is obtained when building the collision tensor this pull request causes the number of grains in the network to be decreased by a factor of 2 (which should decrease the tensor size by a factor of 4).  The energy list is reconstructed with the smaller grain size and the function is called recursively within itself until the grain size is small enough that the tensor can be built without a MemoryError.  
Should fix #1129.
> Automatically Decrease grain size to keep collision tensor manageable

- documentation/source/users/rmg/input.rst
- examples/rmg/minimal_staged/input.py
- examples/rmg/minimal_surface/input.py
- rmgpy/reduction/reduction.py
- rmgpy/reduction/reductionTest.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/mainTest.py
- rmgpy/rmg/model.py
- rmgpy/rmg/settings.py
- rmgpy/solver/base.pxd
- rmgpy/solver/base.pyx
- rmgpy/solver/baseTest.py
- rmgpy/solver/liquidTest.py
- rmgpy/solver/simpleTest.py
- rmgpy/tools/fluxdiagram.py
- rmgpy/tools/sensitivity.py
This represents part 3 of the AcceleratorTools branch.  
This pull request contains a number of tools for manipulating the RMG algorithm:
1) Model Concatenation:  model() and simulator() inputs from the input file are now appended to a list and iterated through in main.  This allows model runs to be done one after another (i.e. run it at certain parameters at first and then after the first run terminates start the next run with the model produced by the first run.  
2) Max Number of Species Termination Criterion:  this setting causes a run to terminate when the number of species reaches a set number 
3) Number of Objects Returned from Simulate Setting:  this setting causes simulate runs to continue until they have a set number of objects contained with invalidObject rather than …
> Accelerator Tools (AcceleratorTools part 3)

- rmgpy/data/thermo.py
this prevents the pre-HBI corrected thermo label from being used for the HBI corrected thermo
> removes the ThermoData.label for HBI

- rmgpy/data/thermoTest.py
Ensures that database changes won't lead to the test failing.
> Fix unit test to ensure that thermo comes from GAV

- examples/rmg/minimal_thermofilter/input.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/modelTest.py
- rmgpy/rmg/settings.py
This feature enables the user to prune based on the Gibbs energy of formation:  
The scaling used is Gn = (G_fi - G_max) / (G_max - G_min) where G_max and G_min are the minimum over all core species at the maximum reactor temperature.  
This is compared with a new parameter:  toleranceThermoKeepSpeciesInEdge.  For this parameter 0.0 denotes the maximum value of Gn within the core so 0.1 denotes 10% of the core Gibbs range beyond the maximum Gibbs value in the core.
> Thermodynamics based pruning

- rmgpy/exceptions.py
- rmgpy/qm/mopac.py
- rmgpy/qm/mopacTest.py
This PR adds some additional checks to `Mopac.testReady()`:
- Check if the executable has expired, log a warning if so, but continue by pressing enter
- Raise an exception is the license has not been entered
- Raise an exception if the `MOPAC_LICENSE` environment variable needs to be set (Windows only)
This fixes #1163, and allows Travis to pass with an expired MOPAC executable.
This also addresses the issue on Windows where the test suite would always hang on the MOPAC test.
One thing I'm not sure about, is that the warning for an expired MOPAC exectuable is logged every time `testReady()` is called. In a standard RMG job with QMTP, it would probably be called numerous times. Is it worthwhile to make a module level variable in order to only print the warning once, or is it fine to print …
> Check for common MOPAC errors

- rmgpy/rmg/input.py
This PR will avoid the most recent slowdown by making the default to not generate seed mechanisms.
> make seed mechanism generation default off

- testing/databaseTest.py
this PR improves database test for non-identical adjacency lists in training reactions. The previous method only checked that atom labels of the first reaction were on the second reaction. Not checking all of them made the two adjacency lists throw an error.
```
HO
multiplicity 2
1 *1 O u1 p2 c0 {2,S}
2    H u0 p0 c0 {1,S}
```
```
HO-2
multiplicity 2
1 *4 H u0 p0 c0 {2,S}
2 *1 O u1 p2 c0 {1,S}
```
Shoutout to RMG's newest member @awaggett for finding this bug.
> ensure database test checks all atom labels

- rmgpy/molecule/graph.pyx
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
the docstrings for Atom, Bond, and Molecule were missing some
attributes, so this commit/PR adds them to the docstring to improve
code readability and usability.
> extend docstring for Atom, Bond, Molecule

- ipython/generateReactions.ipynb
- rmgpy/rmg/main.py
Improves error generation for wallclock updates by 
1. changing when an error is thrown by the wallclock
2. fixing the input file for generateReactions.ipynb to use the correct format.
> Wallclock error fixes

- documentation/Makefile
- documentation/source/conf.py
- setup.py
Mostly self explanatory.
- Change the setup_github_pages make target
- Update copyright date
- Add cython directive to embed docstrings, eliminates 95% of sphinx warnings
Should be tested before merging.
> Update some settings for building documentation

- documentation/source/users/rmg/input.rst
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/library.py
- rmgpy/data/kinetics/libraryTest.py
- rmgpy/data/kinetics/rules.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/test_data/testing_database/kinetics/libraries/ethane-oxidation/dictionary.txt
- rmgpy/test_data/testing_database/kinetics/libraries/ethane-oxidation/reactions.py
This pull request improves seed mechanism generation:
1) created seeds are checked for duplicates when they are loaded rather than when they are created to save time
2) created seed/libraries are loaded as template and original library reactions, (pdep reactions are still treated as library reactions for now)
> Proper seed mechanisms

- rmgpy/rmg/mainTest.py
- rmgpy/rmg/test_data/mainTest/input.py
- Create permanent input file so it is not written every time
- Split tests into multiple test methods
- Add tests for edge seed libraries
- Clean up properly after tests
> Completely refactor rmgpy.rmg.mainTest.TestMain

- rmgpy/data/thermo.py
to avoid infinite looping incase a thermo pointer is corrupt
> Added a raise DatabaseError to thermo.py

- documentation/source/users/rmg/database/kinetics.rst
Added the kinetic library Klippenstein_Glarborg2016 to library list in the documentation
Should be merged along with https://github.com/ReactionMechanismGenerator/RMG-database/pull/210
> Added Klippenstein_Glarborg2016 to documentation

- rmgpy/cantherm/pdep.py
Relocated the library/family comment from Reaction to kinetics to avoid ending up with two `comment` instances in PDep network files.
Thanks @jimchu10 for [pointing this issue up](https://github.com/ReactionMechanismGenerator/RMG-Py/commit/1ae3a89b24122f7cdedf0bbfd6dd568e1da5ea9e#commitcomment-23796076).
> Fixed info of reaction type in PDep network files

- documentation/source/users/rmg/input.rst
- examples/rmg/commented/input.py
- rmgpy/constraints.py
- rmgpy/constraintsTest.py
- rmgpy/data/kinetics/family.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/rmg/input.py
Adds two new species constraint options:
- `maxSingletCarbenes`: limits the number of carbon atoms with lone pairs in a molecule
- `maxCarbeneRadicals`: limits the number of unpaired electrons a molecule with a carbene can have
This eliminates the need for the global forbidden groups added in ReactionMechanismGenerator/RMG-database@2e18d62346778526ba25ca3ae10543ac926fc581, and addresses the speed concerns raised in #1079. Since the intention of the forbidden groups was to prevent molecules with 2 carbenes or 1 carbene and 1 radical from being formed, using species constraints provides a more robust filter than the forbidden groups.
__Note:__ I set the default for `maxSingletCarbenes` to 1 and the default for `maxCarbeneRadicals` to 0, which makes them the only species constraints with a …
> Add carbene species constraint

- documentation/source/users/rmg/thermo.rst
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/symmetry.pxd
- rmgpy/molecule/symmetry.py
- rmgpy/molecule/symmetryTest.py
- rmgpy/species.pxd
This PR is meant to solve issue #1177. It implements:
1. turning the symmetry number into a float (we don't compare or change symmetries, so this should be easier than bonds or degeneracy)
1. halving the symmetry number when a chiral center is found. This occurs in the calculateAtomSymmetryNumber method since finding a chiral center (an atom with four different groups), already occurs there. We half the symmetry number because a chiral center increases entropy by $R\ln(2)$, which is the same effect as halving the symmetry number (the symmetry number effects entropy by $-R\ln(\sigma)$).
1. adding a unittest to test for a change in atom symmetry number with a chiral center (we didn't have a chiral center in symmetry unittests before this one)
1. updating documentation to describe that the …
> Account for enantiomers in entropy

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/molecule/molecule.py
Bicyclic decomposition method works well when our database has comprehensive set of bicyclics and monocyclics. However, this assumption is not exactly true; database has a comprehensice set of saturated bicyclics while only a few of unsaturated ones. As one can imagine, data coverage is quite sparse there since one single bicyclic frame can have multiple ways of placing an unsaturated bond in the rings. It also seems not practical to calculate those unsaturated ones.
We had this idea of estimating unsaturated bicyclic correction from saturated bicyclics and monocyclics (see an example below)
This PR adds implemented this idea, which serves as an additional layer to bicyclic decomposition method. I tested the algorithm on 195 unsaturated bicyclics (the dataset is crafted by @zjburas and …
> estimate highly unsaturated bicyclic correction via heuristic method

- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
Numerical drift was causing errors when adding bonds due to lack
of flexibility in the change bond methods in the Bond class. 
This PR added flexibility to the thousandths place.
This was pulled from `only_core_degeneracy`, but moved here to speed up merging of bug fixes.
> make bounds for change bonds more flexible

- .travis.yml
- Makefile
- rmgpy/reduction/reductionTest.py
- rmgpy/rmg/mainTest.py
- rmgpy/tools/fluxtest.py
- rmgpy/tools/regressionTest.py
- rmgpy/tools/testGenerateReactions.py
This PR separates functional tests from the rest of the tests using the attribute 'functional', so that coverage is testing only unittests. The boundary between unittest and functional test is gray, but I drew the cutoff when an external `input.py` file is used to run RMG. 
Overall, 10 (out of 1277) tests became functional. These ten tests took over a third of the runtime for tests.
> Categorize tests into unittests and functional tests and only use unittests for coverage report

- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/modelTest.py
This pull request cleans up surface management by creating three new functions in model.py for surface management:
addNewSurfaceObjects
adjustSurface
clearSurfaceAdjustments
these are now called in main.py and surface management operations have been moved to these functions.
> clean up surface management

- .travis.yml
- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
This fixes issues with Travis builds failing due to installation of an older version of Cantera.
See #1208.
> Increase Cantera version requirement

- rmgpy/data/kinetics/family.py
- rmgpy/test_data/testing_database/forbiddenStructures.py
- rmgpy/test_data/testing_database/statmech/depository/depository.py
- rmgpy/test_data/testing_database/statmech/groups/groups.py
- rmgpy/test_data/testing_database/thermo/depository/radical.py
- rmgpy/test_data/testing_database/thermo/depository/stable.py
- rmgpy/test_data/testing_database/thermo/groups/other.py
- rmgpy/test_data/testing_database/transport/groups/nonring.py
- rmgpy/test_data/testing_database/transport/groups/ring.py
- rmgpy/tools/uncertainty.py
- rmgpy/tools/uncertaintyTest.py
The pull request solves a number of current issues with uncertainty:
1.  Degeneracies can now be floats
2.  The parser doesn't break when the 'from training reaction' statement comes before and on a different line than 'estimated using template'
3.  Uncertainties can now deal with radical HBI corrections when the saturated species of the radical is not a species in the model
I've added a primitive test that checks that the uncertainties module can load the parameter uncertainty engines (effectively that it doesn't fail to estimate any raw thermo or kinetic uncertainties).  This test should be sufficient that things like 1-3 won't happen again.  
I had to add files to testing_database to pass the tests, but all of the new files are empty.  I had to update the other.py thermo group file …
> Fix uncertainty

- Makefile
Since the latest Makefile test, the RMG-db repository could not pass Travis since its .travis.yml file has the command `- make test-all`.
Consulting with @nyee and @mliu49 , we decided it is probably a good idea to restore the `test-all` in the Makefile.
> Restored test-all in Makefile

- examples/rmg/minimal_multisurf/input.py
- examples/rmg/minimal_staged/input.py
- rmgpy/rmg/input.py
- rmgpy/rmg/settings.py
- rmgpy/solver/base.pxd
- rmgpy/solver/base.pyx
- rmgpy/solver/baseTest.py
This pull request implements true adding multiple species at a time.  The original Accelerator Tools only considers the object with the highest value of a given criterion so for it multiple species only applied to objects that had the highest value when they were greater than the set tolerance.  
Since this required entirely restructuring base.pyx this wasn't included in the original Accelerator Tools pull request.  
Now each iteration all new objects violating a tolerance are added to a list and all termination criteria related to tolerances and object number are checked.  Objects exceeding the maximum number of objects are removed from the list (the last objects in the list are removed first).  Then the list of new objects is iterated through and everything is added to invalidObjects, …
> Accelerator Tools 2 (Accelerator Tools part 4)

- rmgpy/rmg/main.py
Fixes #1210.  This causes thermoFilterDown to be called only when setThermodynamicParameters has also been called.
> Fix Thermodynamic Filtering Bug

- rmgpy/cantherm/kinetics.py
Causes the equilibrium constant and reverse rate coefficients to be printed out along with the forward rate coefficients in a Cantherm kinetics job.
> print out reverse rates in cantherm kinetics jobs

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/rmg/react.py
This PR is to speed up reaction generation and degeneracy calculation without a loss in accuracy by reducing unnecessary computation:
1) Only generate and compare product resonance structures, since the reactants molecules are implicitly resonance structures of the same species.
2) Save a flag indicating whether the reaction was generated in the forward or reverse direction instead of making the determination using isomorphism.
This PR tries to address the same issue as #1113, and therefore conflicts with its changes. Performance comparison tables are shown below:
Benchmark: master
New: degeneracy_speedup
example|time benchmark|time new|memory benchmark|memory new
---|---|---|---|---
eg1|00:00:03:12|00:00:02:43|454.98|436.22
eg3|00:00:07:10|00:00:06:10|397.36|398.64 …
> Degeneracy speedup

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/rmg/react.py
This follows up on the last item in #1182 and updates Connie's fix for debugging cases where the reverse reaction is forbidden.
The debugging portion now calls `findDegeneracies` and accounts for multiple transition states. The method for deleting the forward reaction in cases where the reverse reaction is forbidden has also been changed. It seems like the previous method did not actually delete the forward reaction.
As a side note, #1142 should be merged in soon as well, since it actually does prevent most reactions from reaching this point by identifying that they're forbidden during the reaction generation process.
> Fix bug with automatic debugging of addReverseAttribute

- rmgpy/reaction.py
- rmgpy/reactionTest.py
when degeneracy is reset, it should also modify the kinetics
comments to reflect the updated degeneracy values.
This PR adds this change to the reaction.__setDegeneracy method and writes unittests that ensure the method functions. 
For reviewers:
1. ensure the tests all pass
2. read the code changes in reaction.py to see if they make sense.
> fix kinetics comments when modifying reaction.degeneracy

- documentation/source/users/rmg/database/kinetics.rst
Added the C2H4+O_Klipp2017 library to documentation.
This is a twin PR of https://github.com/ReactionMechanismGenerator/RMG-database/pull/219
> Added the C2H4 +O surface as a kinetic library

- rmgpy/data/rmg.py
- rmgpy/data/solvationTest.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/solver/liquidTest.py
- rmgpy/species.pxd
- rmgpy/species.py
- rmgpy/thermo/nasaTest.py
- rmgpy/thermo/thermoengine.py
- rmgpy/thermo/thermoengineTest.py
- rmgpy/thermo/wilhoitTest.py
- rmgpy/tools/sensitivity.py
We previously had two species classes, one inheriting from the other, which was a source of confusion. This PR merges both classes into species.py and moves the class attributes of the other Species class to other areas of the code.
> only one Species class

- rmgpy/molecule/generator.py
- rmgpy/molecule/parser.py
- rmgpy/molecule/pathfinder.py
- rmgpy/molecule/resonanceTest.py
- rmgpy/species.py
Previously the `generateLonePairRadicalResonanceStructures` was limited to certain structures, since it was written mainly with N2O in mind:
This PR extends it to consider RO[O], RO[NH], RN[O], RN[NH] as well, e.g.:
Resonance tests were also added.
Since RDkit cannot process hypervalance oxygen (e.g. `–[O+]=`), some ROO inchiParsingTests had to be removed . Any comments/suggestions on these deletions are of course welcome.
> Extending the lone pair <=> radical resonance

- rmgpy/chemkin.py
- rmgpy/chemkinTest.py
- rmgpy/data/kinetics/family.py
Previously, `loadChemkinFile` would not save templates or degeneracy of reactions from chemkin file. This PR stores those attributes in the resulting `TemplateReaction` object.
Also improve testing of these methods.
> Read templates from chemkin

- rmgpy/chemkinTest.py
- rmgpy/data/kinetics/family.py
Previously kinetics comments from training reactions started
with the rate rule. Due to the way loadChemkinFile parses the
comments by identifying starts of lines, this caused parsing errors.
This commit reworded that line of the comments to start with
identifiable words. It also updated the uncertainty module parsing
to work with this change as well as updated the unittests.
> change kinetics commenting of training reactions

- rmgpy/rmg/pdep.py
The attribute is unused and its definition is the cause of #1220.  It started causing #1220 because now that both Species classes have been combined into one cythonized Species calss it can no longer add new attributes to the object as it did when it was added to the uncythonized Species class.
> remove collisionModel Attribute definition

- rmgpy/molecule/pathfinder.py
- rmgpy/molecule/resonanceTest.py
Since the reactivity of structures such as `R[O+.][O-]` (formed from `RO[O.]`) isn't yet implemented in RMG, the previous changes to `findAllDelocalizationPathsLonePairRadical` are reverted here to account only for NO2-like structures.
> Revise findAllDelocalizationPathsLonePairRadical to allow only NO2

- examples/rmg/MR_test/input.py
- examples/rmg/minimal_surface/input.py
- rmgpy/reduction/reduction.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/settings.py
- rmgpy/solver/base.pyx
- rmgpy/solver/baseTest.py
This feature attempts to kick the model dynamics by adding a few species/reactions if a DASPK error occurs, in order to make sure the rates information is present when any DASPK error occurs I've set it to skip the stepping function the first time through the while loop in base.pyx, in theory this could cause slight changes in the regression test since it enables objects to be picked up at t=0 rather than forcing it to wait until after the first time step as is currently done.  
This is based from #1082 . 
I have appended the small dynamics time scale feature to this pull request since it is programmatically related:  
This pull request implements a DynamicsTimeScale which is a time before which the dynamics criterion within the surface algorithm will not be able to pull reactions into …
> Model resurrection / Dynamics Time Scale (AcceleratorTools part 5)

- rmgpy/chemkin.py
These are added by readKineticsEntry, which can sometimes end up being saved to a Chemkin file again, e.g. via a library.
The NC example on RMG-tests was encountering this error due to usage of the FFCM1(-) library, which contains warnings about removing SRI parameters. Those lines were originally written from [here](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/chemkin.py#L270), probably because the library was created from a Chemkin file.
I also added the comment about explicit reverse reactions to the list just in case.
This can probably be tested by running the NC example and trying to load the Chemkin file.
> Add additional markers for line breaks in kinetics comments

- examples/rmg/ch3no2/input.py
Adds a simulator block to the ch3no2 example.  This is necessary after the Accelerator Tools pull request that enables model concatenation
> Fix ch3no2 example

- rmgpy/cantherm/kinetics.py
- rmgpy/cantherm/molepro.py
There's no reason not to have functionality for reading RCCSD(T)-F12 energies from Molpro output files, so this PR enables that functionality.
Also fixes a Cantherm error related to the data format of the Tlist when no Tlist is specified explicitly in the Cantherm input file.
> Enable RCCSD(T)-F12 energies in Cantherm

- rmgpy/rmg/model.py
We previously added a specificCollider attribute to the Reaction Class (#1084).
Now RMG recognized these reactions, however it won't add them to the edge if a similar reaction with no specificCollider exists (or vice versa), claiming "This library reaction was not new".
This small fix allows RMG to recognize a reaction as non-identical based on the specificCollider attribute, not only its reactants and products.
This fix was confirmed to work on an unmerged branch and to include `O(6) + SO2(1) (+N2) <=> SO3(4) (+N2)` in addition to `O(6) + SO2(1) <=> SO3(4)`.
> Add specificCollider to areIdenticalSpeciesReferences()

- rmgpy/thermo/thermodata.pyx
If `CpInf` ([a theoretical calculation](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/molecule/molecule.py#L1542)) is lower than `Cphigh`, RMG may not be able to calculate the Entropy at certain temperatures due to `log(negative number)`, e.g.:
[`T0 = (CpInf - Cphigh) / slope + Thigh`](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/thermo/thermodata.pyx#L306)
[`S += slope * (T0 - Thigh) + intercept * log(T0 / Thigh) + CpInf * log(T / T0)`](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/thermo/thermodata.pyx#L310)
In such a case, S will be `NaN` at certain temperatures, and therefore the calculated reverse rate will be corrupt.
This small PR checks whether `CpInf < Cphigh`, and if so sets `CpInf = Cphigh` and outputs …
> Fix a CpInf < Cphigh case in getEntropy()

- rmgpy/molecule/molecule.py
Molecules without atomtypes can encounter other errors during SMILES generation, which obfuscates the actual issue.
This is commonly encountered on the website when users input an incorrect SMILES string. While `AtomTypeError` can be properly handled by the website, this bug causes an `AttributeError` to be raised instead, which breaks the website.
> Do not log SMILES in updateAtomTypes when AtomTypeError is encountered

- rmgpy/chemkin.py
- rmgpy/molecule/draw.py
- rmgpy/molecule/molecule.py
- rmgpy/rmg/model.py
- rmgpy/thermo/nasa.pxd
- rmgpy/thermo/nasa.pyx
This PR improves thermo generation and isotope representation (put into one PR since each is small leading to hassle with re-basing before each merge). 
Thermo fixes:
* Adds a method that modifies the entropy of a NASA object without converting it to wilholt, which leads to some extra conversion error.
* Only submit thermo calculations if thermo is not already provided (for example if it is loaded from a file)
Isotope fixes:
* Color the element of enriched carbon when drawing isotopes
* Allow isotopes to be properly pickled when they are elements in molecules
etc:
* Increase the sig-figs output to the chemkin file. 3 decimal places was too much error when comparing isotope effects.
> Minor thermo isotope tweaks

- rmgpy/data/thermo.py
The main functional change is that loading of generic nodes has been moved from `ThermoDatabase.load()` to `ThermoDatabase.loadGroups()`. The reason is that RMG-website uses `loadGroups()` and not `load()`, so the generic nodes were not being populated. Because `load()` calls `loadGroups()`, there is no effect on normal operation.
As a bonus commit, I also simplified the code in `loadGroups()` to reduce code duplication.
> Modify loading of thermo groups

- rmgpy/data/base.py
- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/test_data/parsing_data/chem_annotated.inp
This pull request adds a few changes to kinetics: 
* Replaced general exceptions to more specific ones in `family.py` for better error catching
* Improved the robustness of a method by also checking for reverse reactions
* The template is now output when RMG matches a training reaction (since knowing the template is necessary to relabel reactants if the depository isn't loaded)
* Make the default kinetics estimator 'rate rules' instead of group additivity, which I don't think people use much. This allows for the line to be omitted from input files.
* Fix tab error.
> Minor kinetics fixes

- rmgpy/rmg/model.py
Retrieve the correct Gibbs number for printing in thermoFilterDown.  Can test this by running minimal_thermofilter and noting that the printed Gibbs numbers are distinct and sequential when it filters down to maximumEdgeSpecies.
> fix pruning message

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/test_data/testing_database/kinetics/families/Singlet_Val6_to_triplet/groups.py
- rmgpy/test_data/testing_database/kinetics/families/Singlet_Val6_to_triplet/rules.py
- rmgpy/test_data/testing_database/kinetics/families/Singlet_Val6_to_triplet/training/dictionary.txt
- rmgpy/test_data/testing_database/kinetics/families/Singlet_Val6_to_triplet/training/reactions.py
- rmgpy/test_data/testing_database/kinetics/families/recommended.py
This PR makes it possible to define a family with a `reversible = False` attribute (and sets it to True by default). As a result, all reactions generated by that family will be irreversible (`=>`).
This is meant to be used for families that involve a photon emission such as triplet/singlet conversions. Used correctly, this does not defy thermodynamics.
Since we don't keep track of photons in our system (yet? :smiley:), we cannot and should not try to calculate the reverse rate. The solver/Chemkin should also treat these families as irreversible.
A unit test was added (along with a demo family that is part of the [twin -database PR](https://github.com/ReactionMechanismGenerator/RMG-database/pull/239)).
For the reviewer: checkout the [ twin -database …
> Allow a kinetic family to be irreversible

- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/solver/base.pxd
- rmgpy/solver/base.pyx
After each reactor all of the processing steps except pruning will occur before the next reactor is run.  This severely reduces the number of simulations needed to be run for runs with multiple reactors because it prevents different reactors from picking up the same species.  
Defining a simulation efficiency metric:  Species Per Simulation Time (SPST) that is the number of species added per simulation.  We can see this does very poorly the more reactors you add.  
For a system where only one species is taken at a time this PR forces SPST = 1, (provided no simulations finish) no matter how many reactors are used.  Accounting for finishing simulations it will decrease from 1 over the mechanism generation process as the model becomes more complete.
> make model enlargement occur after each reactor

- documentation/source/users/rmg/installation/dependencies.rst
- documentation/source/users/rmg/installation/index.rst
- documentation/source/users/rmg/installation/linux.rst
- documentation/source/users/rmg/installation/macos.rst
- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
- meta.yaml
- requirements.txt
- rmgpy/molecule/graph.pxd
- rmgpy/molecule/graph.pyx
- rmgpy/molecule/graphTest.py
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/resonance.py
- rmgpy/molecule/symmetry.py
Improved ring handling has been on the to do list for a while, but before adding new features, it seemed important to make sure our ring perception methods are sufficiently robust. This PR introduces a new algorithm for getSmallestSetOfSmallestRings and a new method called getRelevantCycles.
The previous smallest set of smallest rings (SSSR) algorithm was an incomplete implementation of Fan et al.'s algorithm, and failed for molecules with no degree 2 nodes (eg. cubane). Additionally, the SSSR is not always the most useful set of rings. The set of relevant cycles (RC) is often cited as a more "chemically useful" set of rings, and is defined as the union of all possible SSSRs.
Using cubane as an example, intuitively, one would likely say that there are 6 rings. The previous RMG SSSR …
> Ring Perception

- rmgpy/data/kinetics/family.py
This allows failures in reaction pair generation in family to fall back to Reaction.generatePairs.  This makes it easier to write mult-molecular to mult-molecular families.
> Generate reaction pairs error converted to debug warning

- Makefile
- check_dependencies.py
Thanks to @alongd for the idea for this PR!
This PR refines the dependency checking done at the conclusion of the `make` target. Previously, we would check that `symmetry` and `rdkit` were installed. Now, a script has been added which checks more dependencies and is run at the end of the `make` target. If any of the checked dependencies are missing, the user is asked to install them via anaconda.
The `QM` target has been replaced by the new `check` target since the only thing it was doing was checking the dependencies required for QM (it previously did other stuff that was removed following the transition to anaconda). That functionality is still retained in `check_dependencies.py`.
The idea is that only dependencies that are vital to running RMG jobs are checked here. If there are any …
> Check vital dependencies after make

- documentation/source/users/cantherm/output.rst
- rmgpy/cantherm/thermo.py
prints the species dictionary for every species given with a
thermo() function in cantherm. This allows the user to 
more easily add kinetics libraries or do other manipulations
in RMG.
> print species dictionary with cantherm job

- documentation/source/users/cantherm/input.rst
- rmgpy/cantherm/statmech.py
Fitted with C, H, O, and S atomic energies derived from calculations of methane, ethane, methanol, ethanol, isopropanol, water, dimethyl sulfide, and hydrogen sulfide.
> Add b3lyp\6-31g** as a modelChemistry with fitted atomic energy corrections

- rmgpy/molecule/pathfinder.py
We currently find the ally resonance transformation `[C..]=C[CH2.] --> [C...]C=C`, but we don't find the transformation in the reverse direction, creating a hysteresis (and duplicate species).
(dots above were added to explicitly denote radicals in the SMILES)
As a result, the following are currently different species if they are generated in the following order:
No test was added now since this will also be implemented in a future lone pair resonance PR with appropriate testing for this case as well.
> Allow tri-rads in findAllDelocalizationPaths

- rmgpy/cantherm/kinetics.py
- rmgpy/cantherm/pdep.py
- rmgpy/cantherm/statmech.py
- rmgpy/kinetics/arrhenius.pyx
- rmgpy/kinetics/chebyshev.pyx
- rmgpy/kinetics/chebyshevTest.py
- rmgpy/pdep/configuration.pyx
- rmgpy/pdep/configurationTest.py
- rmgpy/pdep/network.py
- rmgpy/pdep/networkTest.py
- rmgpy/pdep/reaction.pyx
This PR 
* adds default `__repr__` and `__str__` methods to Network and Configuration objects
* allows more inputs into `__init__` for Network objects (so they can recreated from `repr()`)
* prevents throwing an error for cantherm's kinetics method when tunneling values are already set (making it consistent with the pressureDependent method of setting tunneling values)
* added `logging.debug` to see the output from calculations in pdep
* throws an Exception when fitToData does not have any degrees of freedom
For a reviewer, if you could run a pdep cantherm job on this branch in debug mode `-d`, see if the output makes sense. Also you probably want to look at the changes from the commits to see if they make sense.
> Cantherm pdep debug

- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
This is the first part of the implementation of a scheme for accounting for hydrogen bonding in thermo.  This provides a framework for defining and manipulating hydrogen bonds.  Hydrogen bonds are allowed under the following constraints:  
1) The bond must be between a H and an N or O
2) The H must be covalently bonded to an N or O
3) An atom can only be hydrogen bonded to one other atom
4) Formation of an individual H-bond in the un-H-bonded compound should create no rings with less than five members
5) Only two H-bonds can exist in a given molecule
The last prevents explosion of configurations that thermo would need evaluated for.
> Hydrogen Bonding

- rmgpy/chemkinTest.py
- rmgpy/data/kinetics/family.py
Comments of the form:
From training reaction 8 for rate rule C_rad/H2/Cs;HCO
Exact match found for rate rule [C_rad/H2/Cs;HCO]
Euclidian distance = 0
family: CO_Disproportionation
result in C_rad/H2/Cs;HCO being set in rateRuleString instead of [C_rad/H2/Cs;HCO], which threw off the parser
this commit differentiates between the two possible rateRuleString formats
> fix uncertainty parsing issue

- rmgpy/pdep/reaction.pyx
To prevent small values from blowing up in the subsequent calculation of `phi0`.
This has been shown to fix some cases of `InvalidMicrocanonicalRateError`, by @jimchu10 and @mjohnson541. The effect on previously converged pdep jobs has also been shown to be minimal.
> Adjust threshold for zero energy in applyInverseLaplaceTransformMethod

- documentation/source/users/rmg/database/introduction.rst
- rmgpy/data/base.py
- rmgpy/data/baseTest.py
This fixes the capability to specify a molecule as a forbidden structure and adds the capability to specify a species as a forbidden structure.
The benefit of these over groups is that they can use normal isomorphism, which allows comparison of molecular formulas. In the future, they could also be changed to an InChI comparison to completely eliminate the need for isomorphism.
> Minor changes to forbidden structure loading and checking

- rmgpy/rmg/main.py
When a reaction duplicate warning is outputted, the entire reaction object gets print. This isn't informative, and could be frightening to users (~ 100 screens worth of output, see attached example when rxns are PDep)
[RMG_backup.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/1809491/RMG_backup.txt)
This small fix only outputs the reaction strings (in addition to indices).
> Remove reaction duplicate checking at model completion

- rmgpy/molecule/generator.py
- Added known SMILES for: H2S, Cl2, HCl, I2, HI, S, N, CH2,HS, NH2, NH, Cl, I.
- Corrected atom order in formula to be alphabetical (but allowing C to precede H), e.g., `SO` -> `OS`, so this is in accordance with Molecule.getFormula()
- Removed formula which could have several meanings: C2H4 (could be a carbene), SO2, SO3, H2SO4, HSO3
This is a relatively small PR, would anyone like to review?
> Corrected known SMILES in generator.py

- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/database.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/reaction.py
calculateDegeneracy did not assess whether two reactants were
actually pointing to the same reference, as did the newly written
database.generate_reactions_from_families method does. This led
calculateDegeneracy not to be able to track atom IDs (since the
molecules had the same values) and get degeneracy incorrect.
This commit adds code which is used in database.generate_reactions_from_families
to calculateDegeneracy, so it can give accurate degeneracy values.
> Update calculateDegeneracy to deal with identical reactants

- rmgpy/molecule/group.pxd
- rmgpy/molecule/group.py
- rmgpy/molecule/groupTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/util.py
Changes:
- Add `get_element_count` methods to both Molecule and Group. Both implementations are generic with no hard-coded elements.
- Replace element counting done during subgraph isomorphism with `get_element_count`.
- Add check for number of relevant cycles in subgraph isomorphism.
The following plot shows timings for subgraph isomorphism done using the timeit module. The individual values represent the mean of 10 repetitions of 100 calls.
Main conclusions:
- The changes to elements do not have a statistically significant effect on time.
- isCyclic is worse in all aspects. Performing the isCyclic check for dodecane took longer than subgraph isomorphism alone.
- getRelevantCycles increases overhead but provides significant speedup in cases with many cycles
The methods tested were:
- …
> Subgraph isomorphism improvements

- documentation/source/users/cantherm/input.rst
- documentation/source/users/cantherm/input_pdep.rst
- examples/cantherm/reactions/23dimethylpropoxy/dimetpropoxy.py
- examples/cantherm/reactions/23dimethylpropoxy/dimetpropoxy_betasci.py
- examples/cantherm/reactions/CH3OH+HCO/ch3oh.py
- examples/cantherm/reactions/CH3OH+HCO/hco.py
- examples/cantherm/reactions/CH3OH+HCO/ts.py
- examples/cantherm/reactions/H+C2H4=C2H5/TS.py
- examples/cantherm/species/Benzyl/benzyl.py
- examples/cantherm/species/C2H4/ethene.py
- examples/cantherm/species/C2H5/ethyl.py
- examples/cantherm/species/C2H6/C2H6.py
- examples/cantherm/species/H/H.py
- examples/cantherm/species/Toulene/toluene_FreeRotor.py
- examples/cantherm/species/Toulene/toluene_HinderedRotor.py
- rmgpy/cantherm/commonTest.py
- rmgpy/cantherm/input.py
- rmgpy/cantherm/statmech.py
When parsing quantum chemistry output in a Cantherm calculation, there is no reason for the user to specify the types and numbers of atoms, because the information can be obtained from the output files. In fact, mistyping atoms will lead to incorrect thermochemistry and rates, which is avoided in this PR.
This PR also increases the flexibility of Cantherm calculations by allowing the user to supply a dictionary of atomic energies, which means that we are no longer restricted by the hard-coded model chemistries in `rmgpy/cantherm/statmech.py`.
Lastly, another issue in #1315 and #742 is addressed by removing model chemistries that do not specify which basis set was used for the atomic energy calculations. This is a relatively drastic measure, but it should ensure that users do not …
> Remove atoms parameter in Cantherm and allow user-defined atomic energies

- rmgpy/pdep/configuration.pyx
Otherwise, the user gets a `Segmentation fault (core dumped)` error with no trace.
> Raise an error if self.densStates is None

- rmgpy/data/kinetics/library.py
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/rmg/pdep.py
Addresses #741, #394 
This still does not address Josh's comment from #566, and in fact will not allow a second network reaction passing through a different isomer to be included in the model. Let's discuss how we'd like to handle that.
(tag @jimchu10, who expressed interest in this fix)
> Don't add a PDep reaction to the model if it exists as an unflagged LibraryReaction

- rmgpy/molecule/adjlist.py
- rmgpy/molecule/translator.py
- rmgpy/molecule/translatorTest.py
- rmgpy/molecule/util.py
- rmgpy/molecule/utilTest.py
Very straightforward fixes related to identifier generation:
- If a molecule doesn't have atoms, then don't try generating an identifier.
- When counting elements based on InChI, add counts from multiple instances of the same element. This can occur with disconnected molecules (see unit test).
> Identifier fixes

- examples/cantherm/reactions/23dimethylpropoxy/dimetpropoxy.py
- examples/cantherm/reactions/23dimethylpropoxy/dimetpropoxy_betasci.py
This PR fixes two issues @cgrambow and I identified in the Cantherm examples and I've set them to the values @cgrambow thinks they should be.  The symmetry of the methyl rotors in the Toulene example have been fixed from 6 to 3 and the number of opticalIsomers in the 23dimethylpropoxy example have been changed from 1 to 2 to reflect the presence of a chiral carbon.
> Fix cantherm examples

- rmgpy/data/kinetics/family.py
- rmgpy/molecule/adjlist.py
- rmgpy/molecule/adjlistTest.py
- rmgpy/molecule/converter.py
- rmgpy/molecule/group.pxd
- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
This PR enables specification of ring membership for Atoms and GroupAtoms. The level of implementation is currently very basic, but can easily be extended in the future.
Essentially, Group adjacency lists now support a ring property, denoted by `r0` or `r1`, indicating whether or not an atom is part of a ring, e.g.
```
1 R!H u0 p0 c0 r0 {2,S}
2 R!H u0 p0 c0 r1 {1,S}
```
This allows greater specificity when designing groups and can help with ring perception issues when estimating rates.
Internally, this property is stored in a `props` dictionary attribute of Atom and GroupAtom with the `inRing` key. Adjacency list support was not added for Molecules since this is a derived property and not essential to the representation.
> Add ring attribute to atoms

- documentation/source/users/rmg/database/modification.rst
- rmgpy/cantherm/pdep.py
- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/library.py
- rmgpy/data/kinetics/libraryTest.py
- rmgpy/pdep/collision.pyx
- rmgpy/pdep/network.py
- rmgpy/pdep/reaction.pyx
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/rmg/model.py
- rmgpy/rmg/pdep.py
- rmgpy/test_data/testing_database/kinetics/libraries/lib_net/dictionary.txt
- rmgpy/test_data/testing_database/kinetics/libraries/lib_net/reactions.py
This PR allows PDep networks to use kinetics from a LibraryReaction in two cases:
1. When a unimolecular library reaction does not correspond to any kinetics family (but is flagged as `elementary`)
2. When a unimolecular library reaction has PDep kinetics, in which case a high pressure limit rate is generated and saved as a new attribute of the Reaction. This rate is then used in the network.
A test was added for the high pressure limit kinetic generation. This PR involved relatively modest changed to pdep.py, so direct pdep tests were currently not added.
> Allow PDep reactions and non-template library reactions in PDep networks

- documentation/source/users/rmg/input.rst
- rmgpy/rmg/input.py
- rmgpy/rmg/test_data/mainTest/input.py
- rmgpy/solver/base.pyx
Until now RMG has had two termination criteria:  time and conversion.  The fundamental problem with these criteria is that before we run RMG we don't know what the right value is for them.  We don't know how long the chemistry takes.  We don't know if the chemistry continues after conversion of the reactants to something else.  We don't even know if a specified conversion can even be reached.  
This creates issues, terminating using only time can cause you to simulate past where the chemistry is really happening at points where the characteristic rate is very small, which can cause RMG to add undesirable species.  Terminating using conversion will terminate much earlier than desired if the reactant breaks down faster than the downstream chemistry and will never terminate if the specified …
> Characteristic Rate Based Termination Criterion

- rmgpy/data/base.py
This can occur when checking parent/child relationships in kinetics groups if a logic node has a group as a parent. The method will then be called with nodes which may be separated by a couple levels, causing the test to fail.
> Fix matchNodeToChild to account for ancestor comparison

- rmgpy/rmg/main.py
This adds a try except that allows model runs to continue after failed filter simulations.  I believe this caused #1367 and #1258.  It worked as expected on the example in #1367.  However, its worth noting that nothing is reacted until a regular or a filter simulation succeeds and changes the react flags.  In the example in #1367 the run doesn't recover which results in the resurrection process consuming species from the edge until the edge is empty and then crashing.
> Allow Resurrection from Failed Filter Simulations

- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/rmg/model.py
- rmgpy/rmg/modelTest.py
- rmgpy/rmg/rmgTest.py
- rmgpy/test_data/testing_database/kinetics/families/H_Abstraction/groups.py
The multiple TS pull request (#1055) created duplicate reactions any time isomorphic reactions had different reaction templates. That led to cases where there could be 6 or more duplicates of a single reaction due to different resonance structures. This pull request reverses that change for reactions which have different reaction templates due to different resonance structures.
The new algorithm takes advantage of the isIdentical method to distinguish between cases where templates are different due to resonance structures vs. different transition states. This was previously used to distinguish between reactions which contribute to degeneracy vs. ones which don't. The logic is similar for multiple transition states, in that if the exact same atoms are participating in the reaction in the …
> Do not consider template differences from resonance structures as multiple TS

- ipython/kinetics_library_to_training.ipynb
- ipython/kinetics_library_to_training_tools.py
- rmgpy/data/kinetics/family.py
This PR moves the `convertKineticsLibraryToTrainingReactions.ipynb` notebook from RMG-database to RMG-Py. This was done to make it easier to keep the script up to date with RMG-Py.
The notebook was streamlined substantially by converting most of the code to functions and moving them into a separate file. New steps were also added to handle the common issue of having multiple matches and offer summary to review the reactions to be added.
Some improvements were also added to `KineticsFamily.saveTrainingReactions` to make it easier to use.
This PR includes changes from ReactionMechanismGenerator/RMG-database#125 and ReactionMechanismGenerator/RMG-database#241.
> Revamped training reaction ipython notebook

- cantherm.py
- documentation/source/users/cantherm/input.rst
- documentation/source/users/cantherm/input_pdep.rst
- examples/cantherm/networks/acetyl+O2/input.py
- rmgpy/cantherm/input.py
- rmgpy/cantherm/kinetics.py
- rmgpy/cantherm/pdep.py
- rmgpy/cantherm/pdepTest.py
- rmgpy/cantherm/sensitivity.py
- rmgpy/cantherm/thermo.py
- rmgpy/test_data/Cantherm/tst1/pdep_sa.py
Now users can run a Cantherm job (`KineticsJob` or `PressureDependenceJob`) and see to which wells or transitions states the calculated rates are most sensitive to (and hopefully later improve them).
The output of the SA is saved into a `sensitivity` folder in the output directory with a text file tabulating all normalized sensitivity coefficients per reaction (in both direction if the network reaction is reversible), and figures visualizing the sensitivity coefficients per network reaction at all conditions defined for the sensitivity analysis.
Test, example, and some documentation also added.
> Added sensitivity analysis to Cantherm

- utilities.py
Came across #446 while reviewing stale branches and discovered how to retrieve OpenBabel's version number, which I couldn't figure out before. This adds adds version reporting to the check_dependencies function.
Confirmed to work on Linux. Perhaps Windows should be tried?
> Report OpenBabel version in check_dependencies

- rmgpy/cantherm/kinetics.py
A variable name in Cantherm's kinetics draw is wrong
Corrected name
Run the `examples/cantherm/networks/methoxy` example
Nothing in particular
> Fixed wrong parameter name in kinetics draw

- rmgpy/chemkin.pyx
Currently, due to incorrect library name parsing of Chemkin files, the H2S test crashes with:
```
File "rmgpy/chemkin.pyx", line 907, in rmgpy.chemkin.loadChemkinFile
File "rmgpy/chemkin.pyx", line 960, in rmgpy.chemkin._process_duplicate_reactions
rmgpy.exceptions.ChemkinError: Identical reactions HSS(56) + H(3) <=> SH(21) + SH(21)
and HSS(56) + H(3) <=> SH(21) + SH(21) taken from different libraries:
Sulfur/GlarborgH2S, 3239-3247
```
for the duplicate reaction:
```
! Reaction index: Chemkin #55; RMG #252
! Library reaction: Sulfur/GlarborgH2S
HSS(35)+H(3)=SH(21)+SH(21)                          9.700000e+07 1.620     -1.030   
DUPLICATE
! Reaction index: Chemkin #56; RMG #252
! Library reaction: Sulfur/GlarborgH2S
! Sendt K Jazbec M Haynes BS PCI 29:2439-2446 2002
! CR Zhou K Sendt BS …
```
> Correct library name parsing in Chemkin readReactionComments()

- rmgpy/reactionTest.py
This PR added an unittest for problematic `generatePairs()` which currently determines pairs of the reaction non-deterministically.
> generatePairs() unittest

- Makefile
- rmgpy/data/thermoTest.py
Travis build depends on the server hosting the TCD being online, which is not always true.
Add functions to automatically skip TCD tests if the host is not available (determined via pinging). Also skip the test if the proper environment variables are not defined. This eliminates the need for the 'auth' attribute for unit tests and the related make target can also be removed.
Check that Travis passes.
> Automatically skip TCD tests if TCD is unavailable

- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
This prevents and adds a warning for when pruning attempts to prune species that exceed toleranceMoveToCore.
The warning informs the user that they should either increase maximumEdgeSpecies (~100000) or decrease
minSpeciesExistIterationsForPrune (~2).
Replaces #1138.
> Prevent pruning of species exceeding flux tolerance

- rmgpy/display.py
This addresses #1360. The cause was an update to IPython where display defaults to print when not in an interactive shell.
Check for interactive shell using IPython method, and if not in interactive shell, set display to pass.
Check that the species are no longer printed in the Travis build log.
> Update rmgpy.display.display method

- rmgpy/tools/fluxdiagram.py
- rmgpy/tools/fluxtest.py
- scripts/generateFluxDiagram.py
This PR makes some improvements and adds new features to RMG's flux diagram capabilities. The solver algorithm is slightly updated to reflect the algorithm used in `rmgpy/solver/base.pyx`. This is done for consistency because slight differences in the resulting simulation profiles were noticed.
The larger part of this PR deals with the treatment of "central species". Previously, specifying a central species only resulted in a flux diagram containing that species and all species directly connected to it through single reactions. Now, multiple central species can be specified, each of which will appear on the flux diagram whether or not they are connected to each other. It is also possible to specify a graph radius, which will draw the connections up to each central species through a series …
> New Flux Diagram Features

- documentation/source/users/cantherm/input.rst
- documentation/source/users/cantherm/input_pdep.rst
- rmgpy/cantherm/sensitivity.py
I made a terminology mistake in CanTherm's sensitivity analysis, fixed here.
While revisiting these lines, I also improved the style of the x axis label.
> Minor: Corrected `r` notation into `k` in CanTherm's SA

- rmgpy/molecule/molecule.py
- rmgpy/molecule/resonanceTest.py
- rmgpy/molecule/translatorTest.py
Use negative of connectivity value to prioritize atoms with high connectivity.
Also eliminate unnecessary `getAtomConnectivityValue` method.
This is a pretty minor fix which somewhat restores prior behavior. In 8abbee9a9856bfd3cbac9d74da8e3d6a856cbefc, I restored a previously implemented improvement to the atom sorting method. However, I failed to notice that `Molecule.sortAtoms()` method sorts in reverse, whereas the `Graph.sortVertices()` method sorts in the forward direction. Therefore, we need to take the negative of `getVertexConnectivityValue` to maintain the same result.
> Adjust atom sorting algorithm for Molecules

- rmgpy/reactionTest.py
This reverts commit af165df2702262c7ff0ff8846c73bb0c7629d565.
The test seems to have stochastic behavior and does not fail consistently.
Removing until we can figure out what's going on.
> Revert "added a work in progress unittest for generatePairs()"

- rmgpy/rmg/main.py
During the final restructuring of #1338, a `trimolecular` attribute was introduced for the `ReactionSystem` class and the `trimolecular` argument was removed from the `initializeModel` method of that class. The `execute` method in `main.py` was still using the `trimolecular` argument even though it had been removed. This PR fixes the error in #1403.
> Fix critical filterReactions bug

- rmgpy/molecule/resonance.py
For certain polycyclics, getAromaticRings can give inconsistent results from call to call, as a result of some non-deterministic behavior in RDKit. If the number of aromatic rings changes, then the size of the matrix will change and previously generated constraint vectors will be the wrong size. Since this does not occur very often and occurs mostly with odd polycyclics, it seems more efficient to catch this error and continue instead of ending the RMG run.
After this is merged, I will remove the polycyclic global forbidden structures from RMG-database.
Instead of raising the error, raise an ILPSolutionError which will be caught by `generate_clar_structures`, allowing the job to continue.
Example molecules which would break previously: `[c]1cc2CC=C3c1cc23`, `Cc1c[c]c2C3=C=Cc2c13`. Running …
> Handle invalid vector errors gracefully in clar optimization

- rmgpy/solver/base.pyx
When a high-p limit rate from a library reaction is converted into a pressure dependent rate upon library loading, a network is created with its source species in the edge. Since the `speciesIndex` dictionary only contains core species, a KeyError is raised.
This fix captures such cases and assigns an index value of `0` to the respective matrix entry. The only usage of `networkIndices` (the matrix in which relevant `speciesIndex` are saved) is in [residual()](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/master/rmgpy/solver/simple.pyx#L489) under simple.pyx and liquid.pyx, where these values are compared to `-1` to derive the number of reactants.
Run the input file of the [long Nitrogen test](https://github.com/ReactionMechanismGenerator/RMG-tests/blob/new_tests/tests/rmg_long/ …
> Fix networkIndices for "edge networks"

- documentation/source/users/rmg/input.rst
- examples/rmg/SR_test/input.py
- examples/rmg/pruning_test/input.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/solver/base.pyx
- rmgpy/solver/liquid.pyx
- rmgpy/solver/simple.pyx
- rmgpy/solver/simpleTest.py
This PR updates pruning to work properly with ranged reactors and solve #1386.  Instead of tracking how many times a ranged reactor is completed ranged reactors are simply run through nSimsTerm times each reactor cycle.  Furthermore, maxEdgeSpeciesRateRatios is now only reset for each reactor at the beginning of the reactor loop allowing ranged reactors to store the maxEdgeSpeciesRateRatios of all the runs they did that reactor cycle instead of just the last cycle.  This also solves the minimum number of iterations to pruning issues as the number of iterations is defined as the number of reactor cycles run.  I've also added an example for testing pruning and updated the documentation to reflect the changes to how ranged reactors operate.
> Ranged Pruning

- rmgpy/molecule/pathfinder.pxd
- rmgpy/molecule/pathfinder.py
- rmgpy/molecule/pathfinderTest.py
- rmgpy/molecule/resonance.pxd
- rmgpy/molecule/resonance.py
- rmgpy/molecule/resonanceTest.py
We're currently not describing the resonance path of
[![image](https://user-images.githubusercontent.com/16158262/41948595-7a71cdfc-798b-11e8-8b9a-517a41c4393e.png) <-> ![image](https://user-images.githubusercontent.com/16158262/41948855-c240aec2-798c-11e8-9590-21b52383fb4e.png)]
This resembles to the transition mentioned in #1293, mainly since this is also probably only important for correct degeneracy determination.
Added resonance transition, pathfinder modifications, and tests
Compare resonance structures for `N[N+]([O-])=O` on master and this branch
(Edit: One of the drawings in the resonance transition above was wrong, now fixed)
> Added a generate_N5dc_radical_resonance_structures resonance transition

- rmgpy/molecule/symmetry.py
- rmgpy/molecule/symmetryTest.py
Previously, the cyclic symmetry algorithm assumed a cycle is planar,
and incorrectly identified some cyclic structures as symmetric
when they are flipped over. This commit looks at the groups attached
to the atom where flipping occurs and makes sure that it would not
result flipping the other groups attached to the ring before assigning
a symmetry value.
Thanks to Max for discussion.
This solves issue #332 and possibly part of #1327.
> Fix symmetry inconsistencies

- documentation/source/users/rmg/modules/index.rst
- documentation/source/users/rmg/modules/isotopes.rst
- rmgpy/constraints.py
- rmgpy/constraintsTest.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/molecule/isomorphismTest.py
- rmgpy/molecule/molecule.py
- rmgpy/rmg/input.py
- rmgpy/test_data/testing_database/kinetics/families/H_Abstraction/groups.py
- rmgpy/test_data/testing_database/kinetics/families/intra_H_migration/groups.py
- rmgpy/tools/isotopes.py
- rmgpy/tools/isotopesTest.py
- scripts/isotopes.py
This PR adds the ability for RMG to create isotopic mechanisms from previous RMG runs.
The file `rmgpy/tools/isotopes.py` contains pretty much all the methods for manipulating isotopes and creating the isotope mechanism. `rmgpy/tools/isotopeTest.py` tests all the methods in `isotopes.py` except for the main run function, and the post-analysis methods to ensure proper degeneracy and symmetry. 
The file `scripts/isotopes.py` allows users to interface the `isotopes.py` method in the terminal.
A page is added to the documentation to describe all the options for using RMG to create isotopic mechanisms. 
Since most of the methods have unittests, for testing I would recommend:
1. peruse the code and testing methods
2. take your favorite rmg mechanism output (which preferably does not use …
> Isotope resonance

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/groups.py
Should be merged together with ReactionMechanismGenerator/RMG-database#262.
Hard-codes flux pairs for new `Korcek_step1_cat` and Baeyer-Villiger families. Also makes sure that the groups in `Bimolec_Hydroperoxide_Decomposition` and `Peroxyl_Disproportionation` are relabeled correctly, because these families all involve identical trees for both reactants.
> Peroxide chemistry families

- rmgpy/chemkin.pyx
- rmgpy/chemkinTest.py
- rmgpy/rmg/model.py
We were not properly marking duplicates for reaction libraries in the edge and irreversible reactions.
Add duplicate checking when loading reaction libraries and update `markDuplicateReactions` to account for irreversible reactions.
Check that the edge mechanism from the new sulfur test in RMG-tests can be loaded in Chemkin.
It would probably also be good to check RMG-tests to see if this has any noticeable effect on performance.
> Duplicate fixes

- rmgpy/chemkin.pyx
- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/groups.py
- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/data/kinetics/rules.py
- rmgpy/molecule/adjlist.py
- rmgpy/molecule/inchi.py
- rmgpy/restart.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/tools/fluxdiagram.py
- rmgpy/tools/loader.py
methods missing deprecation messages
added deprecation messages to:
* save restart period
* RMG-Java reading/writing
* old adjacency lists 
* group additivity
* rxn.label
removed method with 8 month old deprecation warning, `filter_reactions`.
I have not tested this branch yet. Will see what travis tests say.
> Add deprecation warnings before v2.2

- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/rmg/main.py
This collision rate limit check is inspired by [Wang et at. 2017](https://doi.org/10.1016/j.combustflame.2017.08.005).
Currently we only output a warning along with a relevant log file if any core reactions violate this limit.
> Check core reactions for collision rate limit violators

- rmgpy/rmg/main.py
One of the calls to `updateReactionThresholdAndReactFlags` in `main.py` was missing `trimolecularThreshold`. The call to that method was added on 5/19/18, whereas the trimolecular changes were written on 3/29/18. However, because #1338 was not merged until after the new call to the method was introduced, `trimolecularThreshold` was missing from that call. This PR fixes that.
> Add missing trimolecularThreshold

- rmgpy/rmg/main.py
Fixes #1427. Models were entering into infinite loops of adding reactions. The cause was failing to properly reset react flags leading to repeatedly reacting species together.
The `updateReactionThresholdAndReactFlags` method was changed to always reset the react flags regardless of whether or not core species were added. Related changes were made to the `execute` method in order to update these arrays on every iteration, regardless of whether or not core species were added.
Run `eg1` locally (the one in RMG-tests is different). It should now stop properly after reaching 29 core species.
> Adjust updating and resetting of react flags in execute

- rmgpy/data/thermoTest.py
- rmgpy/molecule/vf2.pyx
- rmgpy/molecule/vf2Test.py
Fixes #1344. Previously, the mapping attribute was causing the symmetry algorithm to return unexpected results. This actually affects normal jobs, since the symmetry number is generally determined at the end of thermo estimation, following many calls to isomorphism. As a result, the symmetry corrections were sometimes incorrect.
At the end of `vf2.isomorphism`, clear the `Vertex.mapping`  and `Vertex.terminal` attributes. These are used solely be the vf2 algorithm, so there is no need for them to persist.
Check that the examples in #1344 now work as expected. Thermo estimates are expected to be different in RMG-tests, but should be limited to entropy values.
> Clear vertex mapping after isomorphism

- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/solver/base.pyx
- rmgpy/tools/plot.py
React flags were being reset in the initial react step if filterReactions was on and the user specified multiple reactors. As a result, no reactions would be generated in some cases.
Reorganized the initial react step to be more similar to the react sequence in the main loop. Specifically, we now loop through each reactor, update the react flags, and react the appropriate species. If filterReactions is off, then we break after the first reactor since they all share the same core species.
Also made a few minor changes to logging and fixed a deprecated matplotlib call. If the reviewers prefer, these can be moved to a separate PR.
The particular case that brought this to our attention was a PDD model from @amarkpayne. That should be the main test to make sure the fix worked.
We also expect …
> Fix react flag usage in initial react step

- rmgpy/rmg/main.py
The collision violators log file was being written to the execution directory, unlike the other output files.
Modify the file paths so that it is saved to the output directory insteady
Run an RMG job from a different directory from the location of the input file, e.g.
```
python rmg.py examples/rmg/minimal/input.py
```
from the root RMG directory and confirm that the log is saved in `examples/rmg/minimal` instead of the root directory.
> Adjust file paths for the collision violators log

- rmgpy/molecule/converter.py
- rmgpy/molecule/converterTest.py
- rmgpy/molecule/translatorTest.py
Previously, we couldn't generate identifiers for isotopic molecules because the isotopes would be lost on conversion to an RDKit or OpenBabel molecule.
Properly transfer isotope information when converting to and from RDKit and OpenBabel molecules. Also add a few unit tests.
Check that Travis tests pass. Manually test some other molecules of interest.
> Improved isotope support in converter and translator modules

- examples/rmg/propane_branching/input.py
- rmgpy/rmg/input.py
- rmgpy/rmg/settings.py
- rmgpy/solver/base.pyx
This adds a new very significantly improved algorithm for chain branching/feedback loop pickup.  
In terms of the inputs we add a reaction if its 'core reactants' have no species of multiplicity >2 and has a species of multiplicity 2 that violates:  
1 < min(BR,branchingRatioMax) * RR**branchingIndex / toleranceBranchReactionToCore
Where the core reactants are the species on the side of the edge reaction that are all in the core.  BR = net reaction rate / consumption of the species, RR = net reaction rate / Rchar.  
This very significantly improves pickup of chain branching reactions as can be demonstrated in the provided example.
> Branching Algorithm

- scripts/generateChemkinHTML.py
Delete a bracket of 0 to correct the output path
> correct output path in generateChemkinHTML

- rmgpy/cantherm/explorer.py
- rmgpy/data/kinetics/family.py
- rmgpy/rmg/model.py
- rmgpy/species.pxd
- rmgpy/species.py
This moves global forbidden structure checking from when species are created in the edge to when a species attempts to enter the core. In a test constructing a dodecane combustion model this reduced time spent checking forbidden structures by 148x and overall runtime (in the react regime) by 4.5x without impacting the output model.
> Move Forbidden Structure Checking from Edge to Core (Edgeless RMG Part 1)

- rmgpy/molecule/molecule.py
- rmgpy/molecule/resonance.pxd
- rmgpy/molecule/resonance.py
- rmgpy/molecule/resonanceTest.py
Benzyne and other arynes were previously neglected by the resonance algorithm. As a result, we would treat `C1=C=C=CC=C1` and `C1=CC#CC=C1` as different molecules. As we work towards adding more PAH formation pathways, including ones involving benzyne, this becomes more of an important issue.
This PR adds a new resonance function, `generate_aryne_resonance_structures`, which generates both cumulene and alkyne resonance forms for benzyne and polycyclic arynes. The approach used was to hard-code bond orders which are capable of this transformation. Specifically, two potential bond order arrangements are checked for, corresponding to the two main resonance structures of benzyne.
This is sufficient for a wide range of cases, but does fail to consider certain polycyclic cases which may have …
> Benzyne resonance structures

- rmgpy/cantherm/kinetics.py
This was an issue for example when the forward reaction was bimolecular but the reverse was unimolecular. The output.py file would display units in cm3/mol, but the number would actually be in m3/mol.
> Fix Cantherm Kc Output to Match Units

- .coveragerc
Changes were made in coverage v4.5 to how omit was handled
This makes sure test files are not included the coverage report
Add an omit setting to the [report] block of `.coveragerc`.
Check that Travis reports the true coverage.
> Omit test files from coverage report

- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/tools/loader.py
- rmgpy/tools/simulate.py
For large RMG models, it can be useful to save the sensitivity information for all species so that sensitivity analysis does not have to be run again if information for another species is desired later. This information is calculated regardless, so saving the information for all species only adds an additional small I/O overhead.
Using `sensitivty='all'` in the RMG input file adds all species to the sensitive species list. This is true for calls to simulate.py and mechanism building jobs.
Locally I have tested that the sensitivity example mechanism saves information for all species using simulate.py. I have also set `sensitivty='all'` in the super-minimal example and built the mechanism, in which sensitivity analysis after model generation was successful and saved all of the information.
> Save sensitivity files for all species by specifying 'all'

- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/family.py
After reaction generation, product labels are currently retained even though they are no longer used, while reactant labels are being cleared.
Clear atom labels from reaction products as well, at the end of `KineticsFamily.__generateReactions`.
Also change an unrelated docstring which was incorrect. (Let me know if this should go in a separate PR.)
Check RMG-tests for any unanticipated effects. This change should not affect model generation.
> Clear atom labels from products after reaction generation

- documentation/source/users/rmg/input.rst
This feature was removed in https://github.com/ReactionMechanismGenerator/RMG-website/commit/bbefc37473705f751a2f0267806fce4bdfd1d0a4
> Removed broken link to input file generator form

- rmgpy/molecule/symmetry.pxd
- rmgpy/molecule/symmetry.py
- rmgpy/molecule/symmetryTest.py
- rmgpy/species.py
This fixes the second issue in #1482. Cyclic symmetry numbers were not being properly determined because the `vf2.feasible` method wasn't working properly out of context.
A new method called `_indistinguishable` was created in `rmgpy.molecule.symmetry` to perform the task that `vf2.feasible` was being used for, without the additional infrastructure of `vf2`. The new method checks connectivity values, atom equivalence, and nearest neighbor equivalence to determine if two atoms are feasibly indistinguishable.
All unit tests should be passing, and two tests previously marked as `@work_in_progress` are also now passing. Any additional test cases which are found be necessary should probably be added as new unit tests.
Review the new `_indistinguishable` method to see that it makes sense.
Also, …
> Symmetry fixes

- rmgpy/solver/liquid.pyx
- rmgpy/solver/simple.pyx
- rmgpy/tools/uncertainty.py
The Local uncertainty ipynb was not able to run properly after
the nSims parameter was added to the middle of the arguments when
initiating SimpleReactor, since the arguments sent to the
SimpleReactor from the uncertainty module were all shifted.
This commit/PR fixes this by using keyword arguments in the
uncertainty module.
Run local uncertainty module before and after this PR to make sure the problem is fixed.
> Fix Uncertainty after RangedReactor refactoring

- rmgpy/cantherm/main.py
Mono and diatomic species threw errors while generating the supporting_info_file recently implemented in Cantherm, since the former doesn't have rotational constants / frequencies, and the latter has a `rotationalConstant` in the form of a float (cannot be iterated). This fix checks for such cases and handles them.
> Fix: rotationalConstant supporting info

- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
- examples/rmg/commented/input.py
- examples/rmg/minimal_ml/RMG.sh
- examples/rmg/minimal_ml/input.py
- meta.yaml
- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/ml/__init__.py
- rmgpy/ml/estimator.py
- rmgpy/ml/estimator_test.py
- rmgpy/rmg/input.py
- rmgpy/rmg/inputTest.py
- rmgpy/rmg/main.py
This PR is an alternative version of PR https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1251.
Instead of adding all the CNN modules (data processing, model building, training, testing, loading parameters, and prediction) into RMG, we made a separate package of all these machine learning modules, called [DataDrivenEstimator](https://github.com/KEHANG/DataDrivenEstimator) (package short name: **`dde`**, key module: **`cnn_framework`**) and appended it to RMG's dependency list.
Thus this PR is very light, with only a handful of commits, including
- use **`cnn_framework`** to create a new thermo estimator: **`MCNNEstimator`**.
- load **`MCNNEstimator`** from RMG input file via **`mcnnEstimator()`**,
- an example **`minimal_mcnn`** to show the input file with **`MCNNEstimator`** …
> Integrate MCNN (Molecular Convolutional Neural Network) thermo estimator with RMG

- documentation/source/users/cantherm/input.rst
- rmgpy/cantherm/statmech.py
Temporary solution to #1476, where we found that the Paraskevas BACs for CBS-QB3 were not accurate for aromatic species.
Long-term, it would be best to fit new corrections ourselves, to a larger training set of compounds.
The default BACs for CBS-QB3 have been reverted to the Petersson values. We showed for a few aromatics that they are more accurate than the Paraskevas values, and it's also possible that mixing the two sets of BACs would result in inaccurate results for many other species classes.
The Paraskevas values have been added as a separate model chemistry, `cbs-qb3-paraskevas`, and comments have been added in the code and documentation explaining it.
I've tested that `CBS-QB3-Paraskevas` can be specified in an input file to get the desired results. I'm not sure if there's much …
> Revert changes to CBS-QB3 bond corrections in Cantherm

- rmgpy/molecule/kekulize.pyx
- rmgpy/molecule/kekulizeTest.py
The kekulization module could not properly handle cases where bonds in different aromatic rings were modified as a result of a reaction. For example, Diels_alder_addition of acetylene to the bay site of phenanthrene, which results in bond change in all three rings of phenanthrene.
This updates the kekulization algorithm to do initial bond processing at once at the start of the entire procedure instead of waiting until the start of kekulizing each ring.
Additionally, naming in the entire kekulization module has been redone to conform to PEP-8. Compatibility issues are not expected to be significant because the only outward facing method is `kekulize`, which was not modified.
> The initial bond processing is done by `AromaticRing.process_bonds()`. That method will directly assign bond …
> Improve kekulization algorithm for reacting PAHs

- rmgpy/data/reference.py
Extra quotes are being added when generating the repr for Reference objects because using `{0!r}` for strings automatically includes quotes.
Remove extra quotes being added in the `toPrettyRepr` methods of Reference classes.
To verify that this works, simply call `repr` on any string to see that it adds a set of quotes.
```
>>> repr('abcd')
"'abcd'"
>>> 'title = {0!r}'.format('abcd')
"title = 'abcd'"
```
> Remove extra quotes from pretty repr of references classes

- arkane/statmech.py
Added H(0 K) and Hf(298-0K) data of additional elements (He, Ne, K, Ca, Ti, Cu, Zn, Ge, Br, Kr, Rb, Ag, Cd, Sn, Xe, Cs, Hg, and Pb) into Arkane from [CODATA](http://www.science.uwaterloo.ca/~cchieh/cact/tools/thermodata.html).
Solves #1494
> Added Hf data for addiitonal elements in Arkane

- rmgpy/molecule/pathfinder.py
We sometimes get weird and unexpected structures from carbenes participating in our current resonance transitions (see #1495). Since we don't have a good understanding of carbene resonance (perhaps in the kinetic community?), we should limit these transitions to regimes we have more certainty in.
Carbenes were excluded from resonance pathways recently defined for heteroatoms (lone_pair_multiple_bond, adj_lone_pair_multiple_bond, adj_lone_pair_radical_multiple_bond). They were not excluded, however, from allyl resonance shifts.
Generate resonance structures for weirdo on this branch and on master (should have 1 and 3 structures, respectively). Make sure with @cgrambow that this indeed fixes #1495 
Weirdo's adjLists:
normal:
```
1  C u0 p0 c0 {4,S} {5,S} {6,S} {7,S}
2  C u0 p0 c0 {3,D} …
```
> Forbid carbenes from lone pair resonance transitions

- arkane/statmech.py
- documentation/source/users/arkane/input.rst
Values were obtained from NIST Computational
Chemistry Comparison and Benchmark DataBase
A method's atom correction energies were not defined by cantherm
Added the atom correction energies from https://cccbdb.nist.gov/energy2x.asp using the ground electronic states.
n/a
make sure the numbers match those in https://cccbdb.nist.gov/energy2x.asp or if my method of adding them was screwed up
> Added atomEnergy corrections for wB97X-D-aVTD chemistry

- arkane/statmech.py
Previously, the auto-determined frequency scaling factor for `ccsd(t)-f12/cc-pvtz-f12` was derived from [Truhlar 2010](https://pubs.acs.org/doi/abs/10.1021/ct100326h), but looking there again I don't see it or a similar level in the paper (should have been in Table 8). The previous value of 0.984 seems to be taken from `CCSD(T)/jul-cc-pVTZ` in that table. I think that a better estimation for the frequency scaling factor is for `ccsd(t)/cc-pvtz` from [CCCBDB](http://cccbdb.nist.gov/vibscalejust.asp).
@cgrambow, would you agree?
> Corrected 'ccsd(t)-f12/cc-pvtz-f12' frequency scaling factor

- arkane/statmech.py
This small change allows us to assign a BAC dictionary to a StatMechJob object after the object is created. It is useful when working with scripts that pass arguments into Arkane. Specifically, this is how ARC passes BAC.
For the reviewer:
Try creating a `StatMechJob` object on this branch, then pass a BAC dictionary to it using the `.bonds` attribute.
```python
stat_mech_job = StatMechJob(spec, input_file_path)
bac_dict = {'C-C': 1, 'C-H':4}
stat_mech_job.bonds = bac_dict
```
> Allow a BAC dictionary to be assigned to a StatMechJob object

- arkane/gaussian.py
- arkane/gaussianTest.py
- arkane/main.py
- arkane/molpro.py
- arkane/molproTest.py
- arkane/qchem.py
- arkane/qchemTest.py
- arkane/statmech.py
Previously, non-imaginary frequencies outputted to the supporting information file in Arkane were extracted from the HarmonicOscillator mode, which later gets multiplied by the frequency scaling factor. With this fix, unscaled frequencies are reported.
How to test:
Run any species in arkane (e.g., the C2H4 example) and compare the reported frequencies in the supporting information file generated on this branch and on master with the frequencies reported in the QM log file (easier if the QM software is QChem, where the units are already in cm-1)
>  Output unscaled frequencies in Arkane's supporting information file 

- rmgpy/data/kinetics/family.py
- rmgpy/data/thermoTest.py
- rmgpy/molecule/filtration.py
- rmgpy/molecule/filtrationTest.py
- rmgpy/molecule/graph.pxd
- rmgpy/molecule/graph.pyx
- rmgpy/molecule/group.py
- rmgpy/molecule/resonance.pxd
- rmgpy/molecule/resonance.py
- rmgpy/molecule/resonanceTest.py
- rmgpy/molecule/symmetryTest.py
- rmgpy/rmg/model.py
- rmgpy/species.py
- rmgpy/test_data/testing_database/kinetics/families/R_Addition_MultipleBond/groups.py
With recent changes to resonance structure generation and the implementation of resonance structure filtration, I felt that aromatic resonance structure generation could be refactored to fit better with the new infrastructure. In particular, some filtration which was being done for aromatic species could be relocated to the filtration module for clarity and improved code organization.
Additionally, removing Kekule structures as a representative aromatic resonance structure has been on the to do list for a while. With changes enabling benzene bond reactivity and the new capability to mark non-representative structures as non-reactive, I also felt this was a good opportunity to do that as well. The benefit of doing so would primarily be to reduce the number of resonance structures for …
> Make Kekule structures non-representative and refactor aromatic resonance

- documentation/source/users/rmg/liquids.rst
- rmgpy/kinetics/diffusionLimited.py
The original algorithm used an inexact criterion for deciding whether the rate was limited in the forward or reverse direction.  This PR causes it to be calculated in both directions and the the direction that results in the slowest forward rate to be used.
> fix diffusion limited rate calculations

- rmgpy/species.py
Previously, hasStatMech would return True for any molecule with one atom, even if the E0 parameter was None. This raises issues when creating pdep networks from NASA polynomials in arkane since E0 is necessary. At the same time, this method does not check E0 parameters even for polyatomic
molecules.
This commit reworks hasStatMech to differentiate between atomic molecules, which it only checks the E0 parameter, and polyatomic molecules, which it checks both E0 and the number of modes.
I have tested the arkane example methoxy, which deals with atomic hydrogen, and this commit results in no change in that result. This commit does result in a fix when the user inputs an atomic molecule into the arkane input file given its NASA polynomial.
Look over the code and let me know if anything should …
> Allow hasStatMech to assess atomic molecules

- arkane/molpro.py
- arkane/statmech.py
Minor fixes allowing Arkane to process monoatomic species (atoms) calculated using molpro.
An example for an atom sp job output:
[output.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2680516/output.txt)
Specifically we care about parsing the following part:
```
Point group  D2h 
ATOMIC COORDINATES
NR  ATOM    CHARGE       X              Y              Z
1  H       1.00    0.000000000    0.000000000    0.000000000
NUCLEAR CHARGE:                    1
NUMBER OF PRIMITIVE AOS:          21
```
> Processing monoatomic species in Arkane/molpro

- arkane/thermo.py
Only create the `species_dictionary.txt` file if the species has a structure. This avoids generating empty and suspicious `species_dictionary.txt` files.
> Minor: Modified saving proceedure of species_dictionary.txt in Arkane

- rmgpy/ml/estimator.py
This ensures that the keras backend is set to theano so that dde works properly, regardless of the environment variables set originally. Fixes #1532.
Change the `KERAS_BACKEND` environment variable using `os.environ`.
Should be tested on mac:
- Activate rmg_env
- Check `echo $KERAS_BACKEND`, should be tensorflow
- Verify that `make test` passes
> Set KERAS_BACKEND=theano before importing DDE

- rmgpy/rmgobject.pyx
- rmgpy/rmgobjectTest.py
When RMGObject encounters an empty list, it cannot index it (e.g., call `val[0]`). This occures when running atomic species where the frequencies are just an empty list `[]`.
We shouldn't bother dumping and parsing empty lists, they will get their default values when loading the object.
Files for testing (for carbon atom) are attached
[C_arkane_input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2787635/C_arkane_input.txt)
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2787636/input.txt)
[sp.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2787637/sp.txt)
After successfully generating a YAML file for C, try feeding that YAML file back to Arkane to see that it reads it correctly.
> BugFix: Empty list as val in RMGObject.as_dict() and .make_object()

- rmgpy/chemkin.pyx
- rmgpy/data/kinetics/database.py
- rmgpy/data/thermo.py
- rmgpy/molecule/atomtype.py
- rmgpy/molecule/draw.py
- rmgpy/molecule/graphTest.py
- rmgpy/molecule/vf2.pyx
- rmgpy/quantity.pxd
- rmgpy/quantity.py
- rmgpy/quantityTest.py
- rmgpy/rmg/output.py
- rmgpy/solver/base.pxd
- rmgpy/solver/simple.pyx
- rmgpy/thermo/nasa.pyx
- setup.py
- testing/databaseTest.py
This is a collection of commits that prepares the groundwork for merging the cat branch (heterogeneous catalysis). I think they don't have anything to do with heterogenous catalysis.
My hope of collecting them in a separate pull request is that it will make code review easier.
We could split this PR further if desired.
I am hoping that these will not be too controversial or at least will not break anything.
So far...
- Fix a bug in the VF2 isomorphism code for disjoint graphs (will later be used for things physisorbed onto the surface)
- Improve error logging in various places (implemented while debugging over the last 2.5 years)
- Tweak a few docstrings and comments.
- Edits to chemkin writing. Using a new function to convert units (because surface reactions can have very different …
> Non-cat changes to master from cat branch, 1

- rmgpy/rmg/model.py
When using thermodynamic pruning, can encounter undefined variable error in `processNewReactions()`.
Move initiation of `spcs` variable earlier.
This input file crashes at 10 species without this fix. [input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2826031/input.txt)
> Move variable initiation to avoid undefined variable error

- documentation/source/users/rmg/output.rst
- documentation/source/users/rmg/releaseNotes.rst
- rmgpy/data/kinetics/database.py
- rmgpy/data/kinetics/family.py
- rmgpy/molecule/adjlist.py
- rmgpy/molecule/atomtype.pxd
- rmgpy/molecule/atomtype.py
- rmgpy/molecule/atomtypeTest.py
- rmgpy/molecule/atomtypedatabase.py
- rmgpy/molecule/converter.py
- rmgpy/molecule/draw.py
- rmgpy/molecule/group.pxd
- rmgpy/molecule/group.py
- rmgpy/molecule/groupTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/rmg/listener.py
- rmgpy/solver/base.pyx
This is a follow-on from #1538.
This is the second of two pull requests that don't actually introduce surface sites or heterogeneous reactions, but contains a series of commits that prepare the groundwork for merging RMG-Cat (heterogeneous catalysis) features into RMG. 
- change Hydrogen bonds to have a bond order of 0.1 (instead of 0)
- introduce Van der Waals bonds with a bond order of 0
- introduce Quadruple bonds (with a bond order of 4)
- Snapshots (PNGs and CSVs) now track moles not mole fractions.
The last change (tracking moles not mole fractions) may mess up some regression tests, depending how they're configured, and should come with warnings (that the meaning of RMG's output has changed), but I think it's an improvement. I am open to discussion though, if people feel it should …
> Non-cat changes to master from cat branch, 2 

- rmgpy/molecule/converter.py
- rmgpy/molecule/converterTest.py
This PR lets RMG ignore hydrogen bonds when converting a molecule to an RDKit mol.
> Allow RDKit to ignore hydrogen bonds

- rmgpy/rmg/model.py
This fixes a bug that occurs when forbidden species are removed from the edge.  Currently this is done manually not using removeSpeciesFromEdge which leaves the species and reactions still in memory in more obscure locations leading to key errors later on.  This PR switches to using removeSpeciesFromEdge avoiding these problems.
> Properly remove forbidden species from edge

- README.md
Renamed CanTherm to Arkane and removed the PDF documentation links (are they still alive?)
> Updated documentation links in README.md

- rmgpy/data/rmg.py
Initialize the global `RMGDatabase` object upon calling it  even (and especially) if it already exists.
This solves cases when using RMG's API where the database doesn't get appropriately updated.
> Initialize the global RMGDatabase object upon calling it

- arkane/gaussian.py
The error massage of the loadGeometry method in Arkane's GaussianLog class was elaborated. If a species has more than 50 atoms, users should add the `iop(2/9=2000)` keyword to the input file for ask Gaussian to print the input orientation geometry.
> Enhanced error message of Arkane GaussianLog loadGeometry

- .conda/meta.yaml
- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/data/kinetics/groups.py
- rmgpy/molecule/graph.pyx
- rmgpy/molecule/group.py
- rmgpy/molecule/groupTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/reactionTest.py
- rmgpy/species.pxd
- rmgpy/species.py
This pull request adds functionality to automatically generate trees from any family provided the top nodes are not logic nodes.  It adds the functionality to automatically generate rules using the set of training reactions that match each node weighted based on the uncertainties of the reactions.  It also adds functionality for testing these trees and comparing them with the original RMG trees.  Bugfixes are also a very substantial portion of this PR.  
The algorithm has undergone significant restructuring since part 2, however, the general principles remain the same.  New nodes are generated by determining which of a generated set of potential extension nodes minimize the uncertainty in estimation using the mean after the split.  After the tree is generated they are regularized.  By …
> Automatic Tree Generation Part 3

- arkane/gaussian.py
- arkane/gaussianTest.py
- arkane/log.py
- arkane/molpro.py
- arkane/molproTest.py
- arkane/qchem.py
- arkane/qchemTest.py
- arkane/statmech.py
Currently Arkane requires optical isomer input.
This PR allows Arkane to estimate optical isomer and symmetry using the qm symmetry package.
* I wrote test methods to ensure that the arkane
* I have not tested compatibility with ARC, which may cause an issue since the redundant `symfromlog` boolean was removed.
Run an arkane calculation with & without the symmetry and optical isomer parameter.
> Auto optical isomer ex symmetry arkane

- rmgpy/data/kinetics/family.py
These are in fact the same object in memory, just with different
names. But to clarify the code, I think we should start calling it a productStructure
as soon as we have applied the recipe and turned it into products.
This commit moves where the renaming occurs up a few lines.
It is a small change.
> Move where we start calling the reactantStructure the productStructure

- rmgpy/data/solvation.py
- rmgpy/data/solvationTest.py
- rmgpy/rmg/main.py
- rmgpy/species.pxd
- rmgpy/species.py
We need to define a mixture of solvents in the solvent library
We now parse both a list of descriptors or just a descriptor as a solvent molecule. The descriptors could be either SMILES or adjLists.
A new method, `get_structure` was created in `SolventLibrary` 
Could be tested using -db PR https://github.com/ReactionMechanismGenerator/RMG-database/pull/318
> Allow cosolvents to be defined in a solvent library

- rmgpy/data/kinetics/family.py
In a sibling PR (https://github.com/ReactionMechanismGenerator/RMG-database/pull/296) we introduce two new families, `1,2_NH3_elimination` and `1,3 NH3_elimination`. This PR adds them to the list of families for which the formal charges of the products must be updated. We should merge this PR before merging the related database one.
> Update charge after using the NH3_elimination families

- arkane/data/TS_CCSD(T)_no_F12_sp_molpro.out
- arkane/gaussian.py
- arkane/log.py
- arkane/molpro.py
- arkane/molproTest.py
- arkane/qchem.py
I found out that some jobs don't have the ` Electronic Energy at 0 [K]:                      -768.275662 [H]` line we're currently looking for when parsing energies from a non-F12 CCSD calculation in Molpro. I made a test out of this example, and modified the parser accordingly.
> Parse CCSD(T) energies (no F12) in Molpro

- rmgpy/molecule/molecule.py
- rmgpy/molecule/resonance.py
- rmgpy/molecule/resonanceTest.py
Original issue was `UndeterminableKineticsError` while generating `intra_H_migration` reaction between `C1=C[C]2C=CC3=CC2=C3C1` and `[C]1=CC2=CC3=C2CC=CC13`.
Cause was inconsistent resonance structure generation resulting from minor differences in molecule objects, which led to the inability to identify the correct reverse reaction.
The cause of the resonance structure inconsistency was traced back to an inconsistency in perceived aromatic rings as determined by `Molecule.getAromaticRings()`, which relies on RDKit.
This was compounded by a bug in `generate_optimal_aromatic_resonance_structures` which would only attempt to aromatize the radical delocalization structures with the largest number of aromatic rings.
The combined effect was as follows:
- For one starting structure, RDKit …
> Fix resonance structure generation and filtration bugs

- arkane/log.py
Previously all such error messages related to the `loadGeometry` method, now updated and a `This method should be implemented by a subclass.`message was added.
Addresses #1602
> Correct NotImplementedError messages in Arkane log.py

- arkane/statmech.py
- arkane/statmechTest.py
- documentation/source/users/arkane/input.rst
- examples/arkane/reactions/23dimethylpropoxy/dimetpropoxy.py
- examples/arkane/reactions/23dimethylpropoxy/dimetpropoxy_betasci.py
- examples/arkane/reactions/CH3OH+HCO/ch3oh.py
- examples/arkane/reactions/CH3OH+HCO/hco.py
- examples/arkane/reactions/CH3OH+HCO/ts.py
- examples/arkane/species/Benzyl/benzyl.py
- examples/arkane/species/C2H4/ethene.py
- examples/arkane/species/C2H5/ethyl.py
- examples/arkane/species/H/H.py
- examples/arkane/species/Toulene_Free_Rotor/toluene_FreeRotor.py
- examples/arkane/species/Toulene_Hindered_Rotor/toluene_HinderedRotor.py
Arkane uses the species linearity when projecting out rotor frequencies.
This PR automates the determination of the linearity attribute, so now it is optional in input files.
If the problem can be reduced in dimensionality, we first identify that. We then check that all atoms from the 3rd one on form a straight line (either in 2D space or in 3D space) within some precision with the first two atoms.
Examples and documentations were updated. Tests were added.
> Determine a species linearity from xyz

- arkane/data/molpro_TS.out
- arkane/molproTest.py
Bumping up RMG-Py's coverage by 0.01%!
> Tests: Added a Molpro negative frequency test to Arkane

- Makefile
When database tests fail, you get a million lines of logging statements, making it a pain to find the actual test results.
Disable log capturing for `make test-database`.
Break the database and try running the tests. A couple easy options: change an index in training reactions to be a duplicate or change a group definition to be more specific than its children.
> Modify test-database make target to not capture stdout and log

- arkane/input.py
- arkane/inputTest.py
- arkane/statmech.py
- documentation/source/users/arkane/input.rst
- examples/arkane/explorer/methyl+formaldehyde/input.py
- examples/arkane/reactions/H+C2H4=C2H5/input.py
- examples/arkane/reactions/NH2+N2H3=NH+N2H4/input.py
- examples/arkane/species/N4H6/N4H6/N4H6.py
- examples/arkane/species/N4H6/N4H6/freq.log
- examples/arkane/species/N4H6/N4H6/sp.out
- examples/arkane/species/N4H6/input.py
If the user did not specify the frequency scaling factor, Arkane uses the model chemistry to determine it from a dictionary. However, the model chemistry in Arkane currently respesents the sp level, whereas the freq level should have been used instead.
Arkane can now process a model chemistry in an sp//freq form, e.g., `CCSD(T)-F12a/aug-cc-pVTZ//B3LYP/6-311++G(3df,3pd)`, and determines the frequency scaling factor from the **freq** level, if available.
Also, if the frequency scaling factor was not specified and could not be determined from the dictionary, we now raise an error instead of setting it to `1` and warn the user. This way, software like ARC could capture the error and attempt to derive the frequency scaling factor by itself.
Added an example which also runs in RMG's tests. Also …
> Derive the frequency scaling factor in Arkane from the frequency level

- arkane/input.py
- arkane/inputTest.py
It already has a frequency scaling factor under Arkane statmech assign_frequency_scale_factor()
I chose to remove the newly added hard-coding instead of the table entry to leave the code generic, assuming that the scaling factor dictionary is more likely to change soon anyway (e.g., if we fit our own BACs).
Thanks, @mliu49, for spotting this duplicity.
> Don't hard-code for CBS-QB3-Paraskevas in process_model_chemistry

- rmgpy/data/kinetics/family.py
- rmgpy/data/thermo.py
- rmgpy/kinetics/surface.pxd
- rmgpy/kinetics/surface.pyx
- rmgpy/molecule/util.py
In order to get the RMG-website working with latest version of RMG. May add additional commits if new issues are discovered.
- Set default values for deltaAtomicAdsorptionEnergy when loading the thermo database. Somewhat addresses cfgoldsmith/RMG-Py#76
- Clear atom labels before getting thermo when adding training reactions. Somehow this is only an issue when using `getThermoDataForSurfaceSpecies`. This is likely the problem we were encountering during the catmerge hackathon.
- Add `StickingCoefficient.fitToData` method which is used by the results page of kinetics search. Simply a copy of `Arrhenius.fitToData`.
- Convert Pt back to X when getting element counts from InChI for validating InChI generation.
Suggestions for cat examples to run would be appreciated. Also, it would be a good …
> Small catalysis related fixes for website operation

- arkane/kinetics.py
- arkane/pdep.py
- rmgpy/kinetics/tunneling.pyx
Added a warning if a reaction barrier is too high in Arkane.
Also enhanced a related error message in tunnelling.
Minor: corrected reciprocal T axis units in Arkane plots (`1000/K` is strange, should be either `1/K` or `K^-1`)
> Improve error/warning messages concerning energy barriers in Arkane

- arkane/statmech.py
Arkane determines poor entropies for atoms. The reason is that it appends a translational partition function to modes only if it finds, e.g., 'Molecular mass:' in a Gaussian input file, but that line appears in a freq calculation, not in an sp calculation log file (atoms only have the latter, which is passed to Arkane as the frequency log file as well).
As a result, we get great H298's, but poor S298's:
Detect if the translational mode was not appended to the conformer modes, and if so determine it from the mass and append it.
This results in improved S298:
Much, much better, but could still be improved for O and S (I don't know what the source for the deviation is).
> Calculate the translational mode if doesn't exist

- ipython/kinetics_library_to_training.ipynb
Now that saveTrainingReactions supports lists for metadata, this approach is much faster.
> In training notebook, save once per family instead of per reaction

- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
- rmgpy/molecule/moleculeTest.py
- rmgpy/tools/canteraModel.py
We were artificially limiting our RDKit version, so this removes that limitation.
Major changes:
- Add RDKit and Cantera channels to defaults so we can directly get their packages
- Require RDKit > 2018, mainly so we don't pull from the RMG channel which has higher priority but older versions
Minor changes:
- Update unit tests broken by RDKit changes
- Remove argument to Cantera ReactorNet.step which no longer exists
- Alphabetize environment files
- Remove libgcc and libgfortran because they should be dependencies of packages that use them
- Remove scoop because it's no longer functioning
- Comment out muq and textgenrnn for MacOS and Windows because they don't work
Haven't done any real testing. Seems like this should be safe as long as all of the tests pass.
Not sure if we want to …
> Update environment files, including RDKit and Cantera versions

- arkane/gaussian.py
- arkane/log.py
- arkane/molpro.py
- arkane/qchem.py
- arkane/statmech.py
- documentation/source/users/arkane/input.rst
Previously we used the __frequency__ scaling factor to also scale the zero point energy correction in Arkane. Principally, these should be two different factors. Luckily, there's a simple ratio between them, a factor of 1.014 (+/- 0.002, see https://pubs.acs.org/doi/10.1021/ct100326h section 3.1.3) - largely independent of the model chemistry. So only of the factors one should be known, the second can be easily determined. **This erroneous behaviour causes a systematic error of about 1.5 kJ/mol(!) - or 0.35 kcal/mol - to H298** (see below).
Thanks @dranasinghe for helping me understand what I'm doing :)
Dividing the freq scaling factor by 1.014 to obtain the ZPEC scaling factor when scaling the __ZPEC__.
Here are some species I ran (purposely selected ones with no torsions) prior and …
> Scaling zpe

- requirements.txt
- rmgpy/rmg/main.py
- rmgpy/yml.py
Adds generation of .rms YAML files for use in ReactionMechanismSimulator.
> Reaction Mechanism Simulator YAML File Generation

- arkane/inputTest.py
- rmgpy/thermo/nasa.pyx
- rmgpy/thermo/nasaTest.py
NASA polynomials would throw an error when calling the `as_dict` method when optional variables like `Tmin` are not set.
Added an if statement to the `as_dict` method to only add attributes which are set.
RMG tests should be sufficient
> Bugfix nasa as dict

- environment_linux.yml
- environment_mac.yml
- environment_windows.yml
Lately, every Travis build has been failing during the stage where the conda environment is created, with the following error message:
```
ResolvePackageNotFound: 
- dde -> pydot-ng
- dde -> theano=0.9.0 -> pygpu[version='>=0.6.5,<0.7']
- textgenrnn -> theano=0.9.0 -> pygpu[version='>=0.6.5,<0.7']
```
Interestingly, the conda environment builds just fine from a clean install of anaconda on the current master branch. However, after looking at how we have setup our Travis builds, I saw that we use miniconda on Travis. It appears that miniconda needs the dependencies of pydot-ng and pygpu to be explicitly given.
Added pydot-ng and pygpu to the conda environment files.
On a clean Ubuntu machine, I first tried creating a fresh anaconda install, and creating the conda environment did not cause …
> Fix Travis builds by adding in missing miniconda dependencies

- rmgpy/tools/simulateTest.py
Whenever the unit test are run, the simulation logs in `rmgpy.tools.simulateTest.py` are created but never deleted (whereas everything else with this test is deleted).
Add statements in `rmgpy.tools.simulateTest.py` to remove the log files after the tests have run.
Ran the unit tests and everything passed and the logs were deleted
> Delete simulation files after unit testing

- arkane/common.py
- documentation/source/users/arkane/input.rst
Added a short description of `Angle` and its units when a ScanLog is read from a text file.
Also corrected a minor typo in common.py
> Modified the Arkane ScanLog documentation

- arkane/statmech.py
Added frequency scaling factors for the `wb97xd/def2tzvp` and `apfd/def2tzvpp` levels of theory, calculated using Truhlar's method.
Should be straight forward to review.
> Added two frequency scaling factors to Arkane

- arkane/common.py
- arkane/commonTest.py
- arkane/statmech.py
- rmgpy/quantity.pxd
- rmgpy/quantity.py
- rmgpy/quantityTest.py
- rmgpy/rmgobject.pxd
- rmgpy/rmgobject.pyx
- rmgpy/rmgobjectTest.py
- rmgpy/statmech/rotation.pyx
- rmgpy/statmech/torsion.pyx
- rmgpy/statmech/translation.pyx
- rmgpy/thermo/model.pxd
- rmgpy/thermo/model.pyx
- rmgpy/thermo/nasa.pxd
- rmgpy/thermo/nasa.pyx
- rmgpy/thermo/nasaTest.py
- rmgpy/thermo/wilhoit.pyx
- rmgpy/thermo/wilhoitTest.py
The methods `as_dict` and `make_object` allow for any object that inherits from RMGObject to be easily saved to a yaml file and reconstructed from a yaml file, respectively. However, as currently written is RMG there is a limited recursion depth to how many objects, dictionaries, and lists can be nested inside of each other.
For example, consider an object that has an attribute that is a dictionary which itself contains another object. The desired affect of `as_dict` would be for the object nested inside of this dictionary to be expanded to a dictionary (i.e. for `as_dict` to be called on this object as well). However, the current implementation will return for this attribute a dictionary that contains the object itself rather than the expanded object.
Furthermore, many objects have to …
> Recursive as dictionary

- rmgpy/molecule/atomtype.py
A couple of small atomType fixes for Fluorine, that were causing segfaults when testing the database https://github.com/ReactionMechanismGenerator/RMG-database/pull/317
> Fluorine fixes

- arkane/commonTest.py
- examples/arkane/reactions/23dimethylpropoxy/dimetpropoxy.py
- examples/arkane/reactions/23dimethylpropoxy/dimetpropoxy_betasci.py
- examples/arkane/species/C2H6/C2H6.py
- examples/arkane/species/C2H6/input.py
Setting `frequencyScaleFactor` in an species file instead of an Arkane input file does nothing. Therefore, we should not define this in our example files. See #1655 
~~Must be merged after #1643~~ (Update: This PR can now be reviewed and merged when ready)
> Fix frequencyScaleFactor in Arkane examples

- arkane/commonTest.py
- arkane/statmech.py
- arkane/thermo.py
- arkane/thermoTest.py
Previously thermo blocks in Chemkin files outputted by Arkane did not have an element count if the molecular structure wasn't specified by the user.
Now we use the xyz information Arkane has for each species (specifically the species.conformer.number attribute) to determine the element count.
Additional minor modifications:
- replaced file `open()` `close()` with `with open()`
- don't append a species adjList dictionary to the species dictionary file if the species is already there
Added a thermoTest for the new element_count_from_conformer() method.
Try running a ThermoJob without specifying a structure and look at the Chemkin output
> Element count from conformer

- rmgpy/data/kinetics/groups.py
- rmgpy/kinetics/arrhenius.pyx
- rmgpy/kinetics/chebyshev.pyx
- rmgpy/kinetics/surface.pyx
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/reactionTest.py
- rmgpy/rmg/modelTest.py
- rmgpy/statmech/torsion.pyx
- rmgpy/thermo/wilhoit.pyx
This really should have been fixed a long time ago, but better late than never.
#329 implemented the capability for the PDepArrhenius class to hold MultiArrhenius rates instead of just Arrhenius rates. This is commonly seen in literature rates, especially from MESS calculations, e.g.
```
C2H3+O2=CH2CHOO                                    4.07E+27       -4.67    5222.0
PLOG/1.000E-02    1.55E+24       -5.45    9662.0/
PLOG/1.000E-02    1.78E-09        4.15    -4707.0/                            ! fit btw. 400 and 1250 K with MAE of 0.4%, 1.2%
PLOG/1.000E-01    3.48E+56      -15.01    19160.0/
PLOG/1.000E-01    2.36E+22       -4.52    2839.0/                             ! fit btw. 400 and 1350 K with MAE of 0.2%, 0.5%
PLOG/3.160E-01    1.25E+64      -16.97    21290.0/
PLOG/3.160E-01 …
```
> Support reversing PDepArrhenius objects containing MultiArrhenius rates

- .travis.yml
- rmgpy/rmg/reactTest.py
A bug (well, at least we hope it is a bug and not a new feature) in Travis Worker 6.2.1 means that these builds only run with 1 CPU instead of the expected two. This made us realize that we have a bug in one of our unit tests that does not check the number of CPUs properly (fixed by this PR). We also want to display CPU and memory information in the Travis build log so that we can debug errors like this in the future.
While this PR will not fix Travis builds completely for 6.2.1 (there is no work around for insufficient memory) it fixes everything that we can right now, and we have opened up issues with Travis.
- Reset module level rmgpy.rmg.main.maxproc back to the default of 1 at the end of individual tests
- Print CPU and memory info in the Travis logs.
I have already tested that our …
> Debug travis

- deploy.sh
Simplify logic to deploy only from feature branches
Changes behavior to not deploy from master or stable branches
Running RMG-tests is relatively expensive since it consumes at most 3 Travis builds and takes over an hour to complete. Since the goal of RMG-tests is to compare models between feature branches and master, it seems unnecessary to test on the master and stable branches.
Effective change is to prevent builds on master and stable. Also cleaned up the logic a bit in the deploy script.
It's a bit hard to test, but we should see an RMG-tests build triggered by the push build for this branch. We should confirm that the correct message is displayed for the PR build. However, we'll only be able to confirm that it doesn't build on master after merging.
Double-check that the bash code is …
> Do not deploy RMG-tests for master and stable branches

- documentation/source/users/rmg/input.rst
- examples/rmg/commented/input.py
- examples/thermoEstimator/input_ml.py
- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/rmg/input.py
Adds one more option for Machine Learning Estimator settings to allow one to use machine learning for only heterocyclic species and group additivity for the rest
`onlyHeterocyclics` option is added to Machine `rmgpy.rmg.input.mlEstimator`, and a new method `isHeterocyclic` is added to `rmgpy.molecule.molecule.py`. Relevant changes are made in other rmg files including the documentation. 
If both `onlyCyclics` and `onlyHeterocyclics` options are True, then `onlyCyclics` option overrides, and all cyclic species thermo will be estimated by machine learning.
3 unit tests are added to `rmgpy.molecule.moleculeTest.py` to check that species can be correctly identified as heterocyclic or not by `isHeterocyclic` method.
3 unit tests are added to `rmgpy.data.thermoTest.py` to check that mlEstimator …
> onlyHeterocyclics option for Machine Leaning Estimator Settings

- arkane/commonTest.py
- arkane/encorr/corr.py
- arkane/gaussian.py
- arkane/gaussianTest.py
- arkane/kinetics.py
- arkane/log.py
- arkane/main.py
- arkane/molpro.py
- arkane/molproTest.py
- arkane/qchem.py
- arkane/statmech.py
- arkane/thermo.py
- documentation/source/users/arkane/input.rst
- documentation/source/users/arkane/running.rst
- rmgpy/pdep/configuration.pxd
- rmgpy/pdep/configuration.pyx
- rmgpy/quantity.py
Arkane makes calculating rate coefficients easy, but suffers from not outputting all information needed in publications and also sometimes has unexpected behavior due to poor structuring.
This PR modularizes core methods, like loading statmech, kinetics, and thermo jobs; fixes the `--plot` option; uses species labels in chemkin files; adds try-except statments to prevent output from erroring; creates methods to parse T1 diagnostics, levels of theory, and geometries; allows for termolecular products to be output by pdep; outputs more quantum information necessary for publications; and makes chemkin output and merge models more robust.
Many of the new methods have unit tests to ensure proper functioning. I have run this version for large pressure dependent networks and highp kinetics and …
> Arkane output fixes

- rmgpy/data/kinetics/groups.py
- rmgpy/kinetics/arrhenius.pyx
- rmgpy/kinetics/chebyshev.pyx
- rmgpy/kinetics/surface.pyx
- rmgpy/statmech/torsion.pyx
- rmgpy/thermo/wilhoit.pyx
- utilities.py
#1659 added the `rcond` argument to calls to `numpy.linalg.lstsq`. A side-effect is that we broke compatibility with numpy versions prior to 1.14.
Original plan was to simply increase our numpy version requirement, but after thinking about it a bit more, this change does not seem like sufficient reason to do so.
This PR adds automatic determination of the appropriate value for rcond depending on the numpy version.
It also updates and futurizes `utilities.py`.
Will test in an environment with an older version of numpy. Travis should be sufficient to test that it works in newer versions of numpy.
> Check numpy version before passing rcond to numpy.linalg.lstsq

- arkane/kinetics.py
- arkane/kineticsTest.py
- documentation/source/users/arkane/input.rst
Previously, there were two spots where a list of temperatures
was created for fitting high pressure kinetics in Arkane.
One fit using inverse temperature spacing and the other one fit
with linear temperature spacing. See #1671
This PR consolidates creating a listing of temperatures
to the __init__ method, so there is only one spot where temperatures
are initialized. The default min and max in `generateKinetics` was
moved into the __init__ method. Three unittests were written for
obtaining the proper temperatures in the __init__ method.
`generateKinetics` previously accepted an arguement Tlist, which
is already an attribute of KineticsJob, creating redundancy.
The Tlist argument was removed and self.Tlist was used
in this method instead, simplifying the code.
Calls to quantity.Quantity in …
> Fix kinetics fitting with Tmin & Tmax in Arakne

- arkane/data/methoxy_explore.py
- arkane/explorer.py
- rmgpy/rmg/pdep.py
- rmgpy/rmg/pdepTest.py
This adds a number of miscellaneous bug fixes and improvements for automatic network generation.  Forbidden structure checking is now done on the edge for automatic network generation, flux reduction is now done on netReactions instead of pathReactions and has an additional very robust fallback algorithm just using rate coefficients.  Fixed a bug related to reduction when an isomer is removed.
> Automatic Network Generation 3

- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/rmg/react.py
Two performance related changes, cherry-picked from #1577.
1. Do not make deep copies of species in `react_species` ([reasoning](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1577#issuecomment-519315774))
2. Remove a redundant resonance structure generation step
Tested with the liquid oxidation test from RMG-tests, but on the FilterCritPerReactFamily branch.
Should confirm that RMG-tests show no differences in models except for runtime.
> Reduce species copying and resonance structure generation when reacting

- documentation/source/conf.py
Pages currently have a title that's something like
`<title>Arkane (arkane) &#8212; RMG-Py 2.1.0 Documentation</title>`
which clearly we forget to update with new version numbers.
This should automatically update it with the release version.
The titles are not prominent in some browsers, but are very obvious in google search results etc.
> Make page titles contain current release number instead of 2.1.0

- rmgpy/solver/base.pyx
Helps RMG diagnose #1678 more sensibly.
> raise a DASxError if nan found in moles

- rmgpy/statmech/__init__.py
- rmgpy/statmech/conformerTest.py
- rmgpy/statmech/rotationTest.py
- rmgpy/statmech/schrodingerTest.py
- rmgpy/statmech/torsionTest.py
- rmgpy/statmech/translationTest.py
- rmgpy/statmech/vibrationTest.py
This PR include python 3 compatibility changes to 
```
/rmgpy/statmech/
- __init__.py
- conformerTest.py
- rotationTest.py
- schrodingerTest.py
- torsionTest.py
- translationTest.py
- vibrationTest.py
```
including: 
- PEP-8 reformatting
- PEP-8 renaming of internal variables
- Futurize files
- Replace relative imports (`__init__.py`)
- remove unused `math` module
> Python 3 compatibility change to /rmgpy/statmech

- arkane/common.py
- arkane/commonTest.py
Now outputs [a standardized form of the xyz](https://en.wikipedia.org/wiki/XYZ_file_format)
Test extended accordingly
Addresses issue 1 reported in #1713 
I think this PR should be merged into the py3 branch before #1713, since it doesn't break Py2 compatibility.
> Modified the ArkaneSpecies.update_xyz_string() method

- rmg.py
- rmgpy/rmg/rmgTest.py
- rmgpy/tools/generate_reactions.py
- rmgpy/util.py
rmg.py is not installed as a module in the conda binary, so we cannot import this function
Fixes #1716 
Move `parse_commnad_line_arguments` inside of rmgpy.util where it can be imported for binary installations
> Move parse_command_line_arguments to util.py

- documentation/source/users/rmg/modules/generateChemkinHTML.rst
The documentation suggested to use `importChemkinLibrary.py`. It shoult be `generateChemkinHTML.py`.
Change from `importChemkinLibrary.py` to `generateChemkinHTML.py`
> generateChemkinHTML documentation editted

- documentation/source/users/rmg/running.rst
The option `-n $Processes` is an argument to `rmg.py` not to `python`.
The documentation suggested `python -n $Processes  path/to/rmg.py path/to/input.py` 
It now says `python path/to/rmg.py -n $Processes path/to/input.py`
> Corrected the instructions for running in parallel

- rmgpy/constraints.py
- rmgpy/data/base.py
- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/groups.py
- rmgpy/data/thermo.py
When debugging RMG or a software that depends on RMG the amount of debugging statements that get printed jam the buffer, not allowing the developer to conveniently see the actual original error massage.
Some logging statements, most of which are debugging level, were commented out. I only marked those which get printed too frequently in my experience. The purpose here was to flag them in the code for a discussion of how to best deal with them - leave commented out (so can be conveniently brought back to life if needed) or completely deleting them.
I think we can start the discussion even though we won't merge until the Py3 transition, since the same logging statements will be relevant after transitioning.
> Reduce the amount of logging messages that get too frequently printed during debug

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
Estimating thermo for aromatic species using group additivity can sometimes give weird results because we will get an estimate for every resonance structure and then take the one with the lowest H298. In some cases, this can lead to severe underprediction of enthalpy if there is an inappropriate group which results in a lower enthalpy than a more appropriate group.
For example:
This species has resonance structures where the radical can delocalize into the aromatic ring. One of those structures gives the estimate with the lowest H298 of 61.4 kcal/mol:
`Thermo group additivity estimation: group(Cs-(Cds-Cds)CbHH) + group(Cb-Cs) + group(Cb-(Cds-Cds)) + group(Cds-Cds(Cds-Cds)Cs) + group(Cb-H) + group(Cds-CdsCbH) + group(Cb-H) + group(Cds-Cds(Cds-Cds)H) + group(Cb-H) + group(Cb-H) + …
> Improve group additivity ranking for aromatic species

- arkane/mainTest.py
CH2CHOOHscans was previously being unpacked into the current working directory and was not being cleaned up.
- Add some variables to improve readability of path generation
- Specify the directory to which CH2CHOOHscans should be unpacked
- Check whether q2dtor is installed before unpacking scans and running the q2dtor example
Should be sufficient for Travis to pass.
While I was testing this, I discovered that this test doesn't seem to actually run q2dtor. My guess is that it's because the `r0.pes` file exists (since that's the only difference between this example and the test in ndTorsionsTest).
Was this intentional? If so, I will remove the changes that check that q2dtor is installed. If not, we should fix the example.
> Remove unnecessary zip folder unpacking in arkane/mainTest.py

- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
The updated fingerprint approach resulted in different fingerprint depending on atom order when the molecule contained more than two elements aside from CHNOS.
This fixes #1740.
This fixes the issue by sorting the elements alphabetically.
A unit test was written and the case outlined in the issue was also confirmed to work properly.
> Fix inconsistent molecule fingerprint generation

- rmgpy/tools/plot.py
While working with an ipython notebook, I noticed that the matplotlib backend was being set to `agg` which was not happening before. Turns out that the default value for the `force` argument in `matplotlib.use` changed from False to True in matplotlib 3, which meant that it would always try to change the backend even it it was previously set.
Provide `force=False` as an argument to `mpl.use`.
I've confirmed that this works in an ipython notebook.
> Do not force change matplotlib backend in tools.plot

- utilities.py
added a try/except block around the clean build directories function. This should catch the error and provide a message instead of crashing the script.
fixes `make clean` crashes if no build directory exists #1745
added a try/except block around the rmtree line that is throwing the errors
No testing was performed. 
Suggestions for verifying that this PR works or other notes for the reviewer.
> Update utilities.py to include exception handling

- rmgpy/chemkin.pyx
- rmgpy/solver/base.pyx
Exceptions no longer have a message attribute. We fixed a bunch of cases already, but missed some.
Replace calls to Exception.message with str(Exception).
These changes fixed the issues I was having. I don't know if it's necessary to do additional testing.
> Fix two calls to Exception.message, which no longer exists

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/molecule/filtration.py
- rmgpy/molecule/filtrationTest.py
- rmgpy/molecule/molecule.py
- rmgpy/molecule/pathfinder.py
- rmgpy/molecule/resonanceTest.py
- rmgpy/rmg/input.py
- rmgpy/solver/mbSampled.pyx
- rmgpy/solver/simple.pyx
- rmgpy/tools/simulate.py
This short pull request does 3 things, all related to my work on sulfur oxidation systems.
1. It allows Group Additivity Estimation for sulfur species with hypervalence up to 12 (the previous max was 10, which caused it to be very awkward when GAV was predicting species like CS(=O)(=O)C or the like.
2. When estimating species thermochemistry by GAV, RMG will now prioritize non-charged resonance forms. If there are multiple non-charged resonance forms then the form with the lowest enthalpy of formation will be selected as the representative thermochemistry. This solves problems where RMG would overestimate the stability of molecules that have charged resonance forms because when GAV is used to estimate the thermo of charged molecules it generally defaults to the top nodes. A test of this …
> Dms oxy changes

- .conda/meta.yaml
- Makefile
- rmg.py
In order to build the conda package for RMG-Py 3.0, there are a couple of dependencies that needed to be updated in the conda recipe, as well as a bug or two that needed fixing. While this PR does not update the version numbers, it is possible to build a binary from this branch with these changes **so long as a python 3 version of the database exists as well**.
- Update dependencies in the conda recipe
- Fix a bug in setup.py that prevented `python setup.py install` from working (by calling the solver check that has now been moved to utilities.py)
- Prevent throwing an error if utilities.py is not available, which is the case for the binary builds.
I built the RMG 3.0.0b successfully from this branch, so everything should be in order.
> Fix conda build issues

- scripts/generateFluxDiagram.py
Fix the naming bug for argument parsing
> Fix variable name in FluxDiagram script

- rmgpy/data/thermoTest.py
By default, RMG loads all thermo libraries by searching the libraries directory using os.walk, which uses os.scandir to get files. The resulting file (and library) order is arbitrary.
Additionally, changes the the database (such as adding new libraries) could potentially affect these tests.
This fixes #1733.
This PR adds a thermo library list when loading the thermo database in thermoTest, which ensures more deterministic behavior. The chosen libraries were the minimum necessary for all existing tests to pass.
Confirm that unit tests pass.
> Add thermo library list to rmgpy/data/thermoTest.py

- rmgpy/pdep/network.py
- rmgpy/pdep/reaction.pyx
This PR brings substantial performance improvements to RMG pressure dependence jobs by cutting down unnecessary costs associated with logging.
The key change is related to a subtlety in using the logging module. We commonly call logging with statements such as
```
logging.debug('Something happened to {0}'.format(object))
```
When executing this, Python will first perform the string formatting and pass the result to `logging.debug`. Then, regardless of whether or not the logging level requires this to be printed to the log file, the string formatting will have been performed.
However, the intended usage of logging is by directly providing the arguments to be formatted:
```
logging.debug('Something happened to %', object)
```
Note that sprintf-style formatting is required. In this case, the …
> Performance improvements to pdep logging

- documentation/source/users/rmg/running.rst
Currently renders a warning message:
System Message: WARNING/2 (/home/travis/build/ReactionMechanismGenerator/RMG-Py/documentation/source/users/rmg/running.rst, line 31)
Title underline too short.
Tiny tweak, barely worth a PR
> Title underline too short.

- rmgpy/tools/generate_reactions.py
This pull request resolves #1779     
'maxproc': args.maxproc, was added as an entry to the kwargs dictionary in generate_reactions.py
"python ~/RMG-Py/scripts/generateReactions.py -n 1 input.py" will print the expected "For reaction generation, 1 process is used" from react.py
"python ~/RMG-Py/scripts/generateReactions.py -n 2 input.py" will now print the expected "For reaction generation, 2 processes are used" from react.py
Activity monitor confirms that 2 processes are being used and indeed the run time is faster
All feedback and suggestions are welcome :)
> Allow generate_reactions.py script to accept number of processors 

- documentation/source/users/arkane/input.rst
Arkane's documentation errors [here](http://reactionmechanismgenerator.github.io/RMG-Py/users/arkane/input.html#multidimensional-hindered-rotors). This PR fixes it.
Without an empty line between a text block and a table block, the table won't be auto-formatted. Also deleted a leading space in the text that Sphinx complained about, and fixed a table's header/bottom format.
Looked good when compiled locally.
> Docs: Corrections to Arkane's Multidimensional Hindered Rotors docs

- arkane/input.py
- arkane/inputTest.py
- arkane/main.py
- arkane/output.py
- arkane/outputTest.py
The current Arkane output is not in a format that can be directly pasted into RMG libraries. See #1768 
Now Arkane will output thermo and kinetic libraries into an RMG_libraries folder. Note that only species with structure will be considered for the thermo library, and only reactions with structures for all their reactants and products will be considered for the kinetics libarry.
Added a unit test for an intermediate newly added function, could add functional tests as well.
Run a thermo job, specifying structure for a species, and see the resulting thermo library.
Run kinetics and pdep jobs, specifying structures for all species, and see the resulting kinetics library.
> Output RMG libraries in Arkane

- arkane/common.py
- rmgpy/pdep/me.pyx
- rmgpy/pdep/network.py
- Corrected `Network.eq_ratios` to `Network.eqRatios` in cse
- Fixed an incorrect value assignment line in ME
- Removed an error raised in Arkane when loading YAML files generated without an energy transfer model when running a PDep job
> Several small Pdep bug fixes

- .coveragerc
- Makefile
fixes #1792 
Adds the arkane folder and Arkane.py to code coverage.
Updated the sources in the .coveragerc file 
Checking that Arkane files show up in the coverage report for this PR should suffice
> Include Arkane in code coverage report

- rmgpy/pdep/draw.py
One of the arguments of rmgpy.pdep.draw is renamed from `format` to `file_format` in a previous commit, but the corresponding codes are not fully refactorized, causing failures in generating PES figures in png format. This will further hinder the PES from being generated and displayed on the RMG-website.
rename `format` to `file_format` .
By calling the draw function with `file_format="png"`, it can generate PES figure in .png format
> Fix PES figure generation in png format

- arkane/data/error_termination.out
- arkane/gaussian.py
- arkane/gaussianTest.py
As suggested in #1739
Add LogError to raise LogError for unconverged gaussian log file
didn't test
> Add LogError to raise LogError for unconverged gaussian log file

- arkane/data/Orca_TS_test.log
- arkane/data/Orca_dlpno_test.log
- arkane/data/Orca_opt_freq_test.log
- arkane/orca.py
- arkane/orcaTest.py
- arkane/statmech.py
- arkane/util.py
add OrcaLog and orca test to Arkane. currently limited to parsing energy, geometry, number of atoms, t1 diagnostic.  Freq, spin multiplicity, scan, conformers are not implemented
> added orca parser to arkane

- arkane/pdep.py
Running an RMG-generated network file results in:`TypeError: transition_state() got an unexpected keyword argument 'spin_multiplicity'.`
Reverted `spin_multiplicity` to `spinMultiplicity` in Arkane pdep.py where these networks are being generated. The bug only relates to sting representations of TSs, Species were unaffected.
Run a RMG with PDep on on master and on this branch, try to execute a sample network file via Arkane.
> Revert 'spin_multiplicity' to 'spinMultiplicity' in Arkane pdep

- arkane/data/B2PLYP.LOG
- arkane/data/UCCSDT_C_ATOM.LOG
- arkane/data/UCCSD_C_ATOM.LOG
- arkane/data/UMP2_C_ATOM.LOG
- arkane/gaussian.py
- arkane/gaussianTest.py
Arkane parser for Gaussian does not parse MP2, double hybrid DFT, CCSD, CCSD(T) energies. Previous to this change, HF energy was appended as e0 or energies should be given manually in the Arkane input file.
CBS-QB3 calculation contains CCSD(T), MP2, and CCSD energies, therefore, new if statements were added before CBS-QB3. The elif statements were arranged in the order of appearance in the output file
unit test added 
run a Gaussian calculation and check e0
> Gaussian energies

- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
There was a bug where `remove_van_der_waals_bonds` would modify the dictionary of bonds while iterating over it. I guess Python 3 detects this and crashes, wheras Python 2 didn't.
This pull request adds a failing unit test, then a patch that makes it pass.
For testing, you could run the tests after the first commit (and see them fail) then run them again after the second commit (and see them pass).
Note the test coverage is misleading because this code is cythonized. Coverage should go up, as I added a test.
> Test and fix Molecule.remove_van_der_waals_bonds

- examples/rmg/commented/input.py
Resolves the very minor issue in #1801 in which the commented input.py file was missing some descriptions.
I added some of these descriptions to the commented input.py file. I now realize that looking at RMG-Py/rmgpy/rmg/input.py is probably the best template for generating a new input file.
No testing was performed since the commented input file is never run
None
> Minor: updated parts of the commented input.py file

- documentation/source/users/rmg/modules/isotopes.rst
This commit updates the isotope documentation by linking a publication
and its corresponding scripts, as well as mentioning a caveat when
regenerating all the reactions from the start.
Built locally, checked spelling, viewed in browser, made sure links function
See if the writing makes sense.
> Update isotope documentation

- arkane/statmech.py
I ran a pdep job on Python 3 and encountered some small issues. This commit fixed these bugs.
Figure.close no longer works, so this commit changes how to close the figure. It also renames a variable for consistency.
Ran an RMG pdep job and got the expected result.
Make sure the code looks adequate
> Arkane pdep py3 fixes

- rmgpy/data/solvation.py
- rmgpy/data/solvationTest.py
Solvation correction for radical groups were not applied for radical species even if their radical groups were found in the solvation radical database.
Before, when the radical solvation correction would apply, it applied the correction for each individual radical electron found by using such for loop:
`for electron in range(1, atom.radical_electrons):`
But this was wrong, because the range should start from 0, not 1. If the number of radical electron is 1, then the range is from (1,1), which doesn't really start the for loop at all.
I changed this for loop to:
`for electron in range(atom.radical_electrons):`
such that if the number of electron is 1, the range will be from [0, 1], making the correction to be applied once. Since the number of radical electrons are always 0 or positive …
> Fix solvaion radical bug

- rmgpy/chemkin.pyx
- rmgpy/chemkinTest.py
- rmgpy/molecule/molecule.py
RMG Chemkin files break Cantera ck2cti for species with 5 or more elements. #1634 
- For species with 5 elements, prefer putting the 5th element in columns 74-78 of the first line
- For species with more than 5 elements, fix the line continuation syntax by switching to space delimited entries instead of continuing the `{0!s:<2}{1:>3d}` approach.
- Add read support for thermo entries using the line continuation syntax
- Add unit tests for reading and writing thermo entries
Should test with ck2cti and perhaps Chemkin as well. I have not done so yet.
> Fix bugs in Chemkin thermo entry element reading/writing

- rmgpy/data/solvation.py
- rmgpy/data/solvationTest.py
Solvation group additivity was estimating solute data by averaging over all molecules in species.molecule list (so it was averaging over all resonance structure). However, when the solvation solute groups were fitted from the experimental values, they were fitted using the SMILES of the most stable resonance structure in gas phase. Therefore, averaging over all resonance structures is not a correct way. Instead, it should be estimating solute data from only the most stable structure found by gas-phase. 
Extra Note:
Once might be concerned that the most stable resonance structure might change in liquid phase. But the change in the resonance structures when a species is solvated is already reflected in the experimental solvation energies, which are measured for a certain species in general, …
> fixed the solvation GAV heuristic

- rmgpy/data/kinetics/family.py
This is a duplicate of PR #1827, but only contains the relevant commits.
I found that when generating reverse templates, the action list would go in the same order as the forward, and this would cause issues when making and breaking multiple bonds.
```    ['FORM_BOND', '*1', 1, '*2'],
['CHANGE_BOND', '*1', 1, '*2'],
['CHANGE_BOND', '*2', -1, '*3'],
['BREAK_BOND', '*2', 1, '*3'],
['FORM_BOND', '*3', 1, '*4'],
['CHANGE_BOND', '*3', 1, '*4']
```
This change fixes this template's reverse recipe.
> Reverse recipes should be in reverse order

- rmgpy/chemkin.pyx
Adding Iodine in the elements section of the chemkin input file
file chemkin.pyx  in rmgpy folder.
s = 'ELEMENTS\n'
elements = ('H', ('H', 2), ('H', 3), 'C', ('C', 13), 'O', ('O', 18), 'N', 'Ne', 'Ar', 'He', 'Si', 'S', 'Cl', 'I')
A clear and concise description of testing that you've done or plan to do.
Suggestions for verifying that this PR works or other notes for the reviewer.
> Added Iodine as element in Chemkin input file

- rmgpy/data/kinetics/library.py
These lines checked if reactions were marked as 'Duplicate' when loading in a previously saved seed that was automatically generated by RMG during a previous run.
**Attempts to load in a previous seed from a large mechanism never finished loading and could never start the first iteration.** 
By large, think PDD pyrolysis with 100,000 + reactions, each with large molecules. The seed would load in, but then each reaction was checked against each other to make sure there were no duplicates. Performing subgraph isomorphism checks on EACH molecule would not complete within 24 hours, so in practice, I could never actually restart a job from a seed because it took so long to get started. The check is also redundant since the duplicate flags are preserved when loading in the previous seed
Deleted …
> Remove unnecessary duplicate check

- rmgpy/kinetics/arrhenius.pyx
- rmgpy/kinetics/arrheniusTest.py
Sometimes people represent a complex rate expression as the sum of Arrhenius, or sum of PDepArrhenius terms, one or more of which is negative. Although an overall negative rate expression is not allowed, one part of the sum may be. 
When generating reverse rate expressions, these multiple sum type expressions are reversed one part at a time. The function to generate a reverse rate expression for an individual Arrhenius expression does so by evaluating the rate at some array of temperatures, calculating the reverses (from the equilibrium constants) then  doing least squares regression to fit a new Arrhenius. But that last step involves taking logarithms of the rates, which leads to `nan` if they're negative, which then messes up the least squares regression.
This was the underlying cause …
> Enable fitting and reversing of negative reaction rates.

- .conda/meta.yaml
- arkane/pdepTest.py
- environment.yml
- rmgpy/chemkin.pyx
- rmgpy/chemkinTest.py
- rmgpy/constraintsTest.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/data/thermoTest.py
- rmgpy/data/transportTest.py
- rmgpy/kinetics/arrhenius.pyx
- rmgpy/molecule/converter.py
- rmgpy/molecule/translator.py
- rmgpy/molecule/translatorTest.py
- rmgpy/rmg/rmgTest.py
- rmgpy/thermo/thermoengine.py
- scripts/rmg2to3.py
This PR addresses a number of minor issues in preparation for the 3.0 release.
Please see the individual commit messages for the changes.
I think passing unit tests should be sufficient since these are all relatively minor.
Thoughts on the approaches chosen here would be nice.
I think the increased tolerance for the pdep test may be worth additional discussion. There are still some ongoing efforts to try and identify the root cause of that issue.
> Collection of small fixes

- rmgpy/rmg/input.py
- rmgpy/rmg/inputTest.py
Added some code in rmgpy/rmg/input.py that normalizes the mole fractions if necessary. This resolves issue #1750 
RMG previously would normalize initial mole fractions specified in input files. This functionality was removed in #1331.
Added some code in rmgpy/rmg/input.py that normalizes the mole fractions if necessary
I tested this on the superminimal example with two conditions:
```
initialMoleFractions={
'H2': 0.67, 'O2': 0.33,
},
```
and 
```
initialMoleFractions={
'H2': 67, 'O2': 33,
},
```
The feature seems to work as expected
Minor question: I used `for spec, molfrac in initialMoleFractions.items():` to be explicit about what we were looping over. The code immediately above this addition in line 195 uses a more general `for key, value in initialMoleFractions.item():`. I assume …
> Allow mole fractions to be normalized if they do not sum to one

- rmgpy/rmg/main.py
fixes #1786 
As noted in the issue this fixes, the Windows Subsystem for Linux sometimes throws a permission error 
when trying to renaming non-empty directories, even when the user has the permissions set properly on the directories and files to do so. This is problematic, because we rename the seed directory folder temporarily every time we save a new seed mechanism so that the previous seed mechanism is not lost in case we encounter an error when saving the new one. Renaming the directory does not require copying large amounts of data, so this is the preferred solution in general, but as noted can cause problems for WSL users.
There appear to be several issues opened over a few years complaining about this issue if I am not mistaken, so it appears to be a reoccurring problem. Given …
> Fix WSL permisson bug for renaming directories

- arkane/__init__.py
- arkane/ess/log.py
- arkane/ess/orca.py
- documentation/source/conf.py
- documentation/source/reference/arkane/common.rst
- documentation/source/reference/arkane/explorer.rst
- documentation/source/reference/arkane/index.rst
- documentation/source/reference/arkane/log.rst
- documentation/source/reference/arkane/molprolog.rst
- documentation/source/reference/arkane/orcalog.rst
- documentation/source/reference/arkane/output.rst
- documentation/source/reference/arkane/qchemlog.rst
- documentation/source/reference/arkane/sensitivity.rst
- documentation/source/reference/arkane/terachemlog.rst
- documentation/source/reference/arkane/util.rst
- documentation/source/reference/molecule/filtration.rst
- documentation/source/reference/molecule/index.rst
- documentation/source/reference/rmg/index.rst
- documentation/source/reference/rmg/species.rst
- documentation/source/reference/solver/index.rst
- documentation/source/reference/solver/mbsampledreactor.rst
- documentation/source/reference/solver/surfacereactor.rst
- documentation/source/reference/solver/termination.rst
- documentation/source/users/rmg/liquids.rst
- documentation/source/users/rmg/modules/generateReactions.rst
- rmgpy/molecule/filtration.py
- rmgpy/solver/__init__.py
- rmgpy/solver/mbSampled.pyx
The API documentation is substantially out-of-sync with the current code structure. #1153 is definitely still relevant.
This PR adds a bunch of un-documented modules to the API documentation and also fixes various issues with docstrings so that they can be displayed properly.
The documentation has been compiled to verify that the changes look correct.
This PR does not exhaustively update the API documentation, i.e. there are still portions of the code which are not included. While adding documentation pages is easy, some decision-making is required in choosing how to organize and format the documentation.
Here's a partial list of modules which are not documented:
I'm not sure how many of these could/should be documented before the release. Contributions from others would be necessary if …
> API documentation updates

- arkane/input.py
- examples/arkane/species/Toulene_Hindered_Rotor_SemiClassicalND/toluene_HinderedRotor.py
- rmgpy/statmech/conformer.pyx
- rmgpy/statmech/ndTorsions.py
- rmgpy/statmech/ndTorsionsTest.py
This has a number of numerical improvements for the calculation of ND classical and semiclassical hindered rotor partition functions.  I've removed use of SmoothBivarateSpline interpolation as this resulted in some negative fitted internal reduced moment of inertia values and I've fixed issues with the integration routine.
Also includes miscellaneous Arkane improvements: lets Arkane deal with RateUncertainty objects, makes the semiclassicalND rotors example consistent with the other Toulene examples, and adds a error trigger in internal reduced moment of inertia calculations that prevents use of 0-indexed atom numbers that result in all kinds of weird outputs from the function.
> ND Hindered Rotor Improvements

- environment.yml
Significant memory leaks have been observed when using an rmg_env containing rdkit version 2019.03.4.0 as referenced in issue #1850. The issue is documented on the rdkit page [https://github.com/rdkit/rdkit/issues/2639](https://github.com/rdkit/rdkit/issues/2639) 
Memory leaks are not observed when using a more recent rdkit version of 2019.09.1.0 (and it looks like they've already released a version 2019.09.2.0)
Updated the minimum required version number for rdkit in the environment.yml file
I used this environment.yml file to create an rmg_env. Doing `conda list rdkit` produced the following output, confirming that the change is implemented correctly
```
rdkit                     2019.09.2.0      py37h65625ec_1    rdkit
```
> Update required version of rdkit to avoid severe memory leaks

- ipython/cantera_sensitivity_comparison.ipynb
- ipython/cantera_simulation.ipynb
- ipython/combustion_model_and_ignition_delay_demo.ipynb
- ipython/local_uncertainty.ipynb
`canteraModel` was renamed to `canteramodel` but this change did not make it into the Jupyter notebooks. This PR fixes that.
> Update canteramodel module name in Jupyter notebooks

- rmgpy/qm/gaussian.py
Allows local unit tests to pass when run on servers with Gaussian
When I am checking out a new branch of RMG-Py on a server, it is re-assuring to see that all of the unit tests pass. Recently though I ran into an issue where one of the unit tests for Gaussian in the qm module ran (it only runs if Gaussian is detected) but could not pass because g16 was not listed as a possible executable. This is a very minor change for this reason, but could be important if people want to use QMTP on a server with Gaussian 16.
> Include Gaussian 16 executable

- rmgpy/data/kinetics/family.py
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/reactionTest.py
- testing/databaseTest.py
I was having issues with surfaceArrhenius training reactions that were in the reverse direction, as they would all be overwritten as ArrheniusEP instead of SurfaceArrheniusBEP.  This change fixes that and all tests pass locally and I am able to successfully generate models!
> Adding capability to have reverse surfaceArrhenius training reactions

- rmgpy/rmg/pdep.py
If the solution of the linear system gives NaNs originally the NaN got passed as the concentrations in the network breaking flux based network reduction. This small fix detects this case and returns None instead causing flux based network reduction to fall back to rate coefficient based methods in these cases. 
Input file with the issue this fixes is attached:  
[input.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/4172916/input.txt)
> Detect and handle NaNs in solve_ss_network

- rmgpy/molecule/converter.pxd
- rmgpy/molecule/converter.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/translator.pxd
- rmgpy/molecule/translator.py
- rmgpy/species.pxd
- rmgpy/species.py
RMG's atom types are relatively limited when dealing with non-standard molecules and an `AtomTypeError` might be raised upon calling `Molecule.updateAtomTypes`. Often, it is desirable to use the RMG API simply to create arbitrary molecule objects and use useful RMG methods that may not be as readily available in other cheminformatics packages. One possible application, is to use RMG's isomorphism checks to compare molecules that have been converted to their respective single-bonded versions.
This PR implements a new option, `raise_atomtype_exception` for many methods in the `Molecule` class and functions in the `translator` and `converter` modules, which enables setting the `raiseException` argument that was already available in `Molecule.updateAtomTypes.`
A typical application for me is …
> Add option to ignore atom type errors when making molecules

- rmgpy/data/kinetics/family.py
- testing/databaseTest.py
This is related to #1881, when I found that adding training reactions to the database would pass all database tests but then fail when used to generate rate rules when trying to run rmg.  This adds a check to catch these problem training reactions.
This also removes the hard-coded family work around, introduced in e8e292875bb412c8690b0a0584d2dc31c700d5b9
I have added a new kinetics check called `kinetics_check_surface_training_reactions_can_be_used` that checks all surface family training reactions.
I have changed the hard coded family exception to work for any family that has both reactants vdW bonded to the surface
All tests pass!
> Adding in a new database test to check all surface training reactions are useable

- arkane/explorer.py
- rmgpy/solver/liquidTest.py
- rmgpy/tools/generatereactionsTest.py
Gets rid of the liquidTest restart file that is generated by the unit tests. Also uses the setUpClass method, which is what is actually desired here.
> Liquid test improvements

- rmgpy/pdep/network.py
- rmgpy/rmg/model.py
- rmgpy/solver/base.pyx
- rmgpy/solver/liquid.pyx
- rmgpy/solver/simple.pyx
- rmgpy/solver/surface.pyx
This fixes #1905 and #1911.  The first is fixed by not displaying the warning when the network is in rmgmode. The second is fixed by detecting when the source of a network is not entirely in the core and setting the leak rate to zero in those cases.
> General Pdep Fixes

- rmgpy/kinetics/uncertainties.pyx
If rank 1 accuracy = 0, then in situations where training reactions are all from literature (rank 1), as the case for some newly added families, division by zero would occur when fitting ArrheniusBM model (cf. fit_to_reactions in arrhenius.pyx)
Estimated uncertainty in line 623 arrhenius.pyx is 0 if all training reactions in a family have rank 1. This will then lead to division by zero error during automatic tree generation. This PR provides a fix by changing the estimation for rank 1 from 0 to 0.2 kcal/mol to avoid overflow as suggested by @mjohnson541 
Estimated rank 1 accuracy in the `rank_accuracy_map` is changed to 0.2 kcal/mol instead of 0.
> BugFix: Make rank 1 accuracy 0.2 kcal/mol instead of 0 kcal/mol

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/thermo/thermodata.pxd
- rmgpy/thermo/thermodata.pyx
- rmgpy/thermo/thermodataTest.py
fixes #1877
We'd like to add metadata to GAV when a group is empty or missing.
- Added an `is_all_zeros` method to `ThermoData`
- Add a `missing(<group>)` comment to GAV ThermoData when relevant
tests were added
generate GAV thermo for the molecule in the test or for the molecules in #1877, look at the thermo data comment
> Gav comments

- rmgpy/kinetics/arrhenius.pyx
Now output correct units for trimolecular reactions
`A` unit for a trimolecular reaction was not correctly assigned. 
Updated unit dictionary, now supports a trimolecular reaction.
> Add A units for trimolecular reactions in ArrheniusBM model fits

- arkane/ess/gaussian.py
Very minor. If no negative frequency, an error will be raised due to slice index 0 from an empty list, and `if frequency is None` will never happens.
> BugFix: load_negative_frequency() undesired error behavior

- rmgpy/tools/mergemodels.py
- rmgpy/tools/mergemodelsTest.py
The script mergeModels.py fails to guarantee unique indices, which prevents the merged models from being simulated or restarted as described in issue #1932. 
mergemodels.py was reverted back to how it was before PR #1649. The motivation of PR #1649  was to avoid changing chemkin or cantera names at the expense of not ensuring unique indices. 
An unnecessary check was removed from mergemodelsTest.py. All unittests passed locally.
> Fix indexing while merging models

- rmgpy/data/transport.py
- rmgpy/data/transportTest.py
Because there are no Joback groups for aromatics currently we can't estimate transport properly for benzene, this keuklizes aromatic molecules so they can be estimated using transport Joback groups.
> Use Kekulized structures for Transport Estimation

- rmgpy/data/kinetics/family.py
- rmgpy/molecule/molecule.py
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/reactionTest.py
- rmgpy/species.pxd
- rmgpy/species.py
The Family.add_atom_labels_for_reaction() method may be used for 3D TS guess generation outside RMG. However, currently, it does not preserve the atom order of the original molecule (tracked down to a `struc.update()` call under `apply_recipe()`)
A `save_order` attribute was added to `KineticsFamily`.
> Added an option to save atom order when adding atom labels for a template reaction

- rmgpy/rmg/main.py
Range based reactor didn't work for liquid phase before. It's because RMG used `reaction_system.T` to calculate viscosity for liquid phase. However, `reaction_system.T` is `None` when the input T is a list (range). 
I modified the code such that RMG will check whether `reaction_system.T` exists. If so, viscosity will be calculated when the model is initialized (i.e. not range based). If not, then viscosity will be calculated in each run of `n_sims` with the corresponding T stored in the condition dictionary from `rmg_memories.get_cond()`. `diffusion_limiter` is still enabled in the initiation stage, no matter the liquid phase job is range based or not.
I tested with an old liquid reactor input file. It works now. Output seems reasonable.
> Debugged liquid phase range based reactor

- ipython/data/parse_source/chem_annotated.inp
- ipython/data/parse_source/species_dictionary.txt
This is a minor modification.
The reaction templates commented in the original chen_annotated.inp is no longer valid since PR #334 tree generation for R_recombination. 
I ran a RMG simulation with the original input.py and update the chem_annotated.inp and species_dictionary.
I ran the three uncertainty related jupyter notebook. All can load the new files successfully.
> Minor: Updated files in /ipython/data/parse_source

- rmgpy/molecule/atomtype.py
When developing RMG-website, I found that the error message of AtomTypeError is incorrect. The problem is due to item mismatching when generating the error message.
Correct the error message.
Passed all tests
> BugFix: correct AtomTypeError

- rmgpy/data/solvation.py
- rmgpy/thermo/thermoengine.py
I think it would be nice to know if the species's thermo has been corrected with solvation correction of which solvent.
I add the solvation correction comment in the attribute species.thermo.comment in the method get_thermo_data() for class Species.
Tested locally with benzene as solvant. The result looks like: `Thermo group additivity estimation: group(Cs-CsCsHH) + group(Cs-CsCsHH) + group(Cs-CbCsHH) + group(Cs-CbCsHH) + group(Cb-Cs) + group(Cb-Cs) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + group(Cb-H) + ring(Benzene) + ring(Benzene) + radical(Benzyl_S) + radical(Benzyl_S) Solvation correction with benzene as solvent.`
> Minor: add solvation correction in species.thermo.comment

- rmgpy/data/thermo.py
Related to PR #1924
Put 'H' last, and don't repeat a 'Cb' label for neighboring atoms of a Cb atom.
These small label corrections will allow easier group interpretation in T3.
> Fix labels of missing thermo groups

- arkane/encorr/bac.py
- arkane/encorr/data.py
- arkane/encorr/dataTest.py
- arkane/input.py
- documentation/source/users/arkane/input.rst
Allows excluding elements, specifying charge, and specifying multiplicity for training set molecules used for BAC fitting. Added some new unit tests as well, and tested a BAC Arkane job with some of the new settings.
> BAC options

- arkane/encorr/ae.py
- arkane/encorr/aeTest.py
- arkane/encorr/bac.py
- arkane/encorr/reference.py
- arkane/input.py
- arkane/main.py
- documentation/source/users/arkane/input.rst
We should fit atom energies so that levels of theory that produce incorrect atom energies can be used to compute thermochemistry.
Added `AE` and `AEJob` classes that require a dictionary of species labels with single-point electronic energies (computed using the experimental geometries available in the reference database). For example,
```python
species_energies = {
'Dihydrogen': -1.1607014438,
'Dinitrogen': -109.5502634582,
'Dioxygen': -150.3479925723,
'Disulfur': -796.325655201,
...
}
```
The list of species that has to be provided is available in `SPECIES_LABELS` in `arkane/encorr/ae.py`. Atom energies can be fitted by using the `ae()` function in Arkane input files as described in the updated documentation. Corresponding database PR is ReactionMechanismGenerator/RMG-database#415. …
> Atom energy fitting

- arkane/common.py
- arkane/commonTest.py
- arkane/data/species/reference_species_example.yml
- arkane/encorr/ae.py
- arkane/encorr/aeTest.py
- arkane/encorr/bac.py
- arkane/encorr/bacTest.py
- arkane/encorr/corr.py
- arkane/encorr/data.py
- arkane/encorr/dataTest.py
- arkane/encorr/isodesmic.py
- arkane/encorr/isodesmicTest.py
- arkane/encorr/reference.py
- arkane/encorr/referenceTest.py
- arkane/ess/adapter.py
- arkane/input.py
- arkane/inputTest.py
- arkane/main.py
- arkane/modelchem.py
- arkane/modelchemTest.py
- arkane/statmech.py
- arkane/statmechTest.py
- documentation/source/users/arkane/input.rst
- examples/arkane/bac/wb97m-v_def2-tzvpd/input.py
- examples/arkane/species/Pentyl_isodesmic/input.py
- rmgpy/rmgobject.pyx
- rmgpy/rmgobjectTest.py
Model chemistry definitions in Arkane are not unique because changes in software and options can lead to different results. The goal is to standardize the representation in Arkane and in the RMG database by defining detailed and unique levels of theory to identify the settings used in quantum chemistry calculations.
Implements two new classes, `LevelOfTheory` and `CompositeLevelOfTheory`, which are used by Arkane internally instead of model chemistry strings. Arkane input files can still be specified using the `modelChemistry` syntax, but using the new level of theory objects is now also possible. Arkane will first try to find an exact match for the specified level of theory in the RMG database (including options like software, solvation, and additional arguments) but will fall back to …
> Standardize model chemistry

- arkane/encorr/ae.py
Atom energy fitting will fail if not all species labels are provided. However, for some methods, e.g., DLPNO, some atoms are not available (Br for DLPNO). We would still like to be able to fit atom energies in such cases.
Performs the fit using the species labels from the provided dictionary instead of the complete list of species labels in arkane/encorr/ae.py. Prints warnings if species are missing.
I ran an atom energy job removing some species and it still works.
> Allow atom energy fitting if not all species are provided

- rmgpy/molecule/atomtype.py
Closes #1957. 
Thanks to @xiaoruiDong for pointing to the problem.
Changed the error message to be less misleading when you have double bonds to N or X.
Small change. Tested it on the broken adjacency list described in #1957 and it reports the much more accurate and helpful `AtomTypeError: Unable to determine atom type for atom O-, which has 1 single bonds, 1 double bonds (0 to O, 0 to S, 1 others), 0 triple bonds, 0 quadruple bonds, 0 benzene bonds, 2 lone pairs, and -1 charge.`.
> Tweak the AtomTypeError error message.

- arkane/encorr/reference.py
If you load and then immediately save the reference database, some items in the database change, including SMILES strings, InChI strings/keys, and floating point errors for ScalarQuantity objects, even though the user made no changes to the files.
This PR fixes the issues related to the identifiers by resetting these attributes in the __init__ method if they were supplied (as they would be when loading the database). This avoids the translation errors that occur when creating the species in the call to the super class ArkaneSpecies.
This PR does NOT fix the issues with the floating point errors. It is noteworthy that these errors only occur inside of ScalarQuantity objects. The root cause of this is that quantities with non-SI units are first converted to SI units (ScalarQuantity.value is …
> Avoid SMILES translation errors for reference species

- arkane/input.py
arkane.inpuy doesn't have the same fix that rmgpy.main does, i.e. skipping add_rules_from_training if the tree is auto-generated.
Added a check that if family.auto_generated is True, Arkane will skip add_rules_from_training.
Tested with test_arkane_examples in inputTest.py locally and it passed.
> Add family.auto_generated check in Arkane

- rmgpy/molecule/draw.py
- rmgpy/molecule/drawTest.py
Hydrogen atoms were not drawn explicitly, and (therefore) hydrogen bonds were not drawn. Structures held together (or apart) with hydrogen bonds would just collapse on top of themselves. See before/after example below.
1. Don't remove an H if it has an H bond.
2. Draw H-bonds as dotted lines.
3. Fix a problem that occurred with a complicated system of fused rings.
```
from rmgpy.molecule import Molecule
example =  Molecule().from_adjacency_list("""
example
1  O u0 p3 c-1 {2,S} {10,H}
2  N u0 p0 c+1 {1,S} {3,D} {4,S}
3  O u0 p2 c0 {2,D}
4  O u0 p2 c0 {2,S} {7,S}
5  N u0 p1 c0 {6,S} {8,S} {9,S} {7,H}
6  O u0 p2 c0 {5,S} {10,S}
7  H u0 p0 c0 {4,S} {5,H}
8  H u0 p0 c0 {5,S}
9  H u0 p0 c0 {5,S}
10 H u0 p0 c0 {6,S} {1,H}
""")
example
display(example)
for m in …
```
> Draw hydrogen bonds.

- rmgpy/data/thermo.py
The updated values are consistent with how the atomic binding energies on the other 9 metals are calculated (to be included in the database). [PR#387](https://github.com/ReactionMechanismGenerator/RMG-database/pull/387)
The DFT calculations were conducted by Katrin Blondal and Bjarne Kreitz at Brown University in the fall 2019.
> Updated the Pt binding energy values based on recent DFT calculations

- rmgpy/molecule/resonance.py
Lpsolve steals the interrupt signal when it runs, to handle this the original configuration grabbed the current SIGINT signal and returned it to that value. That worked well when running python normally, but this does not work with python-jl since
python-jl gives SIGINT to julia which causes grabbing the signal to return None. 
Setting it to the default (raise KeyBoardInterrupt) after running lpsolve should work in both cases.
> Return signal.SIGINT to the default after using lpsolve

- rmgpy/species.py
- rmgpy/speciesTest.py
For non-strict isomorphism, a single negative comparison is sufficient to conclude that two species are different. Therefore, `Species.is_isomorphic` should return early instead of doing comparing all resonance structure combinations.
Thanks to @alongd for pointing out the bug.
Fix `Species.is_isomorphic` to return early when `strict=False`.
A unit test was added to confirm that the `strict` argument works properly. I also tested to confirm that it correctly returns early now, but it's not straightforward to write a unit test for that.
> Short-circuit Species.is_isomorphic when strict=False

- rmgpy/rmg/main.py
See #1872.
Essentially the original code intended to get reactions to high pressure limit by setting P=1e8 Pa in LiquidReactor, but it couldn't perform the collision limit violation check for PDep type reactions because LiquidReactor doesn't have Prange attribute. (main.py line 677)
```
try:
self.Pmin = min([x.Prange[0].value_si if x.Prange else x.P.value_si for x in self.reaction_systems])
self.Pmax = max([x.Prange[1].value_si if x.Prange else x.P.value_si for x in self.reaction_systems])
except AttributeError:
pass
```
Added dummy variable `Prange` in LiquidReactor. With this, Pmin = Pmax = P = 1e8 Pa to get reactions to high pressure limit for LiquidReactor.
This is my testing script. The original code gave an AttributeError when trying to access x.Prange. This PR's code can perform …
> Modify Pmin/Pmax code in main.py & Feed in species_list for ThirdBody type kinetics to allow collision limit violation check

- examples/rmg/catalysis/ch4_o2/input.py
- examples/rmg/catalysis/methane_steam/input.py
To be consistent with the hard-coded Pt111 reference binding energy values and with the metal attributes database. https://github.com/ReactionMechanismGenerator/RMG-database/commit/05ee78b278b54f40713d2f58c5b30cd692f5319
(Updated both the bindingEnergies and surfaceSiteDensity).
Addresses issue #1995 
The updated values were calculated by Katrin Blondal and Bjarne Kreitz at Brown University, using the PBE-D3(ABC) functional.
> Updated catalystProperties in catalysis example input files

- rmgpy/rmg/main.py
This commit prevents error message when running with surfaceReactor
For now, Pmin and Pmax of surfaceReactor remain with the default value of `None`
See comments on https://github.com/ReactionMechanismGenerator/RMG-Py/commit/219590135056ceb98571a6bd04a47b6955456eeb
> Readded try-except for Pmin and Pmax determination

- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
1. Currently global uncertainty analysis throws an KeyError message for liquid reactor because it tries to access `reaction_system.sens_conditions['P']` and `del mol_frac_list[0]['P']` in `rmgpy/rmg/main.py/RMG.run_uncertainty_analysis()`. 
2.  Currently, if terminationTime is not assigned in the reactor options block,  `rmgpy/rmg/main.py/RMG.run_uncertainty_analysis()` assigns the `time_criteria` to be `self.uncertainty['time']`. However, if terminationTime is also not provided in the uncertainty options block, `self.uncertainty['time']` would be None and causes an AttributeError. It is desirable for RMG to throw meaningful InputError here. 
I assigned `Plist = ([1e8],'Pa')` for liquid reactor, which uses `self.P = 1e5 #kPa` in liquid.pyx. I also added an informative InputError for …
> Debugged global uncertainty analysis

- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
Currently there's no way to force RMG to react species that we know are important. This PR adds a react() block that takes in a list of tuples of species labels. Each tuple corresponds to a group of species that are reacted at the beginning of the run.
> Allow Specification of an Initial Set of Reacts

- rmgpy/kinetics/model.pxd
- rmgpy/kinetics/model.pyx
- rmgpy/reaction.py
- rmgpy/reactionTest.py
Units for reverse rate constants are in volume units for surface reactions, but they should be in area units.  For example, for the reaction `H2 + X + X <--> H-X + H-X`, rmg assigns units of `m^3/(mol*s)` to the reverse rate constant kr, but since H-X is in area units (mol/m^2), the rate r=kr[H-X][H-X] would have units `mol/(m*s)`.  
Modified the `get_rate_coefficient_units_from_reaction_order` to consider the number of gas and surface species, and assign the units accordingly.
Added a unit test for `H2 + X + X <--> H-X + H-X` to make sure we get `m^2/(mol*s)` units for the reverse rate constant.
> Unit fix for reverse rate constants with surface species

- testing/databaseTest.py
I am adding a new family Retroene. The accessibility test of Retroene family does not pass, which is due to that RMG-Py database test cannot correctly generate sample molecules for groups with `inRing` attributes. 
Accessibility would not be a problem for ATG generated trees. I simply added  `Retroene` into the `difficult_families` so that it won't run the accessibility test for Retroene. This should be merged before merging the database PR https://github.com/ReactionMechanismGenerator/RMG-database/pull/438 to allow the database PR passing the Travis tests.
> Avoid accessibility test for Retroene family

- rmgpy/molecule/isomorphismTest.py
- rmgpy/molecule/molecule.py
If you ran `Molecule.is_isomorphic` with an incorrect initial map, it would assume nothing was wrong with the map, and if it found no non-isomorphic things in the _rest_ of the molecule, would conclude the molecules were isomorphic.
This was causing some incorrect failing database tests.
If given an initial mapping, check it's valid.
Made a unit test that fails, then fixed it and it passes.
> Find and fix a bug in Molecule isomorphism

- rmgpy/data/kinetics/family.py
- rmgpy/kinetics/arrhenius.pyx
1. If there's only one training reaction in the node, we should be able to solve E0 for ArrheniusBM with A and n from the training reaction.
2. The `"BM rule fitted to {0} training reactions at node {1}".format(len(rxnlists[i]), entry.label)` always show BM rule fitted to 2 training reactions right now
1. If `len(rxns) == 1` in `fit_to_reactions`, E0 will be solved numerically with Ea from the one training reaction. Otherwise it will perform the original fitting.
2. Changed to `"BM rule fitted to {0} training reactions at node {1}".format(len(rxnlists[i][0]), entry.label)` because `rxnlists[i]` is a tuple containing a list of training reactions and the entry label `([rxns], entry.label)`.
One-training-reaction node is very sensitive for the initial guess of E0 fed to curve_fit. For a …
> Used fsolve for BM if only 1 training reaction

- rmgpy/chemkin.pyx
Some chemkin files, like those published with
https://doi.org/10.1016/j.combustflame.2019.04.040.
put some of their Chebyshev coefficients on the first line immediately after declaring the order of the polynomials, like this:
```
O2+A1CH2=OH+A1CHO                                       1.0000e+00    0.000         0.00
TCHEB/ 300.0 4000.0 /
PCHEB/ 0.0132 232.0000 /
CHEB/ 8 4 3.32750 -0.0203970 -0.00742560 -0.00160600  /
CHEB/ 4.63780 0.0305250 0.0124980 0.00157280 -0.578460 -0.0199920  /
CHEB/ -0.00488330 -0.000692790 -0.465680 0.00426740 0.00237970 8.65490e-05  /
CHEB/ -0.309580 0.00107990 0.000855640 0.000952210 -0.159150 -0.000427600  /
CHEB/ -0.000454890 -0.000143740 -0.0667800 -0.000709740 -0.000378320 -0.000119820  /
CHEB/ -0.00356040 0.000891270 0.000485330 0.000204740  /
```
instead …
> Read all Chebyshev coefficients from Chemkin files

- rmgpy/data/reference.py
The string attribute .encode("utf-8") returns bytes object, and thus lines written by the old code can't be read & written with this same function again, which is inconvenient. 
1. Removed unicode encoding since the string in python 3 is unicode. 
2. Converted format to f-string.
> Minor: Remove unicode encoding & use f-string in reference

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
Before the changes, when running with bidentate surface families the mechanism generation would in some cases crash due to the following resonance structure of gas-phase CO when obtaining the gas-phase counterpart of bidentate CO:
```
Error: Could not update atomtypes for this molecule:
multiplicity 1
1 O u1 p1 c0 {2,T}
2 C u1 p0 c0 {1,T}
```
The surface species in question is:
```
Before removing from surface:
1 O u0 p2 c0 {2,S} {4,S}
2 C u0 p0 c0 {1,S} {3,T}
3 X u0 p0 c0 {2,T}
4 X u0 p0 c0 {1,S}
```
1. This adds a unit test for the treatment of the bidentate CO adsorbate that previously had the strange gas-phase counterpart.
2. More descriptive messages that help to debug this kind of error when obtaining surface thermo.
3. Adds an if statement to correct the resonance structure of …
> Bidentate CO treatment improved

- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/reactionTest.py
This is related to issue https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1937
We currently assume ideal gas mixture to determine Kc.  We should be using different reference concentrations for gas and surface species.  
Use reference concentration of (surface site density) for surface site species and ideal gas (P/RT) for gas species.  That way, gas concentration scales with temperature and surface species concentration is independent of temperature.  Therefore, we use the change in mols of gas in the reaction to determine Kc (instead of len(reactants) - len(products)).  However, the species object needs a molecule to determine its phase (if it contains surface site), so I added a try and except for this.
I added unit test for determining Kc for a surface reaction. I also …
> Reference concentration for surface species when calculating Kc

- rmgpy/rmg/model.py
Hopefully this closes #2043, which reported this problem when pruning:
```
File "/home/thor/anaconda3/envs/rmg_env/bin/rmg.py", line 111, in 
main()
File "/home/thor/anaconda3/envs/rmg_env/bin/rmg.py", line 105, in main
rmg.execute(**kwargs)
File "/home/thor/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/rmg/main.py", line 925, in execute
model_settings.min_species_exist_iterations_for_prune)
File "/home/thor/anaconda3/envs/rmg_env/lib/python3.7/site-packages/rmgpy/rmg/model.py", line 1257, in prune
logging.info('Pruning species {0:<56}'.format(spec))
TypeError: unsupported format string passed to rmgpy.species.Species.format
```
The Species class doesn't have an ability to interpret a format
specifier "<56" (although the Species.label would, …
> Fix format specifier when logging species pruning.

- documentation/source/users/rmg/surfaces.rst
- examples/rmg/catalysis/ch4_o2/input.py
- examples/rmg/catalysis/methane_steam/input.py
- rmgpy/data/thermo.py
The recently merged https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1907 and https://github.com/ReactionMechanismGenerator/RMG-database/pull/391 renamed the surface thermo libraries to include the facet, i.e `surfaceThermoPt` became `surfaceThermoPt111`.
This small pull request updates the example rmg input files and documentation to match.
Also fixes the reference adsorption energies in the documentation, which had been overlooked.
> Correct surfaceThermoPt111 library name in examples and documentation.

- rmgpy/data/kinetics/family.py
Addresses [database issue #448](https://github.com/ReactionMechanismGenerator/RMG-database/issues/448) caused by the reverse Surface_EleyRideal_Addition_Multiple_Bond reaction of a bidentate.
Involves hard-coding 'eleyrideal' in family.py and is treated the same way as avoiding desorption of half of a bidentate in reverse adsorption.
I tested this on the latest RMG master (database and RMG-Py) for methane catalytic combustion. Before these changes I got the error reported in [issue #448](https://github.com/ReactionMechanismGenerator/RMG-database/issues/448). With these changes, the mechanism generation completed without errors.
> Remove Eley-Rideal reactions that involve no gas-phase species 

- rmgpy/species.py
- rmgpy/speciesTest.py
The problem is that when a `Species` is defined `from_adjacency_list()` and the adjlist has the multiplicity in the first line, the species label is being assigned with the multiplicity values, e.g. , `spc.label = 'multiplicity 2'`.
Now checking that the keyword 'multiplicity' is not in the label being assigned from the adjlist.
A simple test was added.
> Species label is wrongly being assinged the multiplicity string

- arkane/pdep.py
Species structures saved in Arkane network files is given in SMILES, which sometimes can be ambiguous. The case I came across was CH2(S) which has the same SMILES as CH2(T), and reading it automatically by T3 failed. Of course in this particular case the multiplicity, which is also given, could be used to differentiate between these states, but we could think of other cases where adjacency list is superior to SMILES in terms of ambiguity (e.g., smiles for hyper-valence species is at times interpreted wrong, whereas adjlists are usually/always better.).
Added an attribute to RMG passed to `CoreEdgeReactionModel` and then to `PDepNetwork` for requesting an adjlist structure form in Arkane network files instead of SMILES.
> Use adjlist as the species structure instead of SMILES in an Arkane PDep network file

- ipython/kinetics_library_to_training.ipynb
- ipython/kinetics_library_to_training_tools.py
- rmgpy/data/kinetics/family.py
I encountered two errors while converting a library containing this Diels-Alder reaction to training reaction. 
(1) Two reactants were wrongly added with the same atom label by `add_atom_labels_for_reaction` because the two reactants are isomorphic.
(2) The A unit caused problem in `add_rules_from_training` because only cm mol s units were expected.
```
Reaction(reactants=[Species(label="ISP", molecule=[Molecule(smiles="C=CC(=C)C")], molecular_weight=(68.117,'amu')), Species(label="ISP", molecule=[Molecule(smiles="C=CC(=C)C")], molecular_weight=(68.117,'amu'))], products=[Species(label="DISP_2", molecule=[Molecule(smiles="C=CC1(C)CCC=C(C)C1")], molecular_weight=(136.234,'amu'))])
```
(1) In `add_atom_labels_for_reaction`, I modified such that the labeled_molecule is removed after it is …
> Debug library to training script

- rmgpy/rmg/main.py
We had a user run into an issue where running an RMG job the second time crashes because there was an existing temporary seed mechanism. This PR checks for this possibility before trying to overwrite the temporary seed.
> Remove temporary seed mechanisms if they exist

- .gitignore
A better way to add RMG-Py to the PYTHONPATH variable is to run `pip install -e` from within the rmg_env. This has the benefit that the repo is isolated to the conda environment, so multiple installs of RMG-Py can be managed by making/managing multiple conda environments.
Doing this creates egg-info files, which should be ignored by git
> Ignore RMG_Py.egg-info files

- rmgpy/data/thermo.py
AttributeError: 'ThermoDatabase' object has no attribute 'binding_energies'
https://github.com/ReactionMechanismGenerator/RMG-website/issues/208
Use Pt111 binding energies as default.
> Default binding energies for ThermoDB

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
Surface bidentate reaction crashed (#2039) trying to get the thermo model for some species. It looks like it sometimes tried the wrong configuration of the gas-phase molecule.
Added code to try multiple configurations and pick the one that works.
If multiple configurations are valid it uses the lowest energy one.
Currently has thermo test for `N(=X)N(X)OH`
and tests for the molecules mentioned in the issue 2039 thread:
`C*O*` becomes `C[-1]#O[+1]`
`O*O*` becomes `[O][O]`
`C*C*` becomes `[C]#[C]`
`N*N*O` becomes `N#N=O` (the middle Nitrogen has valence 5)
> surface bidentate thermo fix

- testing/databaseTest.py
There were recently some problems detected in reaction family recipes and templates (eg. #2038, #2039), and I wanted to see if these could have been found earlier with better testing of the database.
The new test, which runs on every reaction family, uses the machinery of the existing test for descending the tree, to create a sample molecule from the group definition of every node. It then takes these sample molecules, and tries reacting them according to the reaction recipe. It doesn't do every combination (I thought that might be too many) but reacts each molecule at least once. It reports any errors, from things like charged species, atoms that fail atom-type generation, etc. 
The new test fails (correctly) on the master database at commit 2aae843, because it detects the problem …
> Test reaction family recipes when testing database

- documentation/source/users/rmg/input.rst
- rmgpy/constraints.py
- rmgpy/constraintsTest.py
- rmgpy/rmg/input.py
The bidentate families can make molecules with a bunch of surface sites.  I was getting a bunch of edge species with 3 or 4 sites.  This PR adds a `maximumSurfaceSites` constraint if you want to limit the number of surface sites that can be in a species in your model.  
Added a `maximumSurfaceSites` constraint with default value `-1` (no constraint)
Added a unit test and successfully used `maximumSurfaceSites = 2` when running RMG.
> Surface site constraint

- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/reactionTest.py
RMG had no method to reverse Sticking Coefficient kinetics.  I believe this is related to this website issue https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2079.  Adding a method to reverse Sticking Coeffs could be useful to compare Sticking Coeff kinetics with literature rates that are expressed as Arrhenius in the reverse direction.  This method could also be useful if we need to reverse sticking coefficient kinetics in training reactions.
Added StickingCoefficient kinetics handling to reaction `get_rate_coefficient` method so that we can use this method for all types of kinetics.
Added a method to reverse StickingCoefficient kinetics with default surface site density.
Added a unit test for reversing StickingCoefficient kinetics
> Reverse kinetics for sticking coefficient

- rmgpy/kinetics/chebyshev.pxd
- rmgpy/kinetics/chebyshev.pyx
Having them cdef is really inconvenient when writing tools and the operation is definitely not a performance bottleneck.
> Change Chebyshev Functions to cpdef

- documentation/source/users/arkane/input.rst
This PR updates the documentation tabulating which levels of theory are supported by Arkane. It adds `ωB97X-D3/def2-TZVP` and `B97-D3/def2-mSVP`, which were added in [RMG-database PR #459](https://github.com/ReactionMechanismGenerator/RMG-database/pull/459). It also adds `ωB97M-V/def2-TZVPD` to the Arkane documentation since this LoT was already in [RMG-database](https://github.com/ReactionMechanismGenerator/RMG-database/blob/aec_bac_wb97xd3_b97d3/input/quantum_corrections/data.py#L77).
Let's merge this PR once [RMG-database PR #459](https://github.com/ReactionMechanismGenerator/RMG-database/pull/459) is merged.
> Update model chemistry documentation

- .gitignore
- documentation/source/users/rmg/installation/anacondaDeveloper.rst
The developer installation instructions for Linux are really only written for Ubuntu.
While most developers using another Linux distribution could probably "figure it out" the documentation ought to add explicit information for other distributions and also clarify the requirements beyond listing the Ubuntu package names.
Explicit package installation for Fedora, Red Hat, Debian, Arch, and Manjaro (sorry, didn't get to openSUSE yet).
Rearranged some comments about restarting the terminal and/or sourcing to add clarity.
Explicitly identified installation of GNU Make and the C and C++ compilers provided by the GNU Compiler Collection with weblinks, removing previous use of Ubuntu package names `make`, `gcc`, `g++` - required packages are now made explicit in installation step by …
> Documentation: Inclusion of diverse Linux distributions

- environment.yml
- rmgpy/qm/molecule.py
- rmgpy/qm/mopac.py
- rmgpy/qm/qmdata.py
As mentioned in https://github.com/ReactionMechanismGenerator/RMG-Py/issues/756 it would be nice to use the official [cclib](https://github.com/cclib/cclib) rather than a fork that we need (but fail) to maintain. For example the current fork has some bugs like #1864 #1875, and is incompatible with OpenBabel 3+, delaying #2088, and we don't even have [conda binaries](https://anaconda.org/rmg/cclib) for Mac OS X, meaning Mopac etc. has I think been broken for Mac OS users for ages.
Currently a work in progress, but the aim is to use the official cclib.
- switch the environment.yml to specify the conda-forge channel
- change the name of the MOPAC parser
- calculate molar mass if it's not parsed
- parse the molar mass from MOPAC files
Running unit tests.
At one point an entropy calculated …
> Switch to newer cclib?

- rmgpy/molecule/element.py
Our element mass value for Ar is outdated.
The element mass is used in Arkane to compute the molar mass of a species, affecting calculated pressure-dependent rates.
The element mass for Ar as well as other common elements was updated.
Data taken from IUPAC (https://applets.kcvs.ca/IPTEI/IPTEI.html)
Element isotope composition was averaged when needed, comments were added.
For most other elements (not Ar), the change was not significant. I used the significant digits from the IUPAC source.
> Updated the amu values of common elements in gas phase chemistry

- arkane/encorr/bacTest.py
- arkane/encorr/data.py
- arkane/encorr/dataTest.py
- documentation/source/users/rmg/species.rst
- environment.yml
- rmgpy/molecule/converter.pxd
- rmgpy/molecule/converter.py
- rmgpy/molecule/pathfinderTest.py
- rmgpy/molecule/translator.py
- rmgpy/molecule/translatorTest.py
- utilities.py
The release notes say OpenBabel 3 a major improvement
https://github.com/openbabel/openbabel/releases/tag/openbabel-3-0-0
but it does break some things in the API
https://open-babel.readthedocs.io/en/latest/UseTheLibrary/migration.html#migrating-to-3-0
so subsequent commits on this pull request should fix RMG to be compatible.
This pull request is currently a stub. Please feel free to contribute commits!
- update the environment.yaml to use the official updated cclib and openbabel conda packages.
- change import statements
- when reading radicals from OpenBabel molecules, calculate spin multiplicity based on undervalence of atoms, because OpenBabel no longer does this for you
- Mark a couple of broken unit tests as work_in_progress, because they seem to have malformed InChIs that we can …
> Switch to OpenBabel 3

- .github/workflows/CI.yml
- trigger-rmg-tests.sh
Dual PRs that update both RMG-Py and RMG-database simultaneously cannot currently be tested since we moved continous integration to Github Actions.
My goal is there's just one spot to update the required branch, and it's a single environment variable in the CI.yml file.
I changed the CI workflow. I'm making similar changes to the RMG-database, and updating the RMG-tests repo too.
Also will be updating the instructions at https://github.com/ReactionMechanismGenerator/RMG-Py/wiki/Simultaneous-Update-of-RMG-Py-and-RMG-database
If it works as I hope, it should be quite straightforward, and symmetrical.
Will see if it works...
> Better Github Actions workflow for dual Py/Database updates.

- documentation/source/users/rmg/surfaces.rst
- examples/rmg/catalysis/ch4_o2/input.py
This PR updates the surface documentation with instructions on how to use the metal database to specify certain metals instead of having to manually enter in binding energies and surface site density.
I also changed the ch4_o2 example input file to call `Pt111` in place of listing out Pt111 binding energies and surface site density
> Updating documentation and input file using metal database

- documentation/source/reference/molecule/atomtype.rst
- rmgpy/data/base.py
- rmgpy/data/thermo.py
- rmgpy/molecule/atomtype.py
- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/translator.py
- rmgpy/molecule/translatorTest.py
- testing/databaseTest.py
This PR goes with https://github.com/ReactionMechanismGenerator/RMG-database/pull/434.  Importantly, this PR adds the lone pairs to make a sample bromine atom, which was previously causing the DB Travis build to fail.  I also added a new atom type `R!H!Val7!`, which will be used in kinetics trees, and halogen identification functions (i.e `is_bromine`) to the molecule and group Atom classes.
> halogen additions (simultaneous update with DB)

- arkane/explorerTest.py
Adding some species to the primaryThermoLibrary in  https://github.com/ReactionMechanismGenerator/RMG-database/pull/478 and improving their thermochemistry (better than group additive guesses) causes the number of reactions explored in an Arkane unit test to change, so this PR changes the "blessed" output in the unit test. Should be merged simultaneously with https://github.com/ReactionMechanismGenerator/RMG-database/pull/478
> Primary thermo library - unit test change

- .github/workflows/docs.yml
I pushed to my own fork's master branch then received a notification that the documentation had failed to publish.  I'm glad that it failed; this will stop it from attempting.
Only publish the documentation if it's coming from `ReactionMechanismGenerator/RMG-Py`
Hard to test except in production.
> Only publish documentation from official fork

- rmgpy/data/thermoTest.py
simultaneous with https://github.com/ReactionMechanismGenerator/RMG-database/pull/473
This PR changes the molecule to use for missing thermo group test since the thermo group for the old molecule is no longer missing (so the test was failing)
> Halogens thermo - missing group test

- rmgpy/data/thermo.py
So this is a bandaid for #1864 and establishes a way for QM to fallback to ML or GAV when it errors. #1864 needs more investigation, but this PR would at least enable jobs using QM to run sensibly.
> Catch Bad Conformer ID error from rdkit

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/molecule/group.py
- rmgpy/test_data/testing_database/kinetics/families/Surface_Abstraction_vdW/groups.py
- rmgpy/test_data/testing_database/kinetics/families/Surface_Abstraction_vdW/rules.py
- rmgpy/test_data/testing_database/kinetics/families/Surface_Abstraction_vdW/training/dictionary.txt
- rmgpy/test_data/testing_database/kinetics/families/Surface_Abstraction_vdW/training/reactions.py
This PR attempt to fix this issue https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2122
If we are applying a family in reverse and the template reactants restrict multiplicity, we need to make sure that
a reverse product matches the multiplicity-constrained template reactant because the forward template products
do not enforce the multiplicity restriction.  Without this check, we get an `UndeterminableKineticsError` if the reverse products have a multiplicity that does not match the multiplicity constraint of the template reactants.
Added a multiplicity check when applying the template in reverse.
Need to add unit test.  Tested a few reactions which had `UndeterminableKineticsError` but now are no longer generated since they don't satisfy the multiplicity constraints in the …
> check multiplicity of reverse products if the family template reactants have multiplicity constraints (vdW groups)

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
Currently, empty surface site template groups match with vdw adsorbates since they both have the `Xv` atomtype.  This creates problems when generating reactions when a vdw adsorbate matches with the `Xv` group that is meant to be an empty site.  This problem has occurred in the reverse direction for the `Surface_Addition_Single_vdW` family which generates this reaction from its reverse template:
Added a check to make sure that if the template group is an empty surface site, it should only match a structure that is an empty surface site
the `Surface_Addition_Single_vdW`  no longer generates the reaction above.
> an empty surface site template group should only match an empty surface site

- rmgpy/chemkin.pyx
Resonance structure generation can slow down loading of species dictionaries.  Usually this is not significant, but it can be if you are loading a very large species dictionary from a model's edge.  This PR makes it optional (with defaulting to True), similar to how it is for `get_species` method for database
> optionally `generate_resonance_structures` when loading species dicts

- documentation/source/users/rmg/installation/linuxSubsystem.rst
fixes #2141 . The graphviz dependency requires many render libraries to work properly. Unfortunately, these dependencies are not listed by this package, so conda does not
install them in the conda environment. Instead, the system wide libraries are used if
available. On most native Linux distro like Ubuntu, these libraries are installed by default.
However, these libraries are not installed by default in WSL versions of Ubuntu. This
means that WSL users are missing dependencies that they need to run many RMG
related scripts and features.
Updated WSL installation documentation to prompt user to install the graphviz package system wide. This is preferred over figuring out which dependencies graphviz needs that
are not currently installed by default, as these could change over time. In an …
> Have WSL users install graphviz system wide

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/molecule/resonance.py
- rmgpy/molecule/resonanceTest.py
1) vdw radicals - We previously implemented a multiplicity check to ensure products in the reverse direction match the multiplicity of the template reactants . However, we are getting vdw products that do not obey multiplicity restriction in the forward direction (https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2122) , so we also need to check this direction as well. 
2) radicals on X - if resonance generation puts radicals/lone pairs/or a formal charge on `X`, RMG crashes.  I added a commit on this PR to filter out these structures
3) bidentate vdw - We were getting bidentate vdw structures. This PR makes them forbidden for surface families
added unit test for forbidden vdw bidentates and successfully built an ammonia cat oxidation model that was previously crashing.
> Cat fixes - vdw radicals, bidentates, resonance

- rmgpy/data/kinetics/family.py
Some small fixups in the `get_training_set` method which is used for autogen tree method
1) make a deepcopy of the species to get the thermo.  This is needed to clear the atom labels on the molecule which can mess with getting thermo
2) parse out the metal from the entry
> fixups in `get_training_set` family method

- testing/databaseTest.py
Multiple PRs in RMG-database related to tree generation failed the database test (e.g. https://github.com/ReactionMechanismGenerator/RMG-database/pull/493 and https://github.com/ReactionMechanismGenerator/RMG-database/pull/495)
Made the code to look for auto_generated tag instead of the hardcoded list to avoid needing to twin PR
I didn't run a test as this should be a straight forward change
> Use autoGenerated tag instead of the hardcoded family list

- .gitignore
- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/family.py
- rmgpy/molecule/filtration.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/resonance.pxd
- rmgpy/molecule/resonance.py
- rmgpy/reaction.pxd
- rmgpy/reaction.py
- rmgpy/species.pxd
- rmgpy/species.py
We try to perform atom labeling for species participating in a reaction while keeping the atom order constant (in the context of ARC). However, not all current methods support passing the (already existing) `save_order` argument around.
The `save_order` argument was added to methods that were identified as "problematic", and is now being passed on (eventually to the vf2 algorithm) appropriately.
These additions were tested separately via ARC, yet unit tests were not added. This is a relatively "minor" modification, but I'm happy to hear thoughts on implementing tests.
> Added a save_order attribute to some methods, and make sure it is properly being passed around

- rmgpy/rmg/decay.py
- rmgpy/rmg/model.py
This improves RMG's handling of Q.OOH species that usually don't really exist. There are a couple fixes particular to Q.OOH, but most importantly this lays out a larger framework for handling species RMG templates think exist, but really aren't wells. Within this framework a set of recipes for decays are defined and automatically applied to species involved in new reactions. If the reaction can be estimated in a direction where any decaying species are in the products RMG will estimate in that direction and break apart the decaying species giving a more physical reaction sequence and improving rate estimation.
> Decay Framework

- ipython/estimate_solvation_thermo_and_search_available_solvents.ipynb
- ipython/temperature_dependent_solvation_free_energy.ipynb
- rmgpy/data/solvation.py
- rmgpy/data/solvationTest.py
**Note that none of these changes actually affect RMG-Py. These PR is mainly for RMG-website use.**
1. The `get_all_solute_data` first searches for the solute data from the solute library and then it also uses the group additivity method to get the solute data estimates. It should use `get_solute_data` function instead of `get_solute_data_from_groups` function for the group additivity method. The reason is that `get_solute_data` allows the GAV to check whether the saturated form or non-halogenated form of the solute compound is found in the solute library and then applies the appropriate radical or halogen correction on top of that.
For example, for '[O]CCCCCl' compound, each function gives the following output:
- `get_solute_data`: …
> Minor change to `get_all_solute_data` function.

- rmgpy/chemkin.pyx
I tried to load RMG generated chemkin file, but errors were raised when
1) trying to read thermo block with extended elemental composition syntax
2) reading a reaction with a species the has a digit as its first character (i.e. 2-BTP)
1) check for extended syntax notation, and append the elemental comp. line to thermo block
2) check species dictionary before assuming that the leading digit corresponds to stoic coefficient
I was able to load my chemkin files
> Load chemkin bug fix - extended elements and digits

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/molecule/filtration.py
- rmgpy/molecule/resonance.py
- rmgpy/reaction.py
To assist in atom-mapping RMG reactions, some relatively minor modifications were made.
-  Use the save_order argument in generate_resonance_structures() 
- Added labeled_reactant/product_atom attribute to TemplateReaction
- Added relabel_atoms and delete_labels arguments to methods of KineticsFamily. These are used to optionally avoid relabeling atoms and to optionally avoid deleting atom labels, respectively. The original behavior is preserved.
In all cases, the original behavior was preserved.
A test of retaining atom labels in a template reaction was added.
> Added additional features to preserve atom order and template labels when generating reactions

- documentation/source/users/rmg/surfaces.rst
- rmgpy/chemkin.pyx
- rmgpy/chemkinTest.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/library.py
- rmgpy/kinetics/surface.pxd
- rmgpy/kinetics/surface.pyx
- rmgpy/kinetics/surfaceTest.py
- rmgpy/reactionTest.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/solver/surface.pyx
- rmgpy/solver/surfaceTest.py
- rmgpy/test_data/testing_database/kinetics/libraries/surface-example/reactions.py
- testing/databaseTest.py
Coverage dependent effects are found in many surface mechanisms, and we have been unable to use them.  These effects can become significant at high temperatures and pressures. Additionally, some models would have too much O2 adsorbing to the surface too quickly, blocking anything else from happening.
A new kinetics attribute called `coverage_dependence` was added that is a dictionary of dictionaries that holds the Species the parameters correspond to and the coverage dependent parameters. 
Unit tests to make sure RMG can read in kinetics entries with coverage dependent parameters, write chemkin and cantera output files with the coverage parameters, and use the parameters correctly. We've built a few models with it, and it seems to be working.
Goes with …
> Adding in coverage dependent effects to surface kinetics

- arkane/encorr/bac.py
- arkane/encorr/bacTest.py
- documentation/source/users/arkane/input.rst
This minor PR updates the documentation that tabulates which levels of theory are supported by Arkane. It reflects changes from a recent RMG-database [PR](https://github.com/ReactionMechanismGenerator/RMG-database/pull/508), which expanded the supported AEC atom types for coupled cluster calculations with `CCSD(T)-F12/cc-pVDZ-F12` and `CCSD(T)-F12/cc-pVTZ-F12`.
> Update documentation to reflect additions in RMG-database

- rmgpy/data/solvation.py
- rmgpy/data/thermo.py
Following error trace shows up during my model generation. I found that it's related to the handling of string data node during averaging children solute data.
```
File "/home/gridsan/hwpang/Software/RMG-Py/rmg.py", line 118, in <module>
main()
File "/home/gridsan/hwpang/Software/RMG-Py/rmg.py", line 112, in main
rmg.execute(**kwargs)
File "/home/gridsan/hwpang/Software/RMG-Py/rmgpy/rmg/main.py", line 923, in execute
trimolecular_react=self.trimolecular_react)
File "/home/gridsan/hwpang/Software/RMG-Py/rmgpy/rmg/model.py", line 641, in enlarge
self.apply_thermo_to_species(procnum)
File "/home/gridsan/hwpang/Software/RMG-Py/rmgpy/rmg/model.py", line 853, in apply_thermo_to_species
self.generate_thermo(spc, rename=True)
File …
```
> Handle string data properly when averaging children solute

- rmgpy/data/kinetics/family.py
- rmgpy/molecule/element.py
This PR adds a few changes needed to run the autogen tree script for halogen families.  This branch was used to generate the trees for this RMG-database PR https://github.com/ReactionMechanismGenerator/RMG-database/pull/510
- Added BDEs for X-O (X=halogen)
- Added F and Br to R elements in `simple_regularization` method
- use family.reverse_map instead of hard coded changes to swap labels for own reverse families when applying the reaction recipe
> autogen trees with halogens

- rmgpy/kinetics/arrhenius.pyx
a_dict needs to be retrieved after mol is made because we are deep copying the reactant mol (and therefore the atoms are different)
I was getting this unit test error here https://github.com/ReactionMechanismGenerator/RMG-database/pull/499/checks?check_run_id=3138777551
```
5977
======================================================================
5978
ERROR: test that there are six rules and each is under a different group
5979
----------------------------------------------------------------------
5980
multiprocessing.pool.RemoteTraceback: 
5981
"""
5982
5983
File "/usr/share/miniconda/envs/rmg_env/lib/python3.7/multiprocessing/pool.py", line 121, in worker
5984
result = (True, func(*args, **kwds))
5985
File …
```
> `a_dict` bugfix in `get_w0`

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- documentation/source/users/rmg/installation/anacondaDeveloper.rst
- documentation/source/users/rmg/installation/anacondaUser.rst
- environment.yml
- examples/rmg/rms_constant_V/input.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/modelTest.py
- rmgpy/rmg/reactors.py
- rmgpy/solver/base.pyx
- rmgpy/solver/termination.py
- rmgpy/statmech/ndTorsions.py
This PR integrates pyrms into RMG enabling us to very easily write new reactor types running simulations and Edge Analysis in RMS.  
There's a lot of small details that are worth mentioning: 
Potentially farther reaching changes:
- Species labels are forced to be unique
- Kinetics and thermo are generated when the Species/Reaction objects are created instead of later in enlarge
As far as I can tell we seem to be unable to mix pyjulia and nosetests. This put some significant constraints on the structure of these changes. I managed to limit all the rms function calls to the new reactors.py file so this has almost no impact on our current testing infrastructure, however it does mean that the infrastructure in the reactors.py file can't be tested using our current nosetests framework. (This …
> Enabling use of pyrms for RMG Simulations and Edge Analysis

- examples/rmg/liquid_cat/input.py
- rmgpy/data/solvation.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/reactors.py
This PR implements a liquid-surface reactor within RMG that can be used to model solid-electrolyte interfaces. Along the way fixing a number of bugs related to surface handling within the new framework. For now the solvent correction for a surface species is calculated from the desorbed saturated form of that species.
> Pyrms Reactor Bugfixes and Liquid-Surface Reactor for RMG Electrocat

- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/pdep.py
This PR is an attempt to fix this issue https://github.com/ReactionMechanismGenerator/RMG-Py/issues/1725.
```
'Attempted to explore isomer {0}, but that species not found in product channels.'.format(isomer))
Exception: Attempted to explore isomer cO4(812), but that species not found in product channels.
```
When multiple species in a pdep network are removed from edge, we can run into this bug.  
This happened for this pdep network where both `[O]OO[O](251)` and `cO4(812)` are forbidden.
```
========================================================================
PDepNetwork #463 network information
------------------------------------
Isomers:
[O]OO[O](251)                                         9.48859 kJ/mol
Reactant channels:
O=O(149) + O=O(149) …
```
> Pdep bugfix - removing edge species

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/CI.yml
- .github/workflows/docs.yml
- README.md
- trigger-rmg-tests.sh
The default branch name is hard coded in a few different places. To make the switch to `main`, we need to
change the default branch name in these locations.
I searched the whole repo for `master` and replaced it with `main` where appropriate.
Hopefully the tests pass?
> Change default branch to `main`

- rmgpy/rmg/reactors.py
This fixes a few different bugs related to construction of RMS objects for more complex kinetics types particularly Multi/Pdep/Arrhenius and falloff types. 
Best test is to run RMG with libraries containing these kinetic types.
> Fix RMS Object Construction

- rmgpy/molecule/resonance.pxd
- rmgpy/molecule/resonance.py
- rmgpy/molecule/resonanceTest.py
Previously, `generate_resonance_structure` will not keep the atom order when applying `keep_isomorphic=False` and `save_order=True`. The key issue is `Molecule.is_isomorphic` is called in the function and will sort atoms by default. The current change adds the correct argument to `is_isomorphic` and thus avoid such behavior. Moreover, `filter_structures` is removed from `_generate_resonance_structure`. since it is not used inside the function
> Fix atom order issue in generate_resonance_structure

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/groups.py
- testing/databaseTest.py
This is a twin PR for RMG-database PR #545.
It removes stale template matching code for Bimolec hydroperoxide decomposition.
> Remove stale template matching for Bimolec hydroperoxide decomposition

- rmgpy/kinetics/falloff.pyx
RMG fails when trying to convert 2-parameter Troe reactions to Cantera reactions because it has assumed a 3-parameter version. One of the parameters, T2, is optional
I added an if statement to check whether the optional parameter has been set. If so, it calls the 3-parameter version, and if not, it calls the 2-parameter version
I built this version and confirmed that I can convert 2-parameter Troe reactions from RMG to Cantera.
The example I used was this reaction from [RMG-database/input/kinetics/libraries/BurkeH2O2inN2/reactions.py](https://github.com/ReactionMechanismGenerator/RMG-database/blob/main/input/kinetics/libraries/BurkeH2O2inN2/reactions.py)
```
entry(
index = 20,
label = "H2O2 <=> OH + OH",
degeneracy = 1,
kinetics = Troe(
arrheniusHigh = Arrhenius(A=(2e+12, 's^-1'), n=0.9, …
```
> Check for two-parameter Troe reaction when converting to Cantera

- documentation/source/users/rmg/installation/anacondaDeveloper.rst
- documentation/source/users/rmg/installation/linuxSubsystem.rst
- documentation/source/users/rmg/installation/updatingSourceCode.rst
Three commits which are incremental improvements:
1) Update `master` to `main` on update page since the current instructions are erroneous
2) Update the Anaconda web address and Python version for download to reflect the current website - users should be able to figure things out as currently listed, but this makes it clearer
3) Add instructions to clone and pull via `ssh` including links to GitHub documentation on setting up and using `ssh` and converting remote from `https` to `ssh` as password authentication at the command line is deprecated
> Documentation updates for developer install and update

- rmgpy/data/statmech.py
- rmgpy/pdep/configuration.pxd
- rmgpy/pdep/configuration.pyx
- rmgpy/rmg/main.py
- rmgpy/rmg/pdep.py
This PR makes it possible to run pdep for halogen models.
It is simultaneous with https://github.com/ReactionMechanismGenerator/RMG-database/pull/522 which adds halogens frequency data and groups.
1) get statmech data for halogens by skipping over halogen atoms (since the are not treated as center atoms, similar to hydrogen)
2) fixed bug for change in number of freqs removed when a group is removed
3) added support for loading statmech libraries
4) added `energy_correction` to pdep network
Was able to get a model running with Pdep for `C=C(F)C(F)(F)F` combustion.
test pdep model for other types of models.  See if we get same results with new `energy_correction`.
> Halogens pdep

- rmgpy/kinetics/arrhenius.pyx
- rmgpy/kinetics/arrheniusTest.py
This small PR adds 2000K to the list of default temperatures used when doing an ArrheniusBM fit. This is relevant because the previous values only went up to 1500K, which forces our rate rules to extrapolate for any system that is operating above 1500K. Thanks to @davidfarinajr for identifying this issue as discussed in RMG-database PR [550](https://github.com/ReactionMechanismGenerator/RMG-database/pull/550).
It also adds a unit test for our ArrheniusBM class
> Allow ArrheniusBM Fitting up to 2000K for RMG-database Rate Trees

- rmgpy/molecule/draw.py
When read from a species dictionary, CO molecule has a different atom order than the one generated from SMILES. It further causes CO drawn as 'OC'. This commit ensures that CO is drawn correctly.
> BugFix: Draw CO as 'CO'

- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
There have been a couple of instances where I wanted to keep the atom labels when converting a molecule to a group.  However, the molecule `to_group` method does not include the atom labels
added atom labels to `to_group` method
added atom labels to `test_to_group`unit test.
> Mol to group with atom labels

- arkane/encorr/ae.py
- arkane/encorr/bac.py
BAC jobs only save the correlation matrix, but not confidence interval estimates.
Add these estimates as a comment in `output.py` of an Arkane job.
Tested by running an Arkane job.
Run a BAC job to test that the CIs are included in the output and check the formulas.
> BAC parameter confidence intervals

- .gitignore
- rmgpy/rmgrc_template
This allows the user to make changes without these changes being reset. The previous solution of storing a permanent copy in $HOME/.rmg/rmgrc still works, but this is not a good solution when a user has multiple RMG installations that each point to different database locations
If a user wanted to point RMG to use a database at a non-default location, one way they can accomplish this is by changing this setting in the rmgrc file. Because we track this file though, any changes the user makes are likely to get overwritten constantly. This PR moves the file to a "template file" location. This allows the user to make their own rmgrc file, which is no longer tracked and in the .gitignore file. This approach has the advantage that multiple RMG installations on the same computer can be supported …
> Change rmgrc to a template file

- rmgpy/qm/molecule.py
- rmgpy/qm/moleculeTest.py
This PR aims to partially solve issue #2138, by implementing a more robust conformed embedding scheme. The RDKit Default algorithm ETKDG may fail some time, which causes no conformers actually created in `rd_embed` functions that further raises an error when `GetConformer` at line 196.
The fix implements two backup algorithms to embed conformers: embedding using random coordinates, and embedding using 2D geometries. Since there is a following force field optimization step, it shouldn't be too bad an idea.
> More robust conformer embed in QM module

- rmgpy/tools/regression.py
RMG tests gets an IO buffering issue as outlined in issue  #2228 on RMG-tests. it attempts to write an output cti file and gets the following error: 
```
File "/usr/share/miniconda/envs/testing/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 308, in main
python(**vars(ns))
File "/usr/share/miniconda/envs/testing/lib/python3.7/site-packages/julia/pseudo_python_cli.py", line 59, in python
scope = runpy.run_path(script, run_name="__main__")
File "/usr/share/miniconda/envs/testing/lib/python3.7/runpy.py", line 263, in run_path
pkg_name=pkg_name, script_name=fname)
File "/usr/share/miniconda/envs/testing/lib/python3.7/runpy.py", line 96, in _run_module_code
mod_name, mod_spec, pkg_name, script_name)
File …
```
> Cantera issue in regression testing 

- rmgpy/data/transportTest.py
The transport groups were previously missing nitrogen. The nitrogen groups for the transport GAV have been added to the RMG-database. Two nitrogen molecules have been added to the `transportTest.py`.
Note that this PR needs simultaneous update of RMG-Py and RMG-database. (Twin RMG-database PR is: [#566](https://github.com/ReactionMechanismGenerator/RMG-database/pull/566))
Several nonring and ring nitrogen groups are added to `RMG-database/input/transport/groups/`.
These group values are obtained from Joback's Ph.D. thesis Table 3 and Table 13. These values can be also found [here](https://en.wikipedia.org/wiki/Joback_method#Critical_temperature). The nitrogen groups with any missing values were not added to the RMG-database. 
Two molecules with SMILES `CNC` and `c1ncc[nH]1` have been …
> Add Nitrogen groups to transport 

- rmgpy/data/kinetics/family.py
Removes a check in reaction generation routine. If a species is already adsorbed, currently it cannot form a new bond. One of the upcoming bidentate families that @kblondal  is working on requires this:
```
*1--*2--*3                   *1--*2    *3 
|                   ---->    |   |     |
~*4~ + ~*5~ + ~*6            ~*4~~*5 + ~*6~~ 
```
Removed the checks specified above. they are no longer required. The original problem this was addressing was the mis-identification of an empty surface site as an adsorbed molecule. the routine ```_match_group_to_template``` does this check now, so it is no longer required.
check with a surface mechanism and ensure it remains unchanged.
> remove check for adsorbate getting adsorbed again

- arkane/input.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/rmg/main.py
- rmgpy/tools/isotopesTest.py
- rmgpy/tools/uncertainty.py
- rmgpy/tools/uncertaintyTest.py
- testing/databaseTest.py
`add_rules_from_training` and `fill_rules_by_averaging_up` should be only called for non-ATG rate rules when initiating the RMG database rate rule estimator.
1. A full keyword search is done using these two function names. Wherever they are called, `if not autogenerated:` is made sure to be added before the block.
2. Bypass the calls of these two methods on ATG families inside these functions. Currently, there is no error raised to avoid breaking up user's private scripts and workflow. But this will be deprecated in the future version, and an error will be raised.
> Correct ATG rate rules initialization

- rmgpy/chemkin.pyx
Original issue [https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2275](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2275)
The load_chemkin_file() function gets tripped up by the site density info at the top of the SITE block for surface chemkin files as well as the bidentate/number-of-sites info (all of the /2/ 's):
```
SITE   SDEN/2.7200E-09/ ! mol/cm^2
vacantX(3)
HX(5)
OX(6)
CH3X(7)
HOX(8)
H2OX(9)
OCX(13)
CX(15)
CH2X(16)
CHX(17)
CH4X(27)
O2X2(28)/2/
O2X(29)
CH3OX(30)
C2H6X(31)
H2X(33)
HO2X(37)
CH4OX(40)
H2O2X(42)
CH2OX2(44)/2/
CH2OX(45)
C2H5X(46)
CH3OX(47)
C2H4X2(49)/2/
C2H4X(50)
CH2X(51)
CH4O2X(56)
CH3O2X(59)
CH3O2X(63)
C2H6OX(71)
CHOX2(77)/2/
C2H4X(78)
CH2OX(79)
C2H3X2(80)/2/
CHOX(87)
COX2(94)/2/
SX(104)
CHOX(115)
END
```
I added an if statement to skip over …
> Fix load_chemkin_file read of surface species

- .gitignore
- rmgpy/data/kinetics/family.py
Per Bill's request, @kspieks and I are working on fixing the `Intra_R_Add_Endocyclic` and `Intra_R_Add_Exocyclic` trees. During RMG subgroup, we discussed the problem identified in PR https://github.com/ReactionMechanismGenerator/RMG-database/issues/577, where we found that the ATG root nodes for these two families are essentially the same, and we are not able to provide enough information from the ring closing direction to tell a priori that whether the closed ring is endo or exo. We have concluded that defining these two families from the ring opening direction is the right way to go (even though it would not be the exothermic's direction).
During generating tree from the ring opening direction, we've found that the check of number of products equal to the number of product groups …
> Skip number of products check for ATG tree

- rmgpy/molecule/group.py
I ran into this bizarre bug where the node a molecule lands on when descending a tree depends on whether the descending is being run in parallel or not. After some investigation, I realized it's because the ring membership of a group disappears when it's being pickled and unpickled. Here's a minimal working example:
```
group = Group().from_adjacency_list("""
1 * R!H u1 {2,[S,D,T,B,Q]}
2   R!H ux r1 {1,[S,D,T,B,Q]}
""")
print_adj(group)
Parallel(n_jobs=-1, verbose=5, backend='multiprocessing')(delayed(print_adj)(g) for g in [group])
```
I add props to `__reduce__`.
After the change, the ring membership remains in parallel.
> Add atom props to __reduce__

- rmgpy/molecule/converter.pxd
- rmgpy/molecule/converter.py
- rmgpy/molecule/converterTest.py
- rmgpy/molecule/fragment.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/resonance.pxd
- rmgpy/molecule/resonance.py
- rmgpy/molecule/resonanceTest.py
In my previous PR (#2229), I was trying to fix cases where atom map changes even when setting `save_order=True` when generating resonance structures. The PR fixes most of the cases except for aromatic molecules that I recently ran into. The atom map is changed whenever RMG tries to analyze the aromaticity and find out potential aromatic rings; Inside `get_aromatic_rings`, RMG will sort the atom order of the molecule and then convert it to an RDKit Mol and do the analysis based on the RDKit Mol. There is a comment inside `to_rdkit_mol` and `to_ob_mol` saying `# sort the atoms before converting to ensure output is consistent between different runs`, this can be useful in the case not sensitive to atom map and unnecessary to the case where the input molecule atom map is critical and need to …
> Fix resonance save order

- arkane/encorr/corrTest.py
- arkane/ess/molproTest.py
I noticed that a few files in Arkane could have better unit test coverage. This short PR adds a few extra unit tests, specifically for getting atom and bond corrections as well as our molpro parser. We can work on adding additional unit tests at the next RMG hackathon :) 
Note that I set a very loose tolerance when checking AEC and BAC values since it's possible that these values are re-fit and thus changed in the future. I just wanted to add a test that makes sure this functionality doesn't break (even if the values themselves may change).
> Add Arkane unit tests

- documentation/source/users/rmg/installation/anacondaDeveloper.rst
- documentation/source/users/rmg/installation/updatingSourceCode.rst
people are having trouble installing rmg because it is using an old rms version, see issue #2290
changed the documentation to use the rms main branch instead of v 0.4. 
did a clean rmg install and verified that I could regenerate the issue with the old install, and that the issue was resolved with the updated instructions. 
Just verify that this is a reasonable way to do this. I think the root cause is the specification of "v 0.4" in the install supercedes any configuration we have in the pyrms wrapper config.
> update developer installation instructions to use the main rms branch

- examples/rmg/external_library/custom_library/dictionary.txt
- examples/rmg/external_library/custom_library/reactions.py
- examples/rmg/external_library/input.py
- rmgpy/data/kinetics/database.py
- rmgpy/data/kinetics/libraryTest.py
- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
Users who execute RMG on a server where it is installed in a read-only partition cannot add new libraries for their runs.
Added functionality to load thermo and kinetic libraries from a user specified location
Tests added
> Allow RMG to load thermo or kinetic libraries from a file

- arkane/output.py
When Arkane saves a kinetics library it currently passes `rxn.label` for the reaction label.
However, in an RMG run PDep networks generated automatically have simple labels such as `reaction1` instead of a chemically meaningful label. Then, running such `network_x.py` files through Arkane will generate an ill-formatted RMG library.
Here we fix the reaction label in the RMG libraries generated by an Arkane kinetics job by using a reasonable reaction label.
> Save the actual reaction label when creating a reaction library in Arkane

- arkane/explorer.py
This PR mostly forces networks to be updated before writing and filtering operations. This avoids some issues with the differences in barrier energy corrections between the networks. I believe this should resolve #2356.
> Pdep Explorer Multinetwork fixes

- rmgpy/molecule/group.pxd
- rmgpy/molecule/group.py
- rmgpy/molecule/groupTest.py
1. hasWildCards should be has_wildcards
2. standardize_atomtype() function throws attribute error because Group() doesn't have has_wildcards attribute. It really should be a checking done on the atoms.
1. Changed from hasWildCards to has_wildcards
2. Add a for loop to loop through self.atoms and changed self.has_wildcards to atom.has_wildcards.
> Minor: Update group attribute name to py3

- arkane/encorr/bac.py
- rmgpy/data/base.py
- rmgpy/data/kinetics/rules.py
- rmgpy/data/surface.py
- rmgpy/molecule/draw.py
- rmgpy/molecule/fragment.py
- rmgpy/molecule/util.py
- rmgpy/qm/gaussian.py
- rmgpy/qm/mopac.py
Added the `r` char at the start of regex pattern strings where it was missing. It designates a python "raw" string which passes through backslashes without change. It's recommend to always write Python regex pattern strings with the `r` char. (see [here](https://developers.google.com/edu/python/regular-expressions))
Practically, it causes many warning messages when debugging (I think Python can do without it, but it rightfully complaints)
> Added 'r' at the start of regex pattern strings where it was missing

- rmgpy/molecule/fragment.py
- rmgpy/molecule/fragment_test.py
- rmgpy/molecule/moleculeTest.py
Related to #2395
Another issue with the `Fragment` class was encountered. It takes time for these errors to pop (in my experience, only in an advanced stage of an RMG run after a few hundred species were added into the core).
I got the following trace:
```
File "/home/alongd/Code/RMG-Py/rmg.py", line 112, in main
rmg.execute(**kwargs)
File "/home/alongd/Code/RMG-Py/rmgpy/rmg/main.py", line 944, in execute
self.reaction_model.enlarge(objectToEnlarge)
File "/home/alongd/Code/RMG-Py/rmgpy/rmg/model.py", line 709, in enlarge
self.update_unimolecular_reaction_networks()
File "/home/alongd/Code/RMG-Py/rmgpy/rmg/model.py", line 1918, in update_unimolecular_reaction_networks
network.update(self, self.pressure_dependence)
File …
```
> 'Fragment' object has no attribute 'is_atom_in_cycle' error

- rmgpy/data/solvation.py
- rmgpy/data/solvationTest.py
- rmgpy/data/vaporLiquidMassTransfer.py
kH as the ratio of pressure of a solute over concentration of a solute is easier to work with on the simulation side. `get_T_dep_solvation_energy_from_input_298` also already contains `rho_l` needed to convert Kfactor to kH (as Psat_solute,g/Csat_solute,l).
I moved the calculation of kH into `get_T_dep_solvation_energy_from_input_298` and calculates kH as Psat_solute,g/Csat_solute,l.
> Improve kH estimation code

- rmgpy/rmg/reactors.py
Currently, the default values in the rms.Species and rms.ElementaryReaction struct wouldn't kick in, which results in RMG-Py needing a Twin PR whenever RMS changes its struct, even when it's not relevant to RMG. This is not ideal.
I made a constructor for rms.Species and rms.ElementaryReaction in RMS (https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/pull/210). This will make sure the default variable to kick in for rms.Species and rms.ElementaryReaction. This also allow for keyword variable input.
I add a new commit at the end and it should launch test on the https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/pull/210 branch.
Remember to drop the last commit when merging the PR.
Edit: …
> Adapt change in RMS to use keyword variables

- .github/workflows/CI.yml
This PR adds a line to the CI that will cause it to skip the `mkdir stable_regression_results` step when it is running on a schedule or a push to main. Under such circumstances, the run _is_ the stable result and will therefore never download anything to this folder making it not needed.
> CI: don't make destination directory for reference results when generating reference results

- rmgpy/solver/simple.pyx
Third body and pressure dependent reactions with collision efficiencies need to have their rate constants recalculated during the solver step because of the efficiencies, which means their reverse rates are re-evaluated using the Keq. If the Keq was left as zero (as the case prior to this commit) because a reaction was irreversible, then it would crash with a zero division error.
This fix allows irreversible, pressure-dependent reactions, with collision efficiencies.
(Not a common scenario - why would a PDep reaction ever be irreversible? but some published kinetic models have them, and so they have crept in to user's seed mechanisms).
When evaluating the equilibrium constant array (that is later reused) set it to `np.inf` for irreversible reactions
rather than leaving it at zero.
I ran …
> Set Keq=inf for irreversible reactions.

- documentation/source/users/rmg/installation/anacondaDeveloper.rst
This PR contains updates to the developer installation instructions for RMG:
- bumped anaconda shell version to latest
- removed outdated Julia installation instructions, since we package Julia with RMG and a system install is not required (and also no longer included by default on all Linux systems)
- added instructions to use the mamba environment solver instead of the default conda solver (functionally the same as using mamba) to make environments solve in a reasonable amount of time
- we had been internally doing this but it was undocumented, see issues below
Resolves #2323 
Resolves #2384
> Updates to RMG-Py installation instructions documentation

- documentation/source/users/rmg/installation/anacondaDeveloper.rst
The installation instructions are not rendering correctly (see [here](https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/anacondaDeveloper.html#:~:text=conda%20config%20%2D%2Dset%20solver%20libmamba%0A..%0A%20%20%20%20The%20above%20step%20is%20retrieved%20from%20https%3A//www.anaconda.com/blog/a%2Dfaster%2Dconda%2Dfor%2Da%2Dgrowing%2Dcommunity%20also%20see%20https%3A//github.com/ReactionMechanismGenerator/RMG%2DPy/issues/2323%0A%0ANow%20create%20the)) due to an inline comment and incorrect spacing. This PR removes the comment and fixes the spacing.
> Fix Incorrect Rendering in RMG-Py Installation Documentation

- CITATIONS.bib
- arkane/README.md
- documentation/source/users/arkane/credits.rst
- documentation/source/users/rmg/credits.rst
Added the citation info for Arkane into the docs and the module README
Also updated RMG's citations list.
Note that RMG's credits docs page has "developers" and "previous developers" lists. The current developers list is outdated, perhaps someone from Green Group and West group can complete it? Alternatively, we can just have one list of credits to avoid the need to update it every couple of years.
(docs were built locally and seem OK)
> Added Arkane citation info

- .gitignore
- rmgpy/thermo/thermodata.pyx
While trying to create a new thermo library, we got an assertion error since Cp data started in 298K.
We modified: `assert Tdata[0] > 298` into `assert  Tdata[0] >= 298`
Also modified gitignore file to consider files of PyCharm and VScode in subfolders
> Modified assertion in thermodata.pyx 

- environment.yml
the default does not provide version information which raises an annoying warning in the docker image
> use conda-forge ncurses instead of default

- rmgpy/rmg/reactors.py
This typo prevents RMG from running if a surface species is in the mechanism.
> fix typo in reactors.py

- documentation/source/users/rmg/installation/index.rst
missing some equal signs, causes a warning to be rendered: https://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/installation/index.html#alternative-install-binary-installation-using-anaconda
> fix typo in updated docker installation docs

- rmgpy/statmech/torsion.pyx
`frequency` and `x` in get_partition_function are only needed in the end of the function if semiclassical correction is needed. I suggest moving them to the end of the function, after checking `self.semiclassical`
Moved `frequency` and `x` to the end of the function.
> Calculate x only when semiclassical corrections are needed

- .github/workflows/CI.yml
- documentation/source/users/rmg/installation/anacondaDeveloper.rst
- documentation/source/users/rmg/installation/anacondaUser.rst
- documentation/source/users/rmg/installation/dependencies.rst
- environment.yml
- rmgpy/qm/gaussian.py
- rmgpy/qm/gaussianTest.py
- rmgpy/qm/mainTest.py
- rmgpy/qm/molecule.py
- rmgpy/qm/mopac.py
- rmgpy/qm/mopacTest.py
- rmgpy/qm/symmetry.py
The current version of MOPAC used by RMG is semi-closed source and requires an key. The new version, OpenMOPAC, is freely available and maintained by the community.
This PR will attempt to switch to this newer version. Doing so will fix some issues on the user side (see below) and also allow forked repositories to run the continuous integration testing (which currently fails due to the requirement for a license key, not present on forks).
Resolves #2328 which originally discussed the possibility of moving to OpenMOPAC.
Resolves #2251 which was facing issues with running the outdated version of MOPAC and attempted to install this new version without success.
Resolves #2407 also facing licensing issues.
PR #2322 attempted to do this in the past but also attempted to upgrade other packages …
> Upgrade to OpenMOPAC

- documentation/source/_templates/sourcelink.html
- documentation/source/users/arkane/installation.rst
The documentation has links to view (and edit) the source code of the documentation. These pointed to master instead of main.
Fix the template.
Also, it seems, I fixed a typo some time ago, and github has mysteriously added it to this pull request. I'm betting that means I'll need to rebase this almost immediately upon creating it.
> Fix documentation View Source links

- Makefile
Now that there's a folder called 'test' the target with the same name doesn't work properly in make, i.e.
if you do `make test` it just checks that the 'test' folder is up to date. 
My making it a "phony" target it doesn't do this, and it  once again works as intended.
Ran `make test` on my computer.
Also using this opportunity to check running the CI from a pull request coming from a fork, rather than just a branch in the official repo.
If you want, learn about phony targets at https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
> Make 'test' a phony target in Makefile

- documentation/source/users/rmg/credits.rst
This PR updates the list of current developers on RMG website: http://reactionmechanismgenerator.github.io/RMG-Py/users/rmg/credits.html#how-to-cite
I added all current members that do work related to RMG. I apologize in advance if I missed anyone. 
@sevyharris could you please add people from Professor West's group to help us update the list?
> Update list of developers

- documentation/source/users/rmg/installation/index.rst
TL;DR: This PR changes a couple lines in the docs to tell users to download RMG v3.1.1, which is a _temporary_ release we decided on in RMG subgroup to point users toward for RMG training (rather than `latest`).
Right now the documentation points users towards the `latest` build, which is the one that is constructed every night and after every merge to main. We should actually point them toward some specific version, which will allow us to actually debug issues since everyone who has problems will be running a version we can try ourselves. The latest build should be used by devs, or in the case that an error has been fixed but a minor or patch release has not yet been published. This should consequently include a more consistent release schedule.
To coincide with this I have pushed a …
> [Documentation]: point users to a specific version of RMG rather than latest

- .github/workflows/docs.yml
Previously I made a needed change to allow docs build and test to run on forks (#2431), but it broke the actual publish step (see https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/4975775636/attempts/1). this commit adds an additional step to the docs build that will build the documentation with a dev token on pushes to main, or just build it for testing without one on forks/dev branches. Needs to be merged ASAP so the docs can be updated for RMG training.
> Fix Documentation Build

- documentation/source/users/rmg/input.rst
- rmgpy/rmg/input.py
- rmgpy/rmg/reactors.py
- rmgpy/rmg/settings.py
During the generation of oligomerization mechanism, I found that current species selection algorithm often prioritize selecting propagation reaction in each iteration, such that RMG has difficulty recognizing the importance of many chain transfer and chain termination reactions. This causes the generated mechanism to contain many radicals that are only consumed by very slow reverse reaction and accumulate to nonphysical concentrations in the longer time span simulation. The algorithm designs to help RMG recognize these important but low flux chain transfer and chain termination reactions.
I add tolerance to move reaction to core based on the dead-end radical algorithm. This is a RMG-RMS twin PR.
> Deadend radical species selection RMG-RMS Twin PR

- rmgpy/molecule/atomtype.py
- rmgpy/molecule/atomtypeTest.py
- rmgpy/molecule/group.py
This unit test at the start of this PR was inspired by efforts to debug something in some changes to the database (https://github.com/ReactionMechanismGenerator/RMG-database/pull/317) , which caused a segfault when running the database Tests, but was in fact caused by an undetected bug in RMG (https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1656) not a problem in the database.  I felt there ought to have been a unit test to prevent the bug.
The goal is to make a group definition out of each atom type, and then make a sample molecule for each group definition. This should test the group definition and the `make_sample_molecule` method.
At first, the test failed, and that was either because of 
1) bug(s) in the way the test is currently written, or 
2) bug(s) in our atom type …
> Test that we can make a sample molecule for every atom type.

- rmgpy/chemkin.pyx
load_chemkin_file crashes if there is an extra species in the transport file that is not in the model. Some transport files (not generated in RMG) that I've received from other sources will have some extra species in the transport file, so I will have to manually search through the transport file and remove them, which can get annoying. This proposed fix allows the user to "skip" species in the transport file in the load_transport_file function without crashing. 
Added a parameter `skip_missing_species` to load_transport_file, and a for loop that catches species in the transport file that are not in the species dictionary and skips them.
Tested .load_chemkin_file (which uses .load_transport_file) with two mechanisms: one with an extra species in the transport file, and one with only the …
> transport warning for undefined species in load_transport_file

- .github/workflows/CI.yml
- documentation/source/users/rmg/installation/anacondaDeveloper.rst
- environment.yml
This PR runs the Continuous Integration on a mac runner in addition to the Ubuntu runner, the idea being that we can catch issues that might crop up on the mac platform independently of debian linux. The results from the ubuntu runner are still considered to be the "baseline" for regression testing.
See #2355 and #2392 for issues related to running on Macs
> `CI.yml` and `environment.yml` updates to run CI on MacOS and Ubuntu

- rmgpy/rmgobject.pyx
- rmgpy/rmgobjectTest.py
Different use cases require additional information to be stored in an Arkane YAML file that is generated using the `RMGObject`. Thy may include atom order in a molecule.
Allow RMG to read Arkane YAML files through the `RMGObject` while ignoring ` mol` and `aux` keywords to store molecular and auxiliary information.
A test was added
> Allow auxilary keywords in an Arkane species YAML file

- documentation/source/users/rmg/installation/anacondaDeveloper.rst
- documentation/source/users/rmg/installation/anacondaUser.rst
Writing the documentation to only reference Anaconda is inflexible and bloated as compared with utilizing Miniconda or Conda available in system repositories. This is of particular relevance of storage-limited systems, such as shared high-performance resources where RMG is often installed (which also frequently run RHEL or another Enterpise Linux which includes `conda` in the repositories, easing administrative burden).
- Use repositories over Ananconda for proper locations, updates
- switch to Miniconda to reduce download and installation size by 10x
- replace deprecated `source` with `conda` in activating environments
Environments created and RMG-Py, RMG-database installed and tested on Fedora and EL systems
> Improve conda installation instructions

- arkane/explorerTest.py
- examples/rmg/halogens/2-BTP/input.py
- rmgpy/data/kinetics/family.py
- testing/databaseTest.py
This PR is a simultaneous with https://github.com/ReactionMechanismGenerator/RMG-database/pull/515
It adds a commit to swap labels for halogen abstraction reactions since these families are their own reverse (similar to h abstraction).
It also swaps labels for `1,2_xy_interchange` which is also its own reverse
> Adding halogens kinetics (twin with DB)

- rmgpy/statmech/torsionTest.py
When testing `HinderedRotor.get_enthalpy()` method using a Fourier series potential in the quantum limit it calls `get_enthalpy` which, in the quantum limit, calls `solve_schrodinger_equation`, which calls `scipy.linalg.eig_banded(H, lower=True, eigvals_only=True, overwrite_a_band=True)`, which apparently now gives a subtly different answer, and the unit test fails.
```
======================================================================
FAIL: Test the HinderedRotor.get_enthalpy() method using a Fourier series
----------------------------------------------------------------------
File "/home/runner/work/RMG-Py/RMG-Py/rmgpy/statmech/torsionTest.py", line 292, in test_get_enthalpy_quantum_fourier
self.assertAlmostEqual(h_exp, h_act, delta=1e-3 * h_exp) …
```
> Relax tolerances when testing HinderedRotor.get_enthalpy()

- Dockerfile
This small patch adds the environment file patch needed for linux systems (see #2456).
The current user Docker image is unaffected, this will just fix the nightly image (and of course later the user image when we release 3.2.0).
> [Docker]: add linux patch step for `libstdcxx-ng<13`

- .github/workflows/CI.yml
- rmgpy/rmg/input.py
- rmgpy/rmg/reactors.py
- test/regression/RMS_CSTR_liquid_oxidation/input.py
- test/regression/RMS_CSTR_liquid_oxidation/regression_input.py
- test/regression/RMS_constantVIdealGasReactor_superminimal/input.py
- test/regression/RMS_constantVIdealGasReactor_superminimal/regression_input.py
- test/regression/RMS_liquidSurface_ch4o2cat/input.py
- test/regression/RMS_liquidSurface_ch4o2cat/regression_input.py
Currently we don't have any regression test for RMS based reactors. See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2442.
I add `input.py` and `regression_input.py` to test RMS's Constant V Ideal Gas Reactor and RMS's CSTR. Once this regression runs normally on CI, I will add more for other RMS reactors.
> Add regression test for RMS reactor

- .github/workflows/CI.yml
- rmgpy/tools/observablesregression.py
- rmgpy/tools/regression.py
- scripts/checkModels.py
I suspect regression tests are often not looked at because the results are buried in the logs.
The biggest change is that regression tests actually report a failure if a model changes significantly - either the core or edge changes or an observable in the simulation changes significantly.
Many changes to RMG are deliberate improvements and ought to change things, so sometimes we want these "regression" tests to pass - but it should probably be a deliberate act of an admin approving the pull request despite the regression, not just everyone ignoring the regression tests because nobody checks the logs.  If there are too many failures and so we have a bottle-neck of approvals, or admins over-riding tests too much, we can revisit the policy. At least these changes now give us the framework to …
> Regression testing updates

- documentation/source/reference/molecule/adjlist.rst
- rmgpy/molecule/adjlist.py
- rmgpy/molecule/adjlistTest.py
- rmgpy/molecule/atomtype.py
- rmgpy/molecule/fragment.py
- rmgpy/molecule/group.pxd
- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
Also adds a "Reaction" bond order for creating bonds between atoms participating in a reaction so the structure can be considered as a whole without specific labels and enables sites to be bonded to each other. 
This enables creation of molecules from adjacency lists such as: 
```
multiplicity 1
metal Cu
facet 111
1 *3 X u0 p0 c0 s"atop" m"terrace"  {2,S} {4,S}
2 *1 O u0 p2 c0 {1,S} {3,R}
3 *2 H u0 p0 c0 {2,R} {4,R}
4 *4 X u0 p0 c0 s"hcp" m"terrace" {3,R} {1,S}
```
> Enable Metal, Facet, site and terrace specification in Molecule

- .github/workflows/CI.yml
- Dockerfile
- documentation/source/users/rmg/installation/anacondaDeveloper.rst
- environment.yml
a new version of Julia has been released that fixes the issue we were facing, so these changes are no longer needed (see issue #2455 and PR #2456).
I have added that version of Julia (1.9.0) to the "do not allow" list for the environment file. We could probably find a way to specifically disallow the problematic _build_ instead, but this is easier.
With this CI update in place, we can look to figure out the issue with regression testing and then finally get the updated CI into RMG-database.
> Revert `libstdcxx-ng` Patches in CI, Docs, and Dockerfile

- documentation/source/users/rmg/installation/index.rst
I notice that we point the users to the latest at one point in the installation instruction, while we specify 3.1.1 in the other parts.
I change from latest to 3.1.1.
> Fix docker instruction

- .github/workflows/CI.yml
Since the regression testing updates are (:crossed_fingers: #2470) almost done, we can switch RMG-database over to using the updated CI.
This PR just allows us to re-use the action file in RMG-database, rather than copy-paste it over there.
> allow the CI to be called from other repos in the organization

- .github/workflows/CI.yml
- scripts/checkModels.py
The regression tests are not working.
Pull request #2470  shows the difficulty in getting the RMS_liquidSurface_ch4o2cat test to work.
It'll be easier once #2335 is merged, which enables loading and comparison of heterogeneous catalysis models.
But in the mean time, let's just skip that RMS_liquidSurface_ch4o2cat test.
We'll still run the test case, so we know it doesn't crash, but we won't try
comparing the output for now, because trying to fix it is holding back our testing.
Also, we weren't saving the results of the model comparisons.
In this PR we don't try comparing the results of the RMS_liquidSurface_ch4o2cat with the "benchmark" run. We still run it, to check that it doesn't crash, but don't check the results.
This PR also enhances the regression testing by saving the results of …
> Getting the regression tests to work

- .github/workflows/stale.yml
This PR is a followup to some discussion had at the previous RMG developer meeting, and is fodder for the meeting we have today.
RMG-Py's GitHub page is... _busy_. As of writing this, we have 384 open issues and 56 outstanding PRs. Of course, many of these issues are no longer relevant (they have been resolved), and many of these PRs are severely out of date or abandoned.
This PR proposes adding a bot which will:
1. Mark any issue or PR that has received _zero_ interaction in the past 90 days as __stale__.
2. Automatically _close_ any issue or PR which it has previously marked as __stale__ if it does not receive any interaction within 30 days after being marked.
This bot is not a temporary measure - it will first help us resolve our significant backlog, but should also stay into the …
> Cleaning up the RMG-Py GitHub with a robot

- rmgpy/chemkin.pyx
- rmgpy/chemkinTest.py
- rmgpy/data/kinetics/library.py
- rmgpy/kinetics/model.pyx
- rmgpy/kinetics/surface.pxd
- rmgpy/kinetics/surface.pyx
- rmgpy/rmg/output.py
- rmgpy/tools/data/diffmodels/surf_model/chem_gas1.inp
- rmgpy/tools/data/diffmodels/surf_model/chem_gas2.inp
- rmgpy/tools/data/diffmodels/surf_model/chem_surface1.inp
- rmgpy/tools/data/diffmodels/surf_model/chem_surface2.inp
- rmgpy/tools/data/diffmodels/surf_model/species_dictionary1.txt
- rmgpy/tools/data/diffmodels/surf_model/species_dictionary2.txt
- rmgpy/tools/diffmodels.py
- rmgpy/tools/diffmodelsTest.py
currently RMG cannot use the "diffmodels" tool to compare surface+gas chemkin files. This means that we can't use a surface model in the CI tests, which is a big problem. This PR is a step towards fixing that. 
This PR combines fixes for several issues:
-  interpreting surface input files
-  combining chemkin gas+surface output files
-  comparing surface species/reactions. 
Currently have tested by creating a diff.html file for a combined gas+surface model as shown in this [minimal example](https://github.com/ReactionMechanismGenerator/RMG-Py/files/9588247/min_example_for_pr.zip) 
Until we add in the a surface mechanism to our functional/CI tests, this will not be used regularly, so try it with a surface mechanism and make sure the output is captured as we expect.
> Surface diff fixup

- rmgpy/chemkin.pyx
When trying to import a chemkin file from NIST, we choked on a species called `CHF:CF2` because RMG does not expect chemkin species labels to contain colons.
Added `:` to the regular expression used to check valid species labels before returning them.
Also found a commit from ages ago where we did the same thing for periods, for some other chemkin file. I added that commit to this PR. Then I found the model also had `[` and `]` in the species names, so I added those.
I will cross my fingers and let travis run the unit tests.
Hopefully any other parts of code that parse strings using regular expressions (or worse, `split()`) are well written and tested.
We are still, in fact, too restrictive to parse all valid Chemkin names. For example see some of the pathological names that Cantera …
> Allow colons and periods in chemkin species names

- rmgpy/chemkin.pyx
Anyone who uses RMG likely has encountered the frustrating `S(14567)` species label.
This has a few commits by @goldmanm cherry-picked from https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1648 which was recently closed as abandoned.
He wrote:
> In RMG it expands the species length from 10 characters to 16 characters, almost entirely eliminating the dreaded S label.
> This PR is compatible with the cantera and modern versions of chemkin. Unmodified versions of chemkin 2 will not be able to run some models because of a limitation on the length of reaction. chemkin 2, however, can be modified by the users to be compatible with the more widely used chemkin specifications.
I skipped the commits that alter Arkane.
There's also a commit that changes the default chemkin output style for …
> Increase allowed length of species labels for chemkin output. 

- arkane/common.py
- arkane/commonTest.py
- documentation/source/users/rmg/input.rst
- examples/rmg/commented/input.py
- rmgpy/constraints.py
- rmgpy/constraintsTest.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/data/solvation.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/reactors.py
- rmgpy/yml.py
Pull request #2316 which adds electrochemistry, adds lithium, adds solvation to surfaces, adds charge transfer reactions, is rather large and hard to review, and also has some necessarry but unrelated things, that can be helpful elsewhere.
I've pulled out a bunch (but not all) of those things into this PR so they can be reviewed and merged, then the electrochem PR can be rebased onto it.   I also reordered things so the fixups commits are mostly right after the things they're fixing.
One feature that was added was the ability to forbid species and functional groups in input files. As I was trying to add examples to the input files and documentation, I found it was already there, since this feature was added in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2185 - authored …
> A collection of Matt and David's commits from #2316

- .github/workflows/CI.yml
- rmgpy/tools/diffmodels.py
- rmgpy/tools/observablesregression.py
- scripts/checkModels.py
Right now the regression tests are failing by default - this PR implements the following to fix that:
- MacOS runners just can't build Julia dependencies, so only the ability to solve the environment and build RMG, then exit
- Regression tests are considered 'passing' if they execute at all, the actual comparison will be written to the PR by a bot for manual review by humans
> Make the Continuous Integration Pass by Default

- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/molecule/resonanceTest.py
This implements an additional heuristic in aromaticity perception which limits the types of molecules which are considered aromatic. Generally, aromaticity requires that a molecule be planar, in order to enable the sharing of pi-electrons across the molecule. (Some amount of curvature is acceptable, such as with corannulene or bucky-balls.)
If there is substantial strain in a molecule, it can negate the potential effects of aromaticity. For example,
is quite unstable despite having the correct number of pi-electrons to suggest aromaticity.
The new heuristic checks for sharing of more than 2 atoms between two rings, which will always break planarity. In such cases, RMG will no longer consider either ring to be aromatic, even if Huckel's rule is met.
The practical effect of doing so is that …
> Limit aromaticity perception for strained polycyclics

- .github/workflows/CI.yml
- .github/workflows/annotate.yml
- scripts/checkModels.py
The results of the regression tests were largely buried in the logs of the continuous integration action workflow, rather than being nicely summarized on the annotation to the pull request.
The summaries and comparisons that are generated by the CI running the regression tests are captured, and used to make the annotation.
The summary is stored as a text file, with the pull request number stored on the first line. This is then uploaded as an artifact. A new workflow runs whenever the CI workflow completes, then downloads the artifact, extracts the summary, and posts a comment. This complicated runaround is needed because workflows run by pull requests from forks do not have permission to write comments directly.
For the markdown formatting, I have run it a bunch, and checked things render …
> Expand the regression test annotations.

- .github/workflows/CI.yml
- .github/workflows/annotate.yml
There are a couple of problems with the new regression test result annotations workflow introduced in #2501
1. I stupidly left out a couple of lines. We need to define the pull request number in an environment variable in the step where we write it to the file. Sorry. (I had done the testing on a much accelerated workflow, and then didn't correctly copy it across to the real workflow).
2. The "Continuous Integration" workflow runs on a push to master (eg merging a PR) and on a cron job, both of which will trigger the Annotation workflow, but neither of which will have uploaded a regression test summary file, so the Annotation workflow will fail. The only problem with this is folks getting emails and notifications about workflow failures. Ideally the workflow just wouldn't run in those …
> Fix a bug in the CI workflow

- .github/workflows/CI.yml
- .github/workflows/annotate.yml
More improvements to the new github workflows
* the regression summary is prepared and added to the workflow job summary for everything but the reference job (the push to main and nightly build).
* the annotation workflow is only run for pull requests, not for pushes and scheduled runs.
* if the annotation job fails for some reason, it reports the event that triggered it, for debugging..
I ran things on my main branch. I think they're working - but this workflow stuff has been remarkably hard to get right first time.
> More github workflow improvements

- rmgpy/rmg/model.py
- rmgpy/rmg/pdep.py
Library reactions marked with an ``elementary_high_p`` flag set to ``True`` can either have PDep kinetics or Arrhenius kinetics. The high-pressure-limit kinetics is used in PDep networks to improve them instead of using RMG's estimations. However, if the original library reaction already has PDep kinetics, then this library rate should end up in the model rather than a PDep estimation. Of course, if the library reaction only has Arrhenius (non-PDep) kinetics, and the reaction is pressure-dependent, the kinetics must be replaced with the PDep estimation.
Only omit a library reaction from the core if an isomorphic  PDep reaction was created and if the library reaction has no PDep kinetics (changes done to model.py).
Also, and complementary, don't add a network reaction to the core if the …
> Don't replace PDep kinetics of a library reaction

- .github/workflows/CI.yml
See https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2510#issuecomment-1658870085
Re-using the RMG-Py workflow removes the ability to (easily) run the tests from forks or to target forks, so we will instead copy the testing action and test files to RMG-database. The workflow will be similar but (as mentioned below) can skip some steps.
> remove reusable workflow logic, make RMG_DATABSE_BRANCH file-scoped

- .github/workflows/CI.yml
This is what we did in the (abandoned) PR #2510 and should have been done in PR #2512.
It means that when the CI runs on pushes to a forked repository, it checks out that forked repository, instead of the official one.
Let's check it actually does the right thing before merging this time!
> Fix CI workflow to function on forked pushes.

- rmgpy/data/kinetics/database.py
I had a reaction library folder with another python file in it (`renumber.py`)that had been used to renumber the reactions
at some point. RMG was trying to load this as if it were a `reactions.py`, and failing the database tests. 
Since named reaction libraries are forced to have the file be called "reactions.py", I think it is OK that the "load all libraries" method makes the same assumption.
So now it only searches for libraries with a file called `reactions.py` (though it is case insensitive).
On my computer, `make test-database` now passes (on the new pytest system) whereas it didn't before this.
> When loading all reaction libraries, only process "reactions.py" files.

- rmgpy/species.py
See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2518.
I remove the label before detecting cutting label.
I test it on the example in https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2518, and it works.
> Remove label in adjlist before detecting cutting label

- .github/workflows/CI.yml
- Dockerfile
- documentation/source/users/rmg/installation/anacondaDeveloper.rst
The "main" branch of ReactionMechanismSimulator.jl is temporarily incompatible with RMG, causing all builds to fail.
For now, there is a dedicated "for_rmg" branch, which we can use, which is currently where main was just before the most recent breaking PR was merged.  Hopefully things can be resolved and a main branch will work for both.
I plan to let the CI run its course.
The failure looks like this in the CI logs:
```
Wed, 09 Aug 2023 15:50:00 GMT   ....installing Julia stuff...
Wed, 09 Aug 2023 16:20:00 GMT
└  
Wed, 09 Aug 2023 16:21:43 GMT
[ Info: Installing molecule.molecule via the Conda rmgmolecule package...
Wed, 09 Aug 2023 16:21:44 GMT
[ Info: Running `conda config --add channels hwpang --file /usr/share/miniconda3/envs/rmg_env/condarc-julia.yml --force` in root environment …
```
> Instruct Docker, Github Actions, and users to use 'for_rmg' branch of RMS

- documentation/source/users/rmg/installation/index.rst
RMG-Py version 3.2 is out (1df107f) :tada:! This PR updates the docs to point users towards that docker image, which I have already built and uploaded to docker hub on the reactionmechanismgenerator/rmg repository.
Resolves #2467 - the required code for the issue mentioned is now in the Docker image.
Let's allow #2516 to go in before this just to save that PR having to rebase (again).
> update docker usage instructions to point to v3.2.0

- documentation/source/reference/kinetics/index.rst
- documentation/source/reference/kinetics/stickingcoefficient.rst
- documentation/source/reference/kinetics/surfacearrhenius.rst
Issue #2085, missing documentation for surface kinetics classes in the [api reference](http://reactionmechanismgenerator.github.io/RMG-Py/reference/kinetics/index.html#module-rmgpy.kinetics)
added a link for each surface reaction type, and a page for each in the index
None of the linear free energy reaction types (ArrheniusEP, ArrheniusBM) are listed [here. ](http://reactionmechanismgenerator.github.io/RMG-Py/reference/kinetics/index.html#module-rmgpy.kinetics). Is that intentional or should they be added.
> Doc surf rxns

- environment.yml
The CI has been failing ([see here](https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/6009736707/job/16299748843#step:4:86)) for a couple days because of the latest release of `cclib` (see [here](https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/5973597214/job/16206162069#step:4:86) for reference), breaking unrelated PRs such as #2533 
Disallows `1.8.0` of `cclib` in the RMG `environment.yml`. This is intended as a temporary patch so PRs can keep working and I can do some work locally to find out why this version of `cclib` is failing, and potentially file a bug report with the maintainers.
Just using the CI here. As mentioned above, need to do some local debugging to try and find out _why_ this is failing.
Should be quick to merge (famous last words).
> Fix Failing CI because of `cclib`

- arkane/encorr/bac.py
When using cross validation, the average RMSE and average MAE are currently calculated as RMSE_avg = sum^{n_fold}_i(RMSE_i)/n_fold and MAE_avg = sum^{n_fold}_i(MAE_i)/n_fold. 
However, during leave-one-out cross validation, this method returns the same number for RMSE_avg and MAE_avg. This is because when there is only one testing data, RMSE_i = MAE_i. 
Instead, I think this average formula should be used, where 
RMSE_avg = sqrt( sum^{n_fold}_i (RMSE_i^2 * Ndata_i) / sum^{n_fold}_i (Ndata_i) )
MAE_avg = sum^{n_fold}_i (MAE_i * Ndata_i) / sum^{n_fold}_i (Ndata_i)
I calculate the RMSE_avg and MAE_avg for leave-one-out cross validation case.
> Update RMSE/MAE average formula for BAC cross validation

- rmgpy/molecule/converter.py
- rmgpy/molecule/inchi.py
- test/rmgpy/molecule/converterTest.py
- test/rmgpy/molecule/translatorTest.py
This PR tries to fix issue #2536, where the SMILES of bicarbon (CC) is not correctly generated.
This PR forces the setting of no implicit Hs when converting the RMG Molecule to an RDKit Mol object. This is viable since all hydrogens in the RMG Molecules are defined explicitly.
Add a few unit tests to test the molecule of CC with various multiplicities. I comment out the case with a quadruple bond, as it is very likely the installed RDKit version doesn't have support for output smiles of quadruple bond (which is introduced in sometime 2022)
<del> There is an InChI error raised due to this change, and I am investigating it.
https://github.com/xiaoruiDong/RMG-Py/actions/runs/6238513699/job/16934497099
> Fix CC smiles

- rmgpy/chemkin.pyx
fixes #2050. This PR fixes the issue that a comment while debugging is repeated excessive amounts of times
I commented out the the logging line
> Removing the excessive debug comment

- rmgpy/data/solvation.py
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [solvation.py](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/main/rmgpy/data/solvation.py#L1725), method: `_add_ring_correction_solute_data_from_tree`, a logical expression uses the identity operator. A new object is created inside the identity check operation and then used for matching identity. Since this is a distinct, new object, it will not have identity an match with anything else. As a result, the identity check will have a logical short circuit and the program may have unintended behavior. iCR suggested that the logical operation should be reviewed for correctness.
```py
if matched_ring_entries is []:
raise KeyError('Node not found in database.')
```
A simple test like below …
> FIX: Updated logical expression to remove short circuit

- documentation/source/users/rmg/database/introduction.rst
This is the PR in response to [issue #2493](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2493). It updates the documentations and makes it clear that you can only specify forbidden molecules or species in the forbiddenStructures.py file and not in groups.py. 
Added in two sentences to `introduction.rst` that remind the reader that forbidden molecules/species cannot be specified in groups.py.
Checked what the new updates look like in the documentation. looked fine.
> changing forbidden groups documentation 

- .github/workflows/stale.yml
Stale label action currently closes old issues and PRs if they have had no interaction in 90 days, _except_ when they are labeled with `bug`. This PR also excepts those labeled with `Announcement`, especially meant for #2559 which will be open for a while but is not a bug.
> exempt announcements from being closed as stale

- rmgpy/molecule/fragment.py
- rmgpy/rmg/reactors.py
This PR contains changes made to https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2413. See this [comment](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2413#discussion_r1362981840) for details. I put it into a separate PR rather than push commits directly PR as suggested by @JacksonBurns.
I use a representative molecule for a fragment to calculate the correct molecular weight, number of atoms, and number of bonds. The number of atoms for the representative molecule is used to estimate radius for a fragment, which is used to estimate the stokes diffusivity. I also pass the kLA and kH into the RMS Species for fragments.
> Getting structure information correctly for fragment

- .github/workflows/CI.yml
- test/regression/RMS_constantVIdealGasReactor_fragment/input.py
- test/regression/RMS_constantVIdealGasReactor_fragment/regression_input.py
- test/regression/fragment/input.py
- test/regression/fragment/regression_input.py
The current fragment regression test only tests that the mechanism can be generated, but not testing that the results actually stay consistent with previous runs. Additionally, currently we are not testing fragment is compatible with RMS reactor.
I add a `regression_input.py` for the fragment + simple reactor regression test. I also add a new regression test for fragment + RMS reactor.
> Add regression input file for fragment + simple reactor and regression test for fragment + RMS reactor

- rmgpy/tools/regression.py
- test/regression/RMS_constantVIdealGasReactor_fragment/regression_input.py
- test/regression/fragment/regression_input.py
We merged in the fragment regression tests in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2571. We thought the failed test was because there was no stable version for comparison. However, it was actually caused by current code not able to read regression input for fragments.
I modified the `regression.py` to read fragment structures by importing necessary functions from `rmgpy.rmg.input`. I also replaced some duplicate functions.
Let's see if the regression test for fragment works in the CI.
> Compatibility of `regression.py` with fragment

- rmgpy/reaction.py
The calculation of the rate constant from the sticking coefficients for adsorption of a gas-phase species as a multidentate adsorbate is currently wrong by a small factor (typically 2).  
Currently, the equation we use to derive the rate constant from the sticking coefficient is
$$k_f=\frac{\gamma}{\Gamma^m}\sqrt{\frac{RT}{2\pi W}} $$
For species adsorbing as a multidentate, this changes to 
$$k_f=\frac{\gamma \prod_{j=1} \sigma_j ^{\nu_j}}{\Gamma^m}\sqrt{\frac{RT}{2\pi W}} $$
according to the Chemkin manual, where \$\nu\$ is the stoichiometric coefficient and \$\sigma\$ the site occupancy of number of species \$j\$. It is only necessary to use the term \$\sigma_j ^{\nu_j}\$ for the multidentate adsorbate since the terms for the surface site are always unity. 
I modified the `reaction.py` …
> correcting bidentate adsorption rate constant

- arkane/data/gaussian/water.out
- arkane/ess/gaussian.py
- test/arkane/ess/arkaneGaussianTest.py
Provide a new keyword '`HF=`' to parse the electronic energy from a Gaussian opt job output file, since '`SCF Done`' is not available in this case
- Add the new keyword in `load_energy` method
- Add a test case in `test_gaussian_energies`, and a new Gaussian opt job output file, `water.out`
we now can test that it is working properly by comparing results within the output file
Suggestions for verifying that this PR works or other notes for the reviewer.
> Add keyword "HF=" to parse electronic energy

- rmgpy/data/thermo.py
We should update `uncertainty_si`, instead of `uncertainty` to be consistent with units when averaging `ThermoData`.
> Update uncertainty SI when averaging ThermoData

- .github/workflows/docs.yml
- documentation/Makefile
GitHub is now requiring 2FA on all accounts - this means our helpful bot RMG_dev, which is used to push documentation to the repo, is 'banished' (or will at least break soon). This PR changes the docs building action to use the GitHub actions bot account to push the changes to the docs instead.
I'm not sure how to test this besides running it on GHA, just to see if it works?
> Change Documentation Build Action to use github-actions bot instead of RMG_dev

- .github/workflows/docs.yml
As luck would have it #2599 did _not_ in fact work, so this PR is attempting (again) to fix it.
Seems like after using the default git checkout github actions step, we can't use other git commands because of some nonsense with the ssh key. Rather than deal with figuring that out, I have just moved all of the weirdness we were doing in the git command to the original checkout command.
I have also removed the `rm -rf build/html` command. That directory does not exist before the clone (I think this was carried over from a previous script, because it doesn't actually break anything).
> fix checkout command for docs building action

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- Dockerfile
These changes are unrelated but small, so I have combined them with reckless abandon.
- The CI has been failing because of an upstream problem with Julia dependencies. To try and resolve this @mjohnson541 suggested pinning the Julia version to 1.8.5 - this PR does that in the CI files with `sed`. (note: ended up using 1.9.1 because 1.8.5 did not work)
- In a continuing effort to address #2582 (at which #2599 and #2602 were only _partially_ successful) this changes some minor syntax in `git` commands inside the doc building action.
- Dockerfile would not run properly on windows, a small patch has been added (see commit message for [51924d9](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2608/commits/51924d98ed65bac069cbbde0ab7c894979c567a5))
If the CI passes this should be good …
> Continuous Integration, Documentation Build, and Dockerfile Fixes

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- Dockerfile
- environment.yml
Julia has been updated to 1.10.0 on Conda-Forge and therefore RMS does not install. https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2608 rectified this issue by patching in a version restriction on Julia to 1.9.1. This PR attempts to restrict the version in the environment.yml file so that we will not need to maintain the patches in the CI/Dockerfile/Doc
Restricted Julia to 1.9.1 in the environment.yml file
> Julia restriction

- .github/workflows/docs.yml
_Still_ trying to fix the docs building action. This time, it seems like omitting `--global` from the git sign in has meant that, for some reason, it just didn't work. See:
https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/7873601921/job/21481327559#step:12:38
> #2602 part 2, Electric Boogaloo

- rmgpy/rmg/main.py
Interruption in simulation during the final model check. 
Added Troe kinetic (along with thirdbody) to the main.py file of the RMG. 
The present RMG code checks if violator[0].kinetics is the ThirdBody and, if True, enters into the if condition where self.reaction_model.core.species (species_list) is supplied as an argument to the function to_chemkin. For all the other types of kinetics, the else loop is followed, which does not have any argument. However, Troe kinetics also requires species_list as an argument to identify collider species, which is considered None as per the current code. Therefore, adding Troe to the if statement is essential to include reactions with Troe kinetics in the violators' log.
For more details, refer to the RMG issue #2604.
The model generation was completed …
> Modified main.py script to include TROE reactions in the violators log

- .github/workflows/docs.yml
Following extensive investigation in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2619 this PR finally fixes the documentation build and modernizes the workflow a bit:
- runs the workflow on a schedule so that we can catch future errors once a week instead of whenever we update the docs
- fixes the incorrect installation order by copying from the CI setup steps
- fixes the path error in the docs building/committing
- reorders the steps somewhat to improve clarity of the actual doc build
This PR will be successful if we get all the way to the last step in the docs build and it is skipped, and if in the "Build Documentation" step all of the changes are shown in the output from the `git add` command.
> documentation builder bug fixes and general overhaul

- environment.yml
A draft PR for testing if we can switch `grof2dot`, `numdifftools`, `quantities` to the conda-forge version.
> Replace a few packages maintained by us to their conda-forge version

- .github/workflows/CI.yml
- .github/workflows/docs.yml
#2621 fixed the docs building but was not tested from forks or with PRs that do not update the docs, and in both cases the action now _looks_ like it fails even though it's fine. This PR removes the test push (which failed from forks) and allow the commit step to fail, which it would do if the PR does not contain docs updates.
#2512 and #2608 left some lint in the CI which this PR removes.
Blocked by #2553 since I accidentally made this branch locally off of that one and am too lazy to rebase + this isn't urgent.
> GitHub Actions Maintenance

- environment.yml
this is related to #2535, regression tests are failing because we are using a newer version of cclib. the previous statement did not restrict newer versions of cclib, just versions that are !=1.8.0. 1.8.1 was released recently and broke out regressions tests again. 
change environment.yaml line for cclib to disallow versions that are equal to or greater than cclib 1.8.0
> restrict newer versions of cclib

- rmgpy/chemkin.pyx
Make chemkin read of transport and thermo files more robust
I ran into these two issues while importing the Aramco 3.0 mechanism:
1. It couldn't read the separate thermo file because of the relative seek command, which apparently requires reading in binary format and gave this error message: `UnsupportedOperation: can't do nonzero cur-relative seeks`
2. It couldn't read the transport file because the shape_index column had been formatted as a float instead of an int.
1. Instead of using a relative f.seek() command, keep track of the previous line and just seek to that. This is how the file is parsed in the rest of chemkin.pyx.
2. Read in the shape_index as a float and then convert it to an int. This works whether the data is formatted as 0 or 0.000 …
> Make chemkin read of transport and thermo files more robust

- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/database.py
- rmgpy/data/kinetics/family.py
In #2630 it was observed that `kinetics.database.generate_reactions_from_families` and `kinetics.family.calculate_degeneracy` can be modularized and improved.
This PR accomplishes the following:
1. Copies the overlapping code in the above functions and re-implements as a new function `kinetics.common.check_for_same_reactants`, which checks to see whether the provided reactants list has duplicate reactants (or not).
2. Allow `resonance` to propagate in `kinetics.family.calculate_degeneracy`. This way, you can specify `resonance=False` when generating families and it will not consider resonance anymore (which is crucial for some species that have many resonance forms, see #2630).
3. Fix up various typos; for example previously `kinetics.database.generate_reactions` does not allow …
> Clean up some code for calculating degeneracy in kinetics codebase

- documentation/source/users/rmg/input.rst
RMG cuts large molecules (default >20 carbon) even when user does not desire to make fragment model
added documentation instructing users to set `speciesCuttingThreshold` to an arbitrarily large number if fragments are not desired in mechanism
> Add documentation about `speciesCuttingThreshold`

- rmgpy/rmg/model.py
In #2649 it seems like we are having issues with adding seed mechanism containing a matching initial species while the initial species are in the edge. 
Because of how we process creating the initial core-edge and running estimation we add the initial species to the edge first later add the seed mechanisms and reaction libraries and lastly add the initial species to core and react them. 
In #2649 we run into a problem because the function for adding seed mechanisms searches for "site" and finds it (it is in the edge), since it finds it, it seems to assume it doesn't need to do anything which becomes a problem when it tries to add the associated reaction directly to core since "site" isn't in the core. 
I have modified add_seed_mechanism_to_core to track species that are in the edge and …
> FIx Handling of Initial Species with Seed Mechanisms

- .github/workflows/CI.yml
- rmgpy/tools/canteramodel.py
- rmgpy/tools/observablesregression.py
- rmgpy/tools/regression.py
- test/regression/minimal_surface/input.py
- test/regression/minimal_surface/regression_input.py
moved over from https://github.com/ReactionMechanismGenerator/RMG-tests/pull/85
We want to make sure in our testing that surface examples work. 
Adding a surface test input file.
This also adds functionality to rmgpy.tools.canteramodel.py to load, simulate, and compare surface mechanisms. Then it also adds hooks in the upstream callers, rmgpy.tools.regression.py and rmgpy.tools.observablesregression.py to pass the surface-specific information into the cantera model
I ran the regression test on an example surface file and then also on the superminimal and nitrogen examples.
This PR can be broken down into two parts: adding the surface functionality to the regression tool, and then adding the surface testing files to the CI workflow.
> Add surface combustion example for regression testing

- rmgpy/thermo/model.pyx
Bug fix for https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2657:
RMG returns false when you call thermo.is_identical_to() on identical vacant sites (all zeros for thermo)
This adds an exact check of the Tdata values at each temperature, in addition to the relative check which fails if both values are zero (divide by zero results in nan)
Here's the script I used to demonstrate the problem/whether it's fixed:
```
import os
import rmgpy.data.thermo
import rmgpy
library_path = os.path.join(rmgpy.settings['database.directory'], 'thermo')
database = rmgpy.data.thermo.ThermoDatabase()
database.load(
library_path,
libraries = ['surfaceThermoPt111']
)
X_thermo_data = database.libraries['surfaceThermoPt111'].entries['vacant'].data
print(X_thermo_data) …
```
> add check for all zeros in thermo comparison

- rmgpy/data/base.py
When there are issues in a database file, such as nan values like `uncertainty=RateUncertainty(mu=nan, var=nan,` in a `rules.py` file (which may be due to a bug in the tree fitting), it was very hard to  find the cause of the error because the stack trace wouldn't tell you where the actual error was in the file, and the file handle had been read by the time you caught the exception, making it misleading in a debugger.
With this change, we first read the file to a variable, then try executing it, and catch and report any exceptions properly, finding the line within the database file that caused the problem.
I got this working and it helped debug something, providing this error message:
```
ERROR:root:Error while reading database /Users/rwest/Code/RMG-database/input/kinetics/families/Intra_R …
```
> Better debugging messages for database errors.

- .github/workflows/CI.yml
- increment miniconda setup to v3 from v2
- set macos build runner to use intel macs rather than m1, since we don't have binaries for m1
- switch download artifact step to use the official github one, which now allows grabbing artifacts from other runs
Resolves https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2611
See https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2667 for more history
> github actions CI maintainence

- .github/workflows/CI.yml
- arkane/ess/gaussian.py
Sometimes, in  gaussian log files, the line that contains the energy has extra characters (more than one line printed in the same line) that prevent the load_energy function in arkane/ess/gaussian.py from parsing the energy. (e.g., it will try to use an "=" as the energy)
Before: find the line that has "SCF Done:", split it, take the 4th index as the energy
After: find the line that has "SCF Done:", find the substring that matches "SCF Done: E(...) = {energyfloat}, split the substring, and take the last item
the same can be done for E2, MP2, E(CORR), CCSD(T), CBS-QB3 (0 K), E(CBS-QB3)=, CBS-4 (0 K)=, G3(0 K), G3 Energy=,G4(0 K), G4 Energy=, G4MP2(0 K), G4MP2 Energy= in the same function
I plan to try the load_energy function on many gaussian log files, some which have extra characters in …
> Change method for loading energies from Gaussian log files to regex search to avoid errors 

- rmgpy/cantera_.py
The yaml_writer_addition branch no longer correctly adds reaction species to the Cantera yaml output file. Species block is always a list of nulls. This issue originated during a rebase of the branch.
* changes to `rmgpy/cantera_.py`:
- `species_to_dict()` method updated to correctly use the parameter `obj` as the RMG species object.
Tested on minimal example and minimal_surface example (minimal_surface errors unless commit [feb70e2](https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2321/commits/feb70e275fe16e53a14788c83bc7b9404dc7510f) is reverted/fixed)
Comment out the temporary "raise exception" calls in `to_cantera_kinetics()` to test on any example that requires this method.
> fix species_to_dict function to use correct parameter as reaction species

- rmgpy/reaction.py
The Chebyshev.fit_to_data() method treats the Pmin and Pmax args as SI (Pa units), see here for example: `self.Pmin = (Pmin * 1e-5, "bar")`. Make sure we transmit the arguments in SI units and not in the arbitrary units they were defined in.
> Send P in SI units to Chebyshev.fit_to_data() when reversing a rate

- test/rmgpy/data/transportTest.py
#2680 and #2681 both fail this unit test despite not touching the associate code in any way:
```
if comment:
>               assert transport_data.comment == comment
E               AssertionError: assert 'Epsilon & sigma estimated with Tc=500.53 K, Pc=48.02 bar (from Joback method)' == 'Epsilon & sigma estimated with Tc=500.53 K, Pc=47.11 bar (from Joback method)'
E                 - Epsilon & sigma estimated with Tc=500.53 K, Pc=47.11 bar (from Joback method)
E                 ?                                                 ^ ^^
E                 + Epsilon & sigma estimated with Tc=500.53 K, Pc=48.02 bar (from Joback method)
E                 ?                                                 ^ ^^
test/rmgpy/data/transportTest.py:181: AssertionError
```
...I _think_ because we updated …
> Fix Failing Joback Method Unit Test

- environment.yml
Also also like number #2680 it turns out that `pyrdl` is also already on `conda-forge`, and @mjohnson541 was the one who prompted the developers to get it listed! See: https://github.com/conda-forge/staged-recipes/pull/19942
This PR will test if it works for us
> switch `rmg::pyrdl` to `conda-forge::ringdecomposerlib-python`

- environment.yml
In the same vein as #2671, I just discovered that someone has been thanklessly maintaining an official `conda-forge` binary of `lpsolve55`: https://github.com/conda-forge/lpsolve55-feedstock
This PR will see if it works for us.
> switch `rmg::lpsolve55` to `conda-forge::lpsolve55` channel

- Makefile
- environment.yml
This PR changes a number of `rmg` channel packages to their official `conda-forge` variants maintained by other people:
- `rmg::muq2` -> `conda-forge::muq` (different name, same version)
- `rmg::lpsolve55` -> `conda-forge::lpsolve55`
- `rmg::py_rdl` -> `conda-forge::ringdecomposerlib-python` (different name, same package and version)
The first change also required adding a new line to the `Makefile` to ensure that correct compiler is used when installing RMG.
> Switch `muq`, `lpsolve55`, and `RingDecomposerLib` from `rmg` to `conda-forge`

- documentation/source/users/rmg/input.rst
- rmgpy/data/kinetics/database.py
- rmgpy/rmg/model.py
Previously a feature (#2340) was added to allow RMG to load external thermo and kinetic libraries. That feature was incomplete, since reaction libraries are stored by their label, and RMG tries to load them by the name provided by the user which is their path.
This issue is not relevant for thermo libraries which are loaded differently in RMG.
A dictionary was added to `KineticsDatabase` to map paths to external kinetic libraries with their labels. It is used now in model.py if needed.
The feature was tested locally only. Any tips for adding a path (absolute? relative?) to an RMG input file are welcomed to modify [the existing test](https://github.com/ReactionMechanismGenerator/RMG-Py/blob/main/examples/rmg/external_library/input.py#L9).
Copy one of the RMG kinetic libraries to a …
> Load a kinetic library not in the RMG database

- arkane/ess/adapter.py
- arkane/ess/factory.py
Currently, the scratch directory in Arkane symmetry calculation is hardcoded to be "./scratch". It makes parallelization difficult as all the jobs will use the same scratch directory name.
I allow the scratch directory to be a user input with default being "./scratch".
After this changes, my script was able to run in parallel without crashing due to scratch directory related errors.
> Allow scratch dir as input for arkane symmetry calculation

- rmgpy/molecule/draw.py
RMG reactions are typically reversible, but they are always drawn with a forward arrow → instead of the double harpoons. ⇌
This PR makes it the default to draw the arrow as described by the `reaction.reversible` property (→ for `False` and ⇌ for `True`). If someone wants to revert to the way things were and always draw the arrow as →, they can set the ReactionDrawer option 'drawReversibleArrow' to `False`.
Here's some code to test out the results in a Jupyter notebook (note the last example writes to a file)
```
import rmgpy.reaction
my_reaction = rmgpy.reaction.Reaction()
my_reaction.reactants = [rmgpy.species.Species(smiles='CCCC'), rmgpy.species.Species(smiles='[OH]')]
my_reaction.products = [rmgpy.species.Species(smiles='O'), rmgpy.species.Species(smiles='[CH2]CCC')] …
```
> Draw reversible arrow if reaction is reversible

- environment.yml
I'm planning to release pyrms v2.0.0 which will mark a switch to pyjuliacall. This PR prevents current RMG-Py from grabbing the new version it isn't compatible with.
> Restrict pyrms to <2

- .conda/meta.yaml
- .github/workflows/CI.yml
- arkane/encorr/isodesmic.py
- arkane/statmech.py
- documentation/source/users/rmg/installation/dependencies.rst
- environment.yml
- rmgpy/molecule/resonance.pxd
- rmgpy/molecule/resonance.py
- rmgpy/reaction.py
- rmgpy/rmg/reactors.py
- test/arkane/encorr/isodesmicTest.py
- utilities.py
This PR replaces #2596 as described in this comment: https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2687#issuecomment-2248642608
> [Python 3.9] Improve isodesmic and add element balance constraints

- environment.yml
- rmgpy/qm/molecule.py
- rmgpy/qm/qmdata.py
regression tests fail with the superminimal example, because it uses mopac for qm calcs. the root cause is the parser has since been updated, and the variable name for rotational constants has been changed from "rotcons" to "rotconsts" (see [this](https://github.com/cclib/cclib/commit/ebff98a7d0dadc92b1c6c23a91210586ab2470aa) commit on the cclib repo). 
additionally, in more recent versions, it looks like the "rotconsts" is part of a default cclib parser object for MOPAC output files, so there the workaround we use is not necessary. I have left the "old way" of adding rotational constants in for backwards compatibility. 
I added checks for whether the cclib_data object has "rotconsts" specified, and assigns the appropriate values to the qm object. 
unit tests and functional tests. If the …
> updating 'rotconsts' ref to be compatible with cclib v1.8+

- arkane/data/orca/N_MRCI.log
- arkane/ess/orca.py
- test/arkane/ess/orcaTest.py
The current Orca ESS adapter in Arkane does not support monoatomic molecules (e.g., `O`, `N`, ...).
This is probably because DKPNO calcs do not support monoatomics. However, we would like to use Orca for other LOTs which can be applied for monoatomics.
Modifications were made to Arkane's Orca ESS adapter to support monoatomics. Most modifications are minor.
Tests were added for the Orca adapter modifications.
> Process monoatomic molecules in Arkane's Orca ESS adapter

- environment.yml
Update Before Merging from @JacksonBurns:
This PR tested and showed that we can remove the `default` channel from our `environment.yml` file. This is important since Anaconda has changed their Terms of Service, and this change brings many of our users back in line with said ToS.
> Remove `default` Channel from `environment.yml`

- .github/workflows/CI.yml
- test/regression/minimal_surface/input.py
Edit 9/15/24: the runner is crashing due to OOM errors. There is a solution to this that involves reducing the memory usage in the regression tests, but implementing this solution is hard. We have opted for an easier solution: severely limit the size of the mechanism. This does not cover as much 'science' as we would like the regression test to do, but does at least offer some basic correctness checks. At this point this is preferable to not testing at all, as we are currently doing since the 'better' solution is quite challenging.
Original PR content follows:
I discovered in #2595 and #2669 that the `minimal_surface` regression test comparison causes the runners to crash with exit code 143. To allow things to still be merged in the meantime, I have removed that test from the CI and …
> Patch `minimal_surface` Regression Test

- .github/workflows/CI.yml
- .github/workflows/docs.yml
Mambaforge will be [sunsetted](https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/) starting from Oct 1, 2024 and only Miniforge will be maintained going forward. This will cause our CI to fail at the environment creation step. 
The `miniforge-variant` parameter is changed to `Miniforge3`.
> Change CI to use Miniforge3 instead of Mambaforge

- .github/workflows/CI.yml
- environment.yml
Resolves issue #2722 .
- Added a step in the CI workflow to create a custom conda config files that excludes the default channel. 
- Replaced the nomkl mutex metapackage that controls whether packages should use MKL or OpenBLAS.
> Deprecate the nomkl mutex metapackage

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- Dockerfile
- documentation/source/users/rmg/installation/anacondaDeveloper.rst
- environment.yml
- rmgpy/pdep/sls.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/pdep.py
- rmgpy/rmg/reactionmechanismsimulator_reactors.py
Can't debug the CLAR implementation right now because the new `juliaup` based installation isn't working. Going to allow running without Julia on this PR, which we were planning on doing in the future, and then add support back for it later. Can't fix two things at once.
> Port Optional RMS Changes into Ongoing SciPy CLAR Implementation

- rmgpy/rmg/model.py
If you include a library for a surface mechanism that uses linear scaling, this can cause some reaction barriers to be below the endothermicity of the reaction. This PR fixes the barrier heights for library reactions that have been scaled across metals.
See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2726 for more details of the issue.
This PR adds a call to fix_barrier_height() if the library reaction is a surface reaction with any species thermo that has been scaled across metals.
I have tested with this CPOX on Rh RMG [input.txt](https://github.com/user-attachments/files/17718558/input.txt) and confirmed that it raises the barrier for the O2 dissociative adsorption reaction taken from the Surface/CPOX_Pt/Deutschmann2006_adjusted library:
```
! Reaction index: Chemkin …
```
> Fix library reaction barrier heights for linear scaling

- rmgpy/data/thermo.py
- rmgpy/molecule/fragment.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/pathfinder.pxd
- rmgpy/molecule/pathfinder.py
- rmgpy/molecule/resonance.pxd
- rmgpy/molecule/resonance.py
- test/rmgpy/molecule/moleculeTest.py
- test/rmgpy/molecule/pathfinderTest.py
- test/rmgpy/molecule/resonanceTest.py
Adsorbate molecules can exhibit resonance similar to gas-phase molecules. For example, the bidentate adsorbate XCXC (where X is a surface site) has the following three configurations:
[X]C#C[X] <-> [X]#CC#[X] <-> [X]=C=C=[X]
Currently, RMG cannot identify resonance structures for adsorbates. 
In this pull request, I made the first step and added functions for the generation of resonance structures for adsorbates. 
Resonance occurs only for adsorbates that have at least two binding sites, also known as bidentate adsorbates. 
Therefore, a function was added to molecule.py to check if an adsorbate has two binding sites. 
The pathfinder.py was updated with functions to find the structures of adsorbates which can eventually have resonance structures. The structures that are searched for in the …
> adding resonance for adsorbates

- rmgpy/data/kinetics/database.py
- rmgpy/data/kinetics/library.py
See https://github.com/ReactionMechanismGenerator/RMG-database/issues/678. 
Some of the new libraries are causing issues with loading the relevant kinetics data into the RMG database.
(1) `LithiumPrimaryChargedKinetics`. The cause of this error was `ArrheniusChargeTransfer` not being included in the local context. **This has been fixed in this PR.**
(2) `LithiumAnalogyKinetics`. The cause of this error is not clear to me yet; still investigating.  As this gets fixed (and if any other errors pop up), they will be addressed in this PR.
To reproduce, try:
```
from rmgpy.data.rmg import RMGDatabase
from rmgpy import settings
database = RMGDatabase()
database.load(settings['database.directory'], thermo_libraries = []', 
kinetics_families=[], kinetics_depositories=[], reaction_libraries=None) # …
```
> Fix database issues with loading new kinetic libraries

- arkane/statmech.py
- examples/arkane/species/OCHO/OCHO.py
- examples/arkane/species/OCHO/freq.out
- examples/arkane/species/OCHO/input.py
Arkane's `statmech.py` has a variable defined within an if statement, but used outside of it. When the statement evaluates to `False`, Arkane crushes.
Defined `e_electronic_with_corrections` and `zpe` formally outside the if statement, and properly deal with `e0` assignment after the condition.
An Arkane example for feeding in E0 directly for a species was added
(Arkane's examples are automatically executed as functional tests)
> Fxi UnboundLocalError: local variable 'e_electronic_with_corrections' referenced before assignment

- CONTRIBUTING.md
Related to larger issue of outdated docs in https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2703.
This PR serves to consolidate contributor guidelines in a `CONTRIBUTING.md` file [as described here.](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
> [Docs] Add CONTRIBUTING file with contributor guidelines

- README.md
After deprecating the Wiki page and gitter chatroom, we forgot to remove those mentions from the README. This PR removes those as appropriate.
> Remove Wiki and gitter from README

- arkane/data/gaussian/starred_rotational_constant.log
- arkane/ess/gaussian.py
- test/arkane/ess/arkaneGaussianTest.py
Some Gaussian files list *****'s for the last set of rotational constants and Arkane errors out reading it.
See https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2760
This update keeps track of previous rotational constants and uses them to fill in any values that Gaussian stars out.
I tested the changes on 
[logfile_with_error.log](https://github.com/user-attachments/files/18789436/logfile_with_error.log)
[logfile_without_error.log](https://github.com/user-attachments/files/18789437/logfile_without_error.log)
using this code:
```
import arkane.ess
gl = arkane.ess.ess_factory('logfile_without_error.log')
conformer, unscaled_freqs = gl.load_conformer()
gl = arkane.ess.ess_factory('logfile_with_error.log')
conformer, unscaled_freqs = gl.load_conformer()
```
Does anyone know why …
> Fix rotational constants in Gaussian files listing ****s

- environment.yml
- test/rmgpy/rmg/inputTest.py
The RMG-database continuous integration is failing because it can't find the right mkl library file: https://github.com/ReactionMechanismGenerator/RMG-database/issues/683
Rather than slap a bandaid over the problem (this PR: https://github.com/ReactionMechanismGenerator/RMG-database/pull/684), this PR tries to fix the versions conda requires.
From what I've seen, I believe it's Cantera that has the MKL dependency. It doesn't specify a version and then errors out when conda grabs something so old it can't find the right file name.
I added a version requirement for MKL to the RMG-Py environment file. I chose the version 2023.1.0 because it's what I have on my local Window's subsystem linux and I was worried that choosing the latest 2025 version would be too strict and cause the conda solver …
> require a more recent version of mkl for Cantera

- arkane/data/orca/freq_orca_5.0.4.log
- arkane/ess/orca.py
- test/arkane/ess/orcaTest.py
The `OrcaLog.load_conformers` required some adaptations to function with the orca version 5.0.4.
1) Made sure the frequencies are read correctly with the new format
2) Verified the LinearRotor object is created with no issues (the past implementation got an error:`TypeError: Cannot convert rmgpy.quantity.ArrayQuantity to rmgpy.quantity.ScalarQuantity` due to parsing an array instead of a single value)
3) Added a new frequencies log to ess/data with the 5.0.4 version
Added a test with the new Orca log.
> Orca parser fixup

- arkane/data/molpro/C5OH5_CCSD(T)_F12.out
- arkane/ess/molpro.py
- test/arkane/ess/molproTest.py
Some Molpro versions list the CCSD(T)-F12 energy as CCSD(T)-F12 (without the "a"), and Arkane is unable to not find the energy.
Relax the requirement to have "a" present in the energy line, it's enough to have both "CCSD(T)-F12" and "energy" on the same line.
A test was added
> Molpro f12a

- rmgpy/data/kinetics/depository.py
This PR fixes a small bug:
- `Reaction` expects `electrons` to be an integer, but the constructor for Depository reactions initializes `electrons` as `None`. This can lead to crashes (as was observed for the `RMG-website`: https://github.com/ReactionMechanismGenerator/RMG-website/issues/288)
- This PR simply changes the constructor to use a default value of `0` rather than `None` like other classes that inherit from `Reaction`.
> Fix bug in electrons initialization for depository reaction data

- .github/workflows/CI.yml
- Dockerfile
- install_rms.sh
Docker builds were failing due to several issues with Julia/RMS integration and environment configuration. The build process also lacked flexibility for testing different branches and had poor logging visibility in CI environments.
- **Fixed Docker build failures**: Biggest fixes are Install Julia, and compile RMG!
- **Improved environment variable handling**: Added explicit exports for Docker compatibility and set `PYTHON_JULIAPKG_PROJECT` to ensure Julia packages install in the correct location
- **Made RMS branch configurable**: Added `RMS_BRANCH` environment variable with `for_rmg` as default, allowing different RMS branches to be tested
- **Enhanced CI flexibility**: Runs Docker build (but not push) on Pull Requests.  Updated CI to pass current branch names to Docker build args …
> Docker build updates

- documentation/source/users/rmg/faq.rst
- documentation/source/users/rmg/installation/index.rst
The last Docker release was 2 years ago. Users might want to use Docker to get a more recent version. This PR updates the installation instructions to tell them how.
The last Conda binary was 4+ years ago, so I hid/removed the instructions recommending that installation method.
As noted in a commit message, we should re-visit these instructions once we've fixed conda builds.
I also found a link to the pdf of the 3.2.0 user guide, so included that link (for people following the instructions to install it), partially addressing #2809.
> A note about installing developer version from Docker.

- arkane/ess/molpro.py
- test/arkane/ess/molproTest.py
Fix the `CCSD(T)-F12a` and `CCSD(T)-F12b` energies parsing issue. More details can be found at https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2814.
Added two variables to identify which sections (i.e., `a` or `b`) are present and parsed the energy based on the same keyword: `CCSD(T)-F12`.
The test has been updated accordingly. Currently, only CCSD(T)-F12a is tested, as there are no CCSD(T)-F12 calculations performed using the 'vqz', 'v5z', 'v6z', 'v7z', or 'v8z' basis sets.
> Fix CCSD(T)-F12 energy parsing

- rmgpy/molecule/atomtype.py
- test/rmgpy/molecule/atomtypeTest.py
Minor fixes to `Li` atom type definitions, added tests
> Fix Li atom type defs

- documentation/source/users/rmg/installation/anacondaDeveloper.rst
- environment.yml
It is still possible to install conda package from the license-restricted official channels, even though we don't explicitly allow them.
This issue is related to and resolves #2843
Explicitly forbid default channels in environment and add developer instructions for further restrictions.
Just need to ensure the CI runs.
Please see if the news docs make sense.
> Explicitly Forbid Default `conda` Channels
