ReactionMechanismGenerator/RMG-Py

- documentation/source/users/rmg/installation/macos.rst
On the basis of our internal document which was most recently tested on a clean Yosemite (10.10) install.
> Updates to Mac OS X installation instructions

- databaseTest.py
This addresses https://github.com/GreenGroup/RMG-database/issues/65
- Makes sure that rule entries are in the correct order like the family's top template.  
- Makes sure that the top templates are defined with products and reactants named differently if the family is not its own reverse.
> New database unit tests

- documentation/Makefile
- documentation/source/_templates/index.html
- documentation/source/_templates/sourcelink.html
- documentation/source/users/cantherm/installation.rst
- documentation/source/users/measure/installation.rst
- documentation/source/users/rmg/installation/QMthermo.rst
- documentation/source/users/rmg/installation/linux.rst
- documentation/source/users/rmg/installation/macos.rst
- documentation/source/users/rmg/installation/windows.rst
- documentation/source/users/rmg/output.rst
Fixing references to GreenGroup on github to now be ReactionMechanismGenerator
> Fixing URLs in documentation

- rmgpy/cantherm/files/co.out
- rmgpy/cantherm/files/npropyl.out
- rmgpy/cantherm/qchem.py
- rmgpy/cantherm/qchemTest.py
- rmgpy/statmech/conformer.pyx
- rmgpy/statmech/conformerTest.py
Closes #390
I rebased the #390 commits and split them up, then noticed that the conformerTest wasn't testing anything. After I fixed that, I found that the thing it should have been testing was broken, so then I fixed that.  After all that, I figure that what started as code review, now needs reviewing...
> Enoch's fixes and some fixes

- rmgpy/rmg/input.py
Previously we divided each term by a different thing,
because we re-evaluated the sum within the loop!
> Fix initial mole fraction normalization!

- rmgpy/data/kinetics/library.py
Add markDuplicate option to checkForDuplicates to allow duplicate
reactions with mixed pressure dependent and non-pdep kinetics
to be marked as duplicate.
Still raises error when duplicates are both pdep or both non-pdep.
> Marking mixed pdep/non-pdep reactions as duplicate

- rmgpy/data/kinetics/library.py
Only marking mixed pdep/non-pdep reactions was found to be insufficient, so all duplicates will now be marked if markDuplicates is set to true. A warning is now issued when a set of reactions is marked.
This addresses differences in what CHEMKIN and RMG view as duplicate reactions. Currently, importChemkinLibrary.py in RMG-database is the only script to use markDuplicates=True.
> Change markDuplicates to mark all duplicates

- .gitignore
- rmgpy/chemkin.py
- rmgpy/data/base.py
- rmgpy/data/kinetics/common.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/library.py
- rmgpy/data/kinetics/rules.py
- rmgpy/data/thermo.py
- rmgpy/molecule/graph.pyx
- rmgpy/molecule/molecule.py
- rmgpy/qm/main.py
- rmgpy/qm/molecule.py
- rmgpy/rmg/model.py
These are commits that I have made while working on the chemkin file importer, but they effect other parts of RMG-Py, so should be reviewed independently and merged into master first.
> Various changes related to chemkin importing

- documentation/source/users/rmg/input.rst
- examples/rmg/commented/input.py
- rmgpy/rmg/input.py
Related to update to Create Input File page on RMG-website. Changes to writing of input files so it can write more options.
> Updates to input file saving

- .travis.yml
- Makefile
- examples/rmg/gri_mech_rxn_lib/RMG.bat
- examples/rmg/gri_mech_rxn_lib/RMG.sh
- examples/rmg/gri_mech_rxn_lib/input.py
- rmgpy/chemkin.py
This PR fixes #454 by specifying the key to sort an array of Molecule objects. It also provides a test case (make eg7) that fails without this patch. Finally, the last commit adds make eg7 to the travis build. It takes less than a minute to run.
> Fix bug454

- environment.yml
- meta.yaml
Trying to fix the travis build problems
> make conda env use RDKit v 2015.03.1

- .travis.yml
- rmgpy/data/base.py
- rmgpy/molecule/graph.pxd
- rmgpy/molecule/graph.pyx
- rmgpy/molecule/vf2.pyx
This pull request tries to fix the breaking of the database tests and the subgraph isomorphism check between groups.  (DO NOT PULL UNTIL WORKING)
Summary of changes:
- Add 'make test-database' to RMG-Py travis build to ensure safety
> Fix group algorithm that was breaking database tests

- documentation/source/users/rmg/installation/anacondaUser.rst
- rmgpy/__init__.py
- rmgpy/version.py
- setup.py
Centralize version even further so we don't have to rewrite it in setup.py
> Additional version control updates

- documentation/source/users/rmg/installation/anacondaUser.rst
- meta.yaml
Now working for OS X. Binaries uploaded to anaconda.org.
> Updated conda build and installation instructions

- rmgpy/quantity.pxd
- rmgpy/quantity.py
- rmgpy/quantityTest.py
> Veto temperature units other than Kelvin

- rmgpy/molecule/molecule.py
- rmgpy/reaction.py
The commit converts bytestring characters such as `\s` to their url equivalents, `%20`, etc...
A PR that makes RMG-Py compatible with django 1.8.5.
> use urllib to convert between url encoded strings and bytestrings

- rmgpy/molecule/parser.pxd
- rmgpy/molecule/parser.py
> Anticipate that OB is not installed

- rmgpy/solver/base.pxd
- rmgpy/solver/base.pyx
- rmgpy/solver/liquid.pyx
- rmgpy/solver/simple.pyx
This PR refactors the initialization of the reactor model implementations of (`rmgpy.solver.base.ReactionSystem`):
- converted a lot of local variables into instance attributes
- replaced some list comprehensions by generators that should consume less memory and be faster
- fixed the bug discussed in https://github.com/ReactionMechanismGenerator/RMG-Py/commit/1bca35a8dce8ef394f51b53f839d78a6df7712b9#commitcomment-14449968
- refactored a lot of duplicated code found in the implementation and moved it to their superclass
- split up the initialization of the reaction system into different methods that make it easier to understand what is happening
- added a lot of documentation to the variables
It does not touch the residual calculation, or the simulation part.
> Reaction System redesign

- rmgpy/rmg/rmgTest.py
this test file is for general rmg work flow tests. There are
two levels of tests currently: unit tests at function/methods
level and example tests at job level. This test file is a level
in between, tests involves multiple methods within the work flow
but no need to create a job to do that.
> added a test file for module rmg work flow

- rmgpy/rmg/input.py
cf. https://github.com/ReactionMechanismGenerator/RMG-Py/issues/495
Currently printed verbatim.
> print input file to log info at beginning of simulation

- Makefile
Makes it simpler to compare to older testing jobs.
> Rename to testing/egX folder when running 'make egX'

- setup.py
I have my eclipse set up to automatically build things this way.
Before you had to run setup.py twice as you could only do 
one set of extensions at a time.
> Modify setup.py so you can do eg. "build_ext main solver".

- scripts/checkModels.py
The idea is to centralize code with RMG-Py dependencies as much as possible, to avoid having to maintain multiple projects with python code.
> Move check models script from RMG-tests to RMG-Py scripts folder

- ipython/canteraSimulation.ipynb
- ipython/regressionTest.ipynb
- rmgpy/tools/canteraModel.py
- rmgpy/tools/observablesRegression.py
A few changes to the regression testing for RMG
> Fix regression

- .travis.yml
- rmgpy/qm/gaussianTest.py
- rmgpy/qm/mainTest.py
- rmgpy/qm/mopac.py
- rmgpy/qm/mopacTest.py
This should get Travis working again, whether or not you have the encrypted MOPAC license in your travis environment, and fixes a bunch of things in the MOPAC and Gaussian unit tests.
I'm going to try setting up a [mention-bot](https://github.com/facebook/mention-bot) to suggest code reviewers (though I have some ideas of my own).  We can turn it off (organization > settings > webhooks) if it's a pain.
> Fix QM unit tests and Travis build script

- rmgpy/molecule/atomtype.py
- rmgpy/molecule/atomtypeTest.py
- rmgpy/molecule/isomorphismTest.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
This PR includes
- adding a new method for identifying sulfur atom
- making `CS` atomType meaningful by defining the condition for `CS` to fix the issue #327 
- adding an unittest for testing `CS` gets properly assigned
> make proper `CS` atomType assignment to fix the issue#327

- rmgpy/data/solvation.py
fixed the error reported by the git issue #693 
https://github.com/ReactionMechanismGenerator/RMG-Py/issues/693
> fixed an indentation mistake

- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
…if the edge species are not going to be saved.
> Stops the markDuplicateReaction function from marking edge species duplicates

- rmgpy/data/kinetics/family.py
Needed for creating training reactions from reaction libraries script in `RMG-database/scripts/convertKineticsLibraryToTrainingReactions.ipynb`
> Migrate addLabelsToReaction function to rmgpy.data.kinetics.family.KineticsFamily

- rmgpy/chemkin.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/thermo.py
- rmgpy/tools/plot.py
A series of somewhat unrelated changes.  Will not be merging from this pull request but pushing directly to master if this passes travis tests.
> A set of miscellaneous fixes/changes

- ipython/data/parseSource/chem_annotated.inp
- ipython/data/parseSource/species_dictionary.txt
- ipython/findParameterSourcesAndAssignUncertainies.ipynb
- rmgpy/data/kinetics/database.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/data/kinetics/parsing_data/chem_annotated.inp
- rmgpy/data/kinetics/parsing_data/species_dictionary.txt
- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/tools/uncertainty.py
This is the beginnings of a new `Uncertainty` class within `rmgpy.tools.uncertainty`.  This class will add uncertainty analysis features to RMG.  This pull request is part one in a series of many pull requests to come to add both local and global uncertainty analysis features to RMG.  I decided to break it down into parts for easier review and clarity.
The following commits primarily parse the comments in a RMG-generated annotated chemkin file.  It then reloads the RMG database with verbose comments to extract all the original source objects from the database and store them in the `Uncertainty` class.  The idea is that by retracing the sources, we can find the weighted dependence on correlated parameters such as thermo groups and kinetic rate rules.  Also, it makes it easier in general to …
> Uncertainty Class Part I: assign uncertainties and extract original model sources

- meta.yaml
- rmgpy/data/thermo.py
This PR prepares for new release by fixing
- switch unnecessary thermo comments to debug mode to make clean log files
-  add `ffmpeg` to `meta.yml` so that binary build will pass unittests
> Fix thermo print and ffmpeg

- rmgpy/data/thermoTest.py
previously in `testAddPolyRingCorrectionThermoDataFromHeuristicUsingPyrene` we tried to get FIRST isomer with 2 aromatic rings for the
downstream testing, however it's not always generating the same
isomers at different OS platforms. This patch is making
the test more deterministic by testing ALL the isomers with 2 aromatic rings.
> fix polycyclic test non-deterministic behavior

- documentation/source/users/rmg/database/kinetics.rst
Add documentation about degeneracy for rules vs training
> Add documentation about degeneracy for rules vs training

- documentation/source/users/rmg/installation/dependencies.rst
- documentation/source/users/rmg/installation/faq.rst
- documentation/source/users/rmg/installation/index.rst
- documentation/source/users/rmg/installation/linux.rst
- documentation/source/users/rmg/installation/macos.rst
This PR is trying to address the issue #790 that requests to add FAQ section and installation guide without anaconda, so it include two following parts
- installation guides without anaconda on linux and macos, windows is not included since we know it's not working without anaconda
- faq page collecting common and rare issues on RMG installations
> RMG installation documentation update

- rmgpy/data/kinetics/family.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/resonance.py
This PR involves several error handling improvements:
- Improved AtomTypeError handling in updateAtomTypes (relates to issues #809 , #810)
- Improved error handling for wrong number of reverse rxns (relates to issue #807)
- Set logSpecies=False for updateAtomType calls in resonance.py
- Improved error handling of inability to apply atom actions (relates to issue #811)
> Improved error logging for debugging

- rmgpy/cantherm/pdep.py
> Modified to prevent user-specified PList from being overwritten

- rmgpy/rmg/model.py
Newly added `CoreEdgeReactionModel.indexSpeciesDict`, `ReactionSystem.speciesIndex` and `ReactionSystem.reactionIndex` are referring to edge species, which causes memory leak during pruning if not remove those references. This patch tries to remove all the new references to edge species so that memory reduction is effective again for pruning.
> update edge species removal for pruning to avoid memory leak

- documentation/source/users/rmg/modules/reduction.rst
- rmgpy/reduction/reduction.py
- rmgpy/reduction/reductionTest.py
RMG has a functioning (though I don't think optimal) method to reduce final mechanisms. 
I modified an error message to help me use the algorithm, and I wrote a 'how to use' in the documentation.
> Reduction Documentation

- rmgpy/rmg/main.py
At the end of an RMG run, save both chem.inp and chem_annotated.inp
as respective .cti files in a new `cantera` folder. See issue #737
> Generate Cantera files using ck2cti

- documentation/source/_static/rmg.css
- documentation/source/_templates/index.html
- documentation/source/latex-rmg.rst
- documentation/source/users/rmg/credits.rst
- documentation/source/users/rmg/database/modification.rst
- documentation/source/users/rmg/index.rst
- documentation/source/users/rmg/modules/index.rst
- documentation/source/users/rmg/modules/reduction.rst
- documentation/source/users/rmg/running.rst
Consolidated the user guide from the RMG Wiki into the RMG User Guide & added a table in the main page to explain to users what to do in a more visual format (since one person mentioned getting confused and tried installing RMG when he just needed to look up thermo chemistry). This addresses issue #840 .
> Documentation Consolidation

- documentation/source/users/rmg/liquids.rst
Small PR to make underline long enough to have correct rendering
> make underline long enough to have correct rendering

- documentation/source/_templates/sourcelink.html
This PR addresses issue #896 .
> Fix sidebar links to update documentation

- documentation/source/users/rmg/installation/anacondaDeveloper.rst
This PR addresses issue #897 .
> update environment name in documentation

- documentation/source/users/rmg/installation/anacondaDeveloperWindows.rst
- documentation/source/users/rmg/installation/anacondaUserWindows.rst
Update installation instructions to inform windows users how to run the command prompt as a administrator
> Update anacondaUserWindows.rst Command Prompt as Admin

- meta.yaml
This PR addresses the issue #922 .
> Solution for source files removal upon binary build completion

- rmgpy/data/kinetics/database.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/thermo.py
- rmgpy/molecule/draw.py
- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
- rmgpy/quantityTest.py
- rmgpy/reaction.py
- rmgpy/rmg/main.py
- rmgpy/solver/base.pyx
- rmgpy/species.py
- rmgpy/stats.py
@cfgoldsmith and I have been working on a version of RMG for heterogenous catalysis for the last ~18 months. During this process we made various small tweaks to RMG, minor optimizations, printing more debugging information, fixing docstrings, etc., that helped us along the way. 
I have cherry-picked (almost) all the commits that do not actually relate to heterogeneous catalysis into this "miscellaneous" pull request. Some changes may not be needed for exclusively gas-phase work, but I don't think any of them do it harm.  They should be reviewed independently of the RMG-Cat work, and merged into master.
We'll then try to merge the latest master back into RMG-cat -- which will surely be fun...
> Miscellaneous changes (from heterogeneous catalysis branch).

- rmgpy/data/thermoTest.py
Add unit tests for the following methods:
- combineCycles
- getCopyForOneRing
> Add Unit Tests to rmgpy/data/thermo.py

- rmgpy/molecule/generator.py
- rmgpy/molecule/generatorTest.py
- rmgpy/molecule/parser.py
- rmgpy/molecule/parserTest.py
This started out being just unit tests for SMILES, but I made some unit tests that were failing
(always the best kind) and then fixed them, so this PR now has bug fixes in as well as new unit tests.
> Test and fix SMILES generation and parsing

- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/data/rmg.py
- rmgpy/data/thermoTest.py
- rmgpy/test_data/testing_database/kinetics/families/H_Abstraction/groups.py
- rmgpy/test_data/testing_database/kinetics/families/H_Abstraction/rules.py
- rmgpy/test_data/testing_database/kinetics/families/H_Abstraction/training/reactions.py
- rmgpy/test_data/testing_database/kinetics/families/R_Addition_MultipleBond/groups.py
- rmgpy/test_data/testing_database/kinetics/families/R_Addition_MultipleBond/rules.py
- rmgpy/test_data/testing_database/kinetics/families/R_Addition_MultipleBond/training/reactions.py
- rmgpy/test_data/testing_database/kinetics/families/R_Recombination/groups.py
- rmgpy/test_data/testing_database/kinetics/families/R_Recombination/rules.py
- rmgpy/test_data/testing_database/kinetics/families/R_Recombination/training/reactions.py
This PR changes database loading in kineticsTest to be done once per class and thermoTest to be done once for the entire module. Warnings about multiple database instances no longer appear.
I was not able to change the loading in kineticsTest to be done once for the entire module because the classes now load different databases. TestReactionDegeneracy loads the actual RMG-database, while TestKineticsParsing loads a toy database located in RMG-Py.
I've also included an old fix for some work-in-progress unit tests in thermoTest so that they work properly, although they still fail. See #887 for more details.
> Fix database loading in RMG-Py unit tests

- rmgpy/molecule/adjlist.py
- rmgpy/molecule/adjlistTest.py
This PR relates to https://github.com/ReactionMechanismGenerator/RMG-Py/issues/965
The multiplicity check was elaborated for up to 4 radicals in a molecule.
> Elaborating the multiplicity check for nRad = 3 or 4

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/groups.py
- rmgpy/data/kinetics/rules.py
- rmgpy/rmg/model.py
It's helpful to put in the docstring a description of what is returned by a method,
because many IDEs have a UI that shows you the docstring when you hover over
a call to that method. Some bits of code rely on, for example, whether the third
element of a tuple is None, and it's handy to know what that is.
Also increased some detail in the verbose kinetics comments.
> Improved some docstrings, comments, messages.

- rmgpy/data/kinetics/kineticsTest.py
fixes and improvements to testFilterReactions
now test filter reactions works and fully checks whether every reaction considered has been properly left in the list or filtered out
fixes issue #983
> fixes and improvements to testFilterReactions

- rmgpy/rmg/mainTest.py
tested that RMG.execute returns a model with more species and
reactions than originally input, and tested that adding cantera
file works and raises exceptions as expected
> added tests for rmgpy.rmg.main

- scripts/diffModels.py
The docstring was not finished previously. Complete the docstring in a
similar fashion to the documentation on the website.
> Add the remaining part of the docstring for diffModels.py

- rmgpy/tools/extractInfoFromckcsv.py
This PR makes species string parsing from ckcsv more robust. Previously the parsing will fail if species name has underscore in it.
> mechanism_analyzer fails to parse species name with underscore

- rmgpy/data/base.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/data/kinetics/kineticsTest.py
- rmgpy/data/solvation.py
- rmgpy/molecule/adjlist.py
- rmgpy/molecule/adjlistTest.py
- rmgpy/test_data/parsing_data/chem_annotated.inp
- rmgpy/test_data/testing_database/kinetics/families/Disproportionation/groups.py
- rmgpy/test_data/testing_database/kinetics/families/Disproportionation/rules.py
- rmgpy/test_data/testing_database/kinetics/families/Disproportionation/training/reactions.py
- rmgpy/test_data/testing_database/kinetics/families/H_Abstraction/groups.py
- rmgpy/test_data/testing_database/kinetics/families/H_Abstraction/rules.py
- rmgpy/test_data/testing_database/kinetics/families/R_Addition_MultipleBond/groups.py
- rmgpy/test_data/testing_database/kinetics/families/R_Addition_MultipleBond/rules.py
- rmgpy/test_data/testing_database/kinetics/families/R_Addition_MultipleBond/training/reactions.py
- rmgpy/test_data/testing_database/kinetics/families/R_Recombination/groups.py
- rmgpy/test_data/testing_database/kinetics/families/R_Recombination/rules.py
- rmgpy/test_data/testing_database/kinetics/families/intra_H_migration/groups.py
- rmgpy/test_data/testing_database/kinetics/families/intra_H_migration/rules.py
- rmgpy/test_data/testing_database/kinetics/families/intra_H_migration/training/reactions.py
- scripts/machineWriteDatabase.py
This PR has several bug fixes and additions to our saveEntry methods. The motivating change was renumbering the indexes when machine writing the database.
> Entry saving

- rmgpy/reduction/main.py
Add control of logging level from the command line.
> Add argparse function to model reduction script for command line control

- meta.yaml
to be consistent with env_linux.txt
> updated meta.yaml cython version

- rmg.py
> Add indexing to args.output_directory to return a string

- Makefile
- examples/rmg/superminimal/input.py
While there are many jokes about impatience that could be made about this pull request, sometimes in the middle of rebasing you want to know that you haven't broken anything major and in those cases it doesn't really make sense to start the entire minimal example especially since it can now take up to 8 minutes to run see #1079 .  This example based on H2 oxidation runs in ~20 sec.  Other people who wish to remain anonymous referred to this as the "ain't nobody got time for that" pull request.  
Can be run from the makefile with "make eg0"
> Superminimal example

- rmg.py
- rmgpy/rmg/main.py
Walltime flag was implemented in rmg.py, but was not utilized in
rmgpy.rmg.main.py
> Add code to set walltime from commandline flag

- rmgpy/reactionTest.py
This pull request adds unit test for fixBarrierHeight.  Importance discussed in #1086.
> added unit test for Reaction.fixBarrierHeight

- rmgpy/kinetics/diffusionLimited.py
- rmgpy/kinetics/diffusionLimitedTest.py
These two tests are for the `getEffectiveRate()` method in `rmgpy/kinetics/diffusionLimited.py`. Some associated changes were made in the module itself.
> Unit tests for the diffusion limited module.

- documentation/source/users/rmg/database/kinetics.rst
Replaced Ea with E0
Elaborated the E0 and alpha descriptions
> Corrected ArrheniusEP documentation

- documentation/source/users/rmg/input.rst
Just moved things around a little, to start the section with an example block then explain the options.
Also consolidated the Chebyshev instructions.
> Reorganized the PDep documentation a bit.

- rmgpy/statmech/translation.pyx
Fixes the issue with the new cython version in #1109.
> cimport statement tweak

- rmgpy/solver/base.pyx
Got rid of the undefined ind variable and replaced it with the proper index.
> Fix surface naming mistake

- rmgpy/rmg/main.py
Fixes #1125  by setting the right arguments and output parameters for simulate.
> fix sensitivity analysis

- rmgpy/data/kinetics/family.py
- rmgpy/rmg/model.py
- rmgpy/rmg/react.py
- rmgpy/test_data/testing_database/solvation/groups/abraham.py
- rmgpy/test_data/testing_database/solvation/groups/nonacentered.py
- rmgpy/test_data/testing_database/solvation/groups/radical.py
- rmgpy/test_data/testing_database/solvation/libraries/solute.py
- rmgpy/test_data/testing_database/solvation/libraries/solvent.py
This PR has some small code improvements. I don't think that anything is particularly controversial. The solvation test database allows for us to use the testing database on unittests with liquids (so we don't have to load the entire database). 
For the reviewer:
make sure unittests pass and you sort of understand the commits. Let me know if you have any questions.
> Small code cleanup

- .travis.yml
This PR tries to have more transparent coverage report for each future pull request.
Codecov will automatically enter PR conversation to give coverage report.
> add codecov to report coverage change

- rmgpy/rmg/react.py
This was polluting my console (and jupyter notebook) in a separate app.
It may not be needed at all (having it will just slow us down a little) but probably not costly to leave it.
> Convert a print statement to a logging.debug

- rmgpy/rmg/main.py
A fundamental problem with using seed mechanisms to restart a run is that an input seed mechanism could be treated one of two ways
1) you don't react them -> you are missing lots of species from the edge that should be there
2) you react them -> you haven't had time to prune so you risk crashing your simulation or being forced to remove lots of edge species that might not have otherwise been pruned
Currently we only treat them as done in (1).  
@amarkpayne suggested that we just save the edge as well as core instead of having to manage all of this.  
This pull request generates an additional seed mechanism named name+"_edge" with an edge thermo library and an edge reaction library.  
Now when effectively restarting a run you can add the core seed mechanism as a seed mechanism and the edge …
> generate edge seeds

- rmg.py
- rmgpy/rmg/rmgTest.py
- rmgpy/tools/generate_reactions.py
Add test for parseCommandLineArguments for proper default values
> Add Unit Test for rmg.py

- rmgpy/__init__.py
- rmgpy/cantherm/gaussian.py
- rmgpy/cantherm/qchem.py
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/library.py
- rmgpy/rmg/main.py
- rmgpy/species.py
Remove print statements in main.py and library.py that would otherwise print regardless of logging level.
> Convert print statements to logging statements

- ipython/generateReactions.ipynb
- rmg.py
- rmgpy/rmg/rmgTest.py
- rmgpy/tools/generate_reactions.py
- rmgpy/tools/testGenerateReactions.py
- scripts/generateReactions.py
- Move lines that modify parsed args into the arg parse module
- Add unit tests for non-default values of command line arguments
- create `main` function for rmg.py
> Restructure rmg.py

- README.md
Small update to the README:
- Consolidate badges at the top of the document for visibility
- Add more badges!
- Minor changes to content
Notes:
- I removed the section on the current version (replaced with badge) so that we don't need to update the file with each new version.
- I removed the section on continuous integration, since I didn't feel like it was particularly important explicitly state that we have it.
> More badges in README and other improvements

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/familyTest.py
- rmgpy/test_data/testing_database/kinetics/families/1,2_shiftC/groups.py
- rmgpy/test_data/testing_database/kinetics/families/1,2_shiftC/rules.py
- rmgpy/test_data/testing_database/kinetics/families/1,2_shiftC/training/reactions.py
- rmgpy/test_data/testing_database/kinetics/families/6_membered_central_C-C_shift/groups.py
- rmgpy/test_data/testing_database/kinetics/families/6_membered_central_C-C_shift/rules.py
- rmgpy/test_data/testing_database/kinetics/families/6_membered_central_C-C_shift/training/reactions.py
- rmgpy/test_data/testing_database/kinetics/families/Intra_R_Add_Exo_scission/groups.py
- rmgpy/test_data/testing_database/kinetics/families/Intra_R_Add_Exo_scission/rules.py
- rmgpy/test_data/testing_database/kinetics/families/Intra_R_Add_Exo_scission/training/reactions.py
- rmgpy/test_data/testing_database/kinetics/families/Intra_ene_reaction/groups.py
- rmgpy/test_data/testing_database/kinetics/families/Intra_ene_reaction/rules.py
- rmgpy/test_data/testing_database/kinetics/families/Intra_ene_reaction/training/reactions.py
- rmgpy/test_data/testing_database/kinetics/families/intra_substitutionS_isomerization/groups.py
- rmgpy/test_data/testing_database/kinetics/families/intra_substitutionS_isomerization/rules.py
- rmgpy/test_data/testing_database/kinetics/families/intra_substitutionS_isomerization/training/reactions.py
Very small PR. Just added 5 new reaction families that are their own reverse to the appropriate hard-coded section of RMG-Py. Companion to Aromatics Updates PR's on Database.
> Aromatics updates

- rmgpy/chemkin.py
> Add `Ea raised from` to list of kinetics comment line breaks

- rmgpy/cantherm/statmech.py
This PR is a copy of #1186, but updated to master branch.
> Updated BAC for CBS-QB3 according to Paraskevas2013

- rmgpy/pdep/network.py
to capture memory errors generating this array
addresses #1215
> Included collFreq in the try block (pdep/network.py)

- rmgpy/molecule/draw.py
> Modify O2 special case in MoleculeDrawer

- examples/cantherm/species/C2H4/input.py
- examples/cantherm/species/C2H5/input.py
- examples/cantherm/species/C2H6/input.py
- examples/cantherm/species/H/input.py
to match the actual calculation modelChemistry
Addresses #371
> Corrected modelChemistry in Cantherm species examples

- rmgpy/pdep/network.py
Fixes issue #1300.  Improves handling of arrays in network.__repr__ method and fixes eg5.
> fix network.__repr__

- documentation/source/users/rmg/modules/sensitivity.rst
- examples/sensitivity/run.sh
This is just a quick fix to #1284
> Fix sensitivity example

- documentation/source/reference/molecule/converter.rst
- documentation/source/reference/molecule/generator.rst
- documentation/source/reference/molecule/index.rst
- documentation/source/reference/molecule/parser.rst
- documentation/source/reference/molecule/translator.rst
molecule.generator and molecule.parser have become molecule.converter and molecule.translator
> Update Documentation for rmgpy.molecule

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
To give guidelines when submitting GitHub issues
> Create issue templates

- documentation/source/users/rmg/kinetics.rst
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/rules.py
- rmgpy/data/reference.py
- rmgpy/test_data/testing_database/kinetics/families/intra_H_migration/groups.py
This makes some improvements to database write.  Redefines ranks to make them more specific identifiers of accuracy and changes the rank we give averaged kinetics accordingly.
> New Rank Definitions

- documentation/source/users/rmg/input.rst
Previously the options for kineticsDepositories were not documented
added description of options for input file
ensure grammar is correct
N/A
> Add description of kinetics depositories to documentation

- rmgpy/cantherm/qchem.py
While working with QChem for thermo calculations I notice that arkane(adjective) Arkane/Cantherm was not loading the atoms and geometries from a geometry log file.
This commit corrects that, at least for the case I was looking at, and raises an error if, after loading the geometry the atom vector remains empty.
> Corrects a geometry reading error for QChem files

- documentation/source/users/rmg/releaseNotes.rst
- rmgpy/version.py
This merges the version number increment and release notes back into master.
> RMG-Py v2.2.1 changes

- rmgpy/data/kinetics/familyTest.py
testSaveFamily previously would not remove files if an
error was raised in family.save. This commit ensures
the files are removed even if an exception is raise
moved try statement
travis testing
ensure tests pass
> Ensure testSaveFamily removes all created files

- rmgpy/cantherm/input.py
Currently we attempt to load the thermo data for a species if no thermo was specified and the structure is given. However, we shouldn't do that in two cases:
- If the species has a path directing to a species.py file (or YAML soon).
- If the species is a bath gas in a pdep job, and the database isn't loaded
Cantherm now first checks for a species path before attempting to load it's thermo from the db. It will also output a warning if the database isn't loaded (and no thermo is given) instead of cruching.
The acetyl+O2 network example crashes on master, and should complete on this branch
> Bug fix: Loading a species' thermo from the database in Cantherm

- rmgpy/cantherm/kinetics.py
- rmgpy/cantherm/sensitivity.py
- rmgpy/cantherm/thermo.py
Fixes #1442
This problem was observed in Windows, but likely affects every OS.
> Create Cantherm Plot Directory in Output Directory Location

- rmgpy/cantherm/pdep.py
> BugFix: Providing an exception to raise in Cantherm's pdep.py

- documentation/source/users/cantherm/input.rst
- rmgpy/cantherm/statmech.py
> Added S atom corrections at CCSD(T)-F12/aug-cc-pVnZ to Cantherm's statmech

- rmgpy/cantherm/main.py
- rmgpy/cantherm/statmech.py
This PR outputs a `supporting_information.csv` file with rotational constants and unscaled frequencies (inc. imaginary frequency if a TS) for all statmech jobs. This is useful when preparing manuscripts using Cantherm's output.
**Review:** 
Run a Cantherm job using statmech (e.g., the C2H4 example). Also try this out for a reaction / network where multiple species are outputted into the same supporting info file (inc. TS), e.g., the CH3OH+HCO example.
I think it is OK to always save the file to the output directory, but let me know if you think this should be activated with a flag.
Tagging @sarahkha as a potential first user
> Output a supporting information file in Cantherm

- documentation/source/users/cantherm/input.rst
- documentation/source/users/cantherm/input_pdep.rst
- examples/cantherm/networks/acetyl+O2/input.py
- examples/cantherm/networks/n-butanol/input.py
- rmgpy/cantherm/input.py
- rmgpy/cantherm/kinetics.py
- rmgpy/cantherm/molpro.py
- rmgpy/cantherm/pdep.py
- rmgpy/cantherm/statmech.py
- rmgpy/cantherm/thermo.py
- rmgpy/chemkin.pyx
- rmgpy/data/rmg.py
- rmgpy/data/statmech.py
- rmgpy/data/statmechfit.py
- rmgpy/exceptions.py
- rmgpy/pdep/collision.pyx
- rmgpy/pdep/configuration.pyx
- rmgpy/pdep/msc.pyx
- rmgpy/pdep/network.py
- rmgpy/pdep/reaction.pyx
- rmgpy/species.py
- rmgpy/statmech/conformer.pyx
Cantherm's power is not being fully utilized. For example, it is integrated into RMG, but lacks the ability to use estimation methods in RMG. Many of the hindrances are just hardcoded extraneous print methods, which cause the program to fail even when it is working properly.
This PR allows cantherm to do much more than it was originally written for. For example, with this PR you can run a pressure dependent job using the inverse laplace transform for barrierless reactions... or you can input the NASA polynomials instead of a quantum file if the quantum job is not available. 
Commits in this pull request mostly fall into a few categories:
1. They prevent the job from dying due to hardcoded extraneous functionality (like the printing of a table of rates into the comment of the output.py …
> Make cantherm more flexible

- arkane/statmech.py
Solves #1494 
We currently use an atom symbol dictionary in Arkane's statmech.py to determine which elements are supported. However, this determination could be made from the atom_hf correction dictionary directly, and atom symbols by atom numbers could be retrieved from the already implemented `symbol_by_number` dictionary in common.py.
Consequently, this PR makes it more intuitive to add new supported elements to Arkane by simply adding their experimental heat of formation into statmech.py.
> Modified the atom-symbol dictionary used in Arkane's statmech

- documentation/source/users/rmg/input.rst
- examples/rmg/MR_test/input.py
- examples/rmg/commented/input.py
The path to the `recommended.py` file documented in several places is incorrect.
Change the path from `RMG-Database/input/families/recommended.py` to `RMG-Database/input/kinetics/families/recommended.py`
Not applicable.
> Fix path to recommended.py

- rmgpy/data/thermoTest.py
The Thermo Central Database is currently offline. The future role of that framework is in need of discussion, but in the meantime, skip these unit tests to allow other development to continue.
Skip TCD unit tests directly instead of checking that RMG server is up.
Check that Travis passes.
> Skip TCD unit tests

- arkane/qchem.py
- arkane/qchemTest.py
- arkane/statmech.py
Added another parsing phrase in Arkane for QChem log files.
Parsing a line in the following format:
` Total energy in the final basis set = -328.6420045839`
Also some pythonic modifications to this block.
An input file for example and review of the code is attached.
[output.txt](https://github.com/ReactionMechanismGenerator/RMG-Py/files/2660465/output.txt)
> Added another parsing phrase to QChem loadEnergy()

- rmgpy/molecule/group.pxd
- rmgpy/molecule/group.py
- rmgpy/statmech/conformer.pyx
Added `isNitrogen()` and `isCarbon()` methods to `GroupAtom`
Also, I happened to take a look at `getPrincipalMomentsOfInertia` in conformer and couldn't resist making some minor changes.
> Added GroupAtom isNitrogen() and isCarbon() methods 

- rmgpy/data/thermo.py
A fix related to RMG-website: add support to thermo search for surface species.
In the getAllThermoData function, gas phase species and surface species are distinguished, so that they can be handled by different group additivity method.
A test has been performed on RMG-website/dev locally where no error showed. A related more robust and comprehensive test will be build in RMG-website package.
> Update thermo search of surface species on RMG-website

- setup.py
This commit adds isotopes script to setup.py so that it is included in the
rmg package installed by users.
This can be done by generating the package
double check to make sure the syntax is correct (and the file exists in base RMG package)
> Add isotopes script to package

- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/rules.py
I deleted this assertion error because it made it so you could not have training reactions that were sticking coefficients.
> Surface training reactions fixup

- arkane/statmech.py
Added a frequency scaling factor for APFD/def2TZVP to Arkane.
Can anyone take a quick look/review? Should be trivial. Thanks!
> Added a freq scale factor for apfd/def2tzvp

- rmgpy/chemkin.pyx
- rmgpy/rmg/main.py
Minor changes in treating collision rate violating reactions:
- Style changes in reporting collision violating reactions
- Remove redundant `\` in collider re expression
> Minor changes in treating collision rate violating reactions:

- arkane/sensitivity.py
- rmgpy/rmg/input.py
- rmgpy/rmg/main.py
We'd like to be able to automate model refinement using electronic structure calculations, and couple it to model generation.
This PR adds the fist stage of automatically calculating species thermodynamic properties by calling RMG and [ARC ](https://github.com/ReactionMechanismGenerator/ARC) iteratively. Various species selection criteria were implemented.
- Crucial dependencies for ARC were added to the RMG environment (ase, paramico, py3dmol).
- Some minor modifications to RMG's API were made.
- The tandem tool was added as a root module in RMG-Py, since it imports from `rmgpy`.
- SA in Arkane will now also output the results in a YAML format (otherwise we would have needed to write a parser for the current txt output)
Run T3 by typing, e.g.:
```
python $rmgpy/rmg.py input.py -t3 …
```
> T3 related modifications

- arkane/util.py
- arkane/utilTest.py
Currently Orca log files are identified by Arkane as Gaussian log files, since the phrase "gaussian" appears in Orca's log files before "orca" (in the contributions sections at the top).
e.g.:
```
*****************
* O   R   C   A *
*****************
--- An Ab Initio, DFT and Semiempirical electronic structure package ---
#######################################################
#######################################################
Program Version 4.2.0 -  RELEASE  -
With contributions from (in alphabetic order):
Daniel Aravena         : Magnetic Suceptibility
Michael Atanasov       : Ab Initio Ligand Field Theory (pilot matlab implementation)
Alexander A. Auer      : GIAO ZORA, VPT2
Dmitry Ganyushin       : Spin-Orbit,Spin-Spin,Magnetic field MRCI
Miquel Garcia          : C-PCM Hessian, …
```
> BugFix: Corrected determine_qm_software for Orca

- arkane/statmech.py
Add frequency scaling factor for wb97xd/def2svp
> Add frequency scaling factor for wb97xd/def2svp

- documentation/source/users/rmg/input.rst
- documentation/source/users/rmg/running.rst
Updates the RMG documentation to include updates from the merged `profiler_tools` branch, PR #1789. I look forward to your feedback.
> Profiler tools doc

- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1942
> added "critical_distance_factor" parameter to "from_xyz"

- documentation/source/users/rmg/liquids.rst
One of the paper that is referenced in Liquid Phase Systems section of the documentation has been published, and its reference information needs to updated in the documentation.
I updated the one of the references in the documentation. I also fixed a minor typo (AICHE -> AIChE) 
No test is needed.
> Update the reference info on the documentation

- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/molecule/molecule.py
Issue #2003 identifies that  the gas-phase precursor of a bidentate adsorbate is currently obtained by breaking both bonds to the surface, leaving a radical at each binding atom. This leads to a gas phase estimate of the biradical, instead of the closed shell species with a higher bond order. 
When fixing that issue, I created some unit tests for adsorbate thermo, which revealed another problem: When CH3X was removed from the surface to make CH3j, it was not matching the CH3j species in the gas phase thermo library. The issue was the atom's connectivity values had not been reset by the call to Molecule.update().
To fix this I
- explicitly call update_connectivity_values() after removing the adsorbate from the surface
- fix the docstrings on .update() so it is no longer misleading about …
> Fixes to adsorption thermochemistry estimation, including bidentate.

- rmgpy/data/kinetics/database.py
- rmgpy/data/thermo.py
- rmgpy/data/thermoTest.py
- rmgpy/rmg/input.py
- rmgpy/rmg/model.py
As described in #2030, the error messages and strack traces are not always super helpful in finding and fixing the cause of the problem. This PR attempts to add a few more diagnostics.
The main approach is to catch an exception as it passes through a section of code that knows something helpful, log a diagnostic error message, and then re-raise the exception so that it carries on as before. 
For example, if you get a bad atom type when trying to estimate adsorption thermo for a species that was included in a reaction library, then it's helpful to know which species, which reaction library, as well as which atom.  But the atom typing code doesn't know this info when it raises the exception, so we have to catch and re-raise it a few times. 
I ran the unit tests. Then added a unit test that …
> Improve debugging error messages

- environment.yml
Resolving the conda dependency tree takes a long time (>800 sec on Travis).
This is an attempt to speed up the solution by removing some channel options
and specifying which packages come from RMG channel.
The specifications were initially based on a recent travis run.
Then I compared with a recent MacOS solution, and loosened the specifications to be compatible with both.
Other OS / platforms have not been tested.  (I'm not sure what others to test and how?)
Feel free to contribute commits to this PR
Runs on travis.
Runs on my mac.
To test it:
```
conda env create --name rmg3test --file environment.yml
```
See if it can solve and install everything. 
(And then check RMG builds and runs)
> Constrain conda channels.

- rmgpy/data/transport.py
- rmgpy/data/transportTest.py
This PR replaces https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2098
(have to make a new pull request to remove the hyphen from the branch name)
added halogen corrections to boiling point when estimating critical properties using group additivity
source:https://doi.org/10.1021/ie00008a029
> Halogens transport

- rmgpy/yml.py
This PR fixes a bug where RMG can output mechanisms where two species have the same name and properly handles surface reactor phases.
> Allow RMS to output surface mechanisms and bugfixes

- rmgpy/chemkin.pyx
- rmgpy/data/kinetics/family.py
- rmgpy/data/kinetics/rules.py
- rmgpy/kinetics/arrhenius.pyx
- rmgpy/kinetics/uncertainties.pxd
- rmgpy/kinetics/uncertainties.pyx
- rmgpy/molecule/group.py
This PR enables the estimator to ascend the tree when uncertainties are sufficiently high at lower nodes in the tree and makes some major improvements to extension generation and the cascade algorithm. It also fixes a couple bugs in parallelization.
> Automatic Tree Generation part 5

- rmgpy/data/kinetics/family.py
Fix spc doesn't have metal attribute error
Changed `r.metal` to `metal`. Also changed dummy variable `r` to `rev_react` for a meaningful name & consistency.
Species doesn't have metal attribute error is gone after the changes
> Fix spc doesn't have metal attribute error

- rmgpy/data/kinetics/family.py
- rmgpy/molecule/group.pxd
- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
We recently discovered molecules in our models that have multiple bonds to the surface through a single adatom
https://rmg.mit.edu/database/molecule/1%20O%20u0%20p2%20c0%20%7B2%2CS%7D%20%7B3%2CS%7D%0A2%20X%20u0%20p0%20c0%20%7B1%2CS%7D%0A3%20X%20u0%20p0%20c0%20%7B1%2CS%7D%0A
I don't think we should be making these molecules.  
added `is_bonded_to_surface` Atom and GroupAtom methods and modified the `_apply` ReactionRecipe function so that it raises an `InvalidActionError` if trying to form a surface bond to an atom already bonded to the surface
Not tested yet
see if these molecules are still in models
> Forming surface bonds

- rmgpy/reactionTest.py
- rmgpy/rmg/model.py
- rmgpy/solver/base.pxd
- rmgpy/solver/liquid.pyx
- rmgpy/solver/mbSampled.pyx
- rmgpy/solver/simple.pyx
- rmgpy/solver/surface.pyx
- rmgpy/solver/surfaceTest.py
A few miscellaneous fixes I made while doing other things, that are unrelated to those things, so are here in their own pull request. Hopefully a quick merge.
* fix some unit test details
* change some Cython declarations of things used for array indices from `int` to `Py_ssize_t` (will require a rebuild)
* make a rarely-seen exception error message more informative for debugging
* remove a duplicated import statement.
I have tested the commits in isolation, and will let the continuous integration suite test this pull request.
Shouldn't be hard - not a lot of big changes here.  Maybe someone newish to reviewing wants to take a turn.
> Some miscellaneous fixes

- rmgpy/molecule/molecule.py
- rmgpy/qm/mopac.py
@12Chao came across a few bugs when building models using Mopac. This tries to handle the errors better.
In one case, just trying the next geometry. In another, just reporting the molecule that caused the problem.
So far, I have run unit tests.
I'm hoping @12Chao will try it out on the input files that caused the problems.
> Making Mopac calculations more robust

- documentation/source/users/rmg/installation/anacondaDeveloper.rst
Added another Linux OS to the documentation.
> change to the documentation, added openSUSE installation instructions

- README.md
One of the reviewers of my manuscript asked us to add the licensing information to somewhere that is easier to find. So I added the licensing information to the README.md file, as well as the link to the resource and references and the disclaimer.
The 'License Information' and 'Disclaimer' parts are directly obtained from the file headers of RMG-Py. 
The 'Resources and References' part directs to the RMG-website resources page. I also added a line saying `Please at least cite our latest publication on Reaction Mechanism Generator v3.0 and other relevant publications when publishing the results using our software` to make sure that the RMG users cite some RMG-related publications.
Please let me know if anything should be changed or worded differently!
N/A
N/A
> Add licensing information to the README file

- rmgpy/data/thermo.py
- rmgpy/molecule/molecule.pxd
- rmgpy/molecule/molecule.py
- rmgpy/molecule/moleculeTest.py
We do not apply long distance interactions if one atom is in cycle and the other atom is not.  This is a problem for cyclic halogenated molecule as leaving out this interaction will cause an underestimation of the enthalpy.  For example, we should include a CF3-C(F) interaction term for this molecule:
- Added `is_bonded_to_halogen` Atom method and test
- Added `is_bonded_to_surface` test (which we were missing)
- apply noncyclic long distance correction is atom2 is bonded to a halogen (regardless if it is in cycle or not)
added unit test for `is_bonded_to_halogen` and tested gav thermo for cyclic halogens.
With PR:
Without PR:
https://rmg.mit.edu/database/thermo/molecule/1%20%20O%20u0%20p2%20c0%20%7B2,D%7D%0A2%20%20C%20u0%20p0%20c0%20%7B1,D%7D%20%7B3,S%7D%20%7B10,S%7D%0A3%20%20O%20u0%20p2% …
> halogen long_distance_noncyclic in cycle interaction

- rmgpy/data/thermoTest.py
Update missing group test now that data is added for the original missing group
Change the testing species and the missing group
> Update missing group test now that data is added for the original missing group

- rmgpy/pdep/configuration.pyx
Small bugfix should fix #2256 in theory.
> give integer num of points to linspace

- rmgpy/rmg/main.py
- rmgpy/rmg/model.py
- rmgpy/rmg/reactors.py
RMG jobs failed when running with pyrms simulators.
Ensure species and reactions are handled correctly for phase systems, especially for seed mechanism.
Local jobs ran successfully
Run a job using pyrms simulator with seed mechanism
> Handle core/edge species/reactions for phase system correctly

- documentation/source/users/rmg/installation/anacondaDeveloper.rst
Hey all,
just added a line in the docs to remind users to activate the environment before making the tests
> reminder to activate env before making tests

- arkane/explorer.py
- arkane/input.py
- arkane/pdep.py
- arkane/pdepTest.py
- arkane/sensitivity.py
- examples/arkane/networks/acetyl+O2/input.py
- rmgpy/pdep/cse.pyx
- rmgpy/pdep/me.pyx
- rmgpy/pdep/network.py
- rmgpy/pdep/sls.py
- rmgpy/rmg/pdep.py
This PR adds the simulation least squares methods and the Georgievskii et al. 2013 CSE variant to Arkane and makes a number of improvements to pdep sensitivity analysis and the explorer tool.
> Pressure Dependence Improvements

- examples/rmg/nox_transitory_edge/input.py
- rmgpy/rmg/input.py
- rmgpy/rmg/reactors.py
- rmgpy/rmg/settings.py
Adds transitory edge analysis species selection algorithm to RMG. RMS dual PR with https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/pull/196.
> Transitory Edge Analysis

- .github/workflows/docs.yml
Documentation was failing after PR #2377. "uses" needed to be specified to use miniconda.
Changed "uses" so it uses miniconda. 
run the documentation tests, along with the other CI tests.
> update doc workflow, was failing bc 'uses' was incorrect

- documentation/source/users/rmg/input.rst
- rmgpy/rmg/input.py
- rmgpy/rmg/reactors.py
- rmgpy/rmg/settings.py
This PR adds the radical flux tolerance to RMG. It is dependent on: https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/pull/200.
> Add radical flux tolerance

- rmgpy/rmg/reactors.py
Adapt `to_rms` function to recent changes in the attribute of RMS's Species and Reaction struct. See https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/pull/200/commits/0bcddc0f8f1930ce5bfa42b0e35033e0ec5044c9 and https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl/pull/200/commits/6f7063075941e36abb1983a8cb5fc99f60cf1c8d.
Input RMG Species's thermo comment to RMS's Species comment, and input RMG Reaction's kinetics comment to RMS's Reaction comment.
> add comment as input to RMS reaction and species object

- rmgpy/rmg/reactors.py
RMS uses `name` instead of `label`.
> Should be name, not label

- .github/workflows/CI.yml
Mistakenly included experimental local changes in previous PR
> accidentally used changes from an experimental local branch, revert

- .github/workflows/CI.yml
- Dockerfile
- documentation/source/users/rmg/installation/index.rst
Primary end user deployment has moved to Docker.
This PR updates the documentation, adds the Dockerfile, and adds a step in the CI to automatically rebuild a 'nightly' image.
If someone could try out the installation instructions as added here that would be good.
The CI step that pushes the docker container will not run until we actually merge into main, which is intended. If it breaks for some reason I will fix it in a follow up PR.
> [Move to Docker]: Add Dockerfile, update installation instructions, add automatic image builds to CI

- .github/workflows/CI.yml
- .github/workflows/docs.yml
This PR adds a number of small changes to the `CI.yml` that will allow execution of the constant integration tests on forks of this repository.
> [Regression Testing]: Small changes to `CI.yml` to allow testing on Forks

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- documentation/Makefile
- documentation/source/users/arkane/credits.rst
- documentation/source/users/rmg/input.rst
- documentation/source/users/rmg/installation/linux.rst
- documentation/source/users/rmg/installation/macos.rst
- documentation/source/users/rmg/liquids.rst
- documentation/source/users/rmg/thermo.rst
- rmgpy/data/kinetics/family.py
- rmgpy/molecule/molecule.py
- rmgpy/pdep/collision.pyx
- rmgpy/thermo/thermodata.pyx
The Continuous Integration (CI) tests of the documentation had not been catching errors, so some errors had crept in.
First this PR fixes the CI so errors are reported as failures.
Once that's was tested and demonstrated, I then fixed the errors.
Now the documentation is tested and passes.
This PR also removes the CI job that consolidates the results of linux and mac, because it's not needed.
The CI testing of documentation is tested by having it find some errors - for example https://github.com/ReactionMechanismGenerator/RMG-Py/actions/runs/5076217899/jobs/9118184824?pr=2448
The documentation is then tested by having it pass the new CI tests.
I also looked at the HTML that was being generated to check it looks good.
> Fix documentation errors (and CI testing)

- Dockerfile
This Dockerfile has been rewritten to use the micromamba image as a base and then during the build, certain packages (apt sources, packages and the downloaded packages for rmg_env) are removed as they are not required. Furthermore, the user name will be `rmguser`. Also included are aliases in the .bashrc
Happy to change the user name if required - it is a simple fix
The current Docker Image is quite large - approximately 4.6gb compressed on [dockerhub.](https://hub.docker.com/layers/reactionmechanismgenerator/rmg/latest/images/sha256-a1d95ddb760b5cb42c3b50367502dc73e0eb40f733bf642cb1a15306e34ccb40?context=explore)
I think it is important that we try to provide users and developers a less heavy image to use, especially when interacting with the container of the image
- Rewrote the …
> Reducing Docker Size

- arkane/explorer.py
- rmgpy/reaction.py
Skip adding energy_correction to  barriers in explorer tool if it isn't defined yet.
> Small fix for explorer tool

- .github/workflows/annotate.yml
The annotation name wasn't showing up right in the actions log.
Now it does.
I actually got this working on my own main branch to check it does the right thing.
This action run https://github.com/rwest/RMG-Py/actions/runs/5746619189 is called **Annotate "a test pull request"**
> Tweak annotation workflow name.

- documentation/source/users/rmg/surfaces.rst
> Minor: Added quotation marks to Pt111 in the docs

- arkane/encorr/ae.py
- arkane/encorr/bac.py
- arkane/main.py
- documentation/source/users/arkane/running.rst
This is one of the changes for the BAC paper. Per Bill's request, we add a discussion regarding the correlation for both AEC and p-BAC.
I add a plotting function and allow the user to plot and save correlation matrix for AECs.
> Allow user to plot correlation matrix for AECs

- rmgpy/solver/base.pyx
There was a typo in the rmgpy/solver/base.pyx described in issue #2070.
I fixed the typo such that the file accesses pydas.dassl if pydas.daspk is not available.
No tests performed.
> changed typo from pydas.daspk to pydas.dassl #2070

- rmgpy/molecule/atomtype.py
- rmgpy/molecule/group.py
- rmgpy/molecule/molecule.py
- test/rmgpy/molecule/groupTest.py
This PR primarily focuses on the addition of the Rx and Rx!H atomtypes along with a few bugfixes.
> Group Structures for Complex Surface Representations

- rmgpy/molecule/resonance.py
Begins to address [Issue #2642](https://github.com/ReactionMechanismGenerator/RMG-Py/issues/2642)
A clear and concise description of what what you're trying to fix or improve. Please reference any issues that this addresses.
A clear and concise description of what what you've changed or added.
A clear and concise description of testing that you've done or plan to do.
Suggestions for verifying that this PR works or other notes for the reviewer.
> Fix Fragment Resonance Structure Bug

- rmgpy/tools/diffmodels.py
- test/regression/minimal_surface/input.py
Patch for surface regression diffmodels
The .github actions script calling scripts/checkModels.py does not use the correct arguments or filenames for checking a surface model. So this adds a check for whether the existence of surface files to rmgpy/tools/diffmodels.py
Rather than changing this part of https://github.com/ReactionMechanismGenerator/RMG-Py/blob/main/.github/workflows/CI.yml ...
```
if python-jl scripts/checkModels.py \
"$regr_test-core" \
$REFERENCE/"$regr_test"/chemkin/chem_annotated.inp \
$REFERENCE/"$regr_test"/chemkin/species_dictionary.txt \
test/regression/"$regr_test"/chemkin/chem_annotated.inp \
test/regression/"$regr_test"/chemkin/species_dictionary.txt
then
```
... I think it would be easier to add a check in Python to see if the surface files exist and …
> Patch for surface regression diffmodels

- rmgpy/molecule/draw.py
Pull request  https://github.com/ReactionMechanismGenerator/RMG-Py/pull/1961  introduced the ability to draw hydrogen bonds.
To do so, Hydrogen atoms that have H bonds shouldn't be removed from the drawings.
This check was  removed without explanation in ec9515351ea9964a5a8499c1f4066378544eca41
which was designed to make drawing work for fragments.
That broke drawing of hydrogen bonds.
The unit test for drawing hydrogen bonds exists, but just checks that a PDF is made, not what it looks like. 
So the regression was not detected.
This restores the check that H atoms in H-bonds are not removed from drawings.
It also removes code duplication that was introduced in #1961 through erroneous rebasing, that @bjkreitz noticed and removed in a different PR.
It was while testing the second commit …
> Draw Hydrogen bonds (again)

- .github/workflows/CI.yml
- .github/workflows/docs.yml
- environment.yml
Artifact upload v3 will stop working in a few weeks - Jan 31st. (#2732)
This PR should presumably address this, but CI is failing due to a separate issue.
> Update CI artifact actions to v4 and fix runner glitch

- rmgpy/data/thermo.py
- rmgpy/thermo/thermoengine.py
When debugging weird thermo, it's helpful to know how things were estimated.
Linear Scaling Relations (LSRs) for moving from one catalyst to another, and solvation corrections, can both change thermo. The comments should now tell you how much it changed by.
I ran the unit test suite.
> Add details to thermo comments.

- rmgpy/kinetics/diffusionLimited.py
LiquidReactor + AFM runs crash with `KeyError: 'Node not found in database.'` (see **#2812**).  
The cause: AFM produces `Fragment` objects containing R/L dummy atoms; Solvation GAV cannot find these nodes.
1. detect `Fragment` and call `get_representative_molecule()` to replace the dummy atom with H.  
2. that function returns a **tuple** `(molecule, mapping)`, which raised a follow‑up `AttributeError`.  
Keep only the molecule:
```python
def clean(obj):                   
return obj[0] if isinstance(obj, tuple) else obj
rep_mol = clean(fragment.get_representative_molecule())
spec_for_solv = Species(molecule=[rep_mol])
Re‑ran the failing input from #2812 (note: terminationConversion key fixed from octane → CCCCR)
Before patch: KeyError
After patch: job completes
Standard LiquidReactor …
```
> Fix AFM fragment crash in LiquidReactor
